### ISSUE TITLE
Fix typos introduced with recent changes

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#1007]
While merging the latest changes from the develop branch across to my improved-logging branch I noticed a couple of typos have been introduced, one of which is a syntax error.

In **Ebizmarts/MailChimp/Block/Adminhtml/System/Config/Form/Field/Mapfields.php** function __renderCellTemplate()_ has the following line:
```
Mage:throwException('Wrong column name specified.');
```
which should actually be:
```
Mage::throwException('Wrong column name specified.');
```

In **Ebizmarts/MailChimp/Model/Api/Customers.php** function _getOptin()_ calls functiion:
```
getOptionConfiguration($magentoStoreId);
```
On the master branch this function is actually called:
```
getOptinConfiguration($magentoStoreId)
```

If anything, the function should probably be renamed to **getOptInConfiguration()**.

In **Ebizmarts/MailChimp/Model/Api/Subscribers.php** a new function is created called:
```
catchMailchompNewstellerConfirm()
```
This should probably be called **catchMailchimpNewsletterConfirm()**.

**Comment by giorello** [comment]
Changes done and merged in #1015 .
