### ISSUE TITLE
500 error, PHP Fatal error:  Call to a member function getUrl() on null

### ISSUE THREAD

**Issue by supportnubix** [mailchimp/mc-magento#1012]
### Preconditions

1. Magento version : 1.9.4.2
2. Mailchimp Magento version : 1.1.17

### Steps to reproduce

1. Go to backend
2. System -> Configuration -> Mailchimp
3. Under 'Mailchimp intergraztion by ebizmarts' set Enabled to Yes
4. Save configuration

### Expected result

1.  Configuration is saved, no errors

### Actual result

1. 500 internal server error
![image](https://user-images.githubusercontent.com/32568309/62039199-8224d080-b1f7-11e9-95fb-1bbd4fc169dd.png)
Server logs show : 

PHP Fatal error:  Call to a member function getUrl() on null in /home/rubroperc/domains/percona.rubro.nl/public_html/app/code/community/Ebizmarts/MailChimp/Helper/Data.php on line 2662, referer: https://percona.rubro.nl/index.php/admin/beheer/system_config/edit/section/mailchimp/key/46e584245d398f39f7b9fef684d915d2/

Data.php code on line 2662:
![image](https://user-images.githubusercontent.com/32568309/62039401-ec3d7580-b1f7-11e9-9fb1-db431521c0eb.png)

**Comment by Santiagoebizmarts** [comment]
Hello @supportnubix 
Thanks for contacting us.
Looks like your Magento is not returning the correct value for the getDefaultStoreView function.
Unfortunately this is a Magento function and it should always return a store object.

There is probably some customization in your Magento instance affecting this.
