### ISSUE TITLE
Uncaught Error: Call to undefined method Ebizmarts_MailChimp_Model_Api_Products::joinMailchimpSyncDataWithoutWhere() in /mc-magento/app/code/community/Ebizmarts/MailChimp/Helper/Data.php:3274

### ISSUE THREAD

**Issue by jan-lukowiak** [mailchimp/mc-magento#1014]
I get an error from mc-magento/app/code/community/Ebizmarts/MailChimp/Helper/Data.php line 3274 where the function Mage::getModel('mailchimp/api_products')->joinMailchimpSyncDataWithoutWhere() is called. Looking into the products api the function is never defined.

The function was renamed on June 3rd on commit 5a4083ce. So to also rename the call to "joinMailchimpSyncData" should fix the fatal error.

**Comment by Santiagoebizmarts** [comment]
Hello @jan-lukowiak ,

Thanks for your report, we will look into this and make an appropriate fix.

Kind Regards.

**Comment by brian-ebizmarts** [comment]
@jan-lukowiak we have solved this problem here #1024  

Kind Regards.
