### ISSUE TITLE
Mcrypt is deprecated

### ISSUE THREAD

**Issue by rafaelstz** [mailchimp/mc-magento#1016]
I'm using a Magento 1.9.4.1 with PHP 7.1 and MySQL 5.6, my logs registered some issues:

<img width="1404" alt="Screen Shot 2019-07-31 at 1 15 33 PM" src="https://user-images.githubusercontent.com/610598/62229713-b08ce200-b396-11e9-97ef-b399072f102a.png">

**Comment by Santiagoebizmarts** [comment]
Hello @rafaelstz 
We don't use mcrypt functions in the extension. There is probably some chain effect happening here.
Please post the entire error log as text in order to see if we can learn more about this.

Kind Regards.

**Comment by rafaelstz** [comment]
Hi @Santiagoebizmarts,

Yes, the latest version 1.1.17. I was debugging why my orders were not being sent to Mandrill, but it was because of another module called **Skyhub**.

So, I stopped to check the issues that I was having, because of that I'm closing this issue.

**Comment by Santiagoebizmarts** [comment]
Thank you for your update on this @rafaelstz 

Kind Regards.
