### ISSUE TITLE
Cannot resend Ecommerce data from particular scope

### ISSUE THREAD

**Issue by brian-ebizmarts** [mailchimp/mc-magento#1017]
### Preconditions
1. Magento 1 any version
2. Mailchimp for Magento 1.1.17

### Steps to reproduce

1. Configure the extension at website or storeview level
2. finish store synchronization
3. click on resend ecommerce data button 

### Expected result

1. Resend all selected items 

### Actual result

1. Resend is working only if the extension is configured in **Default config** scope

**Comment by Santiagoebizmarts** [comment]
No errors should be displayed when clicking the Resend Ecommerce Data button on a particular scope (Not Default Config scope).
