### ISSUE TITLE
PHP notice when MC API call fails

### ISSUE THREAD

**Issue by LucaGallinari** [mailchimp/mc-magento#1021]
In v1.1.17 the constructor arguments for the MailChimp_Error class has been modified but you used it incorrectly here:
https://github.com/mailchimp/mc-magento/blob/1.1.17/lib/Ebizmarts/MailChimp.php#L381
The arguments are arranged differently, and types are incorrent (like the "params" argument that is passed as an array but is concatenated to strings in the Error class...). This leads to a "Notice: Array to string conversion" whenever a call to Mailchimp API fails (status code >= 400) and a messed up exception message/info.

### Preconditions
Mailchimp module 1.1.17

### Steps to reproduce
Open a page that do a call to Mailchimp API that ends with a status code >= 400

### Expected result
No PHP notice and correct exception message when API call fails with a status code >= 400

### Actual result
PHP notice and messed up exception message/info when API call fails with a status code >= 400

**Comment by Santiagoebizmarts** [comment]
Hello @LucaGallinari 
Thank you for your feedback, we will fix this for the next release.

Kind Regards.
