### ISSUE TITLE
Fix for bug preventing carts from synchronising

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#1029]
Carts no longer synchronise due to a bug introduced in commit dcee0f1e76dfd42589d106f99516638ae461f3b1. The issue is in the  __processCartLines()_ method of *app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php* as shown below:
```
        return array('lines' => $lines, $count = $itemCount);
```

The fix is simply:
```
        return array('lines' => $lines, 'count' => $itemCount);
```

**Comment by Santiagoebizmarts** [comment]
Thank you for your feedback @TroyPatteson 
This will be fixed for next release.

Kind Regards.
