### ISSUE TITLE
Add full support for multi-stores.

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#103]
Create multiple stores at MailChimp depending on the configuration for each store view.

**Comment by ljay79** [comment]
Hi There. Is there any update on this enhansement yet?

**Comment by Santiagoebizmarts** [comment]
Hello @ljay79 ,

At the moment no, we focused on improving what we already have. This is a priority now so it should be in the next version.

Regards,

**Comment by ljay79** [comment]
Thx @Santiagoebizmarts 
Just to clearify; as i cant find any mentioning of this multi-store feature missing or included in latest release 1.1.5. - Is the latest version supporting multi-stores with CE 1.9x or not? 

Thx in advanced.

If NO, QQ - in terms of this plugin, what does it imply / impact, running the module on a CE 1.9x multi-store setup without the yet available multi-store support?

**Comment by Santiagoebizmarts** [comment]
Hello,

Version 1.1.5 doesn't include full support for multi-stores.
The problem in such cases is mostly when multi-language exists between each store. Since all the ecommerce data goes to the same place no matter which store view it is associated to, automations will trigger for all the store view in the same way with the same email.

**Comment by seansan** [comment]
This needs to be fixed very soon and has been on the radar since JULY 2016 ... 

We really need full support for multistore

All the larger e-commerce stores often run at least more than 1 .......

**Comment by kristofpoppe** [comment]
Any update on timing ? As from March 4th Mailchimp can't guarantee the correct working of the MageMonkey module, so we need some kind of fix/replacement quite urgent.

**Comment by Santiagoebizmarts** [comment]
Hello,

This is already being tested. Will be available really soon!

**Comment by seansan** [comment]
This is urgent. Hope it comes soon. (and is tested extensively ... ) - We have 6 other merchants waiting for this too

**Comment by RUjmiak** [comment]
Will MageMonkey working tmrw as we have multistore and there is no new working extension.

**Comment by seansan** [comment]
same HERE

And support for configurable products

**Comment by gonzaloebiz** [comment]
Hi @seansan, @RUjmiak 

we are working hard on this.
Please, keep in mind, the issue mechanism is to report issues and no need to comment in a already reported issue that we already work on it

Best

**Comment by leonmex** [comment]
Hi @Santiagoebizmarts when is planning the new release with the changes for the commit's ed7ff24

**Comment by gonzaloebiz** [comment]
Hi @leonmex 

we are testing the new version.

Best

**Comment by ihor-sviziev** [comment]
@gonzaloebiz thank you for update, do you have any estimation when new release will be available?

**Comment by Santiagoebizmarts** [comment]
There is no release date because the testing must verify pretty much everything. Shouldn't take more than two weeks from now.

Regards

**Comment by mschmidt001** [comment]
Hi @Santiagoebizmarts. Will you be releasing multi-store capability this week?

**Comment by seansan** [comment]
Important is that it needs to be rigoursly tested - otherwise
multi-mailchimp lists problems

Will a migration checklist be provided? (from old to new extension)

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
If you have version 1.1.5 or previous, it is recommended to re-configure each store view with a different list, this will create new MailChimp stores for each scope you configure.

The default config scope will be maintained but if you configure a new store for a child store view, the information for that store view will start being sent only for the new MailChimp store.

Regards.

**Comment by seansan** [comment]
So we need to trigger a complete resend? And we do this by creating a new
list?

Difficulty here is that our list is not managed only by Magento -----

Is it possible to create a "hard reset" button to force re-send all
customer data + order data?


On Fri, Mar 31, 2017 at 4:30 PM, Santiagoebizmarts <notifications@github.com
