### ISSUE TITLE
New date helper incorrectly defaults to using store times rather than UTC

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#1030]
The recently introduced date helper defaults to using times in the local timezone of the associated store rather than UTC which breaks synchronisation as records stored in magento use UTC. This can be seen in the core __initEnvironment()_ method of **app/code/core/Mage/Core/Model/App.php**:
```
    protected function _initEnvironment()
    {
        $this->setErrorHandler(self::DEFAULT_ERROR_HANDLER);
        date_default_timezone_set(Mage_Core_Model_Locale::DEFAULT_TIMEZONE);
        return $this;
    }
```
where _Mage_Core_Model_Locale::DEFAULT_TIMEZONE_ is set to 'UTC' in **app/code/core/Mage/Core/Model/Locale.php**.

Previously the current date/time was obtained using __Varien_Date::now()__. Comparing the old and new methods of obtaining the current date/time in the following code shows the issue:
```
require_once '../public_html/app/Mage.php';
umask(0);
Mage::app();

print "Varien_Date::now() => " . Varien_Date::now() . "\n";
print "DATEHELPER->formatDate() => " . Mage::helper('mailchimp/date')->formatDate(null, 'Y-m-d H:i:s') . "\n";
```
The output in my environment where the local timezone is +10:00 from UTC:
```
Varien_Date::now() => 2019-08-13 04:29:12
DATEHELPER->formatDate() => 2019-08-13 14:29:12
```

The helper function responsible is for this in **app/code/community/Ebizmarts/MailChimp/Helper/Date.php** is
```
    public function formatDate($date = null, $format = 'Y-m-d', $avoidOffset = 1)
    {
        $gmtTimestamp = Mage::getModel('core/date')->gmtTimestamp($date);
        $currentTimestamp = $this->getTimestamp($gmtTimestamp);
        if ($avoidOffset) {
            $currentTimestamp = $this->avoidTimeZoneOffset($currentTimestamp);
        }

        $newDate = Mage::getModel('core/date')->gmtDate($format, $currentTimestamp);
        return $newDate;
    }
```

The solution is to simply reverse the default value of the _$avoidOffset_ parameter from **1** to **false**. Note that it is poor practice to use integer values for a boolean type!

The other thing with this method is that the parameter is poorly named. We either want to use UTC or time in the store's timezone so a better name would be something like **$useStoreTime**. The __avoidTimeZoneOffset()__ method should be renamed to something like **_convertUTCToStoreTimestamp()** as follows:
```
    /**
     * Return date in given format in UTC or the timezone of the current store.
     *
     * @param string $format
     * @param $date
     * @param bool $useStoreTime
     * @return mixed
     * @throws Mage_Core_Model_Store_Exception
     */
    public function formatDate($date = null, $format = 'Y-m-d', $useStoreTime = false)
    {
        $gmtTimestamp = Mage::getModel('core/date')->gmtTimestamp($date);
        $currentTimestamp = $this->getTimestamp($gmtTimestamp);
        if ($useStoreTime) {
            $currentTimestamp = $this->_convertUTCToStoreTimestamp($currentTimestamp);
        }

        $newDate = Mage::getModel('core/date')->gmtDate($format, $currentTimestamp);
        return $newDate;
    }

    /**
     * @param int $timestamp
     * @return int
     * @throws Mage_Core_Model_Store_Exception
     */
    protected function _convertUTCToStoreTimestamp($timestamp)
    {
        $timeZone = Mage::app()->getStore()->getConfig('general/locale/timezone');
        $offSet   = Mage::getModel('core/date')->calculateOffset($timeZone);
        return ($timestamp + $offSet);
    }
```

**Comment by Santiagoebizmarts** [comment]
@TroyPatteson Thank you again for your useful feedback.
