### ISSUE TITLE
Fix for exception when editing newsletter subscription in My Account

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#1034]
The following syntax error was recently introduced into the __getEmail()_ method of **app/code/community/Ebizmarts/MailChimp/Block/Customer/Newsletter/Index.php** in the current development version which causes an exception when going to **My Account** and choosing to edit _Newsletter Subscription_:
```
    protected function _getEmail()
    {
        return $this->_helper('customer')->getCustomer()->getEmail();
    }
```
It should be:
```
    protected function _getEmail()
    {
        return $this->getCustomerSession()->getCustomer()->getEmail();
    }
```

**Comment by giorello** [comment]
Thanks Troy for this feedback.
This fix will surely be added in the next release.

Regards, 
Javier Giorello.
