### ISSUE TITLE
Validate data migration on first installation

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#1036]
### Steps to reproduce

1. Install fresh Mailchimp For Magento 1.1.17
2. Enable ecommerce data sending and make sure cron jobs are running.

### Expected result

1. After 3 cron job runs the green message should disappear from account details.
Message: "The store data is currently being migrated to the new version. This process might take a while depending on the amount of data in Magento."

### Actual result

1. Message remains indefinitely and prevent ecommerce data to be sent.

**Comment by giorello** [comment]
Solved in #1040 .
