### ISSUE TITLE
Cron error after upgraden M194.x and V1.1.17 // Your API key may be invalid, or you've attempted to access the wrong datacente

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#1042]
BeforeV1.1.16: worked for months no errors

Preconditions installed M194.x
Updated to V1.1.17

Now we see invalid datacenter or API key. API KEY has not changed !!! 

So is there something wrong with the coded datacenter endpoint?

Cron error while executing mailchimp_bulksync_ecommerce_data:

MailChimp_Error: API Key Invalid for Api Call: {"is_syncing":true} - Your API key may be invalid, or you've attempted to access the wrong datacenter. in lib/Ebizmarts/MailChimp.php:381
Stack trace:
#0 lib/Ebizmarts/MailChimp/EcommerceStores.php(179): Ebizmarts_MailChimp->call('ecommerce/store...', '{"is_syncing":t...', 'PATCH')
#1 app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php(226): MailChimp_EcommerceStore->edit('dd72fedf407a1c4...', NULL, NULL, NULL, true)
#2 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2911): Ebizmarts_MailChimp_Model_Api_Stores->editIsSyncing(Object(Ebizmarts_MailChimp), true, 'dd72fedf407a1c4...')
#3 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(3114): Ebizmarts_MailChimp_Helper_Data->setIsSyncingIfFinishedPerScope(true, '8', 'stores')
#4 app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(197): Ebizmarts_MailChimp_Helper_Data->handleResendDataBefore()
#5 app/code/community/Ebizmarts/MailChimp/Model/Cron.php(28): Ebizmarts_MailChimp_Model_Api_Batches->handleEcommerceBatches()
#6 app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Ebizmarts_MailChimp_Model_Cron->syncEcommerceBatchData(Object(Aoe_Scheduler_Model_Schedule))
#7 app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
#8 app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#9 app/code/local/Xtento/StockImport/Model/Observer/Cron/Config.php(24): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#10 app/code/core/Mage/Core/Model/App.php(1365): Xtento_StockImport_Model_Observer_Cron_Config->addCronjobsToConfig(Object(Varien_Event_Observer))
#11 app/code/core/Mage/Core/Model/App.php(1338): Mage_Core_Model_App->_callObserverMethod(Object(Xtento_StockImport_Model_Observer_Cron_Config), 'addCronjobsToCo...', Object(Varien_Event_Observer))
#12 app/Mage.php(460): Mage_Core_Model_App->dispatchEvent('default', Array)
#13 cron.php(81): Mage::dispatchEvent('default')
#14 {main}

**Comment by seansan** [comment]
After upgrade the API key was cleared in our backend? Wast the confg field changed?

**Comment by roberto-ebizmarts** [comment]
Hello, @seansan 
Please, ensure that your current API key in use is valid. Please verify you API key list in your Mailchimp account.

**Comment by seansan** [comment]
API KEY was valid. Emailed Mailchimp. After this solved. Dont know what was wrong here

**Comment by Santiagoebizmarts** [comment]
Hello @seansan,
Sometimes the browser form autocompleter consider the API Key field as a password modifying the value for your Magento back end password (only if you have it remebered)

Unfortunately there is not much we can do here due to the autocomplete attribute being ignored by the latest browsers.

Just be careful when saving the configuration and you should be fine.

Regards,
