### ISSUE TITLE
Validate API key field at Mailchimp configuration

### ISSUE THREAD

**Issue by roberto-ebizmarts** [mailchimp/mc-magento#1052]
Validate API key field at Mailchimp configuration
### Preconditions
1. Magento 1.9.4.2
2. M4M 1.1.17
3. PHP 7.2

### Steps to reproduce
Insert an invalid API key at M4M configuration. And unfocus the API key field.

### Expected result
Notify to user that the API key introduced is invalid.

### Actual result
User is not notified about invalid API key just introduced.

**Comment by Santiagoebizmarts** [comment]
If an invalid API Key is added in the configuration section of the extension. As soon as you click outside, the border of the field turns red and a message is displayed.
See image:
![Screen Shot 2019-09-30 at 16 39 24](https://user-images.githubusercontent.com/8330778/65910455-16024c80-e3a1-11e9-8b75-090b727ea5e3.png)
