### ISSUE TITLE
Fix for re-using synch batch models causing batch responses to not be processed

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#1057]
The Synch Batches model is re-used in **Ebizmarts/MailChimp/Model/Api/Batches.php** via the _getSyncBatchesModel()_ method when it should not be as that object is not a singleton. This results in synch batch records being overwritten if syncing multiple stores to different mailchimp lists and one or more orders were created for multiple different stores since the _mailchimp_bulksync_ecommerce_data_ cron job was last run. The first call to _getSyncBatchesModel()_ called from __sendEcommerceBatch()_ returns an empty batch model which is saved and the batch model is assigned an ID. The next call to _getSyncBatchesModel()_ returns the same batch model with the ID already set and then proceeeds to save that model overwriting the previous synch batch record. As a result, the overwritten batch response is never processed.

### Preconditions
1. mc-magento v1.1.17 but looking in git the issue was introduced in commit 663f323f4da807ce28515b0214eb2db0cbea586f prior to v1.1.11.
2. magento v1.9.4.2 / php 7.2

### Steps to reproduce
1. Create an order for two or more stores that are configured to synchronise to different mailchimp lists.
2. Run the _mailchimp_bulksync_ecommerce_data_ cron job to sync those orders to mailchimp
3. Wait a few minutes and run the _mailchimp_bulksync_ecommerce_data_ cron job again to process the batch responses for the previous orders.

### Expected result
1. The orders should have the **Synced to MailChimp** column set to **Yes** in the Sales Orders page in the magento backend.

### Actual result
1. Only the last order synchronised has **Synced to MailChimp** column set to **Yes**. The rest are set to **Processing**.

You can also look at the records stored in the _mailchimp_ecommerce_sync_data_ and _mailchimp_sync_batches_ tables to confirm that batch IDs in _mailchimp_ecommerce_sync_data_ are not present in _mailchimp_sync_batches_.

### The Solution

Remove the following protected member variable in  **Ebizmarts/MailChimp/Model/Api/Batches.php**:
```
    /**
     * @var Ebizmarts_MailChimp_Model_Synchbatches
     */
    protected $_syncBatchesModel;
```
In ___construct()_ of **Ebizmarts/MailChimp/Model/Api/Batches.php** remove the following  code:
```
        $this->_syncBatchesModel = Mage::getModel('mailchimp/synchbatches');
```
In the same file replace:
```
     protected function getSyncBatchesModel()
     {
        return $this->_syncBatchesModel;
     }
```
with:
```
     protected function getSyncBatchesModel()
     {
        return Mage::getModel('mailchimp/synchbatches');
     }
```

**Comment by roberto-ebizmarts** [comment]
Thanks, @TroyPatteson
