### ISSUE TITLE
Error in the lib

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento#106]
Hi,

I found a little bug in your MailChimp module.

In lib/Ebizmarts/Mailchimp/ListsMembers.php, line 115, a call is made to 
the Mailchimp API. 
Instead of

'list/'.$listId.'/members/'.$subscriberHash

it should be:

'lists/'.$listId.'/members/'.$subscriberHash

(add the 's' to list)

(Thanks Johan de Kruijf for the feedback)

**Comment by lduh** [comment]
changes verified in the code.
