### ISSUE TITLE
The Monkey image in the order grid

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento#107]
We decide to put a configuration flag to show/hide the monkey in the order grid.
In the other hand, we add a block in the order view to show more specific information about the recovered orders thanks to mailchimp

**Comment by lduh** [comment]
@gonzaloebiz is this outside of System>Configuration>MailChimp? I don't see an option for it in there.

**Comment by lduh** [comment]
Looks like it's working! can we change the copy to "Display icon for MailChimp orders"

**Comment by lduh** [comment]
edit - "Display MailChimp icon in the Orders grid"
