### ISSUE TITLE
REsend subscribers / reset errors and STORE SCOPE

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#1070]
Magento 1.9.4.x
Mailchimp Version 1.1.17

I see many issues closed last periode and have the idea the MC extension finally has some time to focus on other things. 

1 of the problems we have seen is not clear enough feedback in the Magento backend. I will list some issues. 

1. Mailchimp has a max limitation on # merge fields. But if you create a merge field and click save Magento stores it, but is is never synced to MC. THere should be validation on max # fields

2. Mailchimp has a max limitation on # of chars in the merge field name. Magento does not validate this and the result is the data is never sent to MC beacuse the merge field name does not match (it is created though, but cut off in chars. The result van be a merge field name in magento called brand_preference and merge field name in MC called brand_prefe)

3. Magento has different store hierarchies/scopes like a. default config, b. storename level and c. storeview level. MC lists are normally managed on level b or c. However when you click RESEND subsscribers or RESET local errors or RESEND ecom data on default config level or on sotrename level => it is not clear to the user if this is not done at all? (because default config itself has no list linked) OR it is done for all underlying storeviews (thus it loops over all configured stores and executes the action 1 store per store) OR even if it does do this for 1 of the 3 RESEND action if the behavior is the same for all 3. The feedback message saying the RESEND has started can be improved to inform the user exactly WHICH storeviews are being resent.

4. Maybe there are more validation/simple wins for the backend solving large problems.??

I hope there is some time to fix this with minimal time investment. These are quick wins. But have large impact on store performance ... if they do/dont work

Please fix in upcoming release. And dont just close the issue; we have worked with this/previous extensions for 6 years now ... it is important

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
1. This has been fixed at https://github.com/mailchimp/mc-magento/issues/957
2. There is an specific issue for this at https://github.com/mailchimp/mc-magento/issues/1140
3. On default config it affects all the inner hierarchies, other than that it affects the selected scope only.
4. Not sure about what you mean with this. We are constantly improving the code.

Kind Regards.

**Comment by seansan** [comment]
Thx 1 and 2 OK

>> 3. On default config it affects all the inner hierarchies, other than
that it affects the selected scope only.

Please show some feedback / warning / info to the user WHICH storeviews are
being updated after clicking the button

**Comment by Santiagoebizmarts** [comment]
Just created an issue for that: https://github.com/mailchimp/mc-magento/issues/1142

Thanks for your feedback @seansan 

Kind Regards.
