### ISSUE TITLE
eCommerce bulk send ends in report generated and "died" in scheduler

### ISSUE THREAD

**Issue by mattyl** [mailchimp/mc-magento#1080]
Running 1.1.16 - on magento 1.9.4.1 - using php 7.2

On choosing a date to start the eCommerce sync - a report error is thrown during the cron.

the mysql generated seems incorrect - trailing )

when that is removed mysql 

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, at_special_from_date.value, at_special_from_date_default.value)) OR (IF(at_sp' at line 2

mysql

SELECT `e`.`entity_id`, `e`.`type_id`, `e`.`attribute_set_id`, `e`.`special_price`, `e`.`special_from_date`, `e`.`special_to_date`, `m4m`.`related_id`, `m4m`.`type`, `m4m`.`mailchimp_store_id`, `m4m`.`mailchimp_sync_delta`, `m4m`.`mailchimp_sync_modified` FROM `catalog_product_flat_6` AS `e`
 LEFT JOIN `mailchimp_ecommerce_sync_data` AS `m4m` ON m4m.related_id = e.entity_id AND m4m.type = 'PRO' AND m4m.mailchimp_store_id = 'xxx' AND m4m.mailchimp_sync_modified = 0 WHERE (e.status = 1) AND (e.special_price IS NOT NULL) AND (e.special_from_date IS NOT NULL) AND (((IF(at_special_from_date.value_id > 0, at_special_from_date.value, at_special_from_date_default.value)  0, at_special_from_date.value, at_special_from_date_default.value)) OR (IF(at_special_to_date.value_id > 0, at_special_to_date.value, at_special_to_date_default.value) < '2019-09-19  00:00:00' AND m4m.mailchimp_sync_delta <  IF(at_special_to_date.value_id > 0, at_special_to_date.value, at_special_to_date_default.value)) AND mailchimp_sync_delta IS NOT NULL))

**Comment by giorello** [comment]
Hi Mattyl, 

This is an already solved issue in the v1.1.17, please take a look at this issue: https://github.com/mailchimp/mc-magento/issues/964.

Regards, 
Javier Giorello.

**Comment by mattyl** [comment]
thanks!
