### ISSUE TITLE
Please add customer ID (entity id) to MERGE FIELDS options

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#1081]
Using latest M1.94.
Latest extension version

Problem
We now cannot select the Customer ID

Request
We need to link the data for our admin users who can BE SURE they are working with the CORRECT customer

Solution
Add Customer Entity Id as dropdown option in merge field backend select

QUICKWIN

![image](https://user-images.githubusercontent.com/652395/65333430-c9f52200-dbc0-11e9-9e0f-dd32158357e7.png)

**Comment by giorello** [comment]
Hi @seansan, 

With the email address should be enough to identify a customer.
When an email is sent as a guest in an order/quote, mailchimp unifies it with the registered customer, so there's no need to add the customer ID as merge field.

Kind regards, 
Javier Giorello.

**Comment by seansan** [comment]
It is to identify a customer vice versa in magento
