### ISSUE TITLE
campaignCatcher.js 1.1.17 is breaking funcionality Magento 1.9.3.

### ISSUE THREAD

**Issue by newsjunk** [mailchimp/mc-magento#1084]
hi,
We cannot seem to get the lastest release working. Activating MC totally breaks JS and site functionality. 

js error on frontend:

TypeError: document.observe is not a function. (In 'document.observe('dom:loaded', getCampaign)', 'document.observe' is undefined)
Globale code — campaignCatcher.js:55
Globale code — app.js:46

errorlog: 
2019-09-26T22:20:04+00:00 DEBUG (7): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dealdumpert_production.mailchimp_$

I checked file rights, and if it was an old JS but all fresh and new and correct
I tried changing js loading in mailchimp.xml to defer but this did not work. 

Any suggestions welcome! We had to disable mc for now

**Comment by roberto-ebizmarts** [comment]
Hi, @newsjunk 
1. Did you install v1.1.17 from zero? Or did you upgrade from some older version?
2. How did you install the version?
3. If you need some help or have any doubt, please contact us.
This is our email for support: mailchimp@ebizmarts-desk.zendesk.com

**Comment by newsjunk** [comment]
Hi @roberto-ebizmarts 
1. We dit an upgrade, from an older version. 
2. Our Magento dev installed it. 
3. Sure, will mail you with more info

**Comment by roberto-ebizmarts** [comment]
Hi, @newsjunk 
I will close this issue as it's not a confirmed issue.
So, if you need any help in your installation or some tips for solving any problem, I confirm you our contact email: mailchimp@ebizmarts-desk.zendesk.com
