### ISSUE TITLE
Feature Request / Quick Win: Improve logging add customer id

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#1087]
Latest Magento. Latest Extension. 

Debugging issue with the Ebizmart helpdesk when we discovered the following

On the image

1.	The subscriber ID show in the Original column is NOT the Mailchimp unique ID that is used, but rather the ID of the email in the list (which Mailchimp does not show or use anywhere in their backend). **Request**: Please add the universal subscriber id & and/or add a direct link to mailchimp to find the customer https://us4.admin.mailchimp.com/lists/members/view?id=119652661

2. The customer ID should be added to either the Original error string (with clickable link if possible) or at least the error message txt. **Request**: Please add the customer number to the error message, preferably also with a direct link to the customer

![image](https://user-images.githubusercontent.com/652395/65990192-6eae1400-e48b-11e9-87f1-c4afa5681e5d.png)

**Comment by gonzaloebiz** [comment]
Hi @seansan 

the Original column shows the link to the magento object, when reg type is CUS you have a link to the customer, this way you can modify any data on the customer.
When reg type is SUB, magento doesn't allow to edit it, so no sense to put a link because doesn't exist, and have no sense put a link to mailchimp because you can't change anything at mailchimp to resolve the problem.
I think the information in the grid is right

**Comment by seansan** [comment]
Please add a direct link where possible also MC. We discovered this during
debugging it is easier to debug with fewer clicks and no mistakes.

**Comment by Santiagoebizmarts** [comment]
Hello Seansan,

Please note only subscribers may have an actual link to be seen on Mailchimp side. Products, Orders, Carts, Promo Rules will never have a link in Mailchimp as there is no way to see them individually.
In addition when a subscriber fails it will not exist in Mailchimp therefore no link will exist unless it existed previously.
Looking for the subscriber in the Newsletter Subscribers grid filtering by id does not seem that difficult.

Maybe we could add the email address in stead of the id to avoid that extra step.

Regards.

**Comment by seansan** [comment]
Some improvement would be nice; do realize that when debugging that :

we need to link up the customer in MC en MAGENTO: fast

For instance the list id number in MC that is shown is not used in the MC
GUI/UX anywhere ....

And a direct link to the Magento customer would be nice
