### ISSUE TITLE
After Upgrade the latest version 1.1.18 getting issue in order placing

### ISSUE THREAD

**Issue by vmishra341** [mailchimp/mc-magento#1097]
After upgrade MailChimp module to the latest version i.e. 1.1.18 getting error and order not placed.

After upgrading the module to the latest version 1.1. 18 and trying to place the order  I am getting one strange issue in exception.log file and order not placed at all.
Please check the attached error that I am receiving when trying to place a new order. 

Preconditions
M4M 1.1.11 latest
Magento 1.9.1.0

Steps to reproduce
Try to place the order

Expected result
Order needs to placed successfully

Actual result
Recoverable Error: Argument 10 passed to Ebizmarts_MailChimp_Helper_Data::setEcommerceSyncDataItemValues() must be an instance of Ebizmarts_MailChimp_Model_Api_SyncItem, instance of Ebizmarts_MailChimp_Model_Ecommercesyncdata given, called in /home/sites/xxxx/docs/app/code/community/Ebizmarts/MailChimp/Helper/Data.php on line 1561 and defined  in /home/sites/xxxxx/docs/app/code/community/Ebizmarts/MailChimp/Helper/Data.php on line 5138#0 
[exception.log](https://github.com/mailchimp/mc-magento/files/3770696/exception.log)

**Comment by vmishra341** [comment]
anyone update me on this issue, please?

**Comment by roberto-ebizmarts** [comment]
Hello, @vmishra341.
Thanks for contacting us.
In order to assist you, please contact us via mailchimp@ebizmarts-desk.zendesk.com, as I see you have not upgraded properly. Or maybe you have some configuration problems.

**Comment by vmishra341** [comment]
Hi @roberto-ebizmarts ,

I have sent an email to the provided email address. Please check and reply to me on it to resolve that issue.

Thanks,
Vipul Mishra

**Comment by roberto-ebizmarts** [comment]
This issue has become in ref. #1103.
