### ISSUE TITLE
Fatal error: Class 'Mage_Ebizmarts_Mandrill_Helper_Data' not found in /app/public/app/Mage.php

### ISSUE THREAD

**Issue by elvetemedve** [mailchimp/mc-magento#1105]
### Preconditions

1. Magento version EE 1.14.1.0
2. PHP 5.6.4
3. Extension is installed via Composer.
4. Extension version 1.1.18.

### Steps to reproduce

1. Log in to the Magento admin panel.
2. Go the the **System > Configuration > Mailchimp: Mandrill** menu.
3. Set enabled to Yes and fill in the API key. Finally save the configuration.

### Expected result

1. The message about successful save should be displayed.

### Actual result

1. A PHP fatal error is displayed.

![image](https://user-images.githubusercontent.com/596431/68039597-c62ee200-fccc-11e9-9d9f-bfb70c59303b.png)

**Comment by Santiagoebizmarts** [comment]
Hello @elvetemedve 

I have seen similar cases where Magento changes the class name for an extension file. Usually it happened when uninstalling the extension but not refreshing all the caches or not re-compiling.

If this continues to happen please contact our support at mailchimp@ebizmarts-desk.zendesk.com

Kind Regards.
