### ISSUE TITLE
Fails to install with Magento Connect Manager and PHP 7.2 due to PHP Version restrictions 

### ISSUE THREAD

**Issue by griesi007** [mailchimp/mc-magento#1109]
Cannot install 1.1.18 using magento connect manager on Magento 1.9.4:

Error is: CONNECT ERROR: Package /mailchimp+MailChimp_For_Magento 1.1.18: requires PHP version >= 5.2.0 and <= 6.0.0 current is: 7.2.22

**Comment by Santiagoebizmarts** [comment]
Thanks for your update on this. There was certainly an error in the Magento marketplace package creation.
Unfortunately this cannot be changed until the next version package is build.

Kind Regards.
