### ISSUE TITLE
Wrong format for mailchimp_sync_delta field

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#111]
Hi there!

**Preconditions**

1. Magento 1.9.2.4
2. mc-magento 1.1.2
3. Real data is included and Products are exported to MailChimp

**Steps to reproduce**

1. Go to Catalog Product Edit Page in Admin Interface
2. Edit any data
3. Press "Save button"
4. Look how _mailchimp_sync_delta_ field is processing in **Mage_Core_Controller_Varien_Action->_filterDates()**

**Expected result**

1. After **$filterInput->filter** _mailchimp_sync_delta_ becomes correct date value

**Actual result**

1. It becomes uncorrect, for example:
 * 2016-11-29 18:25:35 => 016 -11 -29  18 :25 :35

It brokes correct behaviour:
1. **Zend_Locale_Format::checkDateFormat** can't parse this date
2. After this **$filterInternal** get _mailchimp_sync_delta_ as float and tries to get precision by subtraction, it causes _A non well formed numeric value encountered_ error

Hope it will be fixed soon.
Regards, Nikolay

**Comment by Santiagoebizmarts** [comment]
Hello @elluminatte 

When the extension is saved no mailchimp_sync_delta value is set.
How did you get to that function? What object type is the one you are looking at (Customer, Order, Product)?

Regards.

**Comment by elluminatte** [comment]
@Santiagoebizmarts hi!

What do you mean in "the date time is saved correctly"? It's really saved correctly, but field filtering is broken. Please trace field value at Mage_Core_Controller_Varien_Action->_filterDates() and you will be able to see that after filterInternal filtering value becomes broken

**Comment by elluminatte** [comment]
@Santiagoebizmarts i can provide debug process description. Please look at attached screenshots (this is **Mage_Core_Controller_Varien_Action->_filterDates()** method)

This is like correct format is parsed after **$filterInput->filter()**. Look at **special_date_from** field. If you take a look into the next step **$filterInternal->filter()** you will see that it need an array to process field as date, if it's not an array it's processed like float - it's not a correct behaviour. 

![screenshot - 20 12 2016 - 10 38 04](https://cloud.githubusercontent.com/assets/8599788/21341979/dc0c34c2-c6a8-11e6-8a27-f8785cc4d8f8.png)

This is like **mailchimp_sync_delta** looks like after **$filterInput->filter()**. Note that it's not changed. If you look into method **filter()** you will see that it have not passed **checkDateFormat** and was returned unchanged. But if you remember the first picture description, you know that we need an array after **$filterInput->filter()** to handle date correctly.

![screenshot - 20 12 2016 - 10 36 52](https://cloud.githubusercontent.com/assets/8599788/21341980/dc0f1ef8-c6a8-11e6-91d5-fc22416da7b4.png)

This is like **mailchimp_sync_delta** looks after **$filterInternal->filter**. It's broken. This is because scalar type was provided to this method. The field is processed as float because not array was provided to this method (please take a look into it). If you take a look how float values are processing you will see that is incorrect behaviour - it's unpredictable, and we get a notice while evaluating precision because of dates subtraction.

![screenshot - 20 12 2016 - 10 37 27](https://cloud.githubusercontent.com/assets/8599788/21341981/dc0f7e0c-c6a8-11e6-8b95-8a784ec114a8.png)

I hope it has become much more clear for you now.
Regards, Nikolay

**Comment by Santiagoebizmarts** [comment]
Hello @elluminatte 

I've been investigating this and I can not find a use case where this affects anything.
The solution I found (Magento seems to be rough on the edges when handling datetimes) is to change the frontend_input of the mailchimp_sync_delta attributes to datetime in stead of text as it is at the moment.
To do this go to the database table eav_attribute and search for the attribute_code **mailchimp_sync_delta**, you should see two instances. The one with **entity_type_id** 4 is the one you should edit.
You will see the **frontend_input** as **text**, change it to **datetime**.

Please let us know if this solves your problem.

Regards.

**Comment by elluminatte** [comment]
Hello @Santiagoebizmarts 
Yes, this solves this problem - date is parsed correctly now.
Will it be fixed in the next release of the extension?

Regards, Nikolay

**Comment by elluminatte** [comment]
Hello @Santiagoebizmarts 
could you please answer my question?

If you don't plan to fix it we will apply our own fix

**Comment by gonzaloebiz** [comment]
Hi @elluminatte 

of course, the fix will be included in the next release.

Best

**Comment by lfolco** [comment]
Hi-

This fix broke the extension Magento 1.7; you cannot edit products anymore. There is no Datetime class in this version of Magento:

Warning: include(Varien/Data/Form/Element/Datetime.php): failed to open stream: No such file or directory.

**Comment by Santiagoebizmarts** [comment]
Hello @lfolco 
Changing that to label in stead of datetime should fix it.
You should be able to do that with the following query: **UPDATE eav_attribute SET frontend_input='label' WHERE attribute_code='mailchimp_sync_delta';**

This problem will be solved in the next release because we no longer use the Magento tables to store the sync data. We created our own database table to save this info in order to add multi-store support.

Regards.

**Comment by lfolco** [comment]
Do you have an ETA on the next release? We are in the testing stage currently, but if there will be a significant change like this we may hold off on releasing.

**Comment by lfolco** [comment]
Just a general ETA? This is a significant change that we would rather do before we release than after.

**Comment by gonzaloebiz** [comment]
Hi @lfolco 

we hope next week will release the multi store version

Best
