### ISSUE TITLE
quoteEscape() method doesn't exist on M1.7

### ISSUE THREAD

**Issue by roberto-ebizmarts** [mailchimp/mc-magento#1114]
### Preconditions

1. Magento 1.7

### Steps to reproduce

1. Install M4M1.1.18 on M1.7
2. Click on Mailchimp from Configuration

### Expected result

1. The Configuration form for M4M extension should appear

### Actual result

1. a:5:{i:0;s:136:"Invalid method Ebizmarts_MailChimp_Block_Adminhtml_System_Config_Form_Field_Mapfields::quoteEscape(Array...

**Comment by giorello** [comment]
The solution for this should be using the PHP function 'htmlspecialchars', it is used by the method Mage_Core_Block_Abstract::quoteEscape in Magento 1.8+. 

This solucion generates an warning when running MEQP checks; we should add a method in our Helper to call this function with the needed params (default params in Magento 1.8+ but not the default params defined by PHP) and make the usage of this function more understandable. Making this Helper's method, MEQP checks doesn't detect the string escape throwing: 'WARNING | Unescaped output detected.'.

From there we have two options:
1. Stop supporting Magento 1.7 and previous versions.
2. Ignore the MEQP warning and add the mentioned solution to support Magento 1.7.
