### ISSUE TITLE
Minor issue with translation

### ISSUE THREAD

**Issue by mosonyi** [mailchimp/mc-magento#1117]
To be able to use an external translation, a modification should be made file in this file app/code/community/Ebizmarts/MailChimp/controllers/CartController.php

from
Mage::getSingleton('customer/session')->addNotice("Login to complete your order");
to
Mage::getSingleton('customer/session')->addNotice($this->__("Login to complete your order"));

**Comment by Santiagoebizmarts** [comment]
Thank you for your feedback @mosonyi 

I created a more complete issue at https://github.com/mailchimp/mc-magento/issues/1118
Should be solved in next release.

Regards.
