### ISSUE TITLE
attachments noname

### ISSUE THREAD

**Issue by etessari** [mailchimp/mc-magento#112]
Hi,
I'm having problems when sending attachments from Magento through Mandrill. 
I have tested some extensions PDF,PNG,JPG. 
When they are received, they are just named "noname" without an extension type
Looking forward a fix.
Thanks

**Comment by gonzaloebiz** [comment]
Hi @etessari 

thanks for your feedback.
Please, follow [this steps](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to report an issue.
I will close the issue, you can re open it when you have the info

Best
