### ISSUE TITLE
Not all audiences are listed as options when creating a new store. 

### ISSUE THREAD

**Issue by carlos-reynosa** [mailchimp/mc-magento#1126]
When creating a new store within the Magento admin, not all audiences are listed when an account has a high number of audiences. I had an account with 16 audiences. Our Mailchimp account has 16 audiences. 

https://github.com/mailchimp/mc-magento/blob/9be772526ccdd9cb95190d5e138f78ec2a04f715/app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/MailchimpstoresController.php#L234

**Comment by carlos-reynosa** [comment]
In order to fix it i had to set a count to a high number while retrieving the list of audiences in the referenced code file. I changed it to this:

`$lists = $api->getLists()->getLists(null,null,null,100);
`

**Comment by Santiagoebizmarts** [comment]
Hello @carlos-reynosa 
This has been fixed by setting the default value in the function declaration on the API library.
https://github.com/mailchimp/mc-magento/blob/develop/lib/Ebizmarts/MailChimp/Lists.php#L133
