### ISSUE TITLE
Test overal functionality PHP 5.6

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#1127]
Use this template to register result:
https://docs.google.com/spreadsheets/d/1HFu6Sp7QYLoQZG9-1_qtjsjYDB9kyGnrDEZU81A1rxw/edit?usp=sharing

**Comment by giorello** [comment]
Testing sheet for PHP 5.6 -> [Here](https://docs.google.com/spreadsheets/d/1EUu6T8O39tg3u0NPSQqttymt4b0k3FfktBtcPsxJFFg/edit?usp=sharing)
