### ISSUE TITLE
Add first date for orders

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento#113]
As the carts, add a first date for the orders, all the orders with a date before this, don't be synced.
In some situations this is useful, p.e. if the store owner uninstall a payment method, this cause that when we try to send an order with this payment method

**Comment by lduh** [comment]
It appears that the order data that's coming over with a specified start date doesn't match the # of customers who are returning in segmentation as orders>0. In this case, Ive got one subscriber with revenue, but 28 are are returning as orders > 0.  the 27 with no revenue are showing no orders.

**Comment by lduh** [comment]
I've set my first date for nov 1, 2016 - I've had three orders since then but only one is showing up in mailchimp.

**Comment by gonzaloebiz** [comment]
Hi @lduh 

are you sure that the orders are completed and not contains grouped or bundle products?
I just re check this, and works ok for me.

Can you have the request.log files?

Best

**Comment by lduh** [comment]
Both orders missing contain only simple products and are completed. @takzilla can you help me pull logs?
