### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'results'

### ISSUE THREAD

**Issue by VISHNUMR3841** [mailchimp/mc-magento#1131]
i am trying to make code that can answer my questions, but i facing some errors , im new to python so help me pls

#my program

import wolframalpha
input = input("questions:")
client = wolframalpha.Client("454LTJ-H9R58QG3G2")
res = client.query(input)
answer = next(res.results).text
print(answer)

when i ask a question like:
 questions:5+7
Traceback (most recent call last):
  File "C:/Users/user/AppData/Local/Programs/Python/Python38/python 8.py", line 5, in <module>
    answer = next(res.results).text
AttributeError: 'coroutine' object has no attribute 'results'

**Comment by VISHNUMR3841** [comment]
i forget to mension that im using python 3.8.1

**Comment by gonzaloebiz** [comment]
Wrong repo
