### ISSUE TITLE
Loading animation remains forever if there are no lists in the account after placing API Key

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#1136]
### Preconditions

1. Mailchimp For Magento 1.1.18
2. Magento 1.9.4.3

### Steps to reproduce

1. Create new Mailchimp account
2. Set up API Key in module configuration.

### Expected result

1. Option "Select Mailchimp List" should be displayed

### Actual result

1. Loading animation remains forever.

**Comment by giorello** [comment]
I was no able to replicate this issue, I tried with M1.9.4.3 and M1.9.4.1 with update and non updated modules to the last changes. 
Also I tried to replicate this in Firefox and Chrome, without success, this seems to be working fine with all those enviroments that I tried.

Do you have any other precondition or data that could help me to replicate this?

Regards, 
Javier Giorello.
