### ISSUE TITLE
Mulitple newsletter subscription confirmation emails sent

### ISSUE THREAD

**Issue by cwilson-S48** [mailchimp/mc-magento#1137]
When opting-in to receive newsletters multiple success messages are sent as well as multiple emails to the customer. One appears to originate from 

> \Mage_Newsletter_ManageController::saveAction

The other two from 
> \Ebizmarts_MailChimp_Model_Observer::handleSubscriber

### Preconditions
1. Magento Enterprise 1.14.3.2
2. MailChimp 1.1.13

### Steps to reproduce
1. Log in as a customer
2. Go to the customer's account and update their newsletter subscription preferences
3. Using a form set `is_subscribed` to 1 and call the /newsletter/manage/save/ action 

### Expected result
1. One success message to be displayed and one email to be sent to the customer's email

### Actual result
Three success messages are displayed and three emails are sent
![Screenshot 2020-01-14 at 14 46 14](https://user-images.githubusercontent.com/45945751/72353947-c8ee8000-36dc-11ea-93ca-719600ea64cf.png)

**Comment by gonzaloebiz** [comment]
Hi @cwilson-S48 

thanks for choosing our extension.
Please update the extension to the current version (1.1.18) and confirm the issue.
We have a lot of fixes since your version (p.e. https://github.com/mailchimp/mc-magento/issues/873)


Best

**Comment by cwilson-S48** [comment]
Hi @gonzaloebiz 

I've now upgraded to 1.1.18, however I'm getting even more messages than before

![Screenshot 2020-01-15 at 15 30 56](https://user-images.githubusercontent.com/45945751/72447220-d7a46800-37ac-11ea-868d-ba7cdeee64eb.png)

Any suggestions would be much appreciated!

**Comment by gonzaloebiz** [comment]
Hi @cwilson-S48 

sorry but i don't recognize this dashboard, where i can find it?
And what this means?
![image](https://user-images.githubusercontent.com/6222792/72452311-1b42a600-379c-11ea-8d4d-473fc3584ffc.png)

**Comment by Santiagoebizmarts** [comment]
Hello @cwilson-S48 

This is not happening in our tests. Do you have any customization or other third party extension that might be affecting this behavior?
Please give us more information to try to replicate it.
These are the messages I am getting:
![Screen Shot 2020-01-16 at 14 14 33](https://user-images.githubusercontent.com/8330778/72547077-ac804e00-386a-11ea-8f0a-150e1c4f3d4f.png)
