### ISSUE TITLE
[1.1.15] Not compatible with MySQL 5.5

### ISSUE THREAD

**Issue by aeu** [mailchimp/mc-magento#1138]
Version 1.1.15 is not compatible with MySQL 5.5

### Preconditions
1. MySQL 5.5

### Steps to reproduce
Try to install or upgrade to 1.1.15.

### Expected result
1. It should work

### Actual result
1. Exception.  Logfile contains:

Error in file: "html/app/code/community/Ebizmarts/MailChimp/sql/mailchimp_setup/mysql4-upgrade-1.1.14-1.1.15.php" - SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'

As mentioned in https://github.com/mailchimp/mc-magento/issues/924, the reason this happens is because the upgrade script creates the table 'mailchimp_interest_group' with two DATETIME fields, 'created_at' and 'updated_at'.  The default value for both these fields is set to CURRENT_TIMESTAMP.

The installer fails because CURRENT_TIMESTAMP was added in MySQL 5.6 and is invalid for MySQL 5.5.

**Comment by gonzaloebiz** [comment]
Hi @aeu 

please take a look at https://docs.magento.com/m1/ce/user_guide/magento/system-requirements.html

As you can see, you need mysql 5.6

![image](https://user-images.githubusercontent.com/6222792/72805759-5cbad180-3c32-11ea-921e-e056645960bc.png)
