### ISSUE TITLE
Abandoned carts not sending - No Carts will be synced until the store is completely synced

### ISSUE THREAD

**Issue by Jens-Bourgeois** [mailchimp/mc-magento#1144]
### Preconditions

1. Magento version 1.9.3.4

### Steps to reproduce

1. I verified there are abandoned carts in Magento ready to be sent (via reports)
2. Cronjob is running

### Expected result

1. The carts should be send to MailChimp.

### Actual result

1. The carts are not send to MailChimp.
In the logs I see: "No Carts will be synced until the store is completely synced"

I debugged the code and I don't understand when the carts can actually be send.

When the sync is running there's is a value set in the core_config_data to "1".
When the sync is finished this value changes to the date it is finished, e.g "2020-01-28 15:28:41"

In code I can see this:

if ($helper->getMCIsSyncing($mailchimpStoreId)) {
                    $helper->logBatchStatus('No Carts will be synced until the store is completely synced');

So even when a date is set in this value and not the value "1", this is still true it seems and carts won't be send.

Anyone that can clarify?

Thanks!

**Comment by Santiagoebizmarts** [comment]
Hello @Jens-Bourgeois 
This filter is not available in our latest release.
Please avoid installing unfinished releases.

Kind Regards.
