### ISSUE TITLE
Javascript error in campaignCatcher.js

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#1147]
### Preconditions

1. Mailchimp for Magento 1 - 1.1.18
2. Magento 1.9.4.3

### Steps to reproduce

1. Install extension
2. Access front end with Chrome and open developer console

### Expected result

No errors shown in the console.

### Actual result

![Screen Shot 2020-02-10 at 13 43 27](https://user-images.githubusercontent.com/8330778/74170400-9b2d2600-4c0b-11ea-8f11-3cd286d7e86b.png)

**Comment by giorello** [comment]
Closed in Pull Request #1151 .
