### ISSUE TITLE
Get URL for MailChimp store based on configurations in stead of current URL

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#115]

**Comment by lduh** [comment]
Where is this set in configurations?

**Comment by Santiagoebizmarts** [comment]
@lduh The url is now retrieved from **System -> Configuration -> GENERAL -> Web -> Unsecure -> Base URL** in stead of simply getting it from the browser in order to be more Magento friendly.

**Comment by lduh** [comment]
Looks good, https://cl.ly/1I023Q0H0q1Z matches https://cl.ly/0t1F0U3b3K31
