### ISSUE TITLE
Sync order with deleted products

### ISSUE THREAD

**Issue by dimitrilongo** [mailchimp/mc-magento#1152]
### Preconditions
1. Magento 1.9.4.1
2. Mailchimp 1.1.18

### Steps to reproduce
1. Sync orders with deleted products 

### Expected result
1. sync order

### Actual result
1. Mailchimp error  : A product with the provided ID does not exist in the account for this list.

Hello, 

Don't know if it's normal behavior, but when i try to sync order (from 2014) many are ignored, i investigate, and it seems product **deleted** (not desactivated) belong to orders provide a mailchimp error `A product with the provided ID does not exist in the account for this list`

is there a workaround to include these orders ?

Thanks

**Comment by Santiagoebizmarts** [comment]
Hello @dimitrilongo 
A new version has been released today. I was not able to replicate this in it.
There were several modifications in the order sending process and I think it would be a good idea for you to try it. Find it at https://github.com/mailchimp/mc-magento/releases/tag/1.1.19

If this continues to happen we can reopen this with more information on how we can replicate it.

Regards.
