### ISSUE TITLE
Warning: include(Ebizmarts/MailChimp/Model/Resource/Ecommercesyncdata/Promorules/Collection.php): failed to open stream: No such file or directory  in /data/web/jenkins/public/builds/current/lib/Varien/Autoload.php on line 94

### ISSUE THREAD

**Issue by Jens-Bourgeois** [mailchimp/mc-magento#1156]
### Preconditions

1. Magento version 1.9.3.1
2. PHP 7.1.33-9
3. MySQL 5.6.37-82.2

### Steps to reproduce

1. Running "mailchimp_bulksync_ecommerce_data" cronjob

### Expected result

1. Run without errors

### Actual result

1. Get following error in log (system.log)

Warning: include(Ebizmarts/MailChimp/Model/Resource/Ecommercesyncdata/Promorules/Collection.php): failed to open stream: No such file or directory  in /data/web/jenkins/public/builds/current/lib/Varien/Autoload.php on line 94

Problem seems to be the following lines:

app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php line 476
        $collection = Mage::getResourceModel('mailchimp/ecommercesyncdata_promocodes_collection');
should be
        $collection = Mage::getResourceModel('mailchimp/ecommercesyncdata_promoCodes_collection');

Note the camelcasing in promoCodes

app/code/community/Ebizmarts/MailChimp/Model/Api/PromoRules.php line 458
        $collection = Mage::getResourceModel('mailchimp/ecommercesyncdata_promorules_collection');
should be
        $collection = Mage::getResourceModel('mailchimp/ecommercesyncdata_promoRules_collection');

Note the camelcasing in promoRules

**Comment by Santiagoebizmarts** [comment]
Hello @Jens-Bourgeois 

Thanks for reaching us.
This will be resolved for the next release.

Kind Regards.

**Comment by Jens-Bourgeois** [comment]
Hello @Santiagoebizmarts 
Thanks for confirming, any idea when this release might be?

**Comment by Santiagoebizmarts** [comment]
I think that at the beginning of April we could be ready if there are no significant obstacles.

Regards.
