### ISSUE TITLE
Order Notifications flow in Mailchimp not functioning as expected

### ISSUE THREAD

**Issue by Jens-Bourgeois** [mailchimp/mc-magento#1161]
### Preconditions

1. Magento version 1.9.3.1
2. PHP 7.1.33-9
3. MySQL 5.6.37-82.2

### Steps to reproduce

1. Enable Order Notification Flow in Mailchimp
2. Place order in Magento
3. Ship order in Magento

### Expected result

1. Receive order, invoice, shipment mail from Mailchimp

### Actual result

1. We don't receive the shipment mail from Mailchimp.
When checking the data that is being sent from Magento to Mailchimp, I can see that there is no "fullfillment_status" parameter being sent.
According to the documentation here: https://mailchimp.com/help/test-or-troubleshoot-order-notifications/
The following parameters need to be send to Mailchimp:
financial_status: pending,
fulfillment_status: shipped

2. The billing and shipping addres is also missing:

<img width="818" alt="Screenshot 2020-03-12 at 16 32 38" src="https://user-images.githubusercontent.com/38660465/76539000-73d2ae80-6480-11ea-9c48-bf28fba7b574.png">

**Comment by Santiagoebizmarts** [comment]
Hello @Jens-Bourgeois 

Thanks for contacting us.
These values should be being sent.
What version of Mailchimp For Magento are you testing?

Kind Regards.

**Comment by sudotrin** [comment]
Hi ya'll long time no speak! I'm having the same issue.

Magento 1.9.4.4
Mailchimp v1.1.20
PHP 7.2.30

**Comment by gonzaloebiz** [comment]
Close the issue until news
