### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function Ebizmarts_MailChimp_Helper_Curl::curlExec()

### ISSUE THREAD

**Issue by ClickCons** [mailchimp/mc-magento#1163]
Hi, you have a bug in your release version 1.1.19:

[Tue Mar 24 15:34:33.380772 2020] [fcgid:warn] [pid 15966] [client 88.12.25.192:46304] mod_fcgid: stderr: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Ebizmarts_MailChimp_Helper_Curl::curlExec(), 1 passed in /var/www/clients/client1/web1/web/lib/Mandrill/Mandrill.php on line 158 and at least 2 expected in /var/www/clients/client1/web1/web/app/code/community/Ebizmarts/MailChimp/Helper/Curl.php:22, referer: https://www.xxx.es/contacts

I have overwritten the release with the development version and the error no longer comes out.
But I think it is important that you adjust the release to avoid problems.
Thanks!!

**Comment by Santiagoebizmarts** [comment]
Hello @ClickCons 

Thanks for reaching us.
This is an issue we are aware of and we are accelerating the next release to get it sorted for everyone.

In the meantime the fixes can be applied as in:
https://github.com/mailchimp/mc-magento/pull/1158
https://github.com/mailchimp/mc-magento/pull/1160

Stay safe.
