### ISSUE TITLE
Problem in Zendesk

### ISSUE THREAD

**Issue by ClickCons** [mailchimp/mc-magento#1164]
Hi,
Our contact forms are send automatically to Zendesk.
Since we updated with the latest release of your plugin (Version 1.1.19) the email headers with the customer information that opens the ticket disappear.
This means that Zendesk cannot retrieve the information of the person who opened the ticket (who send the contact form), as a sender it puts us ourselves and it is impossible for us to manage.

Hope you can check it for the new release.
Greetings and Thanks.

**Comment by Santiagoebizmarts** [comment]
Hello @ClickCons 

This sounds like a problem you are experiencing on the Mandrill side of the extension.
If this is right please replicate the following changes:
https://github.com/mailchimp/mc-magento/pull/1158
https://github.com/mailchimp/mc-magento/pull/1160

We are working to get a release with these changes as soon as possible.

Stay safe.

**Comment by m-overlund** [comment]
This and related issues, is still not solved.
Emails from Magento contact forms are sent without replyTo header - this is standard Magento functionality.

\app\code\core\Mage\Contacts\controllers\IndexController.php L:62-104
```
$post = $this->getRequest()->getPost();
...
                $mailTemplate->setDesignConfig(array('area' => 'frontend'))
                    ->setReplyTo($post['email'])
```

The posters/customers email is by default set as replyto address.
However Mandrill does not respect this, hence emails to Zendesk etc., does not work.

Using Magento 1.9.4.5 with latest Mandrill (Mailchimp) module v1.1.22
