### ISSUE TITLE
Deadlock with newOrder Observer

### ISSUE THREAD

**Issue by viable-hartman** [mailchimp/mc-magento#1175]
The newOrder observer randomly deadlocks on order placement when the bulk api product sync is also running.  Thus, I'm assuming the bulk sync is performing a delete that does table level locking, OR READ locking on the mailchimp_ecommerce_sync_data table is used during the bulk sync.

The event used to trigger the  newOrder Observer is poorly chosen as it injects Mailchimp code into core magento place order transaction, thus causing rollback and other issues on failure.  From looking at the code, it really seems **sales_order_invoice_pay** or **sales_order_save_after** with some code checks would be more appropriate and a bit safer.

### Preconditions
Magento 1.9.4.5
PHP 7.2
MySQL 5.7
Latest MailChimp extension

Confirmed all indexes are on the tables, so if this is an INDEX issue, it's due to one that never existed, but at this point I'm not sure it is an INDEX issue.

Disabling Ecommerce Sync makes the issue go away, so its definitely the **newOrder** observer paired with the bulk sync cron causing this.  Also, the */5 bulk sync cron seems a bit excessive, don't you think?

### Steps to reproduce
This is difficult as it happens to random checkouts, but the gist is as follows...
1.  When a customer is checking out with an item that is also being synced (or deleted) by the bulk sync cronjob, deadlock occurs.
1. So basically start a bulk sync with a particular item, and checkout with that item simultaneously.

### Expected result
1. Deadlocks does not occur, payment processes, and order is saved.
1. The event **sales_order_place_after** is a poor choice as it injects your code into the main transaction, so a failure will lead to gateway payments without orders in magento due to transaction rollback.  At the very least, don't use this event.

### Actual result
1. Deadlock occurs
1. Place order transaction rolls back leaving a charge in payment provider with no order in Magento.
1. Observers depending on this order existing, now all throw errors due to its rollback.

```
PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /var/www/html/my-store.com/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
.
.
.
#7 /var/www/html/my-store.com/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(433): Zend_Db_Adapter_Abstract->update('mailchimp_ecomm...', Array, '(id='254447')')
#8 /var/www/html/my-store.com/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Core_Model_Resource_Db_Abstract->save(Object(Ebizmarts_MailChimp_Model_Ecommercesyncdata))
#9 /var/www/html/my-store.com/app/code/community/Ebizmarts/MailChimp/Model/Ecommercesyncdata.php(65): Mage_Core_Model_Abstract->save()
#10 /var/www/html/my-store.com/app/code/community/Ebizmarts/MailChimp/Model/Api/ItemSynchronizer.php(106): Ebizmarts_MailChimp_Model_Ecommercesyncdata->saveEcommerceSyncData('18360', 'PRO', 'f99cbba60c37cfd...', NULL, NULL, 1, NULL, NULL, NULL, false, NULL, true)
#11 /var/www/html/my-store.com/app/code/community/Ebizmarts/MailChimp/Model/Api/ItemSynchronizer.php(180): Ebizmarts_MailChimp_Model_Api_ItemSynchronizer->_updateSyncData('18360', NULL, NULL, 1)
#12 /var/www/html/my-store.com/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php(523): Ebizmarts_MailChimp_Model_Api_ItemSynchronizer->markSyncDataAsModified('18360')
#13 /var/www/html/my-store.com/app/code/community/Ebizmarts/MailChimp/Model/Observer.php(462): Ebizmarts_MailChimp_Model_Api_Products->update('18040')
#14 /var/www/html/my-store.com/app/code/core/Mage/Core/Model/App.php(1374): Ebizmarts_MailChimp_Model_Observer->newOrder(Object(Varien_Event_Observer))
#15 /var/www/html/my-store.com/app/code/core/Mage/Core/Model/App.php(1353): Mage_Core_Model_App->_callObserverMethod(Object(Ebizmarts_MailChimp_Model_Observer), 'newOrder', Object(Varien_Event_Observer))
#16 /var/www/html/my-store.com/app/Mage.php(451): Mage_Core_Model_App->dispatchEvent('sales_order_pla...', Array)
#17 /var/www/html/my-store.com/app/code/core/Mage/Sales/Model/Order.php(1115): Mage::dispatchEvent('sales_order_pla...', Array)
#18 /var/www/html/my-store.com/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
.
.
.
```

**Comment by Santiagoebizmarts** [comment]
Hello @viable-hartman 
We will take a look at this and get back on this issue.
I don't see how using the events you suggest will get around the deadlock problem since it will be executed pretty much the same amount of times in most sites.

We have seen this behavior on sites that have automated tasks affecting either Orders, Carts, Products or Customers. Is this something that happens in your site?

Kind Regards.

**Comment by Santiagoebizmarts** [comment]
Hello @viable-hartman 
Forgot to mention, you can decrease the amount of items sent per batch. That will decrease the amount of times the table is edited. Would be similar to changing how often the cron job runs.

**Comment by viable-hartman** [comment]
Yes this happens randomly on my live site and does affect customer checkout.

My suggestion of different events is not to solve the deadlock, it is to prevent the order place rollback that causes the customer to be charged but no order gets saved.

**Comment by viable-hartman** [comment]
I have already reduced those numbers.  Though it reduces frequency of the deadlock it still occurs.

**Comment by jammy-git** [comment]
Also having this issue. Had to disable the module for now as it stops the order being created when paid for via PayPal Express!

**Comment by Santiagoebizmarts** [comment]
Hello @jammy-git 

Please mention this in the email to our support as well.
Deadlocks can happen when the same table is modified more times than it can handle.
Sometimes it gets triggered by other extensions modifying very often any of the items sent (Products, Carts, Orders, Customers).

**Comment by buderus199** [comment]
@jammy-git same thing here. Having problems with orders paid with PayPal not being saved in Magento. @Santiagoebizmarts how can we speed up solving this issue?

**Comment by Santiagoebizmarts** [comment]
Hello @buderus199 

This has not been identified as an issue in the latest version yet.
We need full report on the new deadlocks as they can happen in many different places and some times it is triggered due to conflicts with other third party extension.
Please reach our support at mailchimp@ebizmarts-desk.zendesk.com.

Regards.

**Comment by viable-hartman** [comment]
@Santiagoebizmarts what more do you need?

I can tell you the deadlock is due to your newOrder observer doing item updates on sales_order_place_after to your own table, which I believe is mailchimp_ecommerce_sync_data. 

I can tell you that your own cron job set to run */5 is the other process accessing it.

I can tell you its likely the delete code that was added causing it.

I can say setting your database transaction isolation to READ COMMITTED helps the situation a bit, but that isn't always possible if you are running a Galera cluster in master-master mode.

I can tell you the reason the orders don't save is because the deadlock caused by this extension causes the default Magento order payment transaction to rollback, with or without any other extensions, and I can tell you that it certainly doesn't do that without your extension.

I provided you the only exception dump there is to provide, so not sure what else you need to make this an issue especially now that multiple stores have confirmed it as an issue?

I also suggested changing the observer so the extension at least does not cause the transaction rollback, which would not fix the Deadlock, but at least processed orders would be saved.  Seems like a good start, but what else do you need?

**Comment by Santiagoebizmarts** [comment]
Hello @viable-hartman 

I understand this can happen in our observer and that is why I asked the following:

> We have seen this behavior on sites that have automated tasks affecting either Orders, Carts, Products or Customers. Is this something that happens in your site?

Do you have an update on this?

We need to set the items as modified therefore there is no way to get around that observer.
We can do the change you mention and see if that helps on the order processing but the deadlock problem will remain and that is what I wanted to help you guys solving.

Kind Regards.

**Comment by Santiagoebizmarts** [comment]
Hello @viable-hartman @jammy-git @buderus199 

We have been studying the case and I have a request for you.
Please run the following command in your SQL console to validate your settings are not the ones causing this problem.
`SHOW VARIABLES LIKE '%timeout%';`

We will work on a fix on the observer method as you requested @viable-hartman and we will also continue studying this to find a definitive solution.

Regards.

**Comment by viable-hartman** [comment]
> SHOW VARIABLES LIKE '%timeout%';

+-------------------------------------+----------+
| Variable_name                       | Value    |
+-------------------------------------+----------+
| connect_timeout                     | 10       |
| delayed_insert_timeout              | 300      |
| have_statement_timeout              | YES      |
| innodb_flush_log_at_timeout         | 1        |
| innodb_lock_wait_timeout            | 50       |
| innodb_print_lock_wait_timeout_info | OFF      |
| innodb_rollback_on_timeout          | OFF      |
| interactive_timeout                 | 28800    |
| lock_wait_timeout                   | 31536000 |
| net_read_timeout                    | 30       |
| net_write_timeout                   | 60       |
| rpl_stop_slave_timeout              | 31536000 |
| slave_net_timeout                   | 3600     |
| thread_pool_idle_timeout            | 60       |
| wait_timeout                        | 28800    |
| wsrep_RSU_commit_timeout            | 5000     |
+-------------------------------------+----------+

mostly just defaults here, are there different settings you'd recommend?  I know specifically you're looking for innodb_lock_wait_timeout, right?

**Comment by buderus199** [comment]
@Santiagoebizmarts I have sent you my exception log and server timeouts in support ticket #31868.

**Comment by Santiagoebizmarts** [comment]
Report ticket 31868:
MariaDB [(none)]> SHOW VARIABLES LIKE '%timeout%';
+---------------------------------------+----------+
| Variable_name                         | Value    |
+---------------------------------------+----------+
| connect_timeout                       | 10       |
| deadlock_timeout_long                 | 50000000 |
| deadlock_timeout_short                | 10000    |
| delayed_insert_timeout                | 300      |
| idle_readonly_transaction_timeout     | 0        |
| idle_transaction_timeout              | 0        |
| idle_write_transaction_timeout        | 0        |
| innodb_flush_log_at_timeout           | 1        |
| innodb_lock_wait_timeout              | 50       |
| innodb_rollback_on_timeout            | OFF      |
| interactive_timeout                   | 28800    |
| lock_wait_timeout                     | 86400    |
| net_read_timeout                      | 30       |
| net_write_timeout                     | 60       |
| rpl_semi_sync_master_timeout          | 10000    |
| rpl_semi_sync_slave_kill_conn_timeout | 5        |
| slave_net_timeout                     | 60       |
| thread_pool_idle_timeout              | 60       |
| wait_timeout                          | 28800    |

**Comment by giorello** [comment]
As quick improvement of this functionality I had added a Try/Catch to avoid the order's transaction rollback and let magento continue with the placement process in case of a deadlock. Also I had added a filter to avoid updating products already marked as modified in our Ecommerce Data table.

The changes would include replacing this:
```
foreach ($items as $item) {
    if ($this->isBundleItem($item) || $this->isConfigurableItem($item)) {
        continue;
    }

    $mailchimpStoreId = $helper->getMCStoreId($storeId);
    $productId = $item->getProductId();
    $dataProduct = $this->getMailchimpEcommerceSyncDataModel()->getEcommerceSyncDataItem(
        $productId,
        Ebizmarts_MailChimp_Model_Config::IS_PRODUCT,
        $mailchimpStoreId
    );

    $isMarkedAsDeleted = $dataProduct->getMailchimpSyncDeleted();

    if (!$isMarkedAsDeleted) {
        $apiProducts = $this->makeApiProduct();
        $apiProducts->setMailchimpStoreId($mailchimpStoreId);
        $apiProducts->setMagentoStoreId($storeId);
        $apiProducts->update($productId);
    }
}
```

For this code section:
```
try {
    foreach ($items as $item) {
        if ($this->isBundleItem($item) || $this->isConfigurableItem($item)) {
            continue;
        }

        $mailchimpStoreId = $helper->getMCStoreId($storeId);
        $productId = $item->getProductId();
        $dataProduct = $this->getMailchimpEcommerceSyncDataModel()->getEcommerceSyncDataItem(
            $productId,
            Ebizmarts_MailChimp_Model_Config::IS_PRODUCT,
            $mailchimpStoreId
        );

        $isMarkedAsDeleted = $dataProduct->getMailchimpSyncDeleted();
        $isMarkedAsModified = $dataProduct->getMailchimpSyncModified();

        if (!$isMarkedAsDeleted && !$isMarkedAsModified) {
            $apiProducts = $this->makeApiProduct();
            $apiProducts->setMailchimpStoreId($mailchimpStoreId);
            $apiProducts->setMagentoStoreId($storeId);
            $apiProducts->update($productId);
        }
    }
} catch (Exception $e) {
    $helper->logError($e->getMessage());
}
```

In the file `app/code/community/Ebizmarts/MailChimp/Model/Observer.php:443` (method '`newOrder`').

Regards, 
Javier Giorello.
