### ISSUE TITLE
Missing reply-to header

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#1176]
#491 # Preconditions

1. Mailchimp For Magento 1.1.20
2. Magento 1.9.4.4

### Steps to reproduce

1. Configure Mandrill.
2. Create a new account in order to trigger welcome email.

### Expected result

1. When looking at the headers of the email the reply-to header is missing.
![reply-to](https://user-images.githubusercontent.com/8330778/81296812-d7282980-9048-11ea-861d-160f96a72a0a.png)

### Actual result

Reply-to header missing.

**Comment by m-overlund** [comment]
Any news on this one?
We do not recieve any emails on our shops helpdesks since March 2020, due to the missing reply-to header, resulting in From and to address is the same.

**Comment by lisandroc** [comment]
Hola Santiago: Alguna novedad?
No podemos actualizar por este tema, te agradecería si puedes decirme algo.
Saludos

**Comment by ClickCons** [comment]
@Santiagoebizmarts hay planes para solventarlo? gracias

**Comment by SantiParagarino** [comment]
@ClickCons Ya hay una posible solución siendo probada, estará en la proxima release.

@m-overlund There is a possible solution being tested, it will be available in the next release.

**Comment by lisandroc** [comment]
Gracias Santiago, quedamos a la espera. 
Saludos
