### ISSUE TITLE
1.1.20 PHP Fatal error:  Uncaught Error: Call to undefined method Ebizmarts_MailChimp_Model_Api_Subscribers_MailchimpTags::getHelper() in /app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php:275

### ISSUE THREAD

**Issue by rbrown** [mailchimp/mc-magento#1177]
1.1.20 PHP Fatal error:  Uncaught Error: Call to undefined method Ebizmarts_MailChimp_Model_Api_Subscribers_MailchimpTags::getHelper() in /app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php:275

Stack trace:
#0 /app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php(239): Ebizmarts_MailChimp_Model_Api_Subscribers_MailchimpTags->_addSubscriberData(Object(Ebizmarts_MailChimp_Model_Subscriber), 'name', 'name', 'emal', 'hash')
#1 /app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php(164): Ebizmarts_MailChimp_Model_Api_Subscribers_MailchimpTags->processMergeFields(Array, true)
#2 /app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php(76 in /app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php on line 275

I guess this is fixed by 8a6c6067 but I wanted to 

a) check before I add 1  patch to the version we're running
b) query the name of mysql4-upgrade-1.1.19-1.1.20.php in the commit, in case that messes up upgrading to 1.1.21 later

**Comment by Santiagoebizmarts** [comment]
Thanks for your feedback @rbrown 

In the meantime you can just replace:
`$this->getHelper();`
With
`Mage::helper('mailchimp');`

Kind Regards.

**Comment by rbrown** [comment]
Yes, I started the cron up again and it's happy, thank you

**Comment by giorello** [comment]
Hello @rbrown.

This issue will get solved with our next release (v1.1.21). As you can see [here](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php#L179), the method name had been changed to 'getMailchimpHelper' and this issue doesn't happen anymore.

Thanks for your feedback.

Regards, 
Javier Giorello.
