### ISSUE TITLE
If the recipient doesn't exists in the email queue skip it

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#118]
Some installations seem to have corrupted data in the email queue.

**Comment by lduh** [comment]
@Santiagoebizmarts can you give me a little context on how to test this?

**Comment by Santiagoebizmarts** [comment]
@lduh 
I saw two cases where Mandrill was not working because some corrupted data in the core_email_queue database table. When the extension was trying to get the email recipients, they were not there and the extension failed.
The fix is simply a verification to see if the recipients does exist before moving forward with the sending to prevent failure.
