### ISSUE TITLE
Error in Ebizmarts_MailChimp_CartController

### ISSUE THREAD

**Issue by fabianaromagnoli** [mailchimp/mc-magento#1182]
### Preconditions

1. mailchimp/mc-magento 1.1.20
2. Magento 1.9.4.5
3. PHP 7.0

### Description
I got the following error:
Error: Uncaught exception 'Error' with message 'Call to undefined method Ebizmarts_MailChimp_CartController::_()' in /home/jeep/public_html/releases/99/magento/app/code/community/Ebizmarts/MailChimp/controllers/CartController.php:40

Seems like there's a typo in two lines in CartController (line 40 and line 65):
`$this->_("...")`
instead of 
`$this->__("...")`

**Comment by Santiagoebizmarts** [comment]
Hello @fabianaromagnoli 

Thanks for raching us with this feedback.
This will be solved in the next release. In the meantime as you correctly suggest changing the lines mentioned will solve this.

Kind Regards.
