### ISSUE TITLE
the subscription could not be applied

### ISSUE THREAD

**Issue by urifoox** [mailchimp/mc-magento#1183]
One of our customers sent us the following screenshot which confused us a bit.
Do you know what triggers the "The subscription could not be applied" notification on the order confirmation screen?

![image](https://user-images.githubusercontent.com/22828430/85074122-a7109200-b181-11ea-8bb1-9c714aa847f7.png)

**Comment by gonzaloebiz** [comment]
Please follow the [issue guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines)

Best

**Comment by urifoox** [comment]
Took 13 months to tell me this? Thanks!
