### ISSUE TITLE
Unsubscribed customers are not synchronised back to Magento

### ISSUE THREAD

**Issue by it6aid** [mailchimp/mc-magento#1185]
### Preconditions
1. mailchimp/mc-magento 1.1.20
2. Magento 1.9.4.2
3. PHP 7.0

### Description
Subscribers unsubscribed from Mailchimp but not synchronised to Magento. They still appear as subscribed in Magento.

**Comment by Santiagoebizmarts** [comment]
Hello @it6aid 

Please make sure the webhook has been correctly configured.
You can contact our support at mailchimp@ebizmarts-desk.zendesk.com for help on this.

If you are certain everything is correctly configured please add the information to the issue.

Kind Regards.
