### ISSUE TITLE
Observer newsletter_subscriber_save_after run multiple time caused the Subscriber model action always return status 500

### ISSUE THREAD

**Issue by tuyennn** [mailchimp/mc-magento#1186]
### Preconditions

1. Magento ver. 1.9.4.5
2. Mailchimp For Magento v1.1.20

### Steps to reproduce

1. My Account -> Newsletter subscription
2. Do subscribe or unsubscribe

### Expected result

1. The subscription could been saved successfully
2. Redirect to customer/account/

### Actual result

1. Blank on page due 500 status

### Investigate
1. newsletter_subscriber_save_after Observer could be dispatched and run for multiple times
2. Prevent the observer run for multiple times, let it run once then the problem could be fixed

**Comment by gonzaloebiz** [comment]
Hi @tuyennn 

i'm trying with Magento 1.9.4.5 with the mageone patches with php 8.0 and works Ok for me.
Can you please give more information to try to reproduce.

Best
