### ISSUE TITLE
Allow custom mailchimp attributes to be deleted from back end.

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#119]

**Comment by lduh** [comment]
@Santiagoebizmarts can you give the a use case for this?

**Comment by Santiagoebizmarts** [comment]
@lduh 
When uninstalling the extension some attributes required a database query in order to remove them.
Now they can be deleted from Magento back end at **Catalog -> Attributes -> Manage Attributes**
<img width="574" alt="screen shot 2017-01-11 at 11 32 48" src="https://cloud.githubusercontent.com/assets/8330778/21852423/b8e7baf2-d7f1-11e6-812d-b8ce3980e1c9.png">

Clicking on them allows this with a "Delete Attribute" option at the top of the page.
