### ISSUE TITLE
Frequent deadlocks on mailchimp_ecommerce_sync_data

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#1190]
M1.9.4.x
php 7.2
Version 1.1.20

We see frequent deadlocks on mailchimp_ecommerce_sync_data

Which is strange because the mailchimp extension is the only code accessing this data .... so in effect the same extension is locking itself out?

### Preconditions
1. install and use

### Steps to reproduce
1. install and use

### Expected result
No DB lock or at least a retry

### Actual result

1213 Deadlock found when trying to get lock; try restarting transaction, query was: UPDATE `mailchimp_ecommerce_sync_data` SET `related_id` = \?, `type` = \?, `mailchimp_store_id` = \?, `mailchimp_sync_error` = \?, `mailchimp_sync_delta` = '2020-09-02 09:28:59', `mailchimp_sync_modified` = \?, `mailchimp_sync_deleted` = \?, `mailchimp_token` = \?, `batch_id` = \?, `deleted_related_id` = \?, `mailchimp_synced_flag` = \? WHERE (id='15854797')

This is

innodb_lock_wait_timeout = 3600

so even after 3600 seconds it cannot access the table

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Could you share your batch amounts configured in the extension?

Kind Regards,

**Comment by seansan** [comment]
everywhere 50

**Comment by ste88** [comment]
I have same problem.

M1.9.3.1
Version 1.1.20

On place order, after creation of order, the mailchimp code generates frequently exception deadlock that prevents the creation of order.

**Comment by seansan** [comment]
I sent all debug and all data

no response ..

**Comment by sprankhub** [comment]
Check if https://github.com/mailchimp/mc-magento/pull/1178/ helps.

**Comment by gonzaloebiz** [comment]
Look at #1178
