### ISSUE TITLE
Change dom loaded to native

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#1191]
js/ebizmarts/mailchimp/campaignCatcher.js

if (document.loaded) {
    getCampaign();
} else {
	document.addEventListener('DOMContentLoaded', getCampaign)
}

**Comment by gonzaloebiz** [comment]
Hi @seansan 

why you need this? Can you please explain?

Best

**Comment by gonzaloebiz** [comment]
Close the issue until news
