### ISSUE TITLE
Uncaught Error: Call to undefined method Ebizmarts_MailChimp_Model_Api_Products::joinQtyAndBackorders() 

### ISSUE THREAD

**Issue by giorello** [mailchimp/mc-magento#1193]
_Uncaught Error: Call to undefined method Ebizmarts_MailChimp_Model_Api_Products::joinQtyAndBackorders() in /home/gear2win/httpdocs/app/code/community/Ebizmarts/MailChimp/Helper/Data.php:2824_

### Preconditions
1. Magento 1.9.x
2. Mailchimp extension 1.1.20

### Solution
Replace line 
`$apiProducts->joinQtyAndBackorders($productCollection);`
For this one
`$productCollection->joinQtyAndBackorders($productCollection);`

This is inside the method _isMissingProductLowerThanId_

**Comment by roberto-ebizmarts** [comment]
Solved here: https://github.com/mailchimp/mc-magento/commit/fcc8dc7b98061aa5cc78b3aab0188d94ba8a6da2
