### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class 'Mage_Mailchimp_Helper_Data' not found in app/Mage.php:550

### ISSUE THREAD

**Issue by vmishra341** [mailchimp/mc-magento#1198]
Hi,

We are using MailChimp and Mandrill module version 1.1.8 on our production Magento1 website. When we tried to disable the MailChimp module using module config file at etc/module folder we are getting below error on frontend website pages.

[Tue Dec 08 18:37:45.594678 2020] [php7:error] [pid 28423:tid [client 10.0.0.204:38442] uri:/index.php ua:'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)' PHP Fatal error: Uncaught Error: Class 'Mage_Mailchimp_Helper_Data' not found in /app/Mage.php:550\nStack trace:\n#0 /app/code/core/Mage/Core/Model/Layout.php(324): Mage::helper('mailchimp')\n#1 /app/code/core/Mage/Core/Model/Layout.php(214): Mage_Core_Model_Layout->_generateAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))\n#2 /app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))\n#3 /app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))\n#4 /app/code/local/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()\n#5 /app/code/core/Mage/Catalog/controllers/CategoryController.php(148): Mage_Core_Controller in /app/Mage.php on line 550

I have already cleared all the cache on server but still i am facing same issue. Please let me know how can I resolve that issue?
I have already check the layout and template files and not found any calling of helper class there apart from MailChimp module file.

**Comment by vmishra341** [comment]
I have also checked MailChimp helper class not called else where in the website. Please check the below screenshot:-
![image](https://user-images.githubusercontent.com/56992673/101594087-166f8c00-3a17-11eb-952d-b59e5a039663.png)

**Comment by SantiParagarino** [comment]
Hello @vmishra341 Please update to the latest release and see if the error continues there.
If that is the case you can contact us to mailchimp@ebizmarts-desk.zendesk.com

Kind regards.
