### ISSUE TITLE
slow querie on mailchimp_errors

### ISSUE THREAD

**Issue by downforce80** [mailchimp/mc-magento#1201]
### Preconditions
1.  Magento ver. 2.3.5-p1
2.  Ebizmarts_MailChimp 102.3.39

### Steps to reproduce
1. using the above config and default setup

### Expected result
1. fast processing queries

### Actual result
1. Our log of slow processing queries (+2 secs) shows the following SQL. This actual one took about 9 secs.
---
SELECT `mailchimp_errors`.* FROM `mailchimp_errors` WHERE (store_id = '8' AND regtype = 'ORD' AND original_id = '39092');
--

**Comment by SantiParagarino** [comment]
Hello,
Please note this repo is for Magento 1 extension.
Seeing your version I see you should have posted at https://github.com/mailchimp/mc-magento2
Also please try to explain better what is going on since this does not add much information for us to understand.

Kind regards.
