### ISSUE TITLE
Bugs in Log 

### ISSUE THREAD

**Issue by HRR1337** [mailchimp/mc-magento#1205]
Using the latest version of Mailchimp, and get the following errors:

Notice: Undefined index: category  in /home/User/domains/Domainname/public_html/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php on line 233

Warning: Invalid argument supplied for foreach()  in /home/User/domains/Domainname/public_html/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php on line 233

**Comment by devzorg** [comment]
Just turn off them in error_reporting
