### ISSUE TITLE
Conversion tracking since update = 0

### ISSUE THREAD

**Issue by HRR1337** [mailchimp/mc-magento#1208]
Hi there,

Since upgrading to the last version, i dont have any conversion tracking (0).

Magento 1.9
Mailchimp extension 1.1.21
Onestepcheckout 5.0.1

Thanks,

**Comment by gonzaloebiz** [comment]
Hi @HRR1337 

thanks for your feedback.
Can you please be more specific, give us some examples and how to replicate

Best

**Comment by gonzaloebiz** [comment]
Close the issue until news
