### ISSUE TITLE
Error in Customer Information after disabling Mailchimp via Ebizmarts_Mailchimp.xml

### ISSUE THREAD

**Issue by jcarlosebizmarts** [mailchimp/mc-magento#1213]
### Preconditions

1. Magento 1.9.4.5
2. Mailchimp for Magento v1.1.21

### Steps to reproduce

1. Install Mailchimp for Magento v1.1.21
2. Enable and configure M4M
3. Disable Mailchimp via Ebizmarts_Mailchimp.xml, setting "true" to "false".
4. Flush Cache
5. Check a Customer Details via Magentos Backend

### Expected result

1. Mailchimp is Disabled and you are able to check the customer details.

### Actual result

1. Mailchimp is disabled but customer details can't be open, and an error message appears instead:
<img width="1440" alt="Screen Shot 2021-04-19 at 12 23 09" src="https://user-images.githubusercontent.com/79095377/115261657-2e17f900-a10a-11eb-9eb2-9c5100b84363.png">

[Error.txt](https://github.com/mailchimp/mc-magento/files/6337190/Error.txt)

**Comment by gonzaloebiz** [comment]
This is not a bug, you MUST disable the extension before modify the Ebizmarts_Mailchimp.xml file (magento works this way for all extensions)

Best
