### ISSUE TITLE
Undefined variables after upgrading from 1.1.20 to 1.1.21

### ISSUE THREAD

**Issue by azambon** [mailchimp/mc-magento#1214]
### Preconditions
Magento 1.9.4.5, PHP 7.0 (set to log notices), Mysql 5.7

### Steps to reproduce
* Install version 1.1.20 of this plugin;
* upgrade to version 1.1.21
* run the crons

### Expected result
No errors should be reported in the logs

### Actual result
There are four repeated errors:
* Notice: Undefined variable: scopeId  in /app/code/community/Ebizmarts/MailChimp/Helper/Migration.php on line 731
* Notice: Undefined variable: scope  in /app/code/community/Ebizmarts/MailChimp/Helper/Migration.php on line 731
* Notice: Undefined variable: scopeId  in /app/code/community/Ebizmarts/MailChimp/Helper/Migration.php on line 732
* Notice: Undefined variable: scope  in /app/code/community/Ebizmarts/MailChimp/Helper/Migration.php on line 732

Indeed in the affected file ( https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Migration.php#L734 ) those variables are used without ever being initialized.

Maybe those should have been $store and $storeId ?

**Comment by azambon** [comment]
Hello @Santiagoebizmarts 

I found this bug while upgrading from 1.1.20 to 1.1.21, so it's not a new installation. That's why I mentioned in the steps to reproduce to first install version 1.1.20, then upgrade to 1.1.21

**Comment by Santiagoebizmarts** [comment]
Hello @azambon 
That bug should only trigger when updating from a very old version (1.1.6) or for new installations.
Given your description I can only think of this happened if the 1.1.20 installation was recent and before getting the extension fully working you updated.

I am countint that as a new installation as well.

The only case where you may not want to run the query I mentioned is if you had a prior version to 1.1.6 with the extension fully configured and working.

**Comment by azambon** [comment]
Hello @Santiagoebizmarts 

this is a very old installation, which has been progressively upgraded.

It started out with ebizmarts/magemonkey:
june 2016: version 1.2.2
october 2016: version 1.2.7
july 2017: switched to ebizmarts/mc-magento version 1.1.7 and then immediately 1.1.8
december 2017: version 1.1.10
march 2018: version 1.1.11, immediately reverted back to 1.1.10 (there must have been some issue, can't remember)
june 2020: version 1.1.20
april 2021: version 1.1.21

I wouldn't call it a "new" installation by any means.

I see that in the https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/sql/mailchimp_setup/mysql4-upgrade-1.1.20-1.1.21.php file the module sets the `mailchimp/general/migrate_from_1120` config flag. And indeed in the DB that one is the **only** flag that I find, there is no flag for the older migrations.

That flag is then read in https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Migration.php#L61 , which invokes the buggy method `_migrateFrom1120()`

The statement "That bug should only trigger when updating from a very old version (1.1.6) or for new installations." would seem to me to apply to the `_migrateFrom116` method, but the bug is in the `_migrateFrom1120` method.

**Comment by SantiParagarino** [comment]
Hello @azambon 

I see your point and you are right, my assumption was incorrect. Sorry about that.

For your particular problem you will get around it by modifying this line: https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Migration.php#L734

With this code:
`$listId = $helper->getGeneralList($storeId, 'stores');`
