### ISSUE TITLE
Simple products do not redirect to grouped level products

### ISSUE THREAD

**Issue by p-e-gardner** [mailchimp/mc-magento#124]
We installed v1.1.4 of the extension last week and noticed that in the recommended product block simple Magento products do not redirect to the grouped level products.

Instead, it is the native Magento URL that is used for the simple recommended products: https://www.magentocommerce.com/magento-connect/redirect-simple-to-parent.html

To get around this we use the JRD redirect Simple to Parent extension and this resolved the issue. However, it would be far more useful for this to be done at source, instead of having to use more third party extensions.

**Comment by gonzaloebiz** [comment]
Hi @p-e-gardner 

thanks for choosing our extension.
This is out of the scope of the extension, but pull request are welcome if you wish to contribute

Best
