### ISSUE TITLE
Cron Error After Updating From 1.1.17 to 1.1.22

### ISSUE THREAD

**Issue by sprankhub** [mailchimp/mc-magento#1257]
### Preconditions

1. Magento 1.9.4.5
2. PHP 7.4
3. Ebizmarts_MailChimp 1.1.22

### Steps to reproduce
1. Install Ebizmarts_MailChimp 1.1.17
2. Configure stores, lists etc.
3. Update Ebizmarts_MailChimp to 1.1.22, so that `\Ebizmarts_MailChimp_Helper_Migration::_migrateFrom1120` is run.

### Expected result
1. Stuff is migrated, cron works without any errors.

### Actual result
1. The migration leads to an error and the cron stops with an error. Stack trace:

        Cron error while executing mailchimp_bulksync_ecommerce_data:

        MailChimp_HttpError: Method Not Allowed for Api Call: https://us18.api.mailchimp.com/3.0/lists/{{OUR_LIST_ID}}/webhooks/ - The requested method and resource are not compatible. See the Allow header for this resource's available methods. in /var/www/{{OUR_SHOP}}/lib/Ebizmarts/MailChimp.php:413
        Stack trace:
        #0 /var/www/{{OUR_SHOP}}/lib/Ebizmarts/MailChimp/ListsWebhooks.php(69): Ebizmarts_MailChimp->call('lists/{{OUR_LIST_ID}}...', '{"events":{"sub...', 'PATCH')
        #1 /var/www/{{OUR_SHOP}}/app/code/community/Ebizmarts/MailChimp/Helper/Migration.php(742): MailChimp_ListsWebhooks->edit('{{OUR_LIST_ID}}', NULL, NULL, Array, Array)
        #2 /var/www/{{OUR_SHOP}}/app/code/community/Ebizmarts/MailChimp/Helper/Migration.php(74): Ebizmarts_MailChimp_Helper_Migration->_migrateFrom1120(1632918302)
        #3 /var/www/{{OUR_SHOP}}/app/code/community/Ebizmarts/MailChimp/Model/Cron.php(35): Ebizmarts_MailChimp_Helper_Migration->handleMigrationUpdates()
        #4 /var/www/{{OUR_SHOP}}/app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Ebizmarts_MailChimp_Model_Cron->syncEcommerceBatchData(Object(Aoe_Scheduler_Model_Schedule))
        #5 /var/www/{{OUR_SHOP}}/app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
        #6 /var/www/{{OUR_SHOP}}/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
        #7 /var/www/{{OUR_SHOP}}/app/code/local/Xtento/ProductExport/Model/Observer/Cron/Config.php(23): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
        #8 /var/www/share/www.chiptuning.com/chiptuning/shop/app/code/core/Mage/Core/Model/App.php(1374): Xtento_ProductExport_Model_Observer_Cron_Config->addCronjobsToConfig(Object(Varien_Event_Observer))
        #9 /var/www/share/www.chiptuning.com/chiptuning/shop/app/code/core/Mage/Core/Model/App.php(1347): Mage_Core_Model_App->_callObserverMethod(Object(Xtento_ProductExport_Model_Observer_Cron_Config), 'addCronjobsToCo...', Object(Varien_Event_Observer))
        #10 /var/www/share/www.chiptuning.com/chiptuning/shop/app/Mage.php(451): Mage_Core_Model_App->dispatchEvent('default', Array)
        #11 /var/www/{{OUR_SHOP}}/shell/scheduler.php(518): Mage::dispatchEvent('default', Array)
        #12 /var/www/{{OUR_SHOP}}/shell/scheduler.php(37): Aoe_Scheduler_Shell_Scheduler->cronAction()
        #13 /var/www/{{OUR_SHOP}}/shell/scheduler.php(545): Aoe_Scheduler_Shell_Scheduler->run()
        #14 {main}

Fast help would be very much appreciated.

**Comment by sprankhub** [comment]
The issue seems to be that no webhook ID is available for some lists... However, some stores even do not have any list at all, so the current migration process fails every time when a store has no list assigned, which is bad.

**Comment by gonzaloebiz** [comment]
Hi @sprankhub 

can you try applying the associated commits and let me know if works for you?

Best

**Comment by sprankhub** [comment]
Thanks @gonzaloebiz! To be honest, I cannot test any more as I had to fix it myself. However, I pretty much did the same: If the webhook ID was empty, I skipped the webhook migration. Hence, I guess this is fine.
