### ISSUE TITLE
Syncing only newsletter subscribers with Mailchimp in Magento 1.9.4.5 using Ebizmarts plugin

### ISSUE THREAD

**Issue by Sumy1337** [mailchimp/mc-magento#1270]
Hello,

I'm using Magento 1.9.4.5 and the Ebizmarts plugin to connect our store with Mailchimp. We have several thousand registered users on our site, but only about 900 of them are subscribed to our newsletter.

Since Mailchimp charges based on the number of contacts, we only want to sync newsletter subscribers rather than all registered users to keep our list manageable and stay GDPR-compliant. Unfortunately, syncing all users has led us to temporarily disable the integration because of these limitations.

However, this has disrupted our ability to sync product updates and track analytics via Mailchimp, making it difficult to utilize the platform effectively.

Could you advise on how we might adjust the plugin to sync only our newsletter subscribers? Ideally, we want to keep our Magento-Mailchimp connection active but only sync those who have explicitly subscribed to our newsletter.

Any guidance or recommendations on resolving this issue would be greatly appreciated!

Thank you in advance!

**Comment by gonzaloebiz** [comment]
Contact our support team at [mailchimp@ebizmarts-desk.zendesk.com](mailto:mailchimp@ebizmarts-desk.zendesk.com)
