### ISSUE TITLE
Recommend products no images when only configurable product has images

### ISSUE THREAD

**Issue by HRR1337** [mailchimp/mc-magento#140]
I have the following issue. 

I would like to recommend products to my customers in the mailchimp newsletter. Though there arent any product images beceause I only add images to the configurable product and not to the simple variant products; example:

Configurable product: Brand T-Shirt Blue << Has the image
Simple product: Brand T-Shirt Blue Size S << Has no image (uses the configurable product image)
Simple product: Brand T-Shirt Blue Size XL << Has no image (uses the configurable product image)

When someone places an order, its orderings a size (example S). Though this product doesn't have an image beceause in Magento it uses the configurable product image. 

It would be great is Mailchimp uses the configurable product image, so I woudn't need to set for EVERY variant (size) an image.

Thanks!

**Comment by HRR1337** [comment]
I think that only simple products will be added to Mailchimp instead of Configurable products. And let we sell shoes and clothing all with configurable products.. :-)

**Comment by seansan** [comment]
This is extremely important. Failing to support the parent product ..... instead of the child .... is knee capping 60-70% of all Magento sites ... @Santiagoebizmarts 

All reports work like this where the parent contains all the product meta data like the price, image, colour, material, manufacturer etc .... all the nice things you want to filter on in mailchimp or anywhere; the simple products children are empty and contian no data .... other extensions all support this and have an option where one can select for which attribute one wants to take the parent and for which the child

Data to sync settings:

Name            Sync    Data level
attribute1      Yes       From parent if exists
attribute2      Yes       From parent if exists
attribute3      Yes       Child only

**Comment by gonzaloebiz** [comment]
Hi @seansan 

thanks for your feedback,
The repo is open to your contribution, PR are welcome.

Best

**Comment by seansan** [comment]
great! thanks Gonzalo that sounds great. Good that you are going to add is

you are the developer for mailchimp and know the extension best

so we will test and bug fix and contribute if and when it is added .... Let
us know when

**Comment by Santiagoebizmarts** [comment]
This has been fixed in the following commit https://github.com/mailchimp/mc-magento/commit/c6943ecd97a8b07730de13010d1177cfe0964475.
Will be available for the next version.

**Comment by seansan** [comment]
Super

Does this mean that product order data is also sent to MailChimp as part of
the new API? From the parent

For example the attribute brand: is stored on parent level

Price is also stored on parent level

Colour is also stored on parent level

Whilst size and ean and sku come from the child

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Indeed product and order data are being sent if you enable the ecommerce section of the module configuration.

Actually Price and color should be placed in the child.
Price is a required field so it will be in the child for sure.
Color and size are usually why you create configurable products, to have different colors and sizes.

Unfortunately brand is not something that MailChimp API supports.

**Comment by seansan** [comment]
I thought you could select the elements you wanted to sync?

1) Color is not always stored on child. Only sometimes. Size is always. So
important to make that distinction. Or make it possible to make that
distinction.

2) For attibutes we want to send to mailchimp: one should be able to tell
the API/EXTENSION where to get the data from

SKU: parent/child = Setting from CHILD
EAN: parent/child = Setting from CHILD
COLOR: parent/child = Setting from PARENT
BRAND: parent/child = Setting from PARENT
SLEEVELENGHT: parent/child = Setting from PARENT
PRODUCT IMAGE: parent/child = Setting from PARENT
MATERIALS: parent/child = Setting from PARENT
etc etc




On Wed, Mar 22, 2017 at 3:31 PM, Santiagoebizmarts <notifications@github.com
