### ISSUE TITLE
Save Customer - Failure 

### ISSUE THREAD

**Issue by dkraze** [mailchimp/mc-magento#143]
Hi,

I installed 1.1.5 on Magento 1.7.

Now, whenever we try to make an edit to a customer record, it will not allow us to save.
The 'Please Wait...' loading image appears in the middle of the screen and stays there to no end.

When I refresh and log back in (after timeout) the changes are not there.

Magento EAG - Error:
An error occured while rewriting "monkey/adminhtml_customer_edit_tab_memberactivity" : "The original class "Mage_Monkey_Block_Adminhtml_Customer_Edit_Tab_Memberactivity" does not exist" (rewriter: "eval")

**Comment by dkraze** [comment]
EAG - Errors:

An error occured while rewriting "monkey/adminhtml_customer_edit_tab_memberactivity" : "The original class "Mage_Monkey_Block_Adminhtml_Customer_Edit_Tab_Memberactivity" does not exist" (rewriter: "eval")

**Comment by Santiagoebizmarts** [comment]
Hello @dkraze 
This is not a problem with MailChimp For Magento extension.
MageMonkey was not uninstalled properly.
Please check [https://edmondscommerce.github.io/upgrade-from-magento-magemonkey-to-mailchimp/?utm_content=bufferc2f4c&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer](https://edmondscommerce.github.io/upgrade-from-magento-magemonkey-to-mailchimp/?utm_content=bufferc2f4c&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)

Please note this is the repository for MailChimp For Magento so this doesn't belong here. Please check our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) for future issues.

Regards.

**Comment by dkraze** [comment]
I completely uninstalled all reference to Magemonkey and old installation
of mailchimp4magento and reinstalled 1.5 and the same issue is happening.




--
Dean Asher
DeanAsher@gmail.com
(818)451-7050

On Thu, Feb 23, 2017 at 5:36 AM, Santiagoebizmarts <notifications@github.com

**Comment by gonzaloebiz** [comment]
Remove the file app/design/adminhtml/default/default/layout/magemonkey.xml
This file is from MageMonkey

**Comment by dkraze** [comment]
There were duplicate records of Mailchimp attributes in the eav-attribute
table. I removed the duplicates and fixed the problem.



--
Dean Asher
DeanAsher@gmail.com
(818)451-7050

On Thu, Feb 23, 2017 at 4:00 PM, Gonzalo Dominguez <notifications@github.com

**Comment by sopedro** [comment]
Delete all the tables started magemonkey_ from your database and you're done.
