### ISSUE TITLE
mkdir() directory already exists

### ISSUE THREAD

**Issue by tomlankhorst** [mailchimp/mc-magento#144]
`2017-02-24T10:24:23+00:00 ERR (3): Warning: mkdir(): File exists  in /data/web/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php on line 245
`

Maybe add an `is_dir()` check?

**Comment by Santiagoebizmarts** [comment]
Hello,

Clearing the mailchimp directory located at  **var/mailchimp** should solve that error.
Make sure you have the latest version 1.1.5.

For future cases please read this [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) before creating an issue.

Regards.
