### ISSUE TITLE
Lower case subscribers class name

### ISSUE THREAD

**Issue by lfolco** [mailchimp/mc-magento#145]
The class https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php has the classname Ebizmarts_MailChimp_Model_Api_subscribers. Shouldn't it be an uppercase "S"?

**Comment by Santiagoebizmarts** [comment]
Thanks again @lfolco for your contribution, it has been fixed and will be in the next release.
