### ISSUE TITLE
No Ecommerce data in mailchimp ?

### ISSUE THREAD

**Issue by rajat981** [mailchimp/mc-magento#146]
Hey developers,

I am using magento 1.9.2.3 and mailchimp version 1.1.5 

I am facing an issue that its not showing any ecommerce data into mailchimp. And its showing newsletter subscriber list into mailchimp..
There is noting in log file as well.

Can anyone help me with this ?

**Comment by gonzaloebiz** [comment]
Hi @rajat981 

thanks for your contact.
Please post this kind of issue in our [forums](https://ebizmarts.com/forums/view/6)

Best

**Comment by rajat981** [comment]
Hi @gonzaloebiz 

Thanks for your reply but there is no response in forums..
can you please help something ?

Thank you
