### ISSUE TITLE
Integrity constraint violation when syncing e-commerce data

### ISSUE THREAD

**Issue by lfolco** [mailchimp/mc-magento#147]
Preconditions:
- Magento v1.7.0.2
- Mailchimp for Magento v1.1.5

Steps to Reproduce:
- Enable e-commerce in system config
- Click 'reset e-commerce data' button in system config
- Save system config
- Run cron to kick off mailchimp_bulksync_data

Result:
No data is transferred. Error messages in MailChimp_Errors.log:

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magentodb`.`catalog_product_entity_datetime`, CONSTRAINT `FK_CAT_PRD_ENTT_DTIME_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `catalog_product_entity` (`entity_id)
```

```
SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 5
```

**Comment by lfolco** [comment]
Anyone?

**Comment by Santiagoebizmarts** [comment]
Hello @lfolco 
 
This looks like a similar error with the issue #111.
I suggest you to run the query below. 
**UPDATE eav_attribute SET frontend_type ='text' WHERE attribute_code='mailchimp_sync_delta';**
If this doesn't work then please share the response of the following query to see if the attribute has something wrong.
**SELECT * FROM eav_attribute WHERE attribute_code='mailchimp_sync_delta';**

**Comment by Santiagoebizmarts** [comment]
With the new management when saving the mailchimp_sync_delta this will not be an issue anymore.

**Comment by lfolco** [comment]
Confirmed that this is working with the latest release. Thanks!
