### ISSUE TITLE
No confirmation email after newsletter subscription

### ISSUE THREAD

**Issue by matteod** [mailchimp/mc-magento#148]
After the migration from MageMonkey Module to Mailchimp4Magento the NewsletterSubscriptionSuccess Email is not send. check the difference here: 
Magemonkey code: https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/Model/Subscriber.php
Mailchimp$Magento:
https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Subscriber.php

I found also a topici in ebizmarts forum
https://ebizmarts.com/forums/topics/view/24807

**Comment by gonzaloebiz** [comment]
Hi @matteod 

thanks for your feedback.
Please, read and follow [this guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to report issues.

Best

**Comment by centerax** [comment]
close this one in favor of https://github.com/mailchimp/mc-magento/issues/151
