### ISSUE TITLE
Guest orders are not synced

### ISSUE THREAD

**Issue by tobiasteatox** [mailchimp/mc-magento#150]
When placing orders as guest the orders are not synced. 

Lets go from the top to the bottom. In Ebizmarts_MailChimp_Model_Api_Orders::GeneratePOSTPayload the function $this->_isModifiedOrder($order) returns true even if it is a completely new order. 

I debugged it so far that in this cases the variable getMailchimpSyncModified is true but on the database level it is still false.  Therefore the creation of a guest id is never reached and Mailchimp will return the error: customer : "Required fields were not provided: id" 

After taking a look where mailchimp_sync_modified is set, i saw that there is an observer orderSaveBefore which calls the update function in Ebizmarts_MailChimp_Model_Api_Orders. If I'am not complete wrong this would mean that any other save Process of an Order before executing the cronjob task would break the process. 

For now i made a hotfix in Ebizmarts_MailChimp_Model_Api_Orders After Line 336 i replaced the part with:

```
if (isset($customers['customers'][0]['id'])) {
  $id = $customers['customers'][0]['id'];
  $data['customer'] = array(
    'id' => $id
  );
} else {
  $data["customer"] = array(
    "id" => ($order->getCustomerId()) ? $order->getCustomerId() : $guestId = "CUSTOMER-" . Mage::helper('mailchimp')->getDateMicrotime(),
    "email_address" => $order->getCustomerEmail(),
    "opt_in_status" => false
  );
}
```

Updating an order after the checkout isn't something special so i think there are a lot of extensions out there who would break this. 

Do you have an better fix for that or is my workaround enough?

**Comment by Santiagoebizmarts** [comment]
Hello @tobiasteatox 
This have been fixed for the new version. The isModifiedOrder value will be passed as a function parameter when running the sending process for modified orders.
You can see it [here](https://github.com/mailchimp/mc-magento/blob/dev_santisp/app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php#L84).

The last parameter is the one that tells if an order is new or modified.

Thanks for your feedback.
