### ISSUE TITLE
Newsletter Success Subscription not sent

### ISSUE THREAD

**Issue by matteod** [mailchimp/mc-magento#151]
Magento ver. 1.9.2.4

Removed Ebizmart_MageMonkey Plugin and add last version of MailchimpForMagento plugin

The mail Newsletter Success Subscription is not sent anymore.

If the module is disabled the mail is sent. 

I found some difference in Model/Subscriber.php extension: 

Ebizmart_MageMonkey_Model_Subscriber:
https://github.com/ebizmarts/magemonkey/blob/develop/app/code/community/Ebizmarts/MageMonkey/Model/Subscriber.php

Ebizmarts_MailChimp_Model_Subscriber:

https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Subscriber.php

**Comment by gonzaloebiz** [comment]
Hi @matteod

thanks for your feedback.
Please, read and follow [this guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to report issues.

Best

**Comment by gergely-42droids** [comment]
@matteod I know it's been a while but did you figure this out? I have the same issue... Thanks

**Comment by centerax** [comment]
closing in favor of https://github.com/mailchimp/mc-magento/issues/250
