### ISSUE TITLE
Admin skin missing a file

### ISSUE THREAD

**Issue by anchev** [mailchimp/mc-magento#156]
`[Fri Mar 03 16:37:09 2017] [error] [client *hidden*] File does not exist: /*hidden*/skin/adminhtml/default/default/ebizmarts/mailchimp/images/tabs_link_over_bg.gif, referer: http://*hidden*/skin/adminhtml/default/default/ebizmarts/mailchimp/css/mailchimp.css`

Appears in Apache log when opening the backend.

**Comment by gonzaloebiz** [comment]
Hi @anchev 

thanks for your feedback, we will check it

Best

**Comment by Santiagoebizmarts** [comment]
Hello @anchev 

Thanks for your feedback.
Can you tell me your Magento version? This image should be at **skin/adminhtml/default/default/images/tabs_link_over_bg.gif**

As you can see it is an image from Magento.

Regards.

**Comment by Santiagoebizmarts** [comment]
Actually I see the path is not correct in the mailchimp.css file. This will be fixed for next release.

Thanks you for your help!

Regards.

**Comment by anchev** [comment]
Can you please tell me how to update to latest stable version? I have installed using modman.
