### ISSUE TITLE
Lots of errors in log files + additional log files with random names created

### ISSUE THREAD

**Issue by anchev** [mailchimp/mc-magento#158]
I have installed the extension on one of my sites which has a bigger customer base. However I notice something weird in the var/log directory of Magento (1.9.1.0):

1. There is no such file named as in the extension settings: `{{base_dir}}/var/log/MailChimp_ApiCall.log`
2. There is a file MailChimp_Errors.log which is growing while data is syncing between Magento and MailChimp. The repeating errors are (hundreds of them):

```
2017-03-04T16:35:21+00:00 DEBUG (7): Invalid Resource : Your merge fields were invalid.
...
2017-03-04T16:30:44+00:00 DEBUG (7): Resource Not Found for Api Call: ecommerce/stores/*hidden*/customers?email_address=*hidden* - The requested resource could not be found.
```

and more rarely there are:

```
2017-03-04T16:50:25+00:00 DEBUG (7): Invalid Resource for Api Call: lists/*hidden*/members/*hidden* : BILLING : Please enter a complete address / SHIPPING : Please enter a complete address
...
2017-03-04T16:30:46+00:00 DEBUG (7): Resource Not Found for Api Call: ecommerce/stores/*hidden* - The requested resource could not be found.
...
2017-03-04T16:40:28+00:00 DEBUG (7): Invalid Resource : *hidden*@*hidden* looks fake or invalid, please enter a real email address.
```
3. Additionally the extension is creating a growing number of logs with (looks like) random names like:

```
829bcf28ef.Request.log
41608fc3bc.Request.log
46831f3c6b.Request.log
54296bfca5.Request.log
379242d465.Request.log
```
They are full of some json data.

I wonder what's going on during this sync, if there are any real issues that need action from my (or developer side) and if my hosting space is in endangered by being filled with these random log files. Some of them are 200Kb+

Can someone please explain?

**Comment by ihor-sviziev** [comment]
1. log files are disabled by default. Check your configuration
As for me - logs should be enabled by default. I think this thing could be improved.

2. We also getting these errors, but they looks normal, in our cases people put incorrect email domain, like hormail.com, hotmai.com, uahoo.com, etc.

3. It looks like these filed should be cleared time to time. This think should be improved

**Comment by anchev** [comment]
1. I know but in my configuration they are enabled. That's why I mention it. This means actuality doesn't match the config.

2. I don't think they are normal because there are valid email addresses in the list

3. Our log directory is already filled up with hundreds of those random named logs. I hope someone can fix this soon.

**Comment by gonzaloebiz** [comment]
Hi @anchev,

thanks for your feedback.
Really this is not the place to put this kind of questions, we have [a forum](https://ebizmarts.com/forums/view/6) for this. (here only the developers can help you, and in the forums we have a support staff)

Best

**Comment by anchev** [comment]
@gonzaloebiz 

Well, it is actually a bug report as the program doesn't what it is told to (in settings) and does things which it is not told to (creates extra logs). That's why I write here.

**Comment by gonzaloebiz** [comment]
These files like var/log/xxxxxxxx.Request.log are not random names, this is the logs for each batch in Mailchimp, and are placed there only for debug purposes. You have a config option to change this.

Best

**Comment by anchev** [comment]
I don't see a setting to disable these non-random debug logs? Here are my settings:

https://snag.gy/x0ocXL.jpg

Which option says "I don't want debug files"? Also please note again that the var/log/MailChimp_ApiCall.log is not created at all although it is set to be created.

**Comment by gonzaloebiz** [comment]
You don't see the "Enable log" option??

**Comment by anchev** [comment]
I see it is "Enable Log" and not "Enable log**s**" + I also see the note under the field which clearly says:

`File is {{base_dir}}/var/log/MailChimp_ApiCall.log`

Nothing says that this will not create this particular file but will create xxxxxxxx.Request.log files.

**Comment by gonzaloebiz** [comment]
This is why we have a forum

**Comment by anchev** [comment]
Ok:

https://ebizmarts.com/forums/topics/view/24947
