### ISSUE TITLE
Add compatibility with aschroder/smtp_pro module

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento#159]
Continuing https://github.com/ebizmarts/magemonkey/pull/154. This module is replacing magemonkey module, so this issue is still actual.

We don't have ability to install these modules in parallel, use mailchimp to subscribe/unsubsribe subscribers and use smtp pro module for sending email.

I could prepare pull request to create checks like these if you'll approve it:
https://github.com/yireo/Yireo_EmailOverride/blob/master/source/app/code/community/Yireo/EmailOverride/Model/Email/Template.php#L12

**Comment by Santiagoebizmarts** [comment]
Hello @ihor-sviziev 
Thanks for your feedback. We are about to release a new version with multi-store support. We will review this as soon as possible. Maybe in the next release or in the one after that.

Regards.

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts FYI we tested this fix in our projects, it works good
