### ISSUE TITLE
No redirect back from customer login when accessing abandoned cart URL

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#162]
If a customer opens their abandoned cart URL and are not currently logged in to the web site they are redirected to the account login page. On successful login they are not redirected back to their cart. The fix is simple. In the cart controller add a call to setBeforeAuthUrl() for the current session before redirecting to the customer account login page:

```
Mage::getSingleton('customer/session')->addNotice("Login to complete your order");
Mage::getSingleton('customer/session')->setBeforeAuthUrl($url);
$url = '/customer/account/login';
```

**Comment by TroyPatteson** [comment]
And while you are in CartController.php you should probably change the notice from:

`Mage::getSingleton('customer/session')->addNotice("Your token cart is incorrect");`

to

`Mage::getSingleton('customer/session')->addNotice("Your cart token is incorrect");`

**Comment by Santiagoebizmarts** [comment]
Hello @TroyPatteson 
Thanks for your feedback, this does makes sense. We will test this and probably add it for the next release. This issue will be referenced once it gets done.
