### ISSUE TITLE
Send e-mail copy type "Separate Email" bug

### ISSUE THREAD

**Issue by omolto** [mailchimp/mc-magento#163]
If a user has the send e-mail copy feature enabled and the copy method is "Separate Email" the extension sends emails with all recipients. This is wrong because a customer would see all backend e-mails configured.

It was a bug from Magento that was solved some time ago. Please see the pull request.

**Comment by Santiagoebizmarts** [comment]
Hello @omolto 

Thanks for your feedback!
We will implement this in the next version.
