### ISSUE TITLE
Order ID being used instead of Order #

### ISSUE THREAD

**Issue by studio2f** [mailchimp/mc-magento#165]
Magento 4 Mailchimp is passing the Order ID to Mailchimp and not the Order Number. This makes all the transactional automations unusable. Customers contacting us regarding their order will be providing an Order ID and not the Order number. It is almost impossible to look up orders by OrderID in Magento 

![Order ID used instead of ORder Number](https://dl.dropboxusercontent.com/u/8230194/Screen%20Shot%202017-03-02%20at%208.52.15%20AM.png)

**Comment by Santiagoebizmarts** [comment]
Hello @studio2f 

Thanks for your feedback. At the moment there is no place for order numbers in the Order Schema of API 3.0 and using it as the order id might cause problems with multi-store instances.
This issue will be handled as soon as possible.

**Comment by m-overlund** [comment]
@Santiagoebizmarts 
It shouldn't cause issues, using increment_id instead.
In multi-store instances, the increment_id is still unique. Each store has it's own series of numbers (1xxxxxxxx, 2xxxxxxx etc.)

**Comment by studio2f** [comment]
@m-overlund exactly.  I don't totally get it. The module is passing Order ID to MailChimp and they're using it as Order Number.  It's not the order number. It can't be used for any of their transactional templates. The whole new MailChimp functionality of generating order emails, shipping confirmations, etc. cannot be used.  I don't see why there's any reason to use Order ID instead of the Order Number.

**Comment by Santiagoebizmarts** [comment]
Hello,

Please note there are extensions that affect the order number.
The only way to be certain is to have both values sent and is a cleaner way as well.
Please note we also need to take in consideration compatibility with previous versions.

Regards.

**Comment by soopadoubled** [comment]
This is such a huge issue. The order reference given in the email (as per example above) essentially means nothing to customers or staff. Makes what could be a great feature unusable in my opinion.
