### ISSUE TITLE
customer re-subscribe fails silently

### ISSUE THREAD

**Issue by bob2021** [mailchimp/mc-magento#167]
If a customer unsubscribes via an email link, and then tries to resubscribe via Magento, then the re-subscribe will fail silently - the customer will think that they have subscribed successfully but they haven't.

I think the `subscriber_status` should be reset and an error message should be shown.  You could also retry the subscription with a 'pending' status.

Here's the quick fix I'm using at the moment: https://github.com/bob2021/mc-magento/commit/02943c79742f8e7911b14a6503944742535c7d46

**Comment by Santiagoebizmarts** [comment]
Hello @bob2021 

Thanks for the feedback. We will test this and look for a solution.
