### ISSUE TITLE
Subscribe during checkout is no longer available

### ISSUE THREAD

**Issue by cshift** [mailchimp/mc-magento#168]
Having switched from MageMonkey to the new Extension the functionality to subscribe the Customer/Guest to the "Newsletter"/List(s) in the Checkout is no longer available.  

Unless this is already being worked on and if this is something that you would consider integrating, I think I could write it and submit via PR.  Otherwise I'll have to write a standalone local mini-extension to do this.  

Please advise.

**Comment by gonzaloebiz** [comment]
Hi @cshift 

thanks for your feedback.
This is in our roadmap to the next release after multi store support. But of course PR are welcome.
By the way, follow [this guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to report issues

Best

**Comment by cshift** [comment]
@gonzaloebiz, thanks for the follow up.  Sorry, guess it should have been be a feature request not a bug :)  I'll try to get this going on my end (time permitting), will submit a PR if I implement in a presentable fashion.

Thank you for providing a good, free extension by the way!

**Comment by gonzaloebiz** [comment]
You are welcome
