### ISSUE TITLE
Unsubscribe web hook not working correctly.

### ISSUE THREAD

**Issue by rbrown** [mailchimp/mc-magento#169]
https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php#L142 is expecting there to be a `data['action']` key in the data the web hook sends, and it is [documented as being there ](https://developer.mailchimp.com/documentation/mailchimp/guides/about-webhooks/). However, in the web hook data we get, it is missing. 

```php
[data] => Array 
( 
    [reason] => manual 
    [id] => XXXXX 
    [email] => blah@blah.com
    [email_type] => html 
    [web_id] => XXXXXX 
    [campaign_id] => XXXX
    [merges] => Array
    (CUT)
)
```
I asked mailchimp support and they had no idea if it was broken or badly documented.

**Comment by moustacherepublic** [comment]
I have commented out the 'switch' logic which had caused massive annoying warnings in system.log:

From line 141
```PHP
            try {
//                switch ($data['data']['action']) {
//                    case 'delete' :
                        //if config setting "Webhooks Delete action" is set as "Delete customer account"
                        if (Mage::getStoreConfig("mailchimp/general/webhook_delete") == 1) {
                            $subscriber->delete();
                        } else {
                            $subscriber->setImportMode(TRUE)->unsubscribe();
                        }
//                        break;
//                    case 'unsub':
//                        $subscriber->setImportMode(TRUE)->unsubscribe();
//                        break;
//                }
            } catch (Exception $e) {
                Mage::logException($e);
            }
```

**Comment by centerax** [comment]
@rbrown are you getting a `type` key on that array?

**Comment by rbrown** [comment]
No, in the log there's a `list_id` key after the merges array and that's it

**Comment by takzilla** [comment]
Hey all,

I'm a dev at MailChimp and was looking into this a bit but was unable to replicate. Would anyone be able to post an example request sent from MailChimp that has the "action" or "type" key absent?

I noticed the original poster included a partial request (thank you!) but I was unable to replicate by trying to emulate it from the details there. If we could, could we post the full request with none of the request data removed? All of this info is helpful in trying to replicate!

Thanks!

- tk

**Comment by rbrown** [comment]
Hi @takzilla, in case having the full email addresses was helpful as well I've emailed you @rsglabs with a full request.

**Comment by takzilla** [comment]
Thanks - will dig in.

**Comment by centerax** [comment]
[code shows](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php#L146) that we use *delete* as default if action is not provided. @rbrown hopefully this helps.

the check was added by @TroyPatteson around [2 weeks ago](https://github.com/mailchimp/mc-magento/commit/f8a48f4c17bdd7f21c7858eebed8c3429603a8b8#diff-508be802baa024f83d1fe5e1ae726e8dR146)

**Comment by rbrown** [comment]
Hey @centerax will there be a release soon? there's been 183 commits to develop since the last release, should I just switch to dev?

**Comment by centerax** [comment]
@rbrown a new version will be uploaded this week, thats the plan.
