### ISSUE TITLE
Unable to send email in queue unless entity_type = 'order'....

### ISSUE THREAD

**Issue by grafikchaos** [mailchimp/mc-magento#174]
See the [Ebizmarts_MailChimp_Model_Email_Queue class for reference](
https://github.com/mailchimp/mc-magento/blob/master/app/code/community/Ebizmarts/MailChimp/Model/Email/Queue.php#L31-L145)

```php
/** @var $message Mage_Core_Model_Email_Queue */
foreach ($collection as $message) {
    if ($message->getId()) {
        if ($message->getEntityType() == 'order') {
            $order = Mage::getModel('sales/order')->load($message->getEntityId());
            $storeId = $order->getStoreId();
            if (Mage::getStoreConfig(Ebizmarts_MailChimp_Model_Config::MANDRILL_ACTIVE, $storeId)) {
                 # ... more code ...
            }
        }
    }
}                    
```

Taking over the core email queue class and then restricting the sending of emails in the queue to only be processable if the `entity_type` is `order` which can create scenarios where no emails are sent to Mandrill for processing because of how the messages are being fetched from the database with a limited amount.

### Example scenario:

We use the Magento email queue to notify administrators if there is a connectivity issue with their ERP system, but because the message we create in the email queue is not an `order` then they can never be notified of the connectivity issue. If enough of those notifications pile up, no other emails can be processed.

### Suggested actions:

+ Remove the check for the entity_type. It shouldn't make a difference as to where the email message came from.
+ Refactor the fetching of the `storeId` to use `Mage::app()->getStore()`
  - maybe even better, why do we have to check the store view layer of configuration to see if Mandrill is enabled? Is there really a scenario in which someone enables/disables Mandrill per website or store view?
+ Add an `else` statement! Be a good player in the module community and let email processing continue if the `entity_type` is not `order`

**Comment by Santiagoebizmarts** [comment]
Hello @grafikchaos 
The fix you propose will only work if Mandrill is enabled in the default config.
There are some scenarios where store owners prefer using Mandrill only on certain stores.

Anyways it makes sense to be able to send every email in the queue so we will see the best way to solve this without affecting the current logic.
This issue will be referenced with the solution when it's done.

Thanks for your feedback!
