### ISSUE TITLE
Code optimizations still needed

### ISSUE THREAD

**Issue by martijnrmediact** [mailchimp/mc-magento#183]
After doing a code check for some of our bigger clients we decided the extension is still not ready for production. We are mostly worried about the performance of how the synchronisation is handled. Hope you can give your view and maybe possible let us know if you are already working on it. We have customers on Magento Enterprise that have more then 500 orders a day and more then 30.000 products.

The following are our most important concerns:
- there are a lot of product->load functions being used which can cause performance issues
- there are product->save functions being used which can cause performance issues and can cause issues with other observers
- the same also for orders, and customers
- quotes are also synchronised inefficient by loading and saving them
- still no configuration to start syncing orders from a specific date
- for Magento Enterprise saving products can cause serieus indexing and (Full Page) caching issues on a live site with lots of visitors

**Comment by gonzaloebiz** [comment]
Hi @martijnrmediact 

thanks for your feedback.
Please, before put an issue read [at this](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines).
In order to your feedback, try the Version 1.1.6, we make a lot of  improvements, including performance improvements.

Thanks

**Comment by martijnrmediact** [comment]
hi @gonzaloebiz , I understand you concern, and read the faq for issues, we as a company with a lot of big Magento Enterprise customer get a lot of time the whish to implement the new Mailchimp extension. We tested 1.1.6 and we still cannot implement the extension for our customers because of major performance issues. We really hope this is on the roadmap for next versions.

**Comment by Swahjak** [comment]
@martijnrmediact @gonzaloebiz this is a big concern for me as well. I've made some (minor) contributions and issues #90 ( #88 ), #91 , #89. We currently have the extension deployed to our development and testing environments but have some doubts about the performance with large lists and synchronizations.

**Comment by centerax** [comment]
@Swahjak and @martijnrmediact thanks for sharing your concerns on this aspect.
Trust me, we will improve our code base to me make it more performant and in compliance with Magento performance best practices. Rest assured its on our roadmap to improve this code and we thank you for your contributions.

**Comment by centerax** [comment]
@Swahjak let me know what you think about this https://github.com/mailchimp/mc-magento/pull/260 we made some improvements on the product batch generation

**Comment by centerax** [comment]
we will create references to code optimizations on batches on isse #91

**Comment by Swahjak** [comment]
@centerax @gonzaloebiz apparently this is still an issue. Just yesterday I found the following in ```app/code/community/Ebizmarts/MailChimp/Helper/Data.php```:

```php
    /**
     * If orders with the given email exists, returns the date of the last order made.
     *
     * @param  $subscriberEmail
     * @return null
     */
    public function getLastDateOfPurchase($subscriberEmail)
    {
        $orderCollection = $this->getOrderCollectionByCustomerEmail($subscriberEmail);
        $lastDateOfPurchase = null;
        foreach ($orderCollection as $order) {
            $dateOfPurchase = $order->getCreatedAt();
            if (!$lastDateOfPurchase || $lastDateOfPurchase < $dateOfPurchase) {
                $lastDateOfPurchase = $dateOfPurchase;
            }
        }
        return $lastDateOfPurchase;
    }
``` 
How is that acceptable. This is most likely the most inefficient way to get the last date of purchase. *All* order columns are loaded for *all* orders by the customer and then you start looping over them. Try doing that for a Magento store with a large amount of customers and orders.

**Comment by Swahjak** [comment]
Not to be the guy that is just throwing comments and no solutions. Off the top of my head (not saying this works out of the box, but to give an idea of more logical solutions).

**Select only the necessary data**
```php
        $orderCollection = $this->getOrderCollectionByCustomerEmail($subscriberEmail);
        $orderCollection
            ->getSelect()
            ->reset(Varien_Db_Select::COLUMNS)
            ->columns(
                array(
                    'last_purchase_date' => new Zend_Db_Expr('MAX(created_at)'),
                )
            );

        return Mage::getSingleton('core/resource')
                      ->getConnection('core_read')
                      ->fetchOne($orderCollection->getSelect());
```
**Just one order, with all columns attached**
```php
        $orderCollection = $this->getOrderCollectionByCustomerEmail($subscriberEmail);
        $orderCollection
            ->setOrder('created_at', Varien_Db_Select::SQL_DESC)
            ->setPageSize(1)
            ->setCurPage(1);

        return $orderCollection->getSize() > 0 ? $orderCollection->getFirstItem()->getCreatedAt() : null;
```

**Comment by Santiagoebizmarts** [comment]
Hello @Swahjak 

You are right, this can be done in a more efficient way. Please create a new issue with this particular case since this was not included in the original issue therefore it is not the same case.

Regards.

**Comment by Swahjak** [comment]
@Santiagoebizmarts while this specific case might be another issue, the global theme is in line with "After doing a code check for some of our bigger clients we decided the extension is still not ready for production". The code is not production ready for (semi) large stores.

**Comment by Santiagoebizmarts** [comment]
@Schrank 

Thanks for your feedback. If you have any constructive feedback about the specific portions of the code you think can be improved we will take it in consideration.

Regards.

**Comment by centerax** [comment]
@Swahjak would it be too much to ask for a PR including this https://github.com/mailchimp/mc-magento/issues/183#issuecomment-359733637 ?

Thanks!

**Comment by Santiagoebizmarts** [comment]
The specific issue has been created https://github.com/mailchimp/mc-magento/issues/619

**Comment by seansan** [comment]
Maybe @martijnrmediact  is the best judge ... knowing this party I can vouch they are serious and know their stuff

- [ ] there are a lot of product->load functions being used which can cause performance issues
- [ ] there are product->save functions being used which can cause performance issues and can cause issues with other observers
- [ ] the same also for orders, and customers
- [ ] quotes are also synchronised inefficient by loading and saving them
- [ ] still no configuration to start syncing orders from a specific date
- [ ] for Magento Enterprise saving products can cause serieus indexing and (Full Page) caching issues on a live site with lots of visitors

In addition we have logged several queries taking 10-12% of TOTAL mysql time ... 

In general a complete performance overhaul/review would not be a bad idea
