### ISSUE TITLE
Batch sync error for orders and products

### ISSUE THREAD

**Issue by dima-loburec** [mailchimp/mc-magento#185]
Hi,

Because products are sent by batches, first time not all product is created. But simultaneously we send orders and therefore some of them have error "Bad Request : A product with the provided ID does not exist in the account for this list." Because not all products are sent yet. 

So, we need new attempts or some flag to prevent order creating before all products will be exported.

Thanks

**Comment by postadelmaga** [comment]
Try to update to the version 1.1.6 solved cron issue for me: see https://github.com/mailchimp/mc-magento/issues/182

Anyway I had a new issue trying to saving products see: https://github.com/mailchimp/mc-magento/issues/188

**Comment by dima-loburec** [comment]
I recheck it more carefully and now for new version any new order's missing products are created previously and the order is created correctly! Thanks.
