### ISSUE TITLE
Minor issue with cron

### ISSUE THREAD

**Issue by postadelmaga** [mailchimp/mc-magento#186]
After installing version 1.1.6 we got the following error in our log

`Notice: Undefined variable: customerId  in app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php on line 174`

`Warning: Illegal string offset 'domain'  in app/code/community/Ebizmarts/MailChimp/Model/Email/Template.php on line 94`

**Comment by ebizmarts-keller** [comment]
Hello @postadelmaga 

I will look into this, but if you could please follow this guidelines (the ones applicable) to post the issue: https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines

Right now what I need the most is the steps to reproduce this and in what log is this producing, also the version of Magento could be useful, please make it as clear as possible.

**Comment by Santiagoebizmarts** [comment]
Hello,

Both cases had been fixed.
You can see the second fix in the commit referenced and the first one can be easily solved adding [this line](https://github.com/mailchimp/mc-magento/blob/dev_santisp/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php#L167).

Regards.

**Comment by postadelmaga** [comment]
@Santiagoebizmarts 
Why the fix for the first issue is not on Master ? 
I know it is a small warning but still is an error in the code and generates log in Magento ...
