### ISSUE TITLE
Subscriber batches remain in pending state

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#187]
Subscriber batches are saved to the **mailchimp_sync_batches** table using the magento store ID but are processed expecting the store ID to be the mailchimp store ID as it is with ecommerce batches.

The solution is to get the mailchimp store ID from the magento store ID in the sendStoreSubscriberBatch() method of Ebizmarts_MailChimp_Model_Api_Batches with:
`$mailchimpStoreId = Mage::helper('mailchimp')->getMCStoreId($storeId);`

and use that when saving the batch by replacing:

```
                    //save batch id to db
                    $batch = Mage::getModel('mailchimp/synchbatches');
                    $batch->setStoreId($storeId)
                        ->setBatchId($batchResponse['id'])
                        ->setStatus($batchResponse['status']);
                    $batch->save();
```
with
```
                    //save batch id to db
                    $batch = Mage::getModel('mailchimp/synchbatches');
                    $batch->setStoreId($mailchimpStoreId)
                        ->setBatchId($batchResponse['id'])
                        ->setStatus($batchResponse['status']);
                    $batch->save();
```

Doing so results in the method _getResults() successfully completing subscriber batches.

**Comment by yoosefi** [comment]
Is it safe to directly update the `mailchimp_sync_batches` table to have the correct ID?

**Comment by TroyPatteson** [comment]
That should be fine. I have been disabling the extension, clearing that table manually and then re-enabling the extension and resetting the store while testing so that old data isn't left in it. The only thing using that table is the Api/Batches class to save batches to send and then get the batch results, and the method used to delete the store which uses it to cancel pending batch requests.

**Comment by Santiagoebizmarts** [comment]
Hello @TroyPatteson 
Thanks for contacting us.
Subscribers are not associated to a MailChimp store, this is why they are stored with the Magento store id, Ecommerce data is associated to a MailChimp store id and this is why they are stored with it.

The problem you mention is related to another problem, I will check it out and let you know what I find.
@yoosefi Do not edit any store id!

Regards.

**Comment by yoosefi** [comment]
So what should be stored in `mailchimp_sync_batches`? Mailchimp ID or Magento ID? Should OP's fix not be applied?

**Comment by Santiagoebizmarts** [comment]
You can see the fix referenced above.
Thank you for helping us noticing this.

Regards.
