### ISSUE TITLE
1.5.5.6-1.5.6 MySQL upgrade memory exhausted

### ISSUE THREAD

**Issue by tomlankhorst** [mailchimp/mc-magento#189]
Something is consuming unacceptable amounts of memory in the MySQL upgrade script between 1.5.5 and 1.5.6.

`PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 209004480 bytes) in /data/web/public/lib/Zend/Db/Statement/Pdo.php on line 228`

**Comment by gonzaloebiz** [comment]
Hi @tomlankhorst 

thanks for your contact.
Please follow  [this guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to report your issue.
Try to take a look at your mysql logs

Best

**Comment by dima-loburec** [comment]
@tomlankhorst  It is problem with size of collection in the update. For me it was:

            //migrate orders
            $orderCollection = Mage::getModel('sales/order')->getCollection();

@gonzaloebiz  You can to add some pagination for all collections retrieving at mysql4-upgrade-1.1.5-1.1.5.6.php to fix this

Thanks

**Comment by gonzaloebiz** [comment]
Hi @tomlankhorst 

thanks for your feedback, your are wright, need to put limit in these collections.
I re open the issue.

Best

**Comment by dima-loburec** [comment]
So, I add a fix, you can add it if you need:

https://github.com/mailchimp/mc-magento/pull/192/files
