### ISSUE TITLE
Signup Source passed as API generic

### ISSUE THREAD

**Issue by lduh** [mailchimp/mc-magento#19]
If we could pass this as MailChimp for Magento, it would make it easier for users to segment.

**Comment by takzilla** [comment]
This looks to be working on my end. I'm seeing subscribers come over with the correct sign up source of "MailChimp for Magento".

Example:
![screen shot 2016-09-21 at 7 48 17 pm](https://cloud.githubusercontent.com/assets/1243467/18732869/60439c5a-8034-11e6-992e-8bcfe6cdb123.png)

@lduh can you confirm whether you're still seeing this happen?

**Comment by takzilla** [comment]
If you're able to see a recent sync of a customer that has ended up with a different sign up source, I can take that example in dig in a bit. It's possible that there could be a specific flow / subscription status scenario that could lead to it.

**Comment by takzilla** [comment]
@lduh are we good to close this out? or have we still been able to replicate?

**Comment by lduh** [comment]
have to wait until 11.7 goes to prod to verify. question- this will only affect new subscribers added, not anyone that has previously been synced?

**Comment by gonzaloebiz** [comment]
Any new on this?

**Comment by takzilla** [comment]
@lduh let's test a new subscriber addition and confirm that this issue doesn't still occur.

**Comment by centerax** [comment]
@takzilla can we close this one?

**Comment by takzilla** [comment]
Yeah, closing.
