### ISSUE TITLE
Order emails are not sent anymore

### ISSUE THREAD

**Issue by postadelmaga** [mailchimp/mc-magento#191]
After we have installed ver 1.1.6 we don't receive anymore the email for new orders, we are not sure if this also affect our customer emails.
We disabled the module and the emails are working again, we could not find any related log error so we are not sure about the exact reason.

Do we miss something here, Is there any related setting ?

**Comment by gonzaloebiz** [comment]
Hi @postadelmaga 

please follow [this guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to post your issue.

Best

**Comment by postadelmaga** [comment]
sorry what is wrong with this report ?
