### ISSUE TITLE
Checkout Problem

### ISSUE THREAD

**Issue by ClickCons** [mailchimp/mc-magento#198]
Hello,
We are experiencing a problem in our online store.
There is a certain volume of sales and just when it is going to make the payment leaves an error.
Anyone know how to fix it?

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 64 bytes) in /web/lib/Ebizmarts/Mailchimp.php on line 273

**Comment by gonzaloebiz** [comment]
Hi @ClickCons 

please follow [this guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to post your issue

Best
