### ISSUE TITLE
Ecommerce automations not working with 1.1.6

### ISSUE THREAD

**Issue by jimains** [mailchimp/mc-magento#199]
I installed 1.1.6 but it doesn't seem to be syncing the store to Mailchimp (see screenshot). It also now won't allow me to save products in the admin either.

I am seeing this in observer.log:
```
Ebizmarts_MailChimp_Model_Observer::productAttributeUpdate
2017-04-11T18:44:30+00:00 DEBUG (7): 0
```

<img width="400" alt="screen shot 2017-04-11 at 20 59 12" src="https://cloud.githubusercontent.com/assets/912665/24925842/dbf52c7e-1ef9-11e7-884c-9ca583e4d331.png">

**Comment by gonzaloebiz** [comment]
Hi @jimains 

plase follow [this guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to post your issue.

Best

**Comment by jimains** [comment]
##Issue Description
I installed 1.1.6 but it doesn't seem to be syncing the store to Mailchimp (see screenshot). It also now won't allow me to save products in the admin either.

###Preconditions
Magento CE  1.9.3.2
mc-magento 1.1.6
Ecommerce enabled in Mailchimp module
Single store configured in Magento
Order notifications enabled in Mailchimp

###Steps to reproduce
Try and trigger an automated order notification in Mailchimp by placing any Magento order
Review status in of automated notification in Mailchimp
Review error logs

###Actual and Expected result
Expected result:
Order is placed and Mailchimp triggers an automated order confirmation
Mailchimp shows that the store is connected when ecommerce is enabled in the Magento module

Actual result:
Mailchimp shows: Store is not connected
No order confirmation is triggered

###Additional information
Product saving doesn't work since installing the module. Possible duplicate of #188
