### ISSUE TITLE
Merge fields not pushed on customer save

### ISSUE THREAD

**Issue by andrewkett** [mailchimp/mc-magento#201]
The 1.1.6 release notes state "When a customer is edited in Magento the merge fields are updated in MailChimp.". We came across this problem in 1.1.5 and were hoping this upgrade would resolve the issue, unfortunately it hasn't so far. 

What we are seeing is when we subscribe/unsubscribe a customer in Magento admin we get the customers merge fields reflected in Mailchimp. However if we simply change a customer attribute, e.g name, and save the customer the changes never make it to Mailchimp. 

On subscribe I see a request from Mailchimp similar to this "POST /mailchimp/webhook/index/wkey/12345/ HTTP/1.1" 200 5 "-" "MailChimp.com" "-". On save we don't see any additional calls happening.

**Comment by andrewkett** [comment]
To expand a bit on this we discovered that the customers firstname/lastname were being sent, just not the merge fields.

The API call going out only has basic information in it:

{“operations”:[{“method”:“PUT”,“path”:“\/ecommerce\/stores\/[storeid]\/customers\/2559”,“operation_id”:“storeid-1_CUS_2017-04-12-04-54-17-70227200_2559”,“body”:“{\“id\“:\“2559\“,\“email_address\“:\“test@test.com\“,\“first_name\“:\“firstname\“,\“last_name\“:\“lastname\“,\“opt_in_status\“:false,\“orders_count\“:1,\“total_spent\“:49.99}“}

and there doesn't seem to be another request made by mailchimp as we see on subscribe/unsubscribe.

**Comment by Santiagoebizmarts** [comment]
Hello @andrewkett 

Thanks for your feedback, we are reviewing this.
Expect to hear from us soon.

Regards.

**Comment by Santiagoebizmarts** [comment]
After some tests I see this working for me.
Please note that subscriber and customer are not exactly the same even though you see them both in the same list.
The customer object only accepts some basic data.

I found that if you edit the address the subscriber data is not updated and made a fix for it but as long as the customer is subscribed you will be able to get all the merge fields updated properly.

**Comment by Santiagoebizmarts** [comment]
@andrewkett 
I will set this issue as done, if there is something else you want to add that I didn't consider I will remove the label and continue with the issue.
