### ISSUE TITLE
When I try to delete customer

### ISSUE THREAD

**Issue by aqib-git** [mailchimp/mc-magento#202]
Call to undefined method Ebizmarts_MailChimp_Helper_Data::getConfigValue() in includes/src/Ebizmarts_MailChimp_Model_Observer.php on line 167.

When I go inside Data.php helper there is no method with name getConfigValue() but there is getConfigValueForScope() only ?

This error doesn't occur on deleting any customer but on few ?

**Comment by gonzaloebiz** [comment]
Hi @aqib-git 

plase, follow [this guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to post your issues.
By the way, disable the magento compilation and for sure this resolve your issue.

Best
