### ISSUE TITLE
Subscription fails when a customer has wrong address data, infinite loop

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento#211]
**mc-magento 1.1.6, Magento EE 1.12 and CE 1.9.2.4**

**Problem:**

Trying to subscribe an email from a customer that has wrong address data will throw Magento into a loop and timeout, instead of displaying an error message. This has been tested all from the front-end.

**Steps to reproduce:**

1. Create a Magento customer with wrong address data.

example:

country - Japan
city - Chicago
postcode - 60604
Leave "state" field empty

2. Try to subscribe that email from the front-end

**Result:** 

It seems an infinite loop appears here _\Ebizmarts_MailChimp_Model_Api_Subscribers::updateSubscriber_ in "catch" blocks
$subscriber->unsubscribe();

**Comment by yoosefi** [comment]
Thanks for _catching_ this. I applied an override to comment out the call to `$subscriber->unsubscribe()`, is this enough to avoid the infinite loop?
