### ISSUE TITLE
Line feeds in default configuration values in config.xml break unserialize

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#213]
In commit 133790bd13da14badf6931737084b678d279d78c on dev_santisp branch line feeds were introduced into the default configuration values presumably for better formatting.
```
    <default>
        <mailchimp>
            <general>
                <webhook_active>1</webhook_active>
                <map_fields>
                      <![CDATA[a:27:{s:18:"_1468601283719_719";a:2:{s:9:"mailchimp";s:7:"WEBSITE";s:7:"magento";s:1:"1";}s:......</map_fields>
                <customer_map_fields>
                    <![CDATA[a:10:{i:0;a:3:{s:5:"label";s:18:"Shipping .....</customer_map_fields>
                <monkey_grid>1</monkey_grid>
            </general>

```

These line feed characters break the code when calling unserialize() in the constructor of Ebizmarts_MailChimp_Block_Adminhtml_System_Config_Form_Field_Mapfields at the following line:

```
        $mapFields = Mage::helper('mailchimp')->getCustomMergeFieldsSerialized($scopeArray[1], $scopeArray[0]);
```

I recommend that you remove line feeds between the start/end tags for all default configuration values.

**Comment by Santiagoebizmarts** [comment]
Thanks for helping us noticing this.

Regards.
