### ISSUE TITLE
Fix for invalid list ID when saving mailchimp system configuration

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#214]
When saving mailchimp configuration using the latest code (dev_santisp branch) I get the following error:
```
Invalid Resource for Api Call: ecommerce/stores - A list with the ID '1' doesn't exist in the account.
```

I have tracked this down to the following line in the _afterSave() method of Model/System/Config/Backend/Ecommerce.php:
```
            Mage::helper('mailchimp')->createStore($this->getValue(), $this->getScopeId(), $this->getScope());
```

Changing that line to the following appears to fix the problem:
```
            Mage::helper('mailchimp')->createStore($listId, $this->getScopeId(), $this->getScope());
```
It looks to me like that might have been a copy and paste error from the _afterSave() method of Model/System/Config/Backend/List.php where $this->getValue() presumably returns the selected list ID from the drop-down list element.

**Comment by Santiagoebizmarts** [comment]
Thanks for your contribution.

Regards.
