### ISSUE TITLE
Multi-store webhook URL uses the default store URL

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#215]
The webhook URL generated when saving mailchimp system configuration in a multi-store magento installation is based on the default store URL regardless of whether a specific website or store scope is used. This can be seen by configuring mailchimp for a specific website scope in magento admin and then logging in to the Mailchimp account, selecting the list and choosing *Settings -> Webhooks*.

The problem appears to be in the _createWebhook() method of Model/Observer.php.

One possible solution is to replace the following line:
```
        $store = Mage::app()->getDefaultStoreView();
```
with:
```
        if ($scope == 'websites')
            $store = Mage::app()->getWebsite($scopeId)->getDefaultStore();
        elseif ($scope = 'stores')
            $store = Mage::app()->getStore($scopeId);
        else
            $store = Mage::app()->getDefaultStoreView();
```

**Comment by Santiagoebizmarts** [comment]
Hello,

The idea is to only generate one webhook per list, doing that will create multiple webhooks for the same list generating unnecessary calls to the server.
The correct stores are retrieved once the webhook call occurs.

Regards.
