### ISSUE TITLE
Cache check for mailchimp store for given scope

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#216]
Helper method _getIfMCStoreIdExistsForScope()_ in Helper/Data.php queries the *core_config_data* table each time this check is made. Just viewing the mailchimp configuration in magento admin results in this method being called two or three times depending on whether mailchimp is enabled for that store.

One simple solution is to cache the result in the registry by replacing:

```
        $mcStoreAssociatedToScope = false;
        $collection = Mage::getResourceModel('core/config_data_collection')
            ->addFieldToFilter('path', array('eq' => Ebizmarts_MailChimp_Model_Config::GENERAL_MCSTOREID))
            ->addFieldToFilter('scope', array('eq' => $scope))
            ->addFieldToFilter('scope_id', array('eq' => $scopeId));
        if (count($collection)) {
            $mcStoreAssociatedToScope = true;
        }

        return $mcStoreAssociatedToScope;
```

with

```
        $mcStoreAssociatedToScope = Mage::registry('mailchimp_store_exists_for_scope_'.$scope.'_'.$scopeId);
        if ($mcStoreAssociatedToScope === null) {
            $mcStoreAssociatedToScope = false;
            $numEntries = Mage::getResourceModel('core/config_data_collection')
                ->addFieldToFilter('path', array('eq' => Ebizmarts_MailChimp_Model_Config::GENERAL_MCSTOREID))
                ->addFieldToFilter('scope', array('eq' => $scope))
                ->addFieldToFilter('scope_id', array('eq' => $scopeId))
                ->getSize();
            if ($numEntries) {
                $mcStoreAssociatedToScope = true;
            }
            Mage::register('mailchimp_store_exists_for_scope_'.$scope.'_'.$scopeId, $mcStoreAssociatedToScope);
        }

        return $mcStoreAssociatedToScope;
```

Also, using the _getSize()_ method on the collection is better than using _count()_ because it actually just issues a _SELECT COUNT(*)_ query rather than returning all of the rows, converting them to a collection of models and counting the number of items in the collection.

This same technique could be applied to helper methods like *getMailChimpScopeByStoreId()*.

**Comment by Santiagoebizmarts** [comment]
@TroyPatteson 

Your several contributions are being really helpful.
Thanks again!
