### ISSUE TITLE
Fixes for cart changes not being uploaded for abandoned cart

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#219]
With abandoned cart enabled new carts are uploaded to mailchimp but changes to existing carts are not. This can be verified by logging in as a customer on the magento store, adding a product to cart and running the _mailchimp_bulksync_data_ cron job. Then change the quantity of product in the cart and run the mailchimp_bulksync_data cron job again. The new details are not uploaded.

There are two issues preventing modified quotes from being uploaded. Firstly, the _mailchimp_sync_modified_ field on the corresponding quote entry in the _mailchimp_ecommerce_sync_data_ table is never set. Since the query issued in **_getModifiedQuotes()** method of _Model/Api/Carts.php_ expects _mailchimp_sync_modified_ to be 1, the changes are not found.

The second issue is that there is an error in the query generated with un-necessary quotes around the 'updated_at' term which results in the query expression **m4m.mailchimp_sync_delta < 'updated_at'** which always returns true so if issue one above is fixed then the changes are continuously sent.

These issues can be resolved by replacing the following line in **_getModifiedQuotes()**:

```
        AND m4m.mailchimp_sync_delta < '" . new Zend_Db_Expr('updated_at') . "'"
```

with

```
        AND m4m.mailchimp_sync_delta < " . new Zend_Db_Expr('updated_at')
```

and replacing the following line in **_getNewQuotes()**:

```
                $this->_updateSyncData($cartId, $mailchimpStoreId, Varien_Date::now(), null, null, null, $this->_token);
```

with

```
                $this->_updateSyncData($cartId, $mailchimpStoreId, Varien_Date::now(), null, 1, null, $this->_token);
```

**Comment by Santiagoebizmarts** [comment]
Hello @TroyPatteson 

Thanks for your contribution.
This time I see an error when replacing the newQuotes function.
This function must not set the modified value in 1 because the cart is already sent. With carts the modified value is not used because we have the updated at field that tells us if a modification was made after the cart was sent.

The solution will be referenced here shortly.

Regards.
