### ISSUE TITLE
Incorrect store id used by productAttributeUpdate() caused exception

### ISSUE THREAD

**Issue by thomashery** [mailchimp/mc-magento#228]
Hi,

The $mailchimpStoreId variable set at @line 541 and used to update api products @line 544 is incorrect. This function should call $storeId which is the store ID in Magento not the Mailchimp store id. If you follow the call stack you will see that this is what the following functions are expecting.

Issue location:
https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L544

This causes a silent exception in Magento when trying to update product attributes since the call to self::app()->getStore($store)->getConfig($path); ends up using Mailchimp store ID
@line 861, throwStoreException()
/Users/thery/www/website-mercator-2016/app/code/core/Mage/Core/Model/App.php

**Comment by Santiagoebizmarts** [comment]
Hello @thomashery 
This have been solved already and will be available for next release.
Here it is the other issue referencing this: https://github.com/mailchimp/mc-magento/issues/204

Regards,
