### ISSUE TITLE
Fix for invalid site_script index error in createStore()

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#232]
Commit https://github.com/mailchimp/mc-magento/commit/3158172492240ba4841a0afc18f3f46412e0bfe3 for installation of the _MC.js_ pixel introduced an error in **createStore()**. The exception is caught which hides the error but results in the mailchimp store ID associated with the list in Mailchimp being different to the one stored in Magento. If the Ecommerce Data is reset new stores are created in Mailchimp but the old stores are not deleted as the mailchimp store IDs don't match.

The fix is trivial. In **createStore()** in _Helper/Data.php_ replace:

```php
$configValues[] = array(Ebizmarts_MailChimp_Model_Config::ECOMMERCE_MC_JS_URL, $response['site_script']['url']);
Mage::helper('mailchimp')->saveMailchimpConfig($configValues, $scopeId, $scope);
```

with

```php
$configValues[] = array(Ebizmarts_MailChimp_Model_Config::ECOMMERCE_MC_JS_URL, $response['connected_site']['site_script']['url']);
```

The call to helper function **saveMailchimpConfig()** isn't required as the mailchimp configuration is saved for all **$configValues** in the line below.

**Comment by Santiagoebizmarts** [comment]
This is already fixed in the development branch.

Thanks @TroyPatteson
