### ISSUE TITLE
mailchimp/api_subscribers->_getMCStatus() returns integers

### ISSUE THREAD

**Issue by yoosefi** [mailchimp/mc-magento#235]
In `Ebizmarts_MailChimp_Model_Api_Subscribers->_getMCStatus()`

```php
...
        elseif (Mage::helper('mailchimp')->getConfigValueForScope($confirmationFlagPath, $storeId) &&
            ($status == Mage_Newsletter_Model_Subscriber::STATUS_NOT_ACTIVE ||
                $status == Mage_Newsletter_Model_Subscriber::STATUS_UNCONFIRMED)
        ) {
            $status = 'pending';
        }
...
```

This should not be conditional on whether confirmation is needed. If confirmation isn't needed, `$status` is returned back as-is (integer). The API doesn't know what statuses `2` and `4` are. This results in an API error.

Proposed fix: Use a switch statement and remove the `$storeId` parameter since looking up configuration isn't needed.

```php
protected function _getMCStatus($status)
{
    switch ($status) {
        case Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED :
            return 'unsubscribed';
        case Mage_Newsletter_Model_Subscriber::STATUS_NOT_ACTIVE :
        case Mage_Newsletter_Model_Subscriber::STATUS_UNCONFIRMED :
            return 'pending';
        case Mage_Newsletter_Model_Subscriber::STATUS_SUBSCRIBED :
            return 'subscribed';
        default :
            throw new LogicException("No equivalent MailChimp status found for newsletter subscriber status: {$status}");
    }
}
```

Reasoning: Avoid cryptic error messages originating from bad data, make the API responsible for returning meaningful state error messages.

**Comment by centerax** [comment]
do you have a working version of your fix? If so, can you create a PR so we can review it? Thanks.

**Comment by yoosefi** [comment]
:100:
