### ISSUE TITLE
Error "A product with the provided ID does not exist in the account for this list."

### ISSUE THREAD

**Issue by govindarajprevaj** [mailchimp/mc-magento#236]
When the cron run we got error in error log 
we are using magento : **1.9.2.2**
and mailchimp module version : **1.1.5**

**Error:** quote 322 not found
**Bad Request :** A product with the provided ID does not exist in the account for this list.
**DEBUG (7):** Resource Not Found : The requested resource could not be found.

**Comment by snebbit** [comment]
We're also getting this issue with 1.1.6 so it's not been fixed yet

**Comment by centerax** [comment]
do you have any stack trace information from the exceptions log file?

**Comment by snebbit** [comment]
@centerax Hey Pablo, since posting we noticed the fix has already been committed and appears to be scheduled for inclusion in 1.1.7 ([this one](https://github.com/mailchimp/mc-magento/commit/ea05c93c60a8f62ebbb82a6d651658219afb14bb)) so mystery potentially solved with this thread

**Comment by centerax** [comment]
got it. please feel free to comment if the problem re appears and we will reopen.

**Comment by mjYin** [comment]
I am having this issue from new 2.1.11 version now

**Comment by gonzaloebiz** [comment]
Hi @mjYin 

thanks for your feedback
Version 2.1.11 of what?

Best
