### ISSUE TITLE
Moto orders clients added to a campaign

### ISSUE THREAD

**Issue by MelissaEbizmarts** [mailchimp/mc-magento#237]
> We're finding that orders we place from the Magento admin (for a customer over the phone), are showing up as being attributed to a MailChimp campaign.  This isn't correct since it's a brand new order from a customer that isn't even in our MailChimp list.
> 
> My assumption of what's happening is that the employee taking the order has viewed an email from a MailChimp campaign and has that cookie set.  And when they place the order through the admin interface for a customer, the extension sees that cookie and attributes the sale to the campaign incorrectly.
> 
> The fix seems like it would be to ignore any campaign cookies when the order comes from the Magento Admin interface.

**Comment by centerax** [comment]
I think this is related to this: #239 

@gonzaloebiz any feedback is appreciated.
