### ISSUE TITLE
Undefined variable: customerId and action in file ProcessWebhook.php

### ISSUE THREAD

**Issue by stas89** [mailchimp/mc-magento#238]
2 errors in system.log:

Notice: Undefined variable: customerId in /home/getbooks/public_html/app/code/community/E
bizmarts/MailChimp/Model/ProcessWebhook.php on line 174

Undefined index: action in /home/getbooks/public_html/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php on line 144

**Comment by ebizmarts-keller** [comment]
Hello, 

The first notice has already been fixed in the development branch, you have to add this line: https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php#L167

The undefined index will be corrected soon as well.
