### ISSUE TITLE
All orders are marked with landing page & as coming from MailChimp.

### ISSUE THREAD

**Issue by enru** [mailchimp/mc-magento#239]
All orders for my site are marked as Mailchimp origin orders with the Freddie logo in the sales admin grid, even though they have not come from a MailChimp campaign. 

To reproduce the problem (I'm using Magento v1.9.3 & mc-magento 1.1.6.3):

1) Create an order on the frontend of the site. 

2) Visit site while logged in as an admin user with the MailChimp referral query string variables set. Any value can be used - the cookie just needs to be triggered & set!

e.g. http://example.com/?utm_source=XXX&utm_campaign=XXX&utm_medium=email&utm_term=XXXX&mc_cid=XXXX&mc_eid=XXXX

3) Update the order in the backend of the site to trigger the order save event. Invoice it or ship it or hold it. 

4) The MailChimp Freddie logo appears in the admin panel's Sales Grid next to the order, even though the customer was never referred by MailChimp.

The admin grid renderer code in _app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Sales/Order/Grid/Renderer/Mailchimp.php_ will mark an order as from MailChimp if the order has landing page, abandon cart flag or a MailChimp campaign id set. 

The landing page is set on an order if there is a landing page cookie set. The observer's orderSaveBefore() function is configured to fire during the order save event. However, this event is currently registered in the global namespace. So it will fire for when the admin user saves the order as well as when the customer creates the order. If the admin user has the landing page cookie set then the order will get marked as having come from MailChimp. This is how I read it anyway.
 
Should the landing page cookie part of this code not be in the frontend namespace?

Or should the landing page cookie be tied to the frontend session?

**Comment by centerax** [comment]
I think you are right @enru .

What do you think @gonzaloebiz ? I think that putting this https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/etc/config.xml#L55-L62 under frontend/events should solve this problem.
