### ISSUE TITLE
Newsletter subscription success emails not sent

### ISSUE THREAD

**Issue by gergely-42droids** [mailchimp/mc-magento#250]
**Techincal details:**
Magento ver. 1.9.2.2 (live site, no test data)
mc-magento 1.1.6.
MailChimp For Magento v1.1.6 - Enabled & Configured
Mandrill For Magento v1.1.6 - Disabled
Aschroder_SMTPPro 2.0.7
Xento Order Export 1.8.7

**Steps to reproduce:**
1) Enabled all modules, configure both Mailchimp & Aschroder SMTPPro
2) On the front-end sign-up to the Newsletter

**Expected result**
1) Magento sends the normal "Newsletter subscription success" email notification via SMTP
2) (If configured, Mailchimp also sends a welcome email - but this is not related)

**Actual result**
1) Magento "Newsletter subscription success" email notification NOT sent

**Additional information**
It would be useful to have an option to enable/disable the default "Newsletter subscription" emails
or notify the user that this is an expected behaviour. Currently, there is no documentation regarding this.

I included the Xento Order Export module in the details as it shows up the in the exception log. However, disabling this module does NOT solve the issue.

If I can be any more help, please let me know.
Thank you for your time.

**Related issues**
#159 
#151
#148

**Exception LOG**
`2017-05-17T12:30:04+00:00 ERR (3):
Zend_Mail_Transport_Exception: Unable to send mail.  in /var/www/magento/lib/Zend/Mail/Transport/Sendmail.php:142
Stack trace:
#0 /var/www/magento/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Sendmail->_sendMail()
#1 /var/www/magento/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#2 /var/www/magento/app/code/community/Ebizmarts/MailChimp/Model/Email/Queue.php(141): Zend_Mail->send()
#3 /var/www/magento/app/code/core/Mage/Cron/Model/Observer.php(326): Ebizmarts_MailChimp_Model_Email_Queue->send(Object(Mage_Cron_Model_Schedule))
#4 /var/www/magento/app/code/core/Mage/Cron/Model/Observer.php(72): Mage_Cron_Model_Observer->_processJob(Object(Mage_Cron_Model_Schedule), Object(Mage$
#5 /var/www/magento/app/code/local/Xtento/OrderExport/Model/Observer/Cron/Config.php(24): Mage_Cron_Model_Observer->dispatch(Object(Varien_Event_Observ$
#6 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1358): Xtento_OrderExport_Model_Observer_Cron_Config->addCronjobsToConfig(Object(Varien_Event$
#7 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1331): Mage_Core_Model_App->_callObserverMethod(Object(Xtento_OrderExport_Model_Observer_Cron$
#8 /var/www/magento/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#9 /var/www/magento/cron.php(78): Mage::dispatchEvent('default')
#10 {main}`

**Comment by centerax** [comment]
Thanks for the detailed information.
We will try to replicate the problem and if there is an issue we will provide a fix.

**Comment by Santiagoebizmarts** [comment]
Hello,

Newsletter confirmation emails are handled in MailChimp when the extension is installed.
Magento confirmation emails not being sent is the expected behavior.

Regards.

**Comment by digitalpianism** [comment]
Do you think it would be possible to have a configuration flag to enable/disable the sending of newsletter emails ? For instance, I don't want to use the Mailchimp welcome email and keep using the Magento ones, what should I do?

**Comment by Santiagoebizmarts** [comment]
Hello @digitalpianism 

Unfortunately at the moment that is not possible.

Regards.

**Comment by digitalpianism** [comment]
@Santiagoebizmarts is that because you don't have time ? Cause I can do a PR if you want.

**Comment by Santiagoebizmarts** [comment]
We would really appreciate that @digitalpianism 
Thanks for your great disposition in this.
