### ISSUE TITLE
Enable overriding e-commerce sync batch size

### ISSUE THREAD

**Issue by lfolco** [mailchimp/mc-magento#256]
The batch size for e-commerce syncing is hard-coded. It would be great if it were a system config variable that could be easily changed. Our system is capable of sending more than the hard-coded limit, but it requires doing a class override in order to enable the change (or editing the extension).

Additionally if it were possible to increase the batch size during certain hours (i.e., send 100 orders between 12am and 6am, and then revert back to 50 during business hours). As it stands, it takes weeks to get all of the e-commerce data sent over to MailChimp, so anything that can increase the throughput would be great.

**Comment by centerax** [comment]
Thanks Laura , we will add this configuration option shortly.
