### ISSUE TITLE
Batches not syncing

### ISSUE THREAD

**Issue by fimion** [mailchimp/mc-magento#262]
batches appear to be failing on my install. I'm using 1.9.2 with 1.1.6.6 of the plugin.

error from MailChimp_Errors.log:
```
2017-05-24T14:40:21+00:00 DEBUG (7): Invalid Resource for Api Call: batches : operations.item:127 : Schema describes object, array found instead
```

**Comment by centerax** [comment]
check the batch report on the admin to see the specific error

**Comment by centerax** [comment]
when you have more information or need support assitance, email us: mailchimp@ebizmarts-desk.zendesk.com
