### ISSUE TITLE
are admin order emails also sent to MC?

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#270]
are admin order emails also sent to MC?

this should be the case

just testing and we were missing emails ... all seem to be admin entered orders

(we take orders also by telephone and enter data for the customer)

these emails should ofcourse be added and sent to MC too

**Comment by centerax** [comment]
can you provide some information on how to replicate the problem? which steps in particular?

**Comment by seansan** [comment]
???

yes upgrade from 1.1.6 to 1.1.7 in a multistore environment

then follow the steps you provided

[image: Inline image 1]

**Comment by centerax** [comment]
Im dumb but I dont see any steps to replicate here.

> are admin order emails also sent to MC?
> this should be the case
> just testing and we were missing emails ... all seem to be admin entered orders
> (we take orders also by telephone and enter data for the customer)
> these emails should ofcourse be added and sent to MC too

**Comment by seansan** [comment]
Go to `sales_order_create/index` create a new order from the admin backend
- new order
- new customer
- enter products, email and such
- submit
- invoice
- maybe even ship

Do you need more info? glad to help

**Comment by centerax** [comment]
and what do you expect o see in mailchimp?

something like this https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines would help

**Comment by seansan** [comment]
I dont understand. We can write a lot of data,lines examples ... 

but the fact is the request: 
- if a magento order is created via de admin (sales_order_create/index, i.e. in the backend)

actual
- email not sent to MC

expected
- email sent to MC just like frontend
(or at least a checkbox to send yes/no option)

**Comment by MelissaEbizmarts** [comment]
Hello Sansan,
You meant to the transactional email? If so, Please note that Mailchimp doesn't handle the transactional emails. You can use Mandrill (is included on the Mailchimp for Magento module).

What version of the module are you using?
Is not happening on my end with v1.1.8

**Comment by MelissaEbizmarts** [comment]
Hello Seansan,
Sorry if I understand you wrong.
the customer email is not appearing on Mailchimp when you create a backend order? 
If so, this is not happening on my end with v1.1.8.
What version of the module are you using?

Kind Regards.

**Comment by seansan** [comment]
so when you create an adminhtml backend order for a new customers
then you find the email of the customer in Mailchimp?
also: is there a box asking YES/NO subscribe in adminhtml backend? (suppose
a customer does not want it)

**Comment by MelissaEbizmarts** [comment]
Hello Seansan,
The  email is on Mailchimp because the module sync all the customers and orders.
But the module doesn't subscribe to the customer to the newsletter when you create a backend order.
Subscribe at the checkout is a feature available for frontend only.

Kind Regards.

**Comment by seansan** [comment]
>> But the module doesn't subscribe to the customer to the newsletter when
you create a backend order.
haha so again does it or does it not subscribe a customer

an option should be present: does the customer want to subscribe to the
newsletter? yes/no

**Comment by MelissaEbizmarts** [comment]
Hello Seansan,
The module **NOT** subscribe the customer to the newsletter when you create an order.
If you have ecommerce feature enabled the module will sync the customer as a CUSTOMER not as subscriber. This mean that you will not be able to send newsletters to that customer.

As I said before: subscribe at the checkout feature is only available on the frontend.

Kind Regards.

**Comment by seansan** [comment]
I am trying to understand why you close the issue?

I mean it is still an issue ... there should be a subscribe option

it was not a question

**Comment by MelissaEbizmarts** [comment]
Hello Seansan,
Is not an issue, can be an Enhancement but not an issue since you can still subscribe that customer to the newsletter on the backend on Customers > Manage Customers > Select the customer > Select Subscribe to the newsletter on actions > Click submit.

If you want to propose this as a new feature please create a new issue with a correct title and a correct description.

Kind Regards
