### ISSUE TITLE
Changing ORDER email or ACCOUNT email

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#271]
Hi we sometimes change the ORDER email in the order when the customer made a typo

It also has an observer to change the account email

For Mailchimp: does this also trigger an update of the email? 

expected result
- remove old email addres = incorrect
- send new email address with all the data = correct

Now we see the old email address -- and this is not the right thing .... (email address that does not exist)

**Comment by centerax** [comment]
please send a support incident to mailchimp@ebizmarts-desk.zendesk.com

**Comment by seansan** [comment]
why> is this not the best PUBLIC visible location for feature request? (Or
is it a bug?)

**Comment by centerax** [comment]
Apologies, I misread the issue. Reopening.

**Comment by seansan** [comment]
Our suggestion is to add an observer to handle this

Email Typos are a reality

**Comment by centerax** [comment]
As far as I know the MailChimp API does not support updating a customer email after it was created so I don't think this is possible right now but lets wait for @takzilla 

Possibly related to #17

**Comment by seansan** [comment]
This is why I suggested

Unsubscribe old email

Subscribe new with order data

In the end you want to get rid of

The wrong old email

And have the correct one

**Comment by seansan** [comment]
PLease mark as 1.1.8 this is important and a real business case to tackle

**Comment by centerax** [comment]
we will wait until the proper procedure is in place. see: https://github.com/mailchimp/mc-magento/issues/17

**Comment by seansan** [comment]
this issue is more than 1 year old

why not do
unsubscribe and subscribe new email
for the time being

until a proper solution is in place of course
