### ISSUE TITLE
Cron Delay

### ISSUE THREAD

**Issue by rafaelpatro** [mailchimp/mc-magento#272]
Why so much time to finish the task? Is there a way I can fix this?
![image](https://cloud.githubusercontent.com/assets/13813964/26523074/22dd9248-42e5-11e7-894a-1f2c15a521f6.png)

**Comment by centerax** [comment]
Hello @rafaelpatro 
We made several performance improvements on the new release, not out yet.

Once this is out the time of Customers and Products batch should be reduced. (assuming this is the problem affecting you.

**Comment by rafaelpatro** [comment]
That's a good notice!
When do you expect to release a new version?

**Comment by centerax** [comment]
we expect a new version to be released this week.
feel free to comment and we will re open this issue if the problem persists after you get the new version.

**Comment by rafaelpatro** [comment]
Could you reopen this issue? After upgrade to 1.1.7 I'm facing the same problem.
I don't think its normal to take more than 10 minutes in a task. And _execution time_ is growing considerably.
![image](https://user-images.githubusercontent.com/13813964/26905830-fde8bc0e-4bbf-11e7-80ec-582169e42c4d.png)

**Comment by centerax** [comment]
I prefer to keep this one closed and refer to #308
