### ISSUE TITLE
Address MERGE tags not created/synced

### ISSUE THREAD

**Issue by MvEerd** [mailchimp/mc-magento#273]
It seems like merge tags relating to customer address information are not being created in mailchimp

I have the following fields set up in the backend and get a response that they've sucessfully been created:
![fields](https://cloud.githubusercontent.com/assets/12560315/26524512/fa3568ac-4334-11e7-86f3-c9f52e12ef28.png)

The following fields appear in Mailchimp (Any fields for address seem to be ignored, with the exception of 'SHIPPING' and 'BILLING')
![postmerge](https://cloud.githubusercontent.com/assets/12560315/26524513/fa362634-4334-11e7-9d22-533f82d908c1.png)

Thinking it might be intended that these were only merged into the address field I added COUNTRYB and COUNTRYS but these also did not get created or synced

Another issue that adds onto this and might be related is that the BILLING and SHIPPING fields have 'USA' as country in mailchimp for all customers, despite mostly being set to 'Netherlands', 'Belgium', 'Germany' or 'France' in the backend so I'm currently unable to use country in mailchimp

I've experienced this with commit 70b6d38d0fe925dae1462c4cfed517a9c19305a7 and 2bfc7b4fdea3c8cefd63be56c2436016e707a945 with multiple lists on both website and store view level (not simultaneously, but tested both)

I'd appreciate any help/tips on how to debug this, thanks in advance!

**Comment by ebizmarts-keller** [comment]
Hello @MvEerd 

I tested this on a local environment and seems you are right, there are several merge fields related to the address that are not being created, we are going to look into this.

I could not reproduce the issue with the country though, it is displaying fine for me. Could you specify the exact steps to reproduce this?

**Comment by cacheworks** [comment]
Thanks for having a look and confirming this issue!

Is the issue you're referring to not being able to reproduce that every address has USA?
I am afraid I don't know many more exact steps than what the manual says but I'll summarise what I do from my perspective

- Install the extension using modman clone, using several (random) commits going back a few weeks
- Choose a list (i've tried both website and store view level)
- Click 'Create merge fields'
- Save configuration
- Wait for sync to finish
- All addresses have USA as country in Mailchimp despite having the correct country in the Magento backend

I've tried this from multiple views on both the development and live server  and have not gotten any address to not say USA
Being able to sync country as a separate field would help to solve this for my usage but if there's anything I can do to help debug the country field for 'BILLING' and 'SHIPPING' I'd be glad to provide you with more information

**Comment by MvEerd** [comment]
Thanks for having a look and confirming this issue!

Is the issue you're referring to not being able to reproduce that every address has USA?
I am afraid I don't know many more exact steps than what the manual says but I'll summarise what I do from my perspective

- Install the extension using modman clone, using several (random) commits going back a few weeks
- Choose a list (i've tried both website and store view level)
- Click 'Create merge fields'
- Save configuration
- Wait for sync to finish
- All addresses have USA as country in Mailchimp despite having the correct country in the Magento backend

I've tried this from multiple views on both the development and live server  and have not gotten any address to not say USA
Being able to sync country as a separate field would help to solve this for my usage but if there's anything I can do to help debug the country field for 'BILLING' and 'SHIPPING' I'd be glad to provide you with more information

**Comment by MvEerd** [comment]
Is this still going to be included in a milestone at some point? Not being able to use country effectively to filter is a limitation

Thanks
