### ISSUE TITLE
Changing store name does not update Sync name in Mailchimp

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#283]
(minor) During setup we left storename default config. Now updated in Magento, to "My storename" Mailchimp still shows the default config value

![image](https://cloud.githubusercontent.com/assets/652395/26667709/c6b9ab9e-46a6-11e7-8ba8-bb7d38f694b9.png)

![image](https://cloud.githubusercontent.com/assets/652395/26667736/eed65b7c-46a6-11e7-9303-bca197f2e38d.png)

**Comment by ebizmarts-keller** [comment]
Hello @seansan 

Could you tell me the version of Mailchimp for Magento you are using and the exact version of Magento so I can try to reproduce the issue? I tried with Magento 1.9.3.1 and Mailchimp for Magento 1.1.6 but this didn't happen to me, the name updates correctly.

**Comment by seansan** [comment]
1932 but please close. I will investigate further
