### ISSUE TITLE
Unnecessary error reporting during user subscription

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#284]
Hello, i'd like to make some kind of feature request for your awesome extension.

**Preconditions:**
1. Magento CE 1.9.2
1. mc-magento 1.1.6 (and 1.1.7 milestone)

**Steps to reproduce**
1. Fire newsletter subscription event any way with fake email (test@example.com for example) or cause any other error in Mailchimp API

**Actual Result:**

1. Error is loged
1. Error is added to session and displays on frontend of website (user can see it)

**Expected Result:**

1. Error is loged
1. Error is not displayed on frontend

**Additional Information:**

To my mind your extension should not add any error to session and should not display it on frontend. Because:
1. It includes techincal information, that user should not see, for example:

> Invalid Resource for Api Call: lists/asda21312/members/2312dsadsad - test@example.com looks fake or invalid, please enter a real email address

2. I think that subscription to Mailchimp is some kind of techical process and user dont need always be informated about problems occurred during this process - if it's necessary local developers should add notifications their self. So extension should not force error notification - it distructs user from "main" business process (checkout for example) and may force user to cancel the decision to buy anyting right now.

Hope you undestand my motivation correctly and will remove forcing the notification from **updateSubscriber()** method soon.

Regards, Nikolay

**Comment by gorbunovav** [comment]
@Santiagoebizmarts, hi! Could you give some feedback here ?

**Comment by sprankhub** [comment]
I just encountered exactly the same issue. If you subscribe to the newsletter during the checkout process, the error is shown on the checkout success page. This really needs to be solved!
