### ISSUE TITLE
Crucial Index is Missing For mailchimp_ecommerce_sync_data Table

### ISSUE THREAD

**Issue by kzozulya** [mailchimp/mc-magento#285]
When number of records greater 50 000 in 
mailchimp_ecommerce_sync_data

batch functions stuck the mysqld.

So, the solution is to add index:
ALTER  TABLE `mailchimp_ecommerce_sync_data` ADD INDEX `IDX_FOREIGN_RELATED_ID` (`related_id`) USING BTREE

Please take a look for this issue.
Thanks.

**Comment by centerax** [comment]
already included https://github.com/mailchimp/mc-magento/commit/f9fd6090d17d4f7b8df5cb62102ebac103dcfd93#diff-8171e6a56fbb5d942378fed3540d282f

next release available soon.
