### ISSUE TITLE
1.9.3.3 Subscription confirmation email

### ISSUE THREAD

**Issue by studio2f** [mailchimp/mc-magento#287]
**Preconditions**

Magento CE 1.9.3.3 *(released 5/31/17)*
mc-magento 1.1.6 

**Steps to reproduce**

New customer completes checkout and chooses to subscribe to newsletter

**Expected Result**

Customer is subscribed to MailChimp list. 
Core Magento Newsletter Success Email Template **IS NOT** sent. Subscription confirmation managed at MailChimp (confirmation, no confirmation, double opt-in, etc). 

**Actual Result**

Customer is subscribed to MailChimp list. 
Core Magento Newsletter Success Email Template **is** sent. 

*I don't know about patch SUPEE-9767, but with a compete upgrade to 1.9.3.3 there doesn't seem to be a way to surpress the builtin Magento newsletter subscription confirmation email from being sent.*

**Comment by studio2f** [comment]
Maybe I have this backwards... all along we've been enjoying mc-magento NOT sending confirmation emails... but I guess that's a bug? 

https://github.com/mailchimp/mc-magento/issues/151

**Comment by MelissaEbizmarts** [comment]
Hello Studio2f,

To be able to archive the Expected result you must:
1- Disable magento success newsletter email.
2- Create a Welcome Automation on Mailchimp.

> We'd much prefer Magento not handle the success transactional email. We'd rather do it all at Mailchimp.

Mailchimp doesn't handle the transactional emails, if you don't want Magento handle the transactional emails you should use Mandrill (Mandrill is included on de Mailchimp for Magento module).
