### ISSUE TITLE
Not send guest carts for registered customer

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento#29]
When have a cart with an email from a registered customer, don't send it

**Comment by fand0rin** [comment]
@Santiagoebizmarts @gonzaloebiz 
Hi
Can anyone explain this restriction?
I could not find any information explaining why it was added

```php
// avoid carts abandoned as guests when customer email associated to a registered customer.
if (!$cart->getCustomerId() && $customer->getEmail() == $cart->getCustomerEmail()) {
    $this->_updateSyncData($cartId, $mailchimpStoreId);
    continue;
}
```

See [Model/Api/Carts.php:164](https://github.com/mailchimp/mc-magento/blob/df69f364656f45d5fe6ff1377db5b4247bd89262/app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php#L165) and 252

I tried to comment out these lines and sync the cart. It looks like Mailchimp correctly handles the guest cart with an email from a registered user.

Thank you

**Comment by Santiagoebizmarts** [comment]
Hello @fand0rin 

When a customer has a cart and then a guest abandons a cart with that same email address the customer cart is the one with priority. This is to avoid duplicate abandoned cart emails.

Kind Regards.

**Comment by gorbunovav** [comment]
@Santiagoebizmarts Hi!

Thank you for the quick response!

>When a customer has a cart and then a guest abandons a cart with that same email address the customer cart is the one with priority. This is to avoid duplicate abandoned cart emails.

But you don't check for the registered customer cart existence - you just load customer by email and if he exists you don't try to send the cart to Mailchimp 🤔

I am not sure why we should avoid duplicate emails if there are several carts abandoned?
And why registered customers are a special case? It is possible to check for duplicated carts for guests also - by email.

>Also in case you do have a registered customer, this will avoid other people to use the same email address and prevent false abandoned cart emails to be sent.

What kind of risk this brings? 🤔

Not every customer logins to their account every time (I think often it happens right before or during the checkout), so I suppose we can be losing noticeable count of abandoned carts on this check (especially if a customer uses a mobile device to start the order).

**Comment by Santiagoebizmarts** [comment]
Hello @gorbunovav 

Thanks for your response.
When an account is created a cart is associated to that account automatically.

About the risk... It can be arguable but some people might be disturbed by receiving several emails flagging them as spam. If you get several complains about sending spam Mailchimp may even block your account.

I understand your point and commenting/removing that entire if block will allow all the carts to be sent.

Kind Regards.
