### ISSUE TITLE
Webhook process might fail if the configured list changes.

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#293]

**Comment by durzel** [comment]
Dumb question probably.. is the webhook called by Mailchimp immediately?  I've install M4M 1.1.7, subscribed to a list, confirmed my subscription, but in Magento "Newsletter subscribers" the address still shows as "Not Activated".  Another email I manually deleted in Mailchimp still appears in Magento as "Subscribed"....

The webhook address in Mailchimp works (as in gives a 200 error code, beyond that I'm unsure how to debug further)

**Comment by andresinspace** [comment]
Possible workaround: Delete the webhook in your mailchimp list and then re-save your mailchimp configuration.
I had similar issue: https://github.com/mailchimp/mc-magento/issues/320
