### ISSUE TITLE
Translation of CGROUP results in error

### ISSUE THREAD

**Issue by jg-development** [mailchimp/mc-magento#294]
Hi,
I have a problem with the translation of the customer group when I want to subscribe to a newsletter.
Magento 1.9.3.3
mc-magento 1.1.7

I always get a result like this:
Invalid Resource for Api Call: lists/xxx : CGROUP : Value must be one of: General, Wholesale, Retailer, Stammfahrer, Special, NOT LOGGED IN (not NICHT ANGEMELDET)
In the "app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php" at line 150
the customer group is translated. Instead of "NOT LOGGED IN" it is translated to "NICHT ANGEMELDET". If I deactivate the translation it works as expected.
Am I doing something wrong here or is this an error?
Greetings Jan

**Comment by centerax** [comment]
please send a support issue to: mailchimp@ebizmarts-desk.zendesk.com
