### ISSUE TITLE
Web hooks continuously processed

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#295]
Web hooks are now being queued and processed from a new CRON job via the _processWebhookData()_ method of the _ProcessWebhook_ model. Web hooks are marked as processed by setting the **processed** field to 1. However when processing web hooks the list of available web hooks to process is not being filtered by those already processed.

The solution is to include _addFieldToFilter('processed', 0)_ to the webhook collection in _ProcessWebhook.php_ as follows:

```
    public function processWebhookData()
    {
        $collection = Mage::getResourceModel('mailchimp/webhookrequest_collection')
            ->addFieldToFilter('processed', 0);
```

**Comment by TroyPatteson** [comment]
You might also want to add a limit to the number of web hooks processed in a single run of the cron job. e.g.
```
        $collection = Mage::getResourceModel('mailchimp/webhookrequest_collection')
            ->addFieldToFilter('processed', 0);
        $collection->getSelect()->limit(200);```

**Comment by centerax** [comment]
we are working on this and will push a fix to *develop* today.

**Comment by jg-development** [comment]
Hi,
I patched my 1.1.7 with your commit and it seems to correct the webhook.
But the newsletter history status is still growing with the same data every time.
```
733 	foo@test.de 	Abonniert 	09.06.2017 23:37:06
733 	foo@test.de 	Abonniert 	09.06.2017 23:45:10
733 	foo@test.de 	Abonniert 	09.06.2017 23:45:10
733 	foo@test.de 	Abonniert 	09.06.2017 23:40:10
733 	foo@test.de 	Abonniert 	09.06.2017 23:40:10
733 	foo@test.de 	Abonniert 	09.06.2017 23:50:02
733 	foo@test.de 	Abonniert 	09.06.2017 23:37:09
733 	foo@test.de 	Abonniert 	09.06.2017 23:37:09
733 	foo@test.de 	Abonniert 	09.06.2017 23:45:03
733 	foo@test.de 	Abonniert 	09.06.2017 23:37:11 
```
Greetings Jan

**Comment by jg-development** [comment]
Ok, that seems to be a problem with the mc-magento and a hook from the magesetup extension

**Comment by hans2103** [comment]
@centerax when will a new version be released?

**Comment by centerax** [comment]
we dont have a release date for v1.1.8 yet but it will be in a couple of weeks.

**Comment by ryanrichard25** [comment]
Im on 1.1.17 and Ive added the changes to ProcessWebhook.php, but the mailchimp_process_webhook_data task just runs forever and I have to manually kill the cron job via ssh.   So im stuck in a permanent issue here as I kill it, magento restarts cron, gets to that task, and its stuck again forever.  It was literally running for over a month recently and never completed.  Any ideas?

**Comment by Santiagoebizmarts** [comment]
Hello @ryanrichard25 

This should not happen in the latest version. If it does then please contact our support to mailchimp@ebizmarts-desk.zendesk.com

Kind Regards.
