### ISSUE TITLE
Serious error in Version 1.1.7 after upgrade from Version 1.1.6

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#300]
Serious error in Version 1.1.7 after upgrade from Version 1.1.6

We updated to Version 1.1.7
Followed all tips to reset local errors + reset ecommerce data
We have automation emails set-up upon subscription

Customers from store view 1, where after the upgrade suddenly subscribed to store view 2
NL = linked to NL and has been for years)
DE = linked to DE and has been for years)

After the upgrade we hade xx thousand new subscribers to the DE list all coming from customers from the NL list (terrible! have been asnwering sorry emails all evening)

**Comment by centerax** [comment]
please send a support issue to: mailchimp@ebizmarts-desk.zendesk.com

**Comment by seansan** [comment]
I think this is important to know

For all upgrading as a serious risk
