### ISSUE TITLE
Checkout error

### ISSUE THREAD

**Issue by cfgalvani** [mailchimp/mc-magento#301]
Yesterday I updated this extension from 1.1.5 to 1.1.7. Today I got this error message when a customer tried to checkout and I don't know what to do:

`SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: UPDATE 'mailchimp_ecommerce_sync_data' SET 'related_id' = ?, 'type' = ?, 'mailchimp_store_id' = ?, 'mailchimp_sync_error' = ?, 'mailchimp_sync_delta' = '2017-06-06 16:55:33', 'mailchimp_sync_modified' = ?, 'mailchimp_sync_deleted' = ?, 'mailchimp_token' = ?, 'batch_id' = ? WHERE (id='749')`

I got this error in only one order today.

**Comment by centerax** [comment]
please send a support issue to: mailchimp@ebizmarts-desk.zendesk.com
