### ISSUE TITLE
Please add new default MERGE CODE: STORELANG

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#303]
Please add new default MERGE CODE: STORELANG in next version

Take from the storeid field store locale

![image](https://user-images.githubusercontent.com/652395/26864255-74f1cea8-4b57-11e7-927c-b6f6fe8b18da.png)

![image](https://user-images.githubusercontent.com/652395/26864292-a4935a3c-4b57-11e7-955e-6832029ad111.png)

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

This info is now being sent as explained at https://github.com/mailchimp/mc-magento/issues/357
You can see the exact line at https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php#L109

Regards.
