### ISSUE TITLE
20 minutes of mailchimp_process_webhook_data and growing

### ISSUE THREAD

**Issue by rafaelpatro** [mailchimp/mc-magento#308]
Do you have a fix for this?

![image](https://user-images.githubusercontent.com/13813964/26909046-af9d3196-4bd4-11e7-9420-3a513e9aaea8.png)

Magento 1.9.3.0
MailChimp 1.1.7

**Comment by jaimiedijstra** [comment]
Noticed this was closed but more recently refered to from separate issue. I have Magento 1.9.3.3, MailChimp 1.1.7. Ecommerce data disabled but the webhook data is crippling the other jobs and taking up to 20 minutes to perform:
![crons](https://user-images.githubusercontent.com/12552943/26968319-2b51d73c-4d34-11e7-8718-b6fb2846c399.png)

**Comment by darekkosyl** [comment]
For us it is running 30 min and failing with "Process "15513" on d.nuserver.uk" cannot be found anymore" error. 
![capture](https://user-images.githubusercontent.com/5444837/26976421-a8040fac-4d1b-11e7-8ede-81ffcde71461.JPG)

**Comment by centerax** [comment]
we are working on this and will push a fix to *develop* today.

**Comment by centerax** [comment]
closing this one in favor of https://github.com/mailchimp/mc-magento/issues/295

**Comment by Mic2005** [comment]
Here also the problem. High MySQL data to the db and mem 190mb and growing ~ job 10 minutes. Can I 
 disable the job via Firegento untill there is a fix?

**Comment by jaimiedijstra** [comment]
patching  mc-magento/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php with latest worked for me.
