### ISSUE TITLE
Slow orders synchronization

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#309]
Hi there.

Seems that orders synchronization is too slow.

Please take a look at profiler screenshots

![1](https://user-images.githubusercontent.com/8599788/26931158-390a6884-4c68-11e7-8687-e30fc1f03458.png)

![2](https://user-images.githubusercontent.com/8599788/26931261-7f2e759e-4c68-11e7-9e36-f7fdbfb82fc2.png)

We can see that Ebizmarts_MailChimp_Model_Api_Batches._sendEcommerceBatch() => Ebizmarts_MailChimp_Model_Api_Orders.createBatchJson() => Ebizmarts_MailChimp_Model_Api_Orders.GeneratePOSTPayload() => Mailchimp_EcommerceCustomers.getByEmail() occupies a big portion of time.

To my mind this is because of calling API method for receiving customer on each order (query in loop).
So we are to wait a very very long while our orders will be synced.

Could you please investigate this problem and offer possible fix in one of next releases?

Regards, Nikolay

**Comment by elluminatte** [comment]
@centerax oh, sorry.
i use mc-magento 1.1.6 with Magento 1.9.3.1 EE.
I see that new version of you awesome extension has been released, has it become faster there?

**Comment by centerax** [comment]
we made some improvements on Customers and Products yes. but we are ironing some issues here and there on the new version.
If you can test it on a dev site with a test list first that would be great.

BTW, which extension are you using to see the delays?

**Comment by elluminatte** [comment]
@centerax hi, i've reviewed code updated in 1.1.7 release, and it seems that this issue is not fixed there - we still have additional request to API for each order.
Is there any plans to do something with it?

I'm using <a href="https://blackfire.io">Blackfire</a> for profiling.

**Comment by centerax** [comment]
the orders piece is not yet refactored. we are working on it.

**Comment by lfolco** [comment]
Any chance of getting this to 1.1.8? We are on 1.1.6 and have been holding off on upgrading because it took nearly a month to sync our orders. I don't want to do this sync multiple times if I can help it.

**Comment by mzeis** [comment]
@Santiagoebizmarts As you moved this to milestone 1.1.9 should we assume that syncing orders is still slow in 1.1.8?

Thanks!

**Comment by Santiagoebizmarts** [comment]
Hello,

We have made several improvements in performance of the sendEcommerceBatch process since this issue was created.
In version 1.1.8 the process should no take that long each run. We are still working on these improvements and this will be closed once we take care of order process specifically.

Regards.

**Comment by seansan** [comment]
see #346 there are 2 possible fixes, it has been marked urgent for a while
So this will probably be added very very soon I presume ... EbMart?

**Comment by seansan** [comment]
Also maybe part of this, are the very slow queries. 1 of them here: https://github.com/mailchimp/mc-magento/issues/583

**Comment by Santiagoebizmarts** [comment]
There have been several improvements in the queries and some Mailchimp calls were removed as the one mentioned by @elluminatte 

> Mailchimp_EcommerceCustomers.getByEmail
