### ISSUE TITLE
PHP Fatal error in syncSubscriberBatchData (cron)

### ISSUE THREAD

**Issue by durzel** [mailchimp/mc-magento#312]
Hi,

Installed the latest 1.1.7 on my Magento CE 1.9.3.3 store via modman.

Have seen the following cron error appear:

```
PHP Fatal error:  Uncaught Error: Call to a member function status() on null in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php:352
Stack trace:
#0 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(138): Ebizmarts_MailChimp_Model_Api_Batches->getBatchResponse('279b3f1641', 0)
#1 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(279): Ebizmarts_MailChimp_Model_Api_Batches->_getResults(0, false)
#2 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(116): Ebizmarts_MailChimp_Model_Api_Batches->_sendSubscriberBatches()
#3 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Cron.php(36): Ebizmarts_MailChimp_Model_Api_Batches->handleSubscriberBatches()
#4 /home/magento/.modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Ebizmarts_MailChimp_Model_Cron->syncSubscriberBatchData(Object(Aoe_Scheduler_Model_Sche in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php on line 352
```

There doesn't appear to be any sanity checking to see whether $api->batchResponse is an object, I guess it's fatal if it isn't?

**Comment by centerax** [comment]
is your APIKEY in place?

**Comment by durzel** [comment]
Yes, API key in place and store shows as connected in Mailchimp. 

I have configured it at a store level though, not "Default Values". I have several stores on the Magneto install, only one of them needs integration currently.

**Comment by durzel** [comment]
For clarity - nothing is configured at Default Values (global) scope, only at Website scope (extension enabled, API key entered, list chosen, etc) for one store.

**Comment by durzel** [comment]
Could someone clarify exactly where I should be configuring the extension?

The [README.md](https://github.com/mailchimp/mc-magento/blob/develop/README.md) says: "If you have a paid MailChimp account and want to use MailChimp Automations go to "Default Config" scope and to the Ecommerce section and set it to Enabled".  If you enable the extension at the Default Values scope, it (presumably) expects an API key, but the Default Values isn't a website.

Is the correct configuration for a multi-store installation - if you want to use automations - to enable the plugin AND enable Ecommerce at the Default Values scope, and then to manually _disable_ the plugin for any store you don't want to use it on?  If this is the case - what are you supposed to put for the API key at the Default Values scope?

**Comment by centerax** [comment]
There is a bug on the code. The method that creates the instance should check if the module is enabled on that scope not only checking if the APIKEY is null. We will fix it shortly.-

**Comment by durzel** [comment]
> There is a bug on the code. The method that creates the instance should check if the module is enabled on that scope not only checking if the APIKEY is null. We will fix it shortly.-

Ok, thanks.

Could you possibly comment on the above?  When using this extension in a multi-store environment enabling it at the Default Values scope seems to me to be counter-intuitive because Default Values isn't a real website in any multi-store configuration, it's a set of common settings across all stores, which is illogical in the context of a Mailchimp integration (every store wouldn't share customers, products, orders, etc).

Also "Enable Log" is a global scope variable, but it only appears at the Default Values scope (when it is enabled), [it is configured not to appear on any other scope](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/etc/system.xml#L160-L172).

**Comment by durzel** [comment]
Sorry to spam the comments, but just had another cron error with the extension only enabled at a single Website scope.  It is fully disabled at Default Values scope...

```
PHP Fatal error:  Uncaught Error: Call to a member function status() on null in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php:352
Stack trace:
#0 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(138): Ebizmarts_MailChimp_Model_Api_Batches->getBatchResponse('61fb2b0de8', 0)
#1 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(279): Ebizmarts_MailChimp_Model_Api_Batches->_getResults(0, false)
#2 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(116): Ebizmarts_MailChimp_Model_Api_Batches->_sendSubscriberBatches()
#3 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Cron.php(36): Ebizmarts_MailChimp_Model_Api_Batches->handleSubscriberBatches()
#4 /home/magento/.modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Ebizmarts_MailChimp_Model_Cron->syncSubscriberBatchData(Object(Aoe_Scheduler_Model_Sche in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php on line 352
```

**Comment by centerax** [comment]
its the same error you pointed on your first post.

**Comment by centerax** [comment]
we will get back to you on this https://github.com/mailchimp/mc-magento/issues/312#issuecomment-307817924 shortly.

**Comment by durzel** [comment]
I think I have tracked down this error...

In [Batches.php at these lines](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L128-L134) an SQL query is built that either contains the Mailchimp Store ID, or Magento Store ID.

Unfortunately if `$magentoStoreId` is zero then it gets entered into the SQL query as follows:

```SELECT `main_table`.* FROM `mailchimp_sync_batches` AS `main_table` WHERE (`status` = 'pending') AND (`store_id` = 0)```

In the table **mailchimp_sync_batches** `store_id` is a VARCHAR field which can contain either the Mailchimp store ID (string), or a Magento store ID (integer).  Unfortunately because of type conversion the above query will return any pending batch that does NOT evaluate to zero, which is every non-integer batch.

**getBatchResponse** will then try and process these invalid batches for Magento Store ID 0 (Default Values), causing this error.

The fix for this is simply to ensure that the variable that is passed to the query builder is parsed as a string (which it should be because the database field is a string):

```
if ($isEcommerceData) {
	$collection->addFieldToFilter('store_id', array('eq' => (string)$mailchimpStoreId));
} else {
	$collection->addFieldToFilter('store_id', array('eq' => (string)$magentoStoreId));
}
```

After doing this, there is no longer a cron error when processing batches.
