### ISSUE TITLE
still don´t understand the fix to #204 and similar

### ISSUE THREAD

**Issue by to8gal** [mailchimp/mc-magento#313]
since I´m at a point where I don´t want to update to 1.1.7  I would like instead to adress temporary the fix to the bulk product update from the frontend returning a blank warning,

I´ve been looking here but I continue to jump in between all closed issue without a real fix

**Comment by yoosefi** [comment]
See the override in #209 to fix

**Comment by to8gal** [comment]
Hello again,

I can stretch my mind and understand but I think this as bad implementation, what is XXXXXXX standing for?

if is an extension /fix to the module (which is already an extension) then better give the whole own ebizmart observer file anew or?

is this the official ebizmart patch?

will I fix all if I update to 1.1.7?

Thanks

L

**Comment by yoosefi** [comment]
It was patched in v1.1.7

XXXXXXX is *[insert your company name here]*

**Comment by yoosefi** [comment]
See additional comment https://github.com/mailchimp/mc-magento/issues/209#issuecomment-308259511

**Comment by to8gal** [comment]
yes I got that, I just think to initiate a new module just to fix another one is too much, I will wait for the 1.1.7

**Comment by centerax** [comment]
closing.
