### ISSUE TITLE
Handling 100K subscribers from Magento to MailChimp

### ISSUE THREAD

**Issue by MagePsycho** [mailchimp/mc-magento#314]
I have following queries, let me know if anyone from MailChimp can answer

- What's the effective way of importing 100K subscribers from Magento to MailChimp?
- What if I run the method `$api->lists->members->addOrUpdate()` in the loop for 100K subscribers, will it ever complete the operation, will cause it black-listed?
- Is Batch processing the best approach for importing 100K subscribers?

Waiting forward for the reply.

**Comment by Santiagoebizmarts** [comment]
Hello @MagePsycho 

The extensions does this out of the box. Just enabling the extension with the configured list and the Magento cron jobs properly configured should do the trick.

Regards.
