### ISSUE TITLE
Force subscription not working

### ISSUE THREAD

**Issue by Hajo-Magre** [mailchimp/mc-magento#317]
In the latest release, the force-subscription-for-guest-checkout 'hack' as described [here](https://ebizmarts.com/forums/topics/view/25189/) seems not be working anymore.

**Comment by Santiagoebizmarts** [comment]
Hello @Hajo-Magre 

This modification still works, in the new version the line numbers changed I just corrected the links to show the correct line that should be modified to get the buyers subscribed.

If this does not solve your issue please open it again and explain more about your situation. You can see a guide on how to create a complete issue [here](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines).

**Comment by Hajo-Magre** [comment]
**Preconditions**

- Magento 1.9.3.1
- MailChimp For Magento v1.1.7
- Uses multistore setup with two stores connected
- Hardcoded fix applied to force subscribtion of guest checkouts as mentioned [here](https://ebizmarts.com/forums/topics/view/25189/).

**Steps to reproduce**
- Make testorder as guest with valid emailadres (and/or search for actual orders meeting this conditions)
- Wait at least 24 hours for Magento to push data to Mailchimp
- Login to Mailchimp and check connected list to see if user/mailadress has been added to the list

**Actual and Expected result*

- Expected result: guest checkout user/mailadress is present in Mailchimp list
- Actual result: no new customers/mailadresses have been pushed to Mailchimp at all after 7 June '17, which is the day I updated to 1.1.7, whilst there have been 30 orders since then.

Before the upgrade to 1.1.7. every guest checkout customer was pushed to Mailchimp as were to expected using the hardcoded fix mentioned above.

**Possible test to perform**
Should I downgrade to 1.1.6?

**Comment by Hajo-Magre** [comment]
Re-opened as #337
