### ISSUE TITLE
Customers with bundle products not pushed to mailchimp

### ISSUE THREAD

**Issue by Hajo-Magre** [mailchimp/mc-magento#318]
If a customer purchases a bundle product, their emailadress is not pushed to Mailchimp. I understand it might not be possible to push the purchased bundle product to Mailchimp, because MC doesn't support that type of product.

It would however be nice if _some_ of the customer data would be pushed to Mailchimp, so I can send them product review reminders etc. Maybe also order value, etc.

At this time, it looks to me that all orders/customers containing bundle products are completely ignored.

**Comment by domb182** [comment]
We need this as well. Is there any type of ETA on this?

**Comment by Santiagoebizmarts** [comment]
Hello @Hajo-Magre @domb182 ,

Guest customers who only made one purchase containing only bundled and or grouped products are the only ones who will not be sent.

This will be solved once bundled and grouped products start being supported.

This issue will be closed along with #23 

Regards.

**Comment by leelawcpd** [comment]
@Santiagoebizmarts we're super keen to see this in place. We generate a substantial amount of our annual revenue from Bundled Products and this is a large gap in our successful utilisation of this integration.

What information would you like from us to assist with lifting the priority on this scope?

We're happy for a narrower implementation that just treats Bundles like Virtual Products by using the default Child Products within each Bundle to determine price etc.

**Comment by oshipper** [comment]
Any news on support for Grouped or Bundled products?

**Comment by Santiagoebizmarts** [comment]
Hello @oshipper 
Unfortunately there is no update on this.

Regards.
