### ISSUE TITLE
Webhook Issue: Invalid Resource for API Call

### ISSUE THREAD

**Issue by andresinspace** [mailchimp/mc-magento#320]
---Steps
Checked Webhook, did not exist in mailchimp list.
Installed mailchimp.
Webhook was created upon installation. Checked list and saw it.
Configured Mailchimp with API key and enabled.
Received following error: *Masked identifiable info with ###
```
Invalid Resource for Api Call: lists/#######/webhooks : url : Invalid URL
Your store could not be accessed by MailChimp's Api. Please confirm the URL: https://www.########.com/mailchimp/webhook/index/wkey/###########/ is accessible externally to allow the webhook creation.
```

---TEMP FIX
Deleted webhook in selected list
Re-saved mailchimp configuration

**Comment by Santiagoebizmarts** [comment]
Hello @andresinspace 

We implemented a new way on how webhooks are handled. It will be in the next release.

Regards.

**Comment by posttechguy** [comment]
Hi, 

I am trying to use Magento Mailchimp on a UAT site. I have set up the verified domain and set the cname and txt records. But the site has a htaccess restriction as we don't want access given to the world. I have tested the webhook url with login details and it works. What can I do to add the u/p details to the webhook url before it calls?

Thanks
