### ISSUE TITLE
Schema describes string, NULL found instead problem

### ISSUE THREAD

**Issue by darekkosyl** [mailchimp/mc-magento#332]
Magento 1.9.3.3  - Mailchimp for Magento 1.1.7

We are getting a lot of the MailChimp errors as below:
**address.province_code : Schema describes string, NULL found instead**  for Reg Type CUS 
State / Province is set to not required and after checking DB region column and see that it is set to NULL by default so we do have loads of customer addresses with NULL set for State/Province.
Our MERGE fields are set to:
SHIPPING -> Default Shipping Address
BILLING -> Default Billing Address
Is there a way to stop/solve this problem?

**Comment by Santiagoebizmarts** [comment]
Hello @darekkosyl 

This has been solved and the solution is available [here](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php#L135-L137).
It will be in version 1.1.8 that will be release very soon.

Regards.
