### ISSUE TITLE
Ecommerce data is processed for all stores, regardless of enabled scope

### ISSUE THREAD

**Issue by durzel** [mailchimp/mc-magento#334]
Hi,

In [handleEcommerceBatches() in Batches.php ](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L93-L97) every store is processed regardless of whether or not the extension is enabled for that store or not.

The **_sendEcommerceBatch** function later on checks to see whether or not Mailchimp & Ecommerce is enabled for the specified store, but by that point it has already built and processed the batches (**_getResults**).  On an installation with many stores, orders, etc this could add up to a lot of wasted CPU time if after all the processing is done the store isn't synced in Mailchimp anyway.

The simple fix seems to be to relocate the check to see if the extension is enabled for a given store further up in the process.

i.e. change:

```
$stores = Mage::app()->getStores();
foreach ($stores as $store) {
	$this->_getResults($store->getId());
	$this->_sendEcommerceBatch($store->getId());
}
```

to:

```
$helper = $this->getHelper();
$stores = Mage::app()->getStores();
foreach ($stores as $store) {
	if ($helper->isMailChimpEnabled($store->getId()) && $helper->isEcomSyncDataEnabled($store->getId())) {
		$this->_getResults($store->getId());
		$this->_sendEcommerceBatch($store->getId());
	}
}
```
and to remove the now-redundant check in **_sendEcommerceBatch**, i.e. lines [173](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L173) and [234](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L234)

**Comment by Santiagoebizmarts** [comment]
Hello,

This is checked [here](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L173).

Regards.
