### ISSUE TITLE
Force subscription not working

### ISSUE THREAD

**Issue by Hajo-Magre** [mailchimp/mc-magento#337]
(Re-opening of #317) 

**Preconditions**

- Magento 1.9.3.1
- MailChimp For Magento v1.1.7
- Uses multistore setup with two stores connected
- Hardcoded fix applied to force subscription of guest checkouts as mentioned [here](https://ebizmarts.com/forums/topics/view/25189/).
- Applied solution for webhooks continiously synching #295 

**Steps to reproduce**

- Make testorder as guest with valid emailadress (and/or search for actual orders meeting this conditions)
- Wait at least 24 hours for Magento to push data to Mailchimp
- Login to Mailchimp and check connected list to see if user/mailadress has been added to the list

**Actual and Expected result**

- Expected result: guest checkout user/emailadress is present in Mailchimp list
- Actual result: no new users/emailadresses have been pushed to Mailchimp at all after 7 June '17, which is the day I updated to 1.1.7, whilst there have been 30 orders since then.
- Before the upgrade to 1.1.7. every guest checkout customer was pushed to Mailchimp as expected using the hardcoded fix mentioned above.

**Possible test to perform**
Should I downgrade to 1.1.6?

**Comment by Hajo-Magre** [comment]
Downgraded to 1.1.6 and the auto subscription works again! 

Is someone going to look into this?

**Comment by Santiagoebizmarts** [comment]
Hello,

The new version has this as a configurable feature. Please update and you will get this feature working.

Regards.

**Comment by Hajo-Magre** [comment]
1.1.8 seems to work finally. I had to configure on storefront level instead of website level. Something that wasn't clear to me, but I somehow came accross a remark in this direction on one of your forum topics. Haven't had the opportunity to check, but is this fact documented somewhere in manual or setup instructions?

**Comment by Santiagoebizmarts** [comment]
Hello @Hajo-Magre 
Configuring the website scope should work normally, we do recommend to setup MailChimp For Magento per store due to some limitations about language and currency.

Regards.
