### ISSUE TITLE
Errors when syncing with MailChimp 

### ISSUE THREAD

**Issue by darekkosyl** [mailchimp/mc-magento#348]
Mailchimp for Magento 1.1.7 
Magento v 1.9.3.3
We are getting a lot of Mailchimp errors during sync (see below) which  is confusing to me because we chose NOT to pass customer address  in 'Customer Fields Mapping'and all the errors relate to address.province_code. Could you please have a quick look and give me some pointers how to tackle it?
ERROR RESPONSE:
` {
        "status_code": 400,
        "operation_id": "storeid-3_CUS_2017-06-22-17-05-13-77961000_2461",
        "response": {
            "type": "http:\/\/developer.mailchimp.com\/documentation\/mailchimp\/guides\/error-glossary\/",
            "title": "Invalid Resource",
            "status": 400,
            "detail": "The resource submitted could not be validated. For field-specific details, see the 'errors' array.",
            "instance": "",
            "errors": [
                {
                    "field": "address.province_code",
                    "message": "Schema describes string, NULL found instead"
                }
            ]
        }
    },`

SUCCESS RESPONSE:
`{
        "status_code": 200,
        "operation_id": "storeid-3_CUS_2017-06-22-17-05-13-77961000_2475",
        "response": {
            "id": "2475",
            "email_address": "jhnwbain@hotmail.co.uk",
            "opt_in_status": false,
            "company": "",
            "first_name": "John",
            "last_name": "Bain",
            "orders_count": 0,
            "total_spent": 0,
            "address": {
                "address1": "",
                "address2": "",
                "city": "",
                "province": "",
                "province_code": "",
                "postal_code": "",
                "country": "",
                "country_code": ""
            },
            "created_at": "2017-06-22T17:06:22+00:00",
            "updated_at": "2017-06-22T17:06:22+00:00",
            "_links": [
                {
                    "rel": "self",
                    "href": "https:\/\/us5.api.mailchimp.com\/3.0\/ecommerce\/stores\/0e90a3057a770ce9648328e8c3249a16\/customers\/2475",
                    "method": "GET",
                    "targetSchema": "https:\/\/us5.api.mailchimp.com\/schema\/3.0\/Definitions\/Ecommerce\/Stores\/Customers\/Response.json"
                },
                {
                    "rel": "parent",
                    "href": "https:\/\/us5.api.mailchimp.com\/3.0\/ecommerce\/stores\/0e90a3057a770ce9648328e8c3249a16\/customers",
                    "method": "GET",
                    "targetSchema": "https:\/\/us5.api.mailchimp.com\/schema\/3.0\/Definitions\/Ecommerce\/Stores\/Customers\/CollectionResponse.json"
                },
                {
                    "rel": "update",
                    "href": "https:\/\/us5.api.mailchimp.com\/3.0\/ecommerce\/stores\/0e90a3057a770ce9648328e8c3249a16\/customers\/2475",
                    "method": "PATCH",
                    "targetSchema": "https:\/\/us5.api.mailchimp.com\/schema\/3.0\/Definitions\/Ecommerce\/Stores\/Customers\/Response.json",
                    "schema": "https:\/\/us5.api.mailchimp.com\/schema\/3.0\/Definitions\/Ecommerce\/Stores\/Customers\/PATCH.json"
                },
                {
                    "rel": "upsert",
                    "href": "https:\/\/us5.api.mailchimp.com\/3.0\/ecommerce\/stores\/0e90a3057a770ce9648328e8c3249a16\/customers\/2475",
                    "method": "PUT",
                    "targetSchema": "https:\/\/us5.api.mailchimp.com\/schema\/3.0\/Definitions\/Ecommerce\/Stores\/Customers\/Response.json",
                    "schema": "https:\/\/us5.api.mailchimp.com\/schema\/3.0\/Definitions\/Ecommerce\/Stores\/Customers\/PUT.json"
                },
                {
                    "rel": "delete",
                    "href": "https:\/\/us5.api.mailchimp.com\/3.0\/ecommerce\/stores\/0e90a3057a770ce9648328e8c3249a16\/customers\/2475",
                    "method": "DELETE"
                }
            ]
        }
    },`
![customer_fields_mapping](https://user-images.githubusercontent.com/5444837/27477337-bb6591e0-5803-11e7-9825-1198cebd2e67.JPG)

**Comment by centerax** [comment]
can you check the batch data sent for that error PUT so we can see where a `NULL` value is being sent?

**Comment by darekkosyl** [comment]
See below for one example. 
`{
        "status_code": 400,
        "operation_id": "storeid-1_CUS_2017-06-23-16-05-05-11552600_297",
        "response": {
            "type": "http:\/\/developer.mailchimp.com\/documentation\/mailchimp\/guides\/error-glossary\/",
            "title": "Invalid Resource",
            "status": 400,
            "detail": "The resource submitted could not be validated. For field-specific details, see the 'errors' array.",
            "instance": "",
            "errors": [
                {
                    "field": "address.province_code",
                    "message": "Schema describes string, NULL found instead"
                }
            ]
        }
    },`

`{"method":"PUT","path":"\/ecommerce\/stores\/4c52ba8a67d1eebe27b1b5a7e6a3e169\/customers\/297","operation_id":"storeid-1_CUS_2017-06-23-16-05-05-11552600_297","body":"{\"id\":\"297\",\"email_address\":\"matthew.j.hulse@hotmail.com\",\"first_name\":\"Matthew\",\"last_name\":\"Hulse\",\"opt_in_status\":false,\"orders_count\":3,\"total_spent\":58.94,\"address\":{\"address1\":\"17 Broomfield Close\",\"city\":\"Winsford\",\"province_code\":null,\"postal_code\":\"CW7 2US\",\"country\":\"United Kingdom\",\"country_code\":\"GB\"}}"}`

**Comment by darekkosyl** [comment]
I don't know whether this is related but it is second time that I've set up 1.1.7 from scratch and mailchimp_bulksync_ecommerce_data , after running fine  for 2 hours, just dies every time it tries to run with TRIGGER: shutdown function (see below for report in var/report). I am really at loss here.

> a:5:{i:0;s:1861:"SELECT `e`.*, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `at_qty`.`qty`, `at_backorders`.`backorders`, `at_category_id`.`category_id`, `product_attribute_name`.`value` AS `name`, `product_attribute_visibility`.`value` AS `visibility`, `product_attribute_description`.`value` AS `description` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_website` AS `product_website` ON product_website.product_id = e.entity_id AND product_website.website_id = '1'
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 LEFT JOIN `cataloginventory_stock_item` AS `at_qty` ON (at_qty.`product_id`=e.entity_id) AND (at_qty.stock_id=1)
 LEFT JOIN `cataloginventory_stock_item` AS `at_backorders` ON (at_backorders.`product_id`=e.entity_id) AND (at_backorders.stock_id=1)
 LEFT JOIN `catalog_category_product` AS `at_category_id` ON (at_category_id.`product_id`=e.entity_id)
 INNER JOIN `catalog_product_entity_varchar` AS `product_attribute_name` ON e.entity_id = product_attribute_name.entity_id
 INNER JOIN `catalog_product_entity_int` AS `product_attribute_visibility` ON e.entity_id = product_attribute_visibility.entity_id
 INNER JOIN `catalog_product_entity_text` AS `product_attribute_description` ON e.entity_id = product_attribute_description.entity_id WHERE (product_attribute_name.attribute_id = '96') AND (product_attribute_visibility.attribute_id = '526') AND (product_attribute_description.attribute_id = '97') AND (`e`.`entity_id` IN()) GROUP BY `e`.`entity_id` LIMIT 100
`";i:1;s:3977:"#0 /var/www/vhosts/shoe-trees.co.uk/httpdocs/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /var/www/vhosts/shoe-trees.co.uk/httpdocs/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/vhosts/shoe-trees.co.uk/httpdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `e`.*, `...', Array)
#4 /var/www/vhosts/shoe-trees.co.uk/httpdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `e`.*, `...', Array)
#5 /var/www/vhosts/shoe-trees.co.uk/httpdocs/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `e`.*, `...', Array)
#6 /var/www/vhosts/shoe-trees.co.uk/httpdocs/lib/Varien/Data/Collection/Db.php(740): Zend_Db_Adapter_Abstract->fetchAll('SELECT `e`.*, `...', Array)
#7 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1046): Varien_Data_Collection_Db->_fetchAll('SELECT `e`.*, `...')
#8 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(871): Mage_Eav_Model_Entity_Collection_Abstract->_loadEntities(false, false)
#9 /var/www/vhosts/shoe-trees.co.uk/httpdocs/lib/Varien/Data/Collection.php(741): Mage_Eav_Model_Entity_Collection_Abstract->load()
#10 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php(80): Varien_Data_Collection->getIterator()
#11 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php(276): Ebizmarts_MailChimp_Model_Api_Products->_buildNewProductRequest(Object(Mage_Catalog_Model_Product), 'storeid-1_PRO_2...', '284aa7c87df280d...', '1')
#12 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php(135): Ebizmarts_MailChimp_Model_Api_Products->sendModifiedProduct(Object(Mage_Sales_Model_Order), '284aa7c87df280d...', '1')
#13 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php(47): Ebizmarts_MailChimp_Model_Api_Orders->_getNewOrders('284aa7c87df280d...', '1')
#14 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(190): Ebizmarts_MailChimp_Model_Api_Orders->createBatchJson('284aa7c87df280d...', '1')
#15 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(96): Ebizmarts_MailChimp_Model_Api_Batches->_sendEcommerceBatch('1')
#16 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Ebizmarts/MailChimp/Model/Cron.php(28): Ebizmarts_MailChimp_Model_Api_Batches->handleEcommerceBatches()
#17 [internal function]: Ebizmarts_MailChimp_Model_Cron->syncEcommerceBatchData(Object(Aoe_Scheduler_Model_Schedule))
#18 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(213): call_user_func_array(Array, Array)
#19 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(605): Aoe_Scheduler_Model_Schedule->runNow(true)
#20 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#21 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#22 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#23 /var/www/vhosts/shoe-trees.co.uk/httpdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#24 /var/www/vhosts/shoe-trees.co.uk/httpdocs/cron.php(76): Mage::dispatchEvent('default')
#25 {main}";s:3:"url";s:9:"/cron.php";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}`

**Comment by darekkosyl** [comment]
Have you had a time to have a look? In regards to the dying cron job I noticed that when I disable M4M and remove the API key and then re-enable it it works for some time before dying.

**Comment by Santiagoebizmarts** [comment]
Hello @darekkosyl 
Customer address is sent automatically, this is not the same as Subscriber address which is what you removed.
For your case you can modify the file at app/code/community/Ebizmarts/MailChimp/Api/Customers.php with the same change as in the commit referenced above.

Regards.
