### ISSUE TITLE
make the logo retina?

### ISSUE THREAD

**Issue by sam327** [mailchimp/mc-magento#350]
In a future edition of the plugin, can you make the source images for the logos 2x (or possibly 3x) wide? 

On my super-fancy-mac-retina-screen, images at regular resolution all look like a blurry mess.

<img width="233" alt="screen shot 2017-06-27 at 10 05 17 am" src="https://user-images.githubusercontent.com/1746360/27591643-4d252324-5b20-11e7-8304-073bb82f94a2.png">

**Comment by ebizmarts-keller** [comment]
Hello, 

This is being looked at and will be implemented in a future version, probably 1.1.9
