### ISSUE TITLE
Abandoned Cart Settings gets ignored when Ecommerce settings is disabled

### ISSUE THREAD

**Issue by reillo** [mailchimp/mc-magento#352]
If we intended that Abandoned cart will be ignored when ecommerce settings is disabled, can we add a message that Ecommerce settings is required to be enabled? Or can you point me towards the documentations that stated this?

https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L173

Correct me if I'm wrong.

Thanks

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for contacting us. This is not really an issue, it is something to send to our support at mailchimp@ebizmarts-desk-zendesk.com.

To create an issue please read our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines).

About your question, you can disable the abandoned cart section and your ecommerce data will still be sent as long as the ecommerce section is enabled.

Regards.
