### ISSUE TITLE
Bulk product attribute update error

### ISSUE THREAD

**Issue by firozenazar** [mailchimp/mc-magento#354]
In Magento admin if I update product attributes in bulk, I get an error on save. I believe there is a bug in in the following code:

Class: Ebizmarts_MailChimp_Model_Observer

Line 544: Mage::getModel('mailchimp/api_products')->update(...) the number of arguments in this function call do not match the actual method in Ebizmarts_MailChimp_Model_Api_Products.

In fact that method is expecting only 2 arguments and the second one should be the Magento store ID and not the MailChimp store ID.

I hope this is of help to someone.

**Comment by Santiagoebizmarts** [comment]
Hello @firozenazar 

Thanks for your feedback. This has been fixed for version 1.1.7 already.
You can see the fix [here](https://github.com/mailchimp/mc-magento/blob/master/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L541).

Regards.
