### ISSUE TITLE
mailchimp_sync_batches pending items are growing

### ISSUE THREAD

**Issue by firozenazar** [mailchimp/mc-magento#355]
I've noticed that the number of pending batch items in this table are growing rapidly. I believe this is because in the Ebizmarts_MailChimp_Model_Api_Batches class the only way an item is market as 'complete' is in the _getResults() method.

However in this method the collection of batches is filtered by MailChimp store ID.

If the batch was created in _sendEcommerceBatch() then that's fine because here the Mailchimp Store ID is used in the store_id column to create the batch entry in the database.

But if the batch was created in the sendStoreSubscriberBatch() method then that method uses the Magento store ID in the store_id column. So batches created in here are never cleaned up and always remain pending. Please can you explain the logic of this and propose a fix I could implement in my code?

Thanks.

**Comment by Santiagoebizmarts** [comment]
Hello @firozenazar 
Thanks for your help. This was a bug in the code but It has been fixed and will be available in the next release. You can see the changes [here](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L130-L134).

Regards.
