### ISSUE TITLE
Is it possible to populate default language via Magento -> MC

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#357]
Is it possible to populate default language via Magento -> MC

We kind of know what language our own store is in. So we presume (unless set otherwise) to set a default language here

For example in our german store: we would set all new customers to german

![image](https://user-images.githubusercontent.com/652395/27830038-ca0d4eb2-60c4-11e7-9c3a-2e37b0402a96.png)

**Comment by centerax** [comment]
@ebizmarts-keller : see https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php#L43 and https://github.com/mailchimp/mc-magento/blob/develop/lib/Ebizmarts/MailChimp/EcommerceStores.php#L34 for reference.
