### ISSUE TITLE
Resend ecommerce corrupted data

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#359]
Create buttons to trigger corrupted data to be sent again without the need of resetting all ecommerce data from MailChimp

**Comment by centerax** [comment]
Create buttons to trigger corrupted data to be sent again without the need of resetting all ecommerce data from MailChimp

**Comment by Santiagoebizmarts** [comment]
Duplicate https://github.com/mailchimp/mc-magento/issues/413
