### ISSUE TITLE
Ebizmarts_MailChimp properties are not defined correctly

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#361]
Hi there.

**Preconditions:**

1. mc-magento 1.1.7

**Steps to reproduce:**

1. Please look at _lib/Ebizmarts/MailChimp.php_ file

**Actual result:**

1. Class properties (like _root_, _authorizedApps_, _automation_, etc.) are not declared, they are defined in class constructor.

**Expected result:**

1. Class properties are defined correctly in class specification before assigning in constructor

**Additional information:**
The reason of this issue is that i use your awesome extension in project where PHPStan is used. And i have extended some of your API classes, where _Ebizmarts_MailChimp::$ecommerce_, _Ebizmarts_MailChimp::$lists_ are being used. So when i try to anylyse my code with PHPStan i get errors like "_Access to an undefined property Ebizmarts_MailChimp::$ecommerce._".
To my mind, class properties should be defined in class spec any way.

Hope you are agree and will deal with this.

Regards, Nikolay

**Comment by centerax** [comment]
the code was taken from here https://bitbucket.org/mailchimp/mailchimp-api-php

I agree this can be improved but its low priority.
