### ISSUE TITLE
Uncorrect return type of Ebizmarts_MailChimp_Helper_Data::loadListSubscriber() method

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#362]
Hi there.

**Preconditions:**
mc-magento 1.1.7

**Actual result:**
1. _Ebizmarts_MailChimp_Helper_Data::loadListSubscriber()_ may return null

**Expected result:**
1. This method always returns _Mage_Newsletter_Model_Subscriber_

**Additional info:**
Please look at method usage in code. We have _$subscriber->getId()_ statement everywhere, so if null will be returned we get fatal error. Please fix this.

Regards, Nikolay

**Comment by Santiagoebizmarts** [comment]
Hello @elluminatte 
This has been solved and will be ready in our next release. You can see the fixes in all the functions [here](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php#L72-L248).

Regards.
