### ISSUE TITLE
Webhook request duplicated processing

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#365]
Hi there.

**Preconditions:**
1. mc-magento 1.1.7

**Actual Result:**

1. Full list of webhook requests are being processed on each cron run

**Actual Result:**

1. Webhook request is not being processed after "_processed_" flag is set to 1

**Additional info:**
Please look at _Ebizmarts_MailChimp_Model_ProcessWebhook::processWebhookData()_:

```php
$collection = Mage::getResourceModel('mailchimp/webhookrequest_collection');
```

this is not filtered by "processed" field, so webhook request will be processed again and again, despite it's "_processed_" flag is already set to "1". This should be something like that:

```php
$collection = Mage::getResourceModel('mailchimp/webhookrequest_collection')
            ->addFieldToFilter('processed', 0);
```

Hope you'll fix this soon.
Regards, Nikolay.

**Comment by Santiagoebizmarts** [comment]
Hello @elluminatte 
This has been fixed and will be in the next release that will be out very soon. You can see the new code here.

https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php#L39-L41

Regards.
