### ISSUE TITLE
Setting up module on Magento behind basic auth

### ISSUE THREAD

**Issue by mlippie** [mailchimp/mc-magento#372]
I'm trying to install the module, but my Magento install sits behind a basic HTTP authentication.
So during setup, after I have submitted the API key, I get the following error `Your store could not be accessed by MailChimp's Api. Please confirm the URL: https://...`.

Is there any way to circumvent this?

Thanks in advance.

**Comment by Santiagoebizmarts** [comment]
Hello,

This is not an issue in the code. Please send an email to our support to mailchimp@ebizmarts-desk.zendesk.com.

Please read our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) before creating an issue.

Regards.
