### ISSUE TITLE
Bug Ebizmarts_MailChimp_Model_Api_Products

### ISSUE THREAD

**Issue by KaipiYann** [mailchimp/mc-magento#394]
In the Ebizmarts_MailChimp_Model_Api_Products _buildNewProductRequest method I think there is a problem with your code if a configurable product doesn not have a children.

When you retrieve the childrenIds you get them grouped... so you should flat the array and check if we got at least one child or the "in" condition will not work.

Here is my corrected code 
```php
$childProducts = $this->productTypeConfigurable->getChildrenIds($product->getId());
$childrenIds = array();
foreach ($childProducts as $groupedChildrenIds) {
    $childrenIds = array_merge($childrenIds, $groupedChildrenIds);
}

    if(count($childrenIds)) {
      //@TODO: No manda los children que no tienen stock.
      $collection = $this->makeProductsNotSentCollection($mailchimpStoreId, $magentoStoreId);
      $collection->addAttributeToFilter("entity_id", array("in" => $childrenIds));

      foreach($collection as $childProduct) {
          $variantProducts[] = $childProduct;
      }
}
```

**Comment by Santiagoebizmarts** [comment]
Hi @KaipiYann 

Thanks for your contribution. We will test this and probably add it soon.

Kind Regards.

**Comment by Santiagoebizmarts** [comment]
This has been solved in the latest version. You can see the fix [here](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php#L545).

Regards.
