### ISSUE TITLE
MailChimp Product Recommendations Blank

### ISSUE THREAD

**Issue by urifoox** [mailchimp/mc-magento#395]
Hello,

One of our customers reported the following:

> I submitted two orders tonight and both MailChimp order notifications were missing the Product Recommendations from the emails - the emails only had the heading for Product Recommendations but no products themselves. I did not delete this part from the MailChimp template.

We are unsure of what settings to check or what could be causing this issue. We have not heard this from any other customer. Have you encountered this before and do you have any suggestions?

**Comment by ebizmarts-keller** [comment]
Hello, 

This doesn't seem to be an issue with the code, it is likely an issue with some configuration.

If you send a support request to mailchimp@ebizmarts-desk.zendesk.com we'll take a look at it.

Please try to include all the relevant information so we can speed up the process, like versions of Magento and the module for example.


Regards
