### ISSUE TITLE
Abandoned Guest checkouts using Subscribed email addresses not passed to MC

### ISSUE THREAD

**Issue by lduh** [mailchimp/mc-magento#40]
Email addresess that is subscribed using the newslettersignup box ((ee+guestAC, lee+guestAC14) show as subscribed. Guest checkouts made in those windows with those email addresses that are then abandoned are not showing up in MC, those emails are not being added to the Abandoned Carts queue.

**Comment by Santiagoebizmarts** [comment]
This refers to the bottom subscription form.
