### ISSUE TITLE
'Get API credentials' button not shown under MailChimp configuration

### ISSUE THREAD

**Issue by mlippie** [mailchimp/mc-magento#400]
## Preconditions
1. Magento 1.9.3.3 with latest patches (filled with a couple years worth of data)
2. mc-magento version 1.1.7

## Steps to reproduce
1. Install mc-magento
1. Navigate to Configuration
2. Click 'mailchimp' under 'mailchimp' section

## Actual and expected results
*Actual*
No 'Get API credentials' button  present
*Expected*
'Get API credentials' button

**Comment by ebizmarts-keller** [comment]
Hello, 

Something must have gone wrong with the installation, the button is showing well in our environments and hundreds of clients.

If you send a support request to mailchimp@ebizmarts-desk.zendesk.com we can give you a hand to try to solve this.

I'm closing this issue.

Regards
