### ISSUE TITLE
Store data Problema

### ISSUE THREAD

**Issue by aquere** [mailchimp/mc-magento#401]
Magento 1.9.2.4
MailChimp 1.1.7

Hello!
I am having problem with the integration of MailChimp is not synchronizing requests, products and clients.
What would be the solution?

[Image Error](http://fazzoletti.com.br/MailChimp.jpg)

**Comment by ebizmarts-keller** [comment]
Hello, 

Please send a support request to mailchimp@ebizmarts-desk.zendesk.com and we'll help you with your problem.
