### ISSUE TITLE
(Ebizmarts_MailChimp) File PHTML missing from the extension package

### ISSUE THREAD

**Issue by frain45** [mailchimp/mc-magento#402]
System
--------------
Using Magento 1.9.3. Downloaded latest version of Magento-Mailchimp integration module (1.1.7) from Ebizmarts web site. Installed correctly. The module's administration pages in System > Config is visible. Module connects successfully to the Mailchimp account.

Problem
--------
When browsing the front-end of the site, each page reports a "Fatal error" in system log: the file "emailcatcher.phtml" is considered an incorrect template. This means that Magento does not find the template file at the expected location. 

In the module's configuration file "mailchimp.xml", the template is located in a "popup" directory:

< block type="mailchimp/popup_emailcatcher" name="emailcatcher" template="ebizmarts/mailchimp/popup/emailcatcher.phtml" >< /block >

However, neither the directory nor emailcatcher.phtml are found in the module's 1.1.7 archive downloaded from Ebizmarts web site.

My solution
------------
I found the file emailcatcher.phtml in Ebizmart's "Abandoned Carts" module. 

In this file, I replaced:
- All references to "Ebizmarts_AbandonedCarts_Model_Config" with "Ebizmarts_MailChimp_Model_Config".
- The capitalized word "ACTIVE" with "GENERAL_ACTIVE".

Finally, I put the file in the expected position: 
/app/design/frontend/base/default/template/ebizmarts/mailchimp/popup

Result
------
Now, the error message about emailcatcher.phtml is not logged any more while browsing the front-end. However, other files could be missing. Also, I took emailcatcher.phtml from another extension: that could lead to more problems.

Expected solution from Ebizmarts
----------------------------------
Please check the Mailchimp module package, version 1.1.7, and include all required files. If I am notified when the updated module package is available, I will test it and report here.

**Comment by ebizmarts-keller** [comment]
Hello, 

The file is located at **app/design/frontend/base/default/template/ebizmarts/mailchimp/popup** in version 1.1.7, I just checked this downloading the extension from the repository here: https://github.com/mailchimp/mc-magento/releases/tag/1.1.7

Can you please re-download and check again?

**Comment by frain45** [comment]
I confirm that the zip that you pointed me to has the required files. 
But the one downloaded from your web site is different! 

- This is the file that I just downloaded from Github:
[mailchimp-MailChimp_For_Magento-1.1.7-github.zip](https://github.com/mailchimp/mc-magento/files/1176381/mailchimp-MailChimp_For_Magento-1.1.7-github.zip)

- This is the one downloaded earlier from Ebizmarts (was tgz, renamed "zip" or Github denies upload):
[mailchimp-MailChimp_For_Magento-1.1.7-ebizmarts.zip](https://github.com/mailchimp/mc-magento/files/1176396/mailchimp-MailChimp_For_Magento-1.1.7-ebizmarts.zip)

**Comment by ebizmarts-keller** [comment]
Hello, 

Can you tell me the site you downloaded it from (the URL)? That doesn't look right, inside the zip archive I see a 1.1MB file with no format.

From our store a 324KB zip should be downloaded for version 1.1.7, that inside has the folder structure, are you sure you are downloading from store.ebizmarts.com? I just downloaded it from there and everything seems to be in place.

If you are sure you are downloading it from there, try re-purchasing the product and download again from "My Downloadable Products" in our store, not sure if it is going to give you 2 links (if so use the new one) or update the existing one, but give that shot.

**Comment by frain45** [comment]
Hello, sorry for the late reply.

I downloaded the first, non-working archive from https://store.ebizmarts.com/mailchimp4magento.html

I started [here](http://kb.mailchimp.com/integrations/e-commerce/connect-your-online-store-to-mailchimp), then arrived [here](http://kb.mailchimp.com/integrations/e-commerce/connect-or-disconnect-mailchimp-for-magento), which brought me [here](https://github.com/mailchimp/mc-magento/issues/402)

I will not go throught the whole process again to re-test downloading from your site: if you say that it works, I believe you. Sometimes archives become corrupted during download.   :-)
