### ISSUE TITLE
Cart email sent despite order being completed

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento#403]
There are some situations where the abandoned cart emails are sent regardless of having the order completed, this could possibly be caused by some third party extension that deals with orders or carts.

This happens in those cases because we are not verifying in the list of orders if the purchase was made or not when sending the converted quotes.

**Comment by seansan** [comment]
Is this issue still open and being worked on?

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Actually this has been solved already with the following lines of code:
https://github.com/mailchimp/mc-magento/blob/master/app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php#L220-L227

Thanks for helping us noticing the issue is still open.

Regards.
