### ISSUE TITLE
Unnecessary batch processing with empty batch_id causes errors

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#404]
Hello!

Hi there.

**Preconditions:**

1. mc-magento 1.1.7
1. records in mailchimp_sync_batches with empty batch_id. Dont know why they have appeared, but i've found two of them in my production DB. Please look at the attach
![empty_batch_id](https://user-images.githubusercontent.com/8599788/28569018-b6e616fc-7140-11e7-9371-77d4ed9fd157.png)

**Steps to reproduce:**

1. Run task _mailchimp_bulksync_subscriber_data_

**Actual result:**

1. In _Ebizmarts_MailChimp_Model_Api_Batches->getResults()_
 * _$item->getBatchId()_ is empty string
 * after loop _rmdir_ **deletes** _var/mailchimp/ folder_
1. On the next iteration:
 * _$item->getBatchId() = "blabla"_
 * in _Ebizmarts_MailChimp_Model_Api_Batches->getBatchResponse()_
     * _$fileName = 'var/mailchimp/blabla.tar.gz'_
     * _fopen($fileName)_ => **Warning: failed to open stream: No such file or directory' (because var/mailchimp was deleted on previous iteration)**
     * _curl_setopt($ch, CUROPT_FILE, false)_ => **Warning: curl_setopt(): supplied argument is not a valid File-Handle resource (because fopen returns false, file doesnt exists)**

**Expected result:**

1. In _Ebizmarts_MailChimp_Model_Api_Batches->getResults()_ items with empty batch_id are skipped (or may be they should be deleted - they will be processed never, and they just spend server time) - directory _mailchimp_ must not be deleted anyway

Regards, Nikolay

**Comment by ebizmarts-keller** [comment]
Hello, 

Can you confirm if the issue is still present in version 1.1.8, if so we'll look into it.

You can download it from here: https://github.com/mailchimp/mc-magento/releases/tag/1.1.8
