### ISSUE TITLE
Error upgrading to 1.1.8

### ISSUE THREAD

**Issue by studio2f** [mailchimp/mc-magento#412]
**Preconditions**

- Magento CE 1.9.3.4
- mc-magento 1.1.6 (installed)
- Magento Compilation not enabled

**Steps to reproduce**

- Clear Cache
- Install mc-magento 1.1.8
- Clear cache again
- Log out of Admin and log back in
- Navigate to Admin > System > Configuration > Mailchimp

**Expected Result**

MailChimp for Magento admin configuration screen displayed.

**Actual Result**

Error dumped: 

```
Fatal error: Uncaught Error: Class 'Ebizmarts_MailChimp' not found in /home/site/domains/my.site.com/app/code/community/Ebizmarts/MailChimp/Helper/Data.php:768 Stack trace: #0 
/home/site/domains/my.site.com/app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Account.php(33): Ebizmarts_MailChimp_Helper_Data->getApi('0', 'default') #1 
/home/site/domains/my.site.com/app/code/core/Mage/Core/Model/Config.php(1357): Ebizmarts_MailChimp_Model_System_Config_Source_Account->__construct(Array) #2 
/home/site/domains/my.site.com/app/Mage.php(463): Mage_Core_Model_Config->getModelInstance('Ebizmarts_MailC...', Array) #3 
/home/site/domains/my.site.com/app/Mage.php(477): Mage::getModel('Ebizmarts_MailC...', Array) #4 
/home/site/domains/my.site.com/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(449): Mage::getSingleton('Ebizmarts_MailC...') #5 
/home/site/domains/my.site.com/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_ in /home/site/domains/my.site.com/app/code/community/Ebizmarts/MailChimp/Helper/Data.php on line 768

```

**Note**
Mandrill configuration tab works. Displays "Mandrill For Magento v1.1.8" and all settings

**Comment by centerax** [comment]
Check that your `lib` folder matches this https://github.com/mailchimp/mc-magento/tree/develop/lib

**Comment by studio2f** [comment]
I match it exactly.

**Comment by studio2f** [comment]
Did the filename case change in /lib/Ebizmarts/MailChimp.php? Was it previously /lib/Ebizmarts/mailchimp.php?

Doing local development on OS X (a case insensitive file system) and then pushing to a case sensitive file system, this update was lost.

**Comment by ebizmarts-keller** [comment]
Hello,

You must make sure the name of the folder in lib is MailChimp (not Mailchimp) and the file is MailChimp.php (not Mailchimp.php)

See this for reference: https://ebizmarts.com/forums/topics/view/26192

If that didn't fix it let us know
