### ISSUE TITLE
Feature Request: Small Image instead of Base Image

### ISSUE THREAD

**Issue by studio2f** [mailchimp/mc-magento#414]
mc-magento is sending the Base Image for all products to MailChimp. We have unique Small Images for each of our products. We'd prefer to have the option of having our Small Images sent to MailChimp instead of Base Image.

**Comment by studio2f** [comment]
Our small images are 500x500, but mc-magento seems to be sending 88x88 images to MailChimp when small image is selected in version 1.1.11

**Comment by Santiagoebizmarts** [comment]
Hello @studio2f 
Magento small images are resized to 88x77.
The base image is the only one going with the real size.

Regards.

**Comment by studio2f** [comment]
If you're using the RWD theme, the small image default is 300px for the front-end.

**Comment by Santiagoebizmarts** [comment]
@studio2f I guess they only affect how it is shown because we call the Magento function getSmallImage, the resize is made automatically by the Magento code.

Regards.

**Comment by studio2f** [comment]
But mc-magento could set the cached image size, no? 

`if($product->getSmallImage()){
            (string)Mage::helper('catalog/image')->init($product, 'small_image')->resize(xxx, xxx);`

Currently, the small image being sent is less than thumbnail sized

**Comment by Santiagoebizmarts** [comment]
@studio2f Alternative: You should be able to modify this sending the size in the parameter function [HERE](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L1270).

Just set it like this: $imageUrl = $productModel->$upperCaseImage(300, 300);

The first number is for width, the second height.

**Comment by studio2f** [comment]
Thanks!
