### ISSUE TITLE
mailchimp_process_webhook_data Cron failures

### ISSUE THREAD

**Issue by mindfriction** [mailchimp/mc-magento#415]
Installed latest v1.1.8 on Magento 1.9.3.4 and mailchimp_process_webhook_data Cron continues to fail with the following error:

Uncaught exception 'TypeError' with message 'Argument 1 passed to Ebizmarts_MailChimp_Model_ProcessWebhook::_profile() must be of the type array, boolean given, called in /html/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php on line 59' in /html/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php:202

Any ideas?

**Comment by ebizmarts-keller** [comment]
Hello, 

Can you tell me the version of PHP that you are using?

**Comment by mindfriction** [comment]
PHP 7.0.17 (cli) (built: Mar 24 2017 13:51:23) ( NTS )

**Comment by ebizmarts-keller** [comment]
Can you try with PHP 5.6? That is likely to be the issue.

Have in mind that PHP 7 is not officially supported by Magento 1, and our extension was made to work with PHP 5 as well.

http://docs.magento.com/m1/ce/user_guide/magento/system-requirements.html

**Comment by mindfriction** [comment]
While I may be incorrect, it appears that the line of code: $data = unserialize($webhookRequest->getDataRequest()); that was introduced in version 1.1.7 is the culprit. Which is why this started when I upgraded from 1.1.6 to 1.1.8

Is unserialize not supported by PHP 7? Or is there a simple alternative piece of code to get around this so version 1.1.7+ will work with PHP 7?

I'm afraid that the performance gains of running PHP 7 are too good to roll back just to get this extension to work.

Do you plan to add PHP 7 compatibility to your roadmap anytime soon (despite PHP 7 not being officially supported by Magento 1)? I have a feeling that I won't be the first to encounter this issue as many have started to use the PHP 7 compatibility extension for Magento 1 by Inchoo

**Comment by mindfriction** [comment]
P.S. I would like to apologize if this was the wrong location to post this (my) issue.

**Comment by ebizmarts-keller** [comment]
Hello,

unserialize is supported by PHP 7, there is something else in the code that PHP 7 doesn't like (it could be related to the line you mention), I'll try to reproduce this and if I come up with something I will let you know.

I'm not sure about full compatibility with PHP7 using the Inchoo extension, to my knowing it isn't in the roadmap for now, it would probably require a big deal of refactoring of the code in most of the extension that I don't know if it will be considered viable by the team.

Maybe.
