### ISSUE TITLE
Certain Merge fields not transferred

### ISSUE THREAD

**Issue by infabo** [mailchimp/mc-magento#420]
It seems like, for example STOREID or STORECODE don't get synced to Mailchimp, if the user is not subscribed to the newsletter. Once the user subscribes to the newsletter, STORECODE/STOREID/... get populated.

**Comment by Santiagoebizmarts** [comment]
Hello @infabo,

Customer objects in MailChimp does not support Merge fields as you can see in the doc here.
Subscribers do as you can see here. Customer data can not be used for campaigns filters anyways due to the transactional status.

Regards.

**Comment by infabo** [comment]
> as you can see in the doc here

can you link this doc please?

**Comment by infabo** [comment]
I am talking about list members, i guess this is what you call "subscriber". 

From the API doc: http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/

Here nowhere any restriction is mentioned. all listmembers, irrelevent whether subscribed or not, have mergefields.
