### ISSUE TITLE
After update to 1.1.8 PayPal redirects to /checkout/cart after purchase

### ISSUE THREAD

**Issue by darekkosyl** [mailchimp/mc-magento#429]
After update to 1.1.8 PayPal redirects to /checkout/cart page with "Your cart is empty" message after successful purchase when using Google Chrome (MS Edge is fine). Paying with credit card redirects to success page as expected. It did not happen with 1.1.7. We use your SagePay Pro v 4.2.1 and One Step Checkout 4.5.8 by idev. There is absolutely nothing in logs to point me anywhere. Could you help?

**Comment by centerax** [comment]
this is the Mailchimp for Magento repository, not sagepay.-
 Check [here](https://ebizmarts.com/contact-us) the support channels we have.

**Comment by darekkosyl** [comment]
This is to do with Mailchimp for Magento 1.1.8, we didn't have that problem before we updated.
