### ISSUE TITLE
flag 'bad' addresses, and stop trying them.

### ISSUE THREAD

**Issue by sam327** [mailchimp/mc-magento#436]
In my Mailchimp_Errors.log file, I've got a few thousand items in my log file that look like this: 

> 2017-08-15T13:25:05+00:00 DEBUG (7): Invalid Resource : xxxx@xxxx.com looks fake or invalid, please enter a real email address.
> 2017-08-15T13:40:03+00:00 DEBUG (7): Invalid Resource : xxxx@xxxx.com looks fake or invalid, please enter a real email address.
> 2017-08-15T13:45:02+00:00 DEBUG (7): Invalid Resource : xxxx@xxxx.com looks fake or invalid, please enter a real email address.
> 2017-08-15T13:45:03+00:00 DEBUG (7): Invalid Resource : xxxx@xxxx.com looks fake or invalid, please enter a real email address.

It's only one email address, and it seems to try this every few minutes - and has been doing so for days...

I found the email in the newsletter subscribers list (not customers) and deleted it, so it'll stop trying to process. It would be nice if the system stopped trying bad addresses after a couple tries.

**Comment by Santiagoebizmarts** [comment]
Hello,

Failing subscribers are already flagged, the problem is in the filter we do when sending the data to MailChimp. It should work okay now in the referenced commit.

Regards.
