### ISSUE TITLE
Double opt-in not working correctly

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento#437]
Magento version: 1.9.3.3
Mailchimp version: 1.1.8

I enable double opt-in in Magento **(System>Configuration>Customers>Newsletter>Need to confirm>Yes)**

1. I subscribe an email to the newsletter from the front-end
2. The address is with status of unconfirmed in both Magento and Mailchimp (as expected)
3. I receive the email and confirm the subscription (as expected)
4. The status changes to subscribed in Mailchimp, but remains as "Not Activated" in Magento (not as expected)

Additionally an user reported the following happening afterwards:

> ...and after some cronjobs later the subscriber is deleted in magento and is cleared in mailchimp.

**Comment by Santiagoebizmarts** [comment]
This is working in the latest version.

**Comment by steffen-wirth** [comment]
Hi,

we are working with 
Magento version: 1.9.2.4
Mailchimp version: 1.1.9.1

and this issue still exists. The new Subscriber status in Magento is not changed and set to "not activated".

**Comment by Santiagoebizmarts** [comment]
Hello @steffen-wirth 

Please contact our support team at mailchimp@ebizmarts-desk.zendesk.com, our support team will be happy to help you out.

**Comment by ebizmarts-keller** [comment]
This could be the cause: https://github.com/mailchimp/mc-magento/issues/508
