### ISSUE TITLE
Warning in MC about wrong version? ==> Disconnected?

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#438]
![image](https://user-images.githubusercontent.com/652395/29534188-5a5c8760-86b5-11e7-977e-4e5cf49f7826.png)
![image](https://user-images.githubusercontent.com/652395/29534202-66bb8286-86b5-11e7-9b53-d7ea3676682d.png)

**Comment by centerax** [comment]
can you provide some more detailed information on the issue?

**Comment by seansan** [comment]
yes
in mailchimp I am warned about a version issue
and are provided a link to your website: please upgrade
in magento we see the version is correct (and not the same as in MC)
so somewhere in the IF 1 system is telling the other system something wrong?

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
Order notifications will work with your current version. The problem is probably caused due to some configuration problem preventing orders to be sent. Please contact us to mailchimp@ebizmarts-desk.zendesk.com
