### ISSUE TITLE
Opt-in confirmation email not sent with user account

### ISSUE THREAD

**Issue by tylerschade** [mailchimp/mc-magento#440]
Preconditions: 
1. Magento CE 1.9.0.1
2. mc-magento 1.1.8

Steps to reproduce:
1. Set `Need to Confirm` to `Yes` in system configuration.
2. Begin creating a user account.
3. Check the `Sign Up For Newsletter` box.
4. Register the account.
5. Wait for the confirmation email. It doesn't arrive.

Or:
1. Set `Need to Confirm` to `Yes`, and `Subscribe On Checkout` to `Enabled - Not Checked By Default` in system configuration.
2. Create a new user account, but do not check the `Sign Up For Newsletter` box.
3. Add a product to cart, and checkout.
4. In the checkout, check the `Sign Up For Newsletter` box. 
5. Wait for the confirmation email. It doesn't arrive.

Expected result, from both sets of steps:
An opt-in confirmation email should be sent to the user.
Actual result:
No opt-in email is sent

Any ideas? This is on a Magento 1.9.x store.

**Comment by MelissaEbizmarts** [comment]
Hello Tylerschade, 
Please check our [guideliness](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to post the issue correctly.

Kind Regards

**Comment by tylerschade** [comment]
@MelissaEbizmarts I'm so sorry about that. I've updated the issue. Please let me know if you need more information.

**Comment by MelissaEbizmarts** [comment]
Hello Tyler, 
Thanks! I will try to replicate on my end and back to you as soon as possible.

**Comment by MelissaEbizmarts** [comment]
Hello Tyler, 
I was able to reproduce on my end. But is also happening on my vanilla magento installation(No modules installed, not even Mailchimp for Magento).
Seems to be a Magento issue.

Kind Regards.

**Comment by tylerschade** [comment]
Alright, thanks!

Tyler
