### ISSUE TITLE
Invalid View Order URL used in Order Notifications for Magento

### ISSUE THREAD

**Issue by jessiebrown** [mailchimp/mc-magento#444]
The View Order link in an Order Confirmation email for MailChimp for Magento leads to the account login page for a store, rather than directly to the order page. The order IDs in MailChimp passed by MC4Magento are the correct IDs, however the order_url parameter being passed via the API is invalid.

For orders completed while logged into an account for the store this is not a problem, as logging into the account will allow the customer to view their previous orders. For a guest checkout to view their order details however, they need to use the "Orders and Returns" link found at examplestoredomain.com/sales/guest/form/ to lookup the order using the order ID and customer details. This is particularly problematic because the order ID MailChimp uses does not correspond to the actual order ID in Magento.

*Example:*
In a test store, for order #100000072 the following order URL passed in the API:
`"order_url\":\"http:\\\/\\\/159.203.84.204:8888\\\/index.php\\\/sales\\\/order\\\/view\\\/order_id\\\/78\\\/?___store=default\"`

In the Order Confirmation email, the View Order link leads to http://159.203.84.204:8888/index.php/sales/order/view/order_id/78/?___store=default&mc_cid=84d4b0a4f8&mc_eid=6ae823b641, which simply redirects to http://159.203.84.204:8888/index.php/customer/account/login/.

**Comment by Santiagoebizmarts** [comment]
Hello @jessiebrown 

Thanks for your feedback. This will be implemented in version 1.1.10 which should be released in about 4 weeks.

Kind Regards.

**Comment by Santiagoebizmarts** [comment]
Hello @jessiebrown ,

After some testing I can see the order url is okay. It makes sense that you need to log in in order to see the order details. Magento does not allow a front end view without being logged in.

Regards.

**Comment by jessiebrown** [comment]
@Santiagoebizmarts thank you!
