### ISSUE TITLE
Magento Mailchimp account shows --- Invalid API Key ---

### ISSUE THREAD

**Issue by bijugit** [mailchimp/mc-magento#445]
Hi,

We have using MailChimp For Magento v1.1.7 by ebizmarts module.

We given api keys details, but we getting error like 

for Api Call: API call to lists?fields=lists&count=100 failed: Failed to connect to us16.api.mailchimp.com port 443: Connection refused -

Regards,

**Comment by bijugit** [comment]
Hi,

We can fix this issue only whitelisting the blocked IP address. This is not a feasible solution, can we fix this issue any other possible way?

Please give you valid reply as soon as possible.

Regards,

**Comment by Santiagoebizmarts** [comment]
Hello @bijugit 

The extension is constantly contacting MailChimp to send and retrieve data. Some permission is required to get this working. I suggest you to contact MailChimp support in order to find out the best way of configuring your server.

Regards.
