### ISSUE TITLE
Ability to pass a store value for Vendor parameter in MailChimp for Magento

### ISSUE THREAD

**Issue by jessiebrown** [mailchimp/mc-magento#446]
Users would like the ability to segment on Vendor information within their List. Currently, MailChimp for Magento doesn't pass information to the Vendor parameters to do this.

**Comment by Santiagoebizmarts** [comment]
Hello,

MailChimp uses the vendor field for category Follow-up, we are implementing this and will be available for version 1.1.10 which should be released in about 4 weeks.

This issue is directly related to https://github.com/mailchimp/mc-magento/issues/476

Regards.

**Comment by Santiagoebizmarts** [comment]
This has been resolved in issue #476
