### ISSUE TITLE
MailChimp for Magento doesn't pass special prices to MailChimp

### ISSUE THREAD

**Issue by jessiebrown** [mailchimp/mc-magento#447]
MailChimp for Magento doesn't pass over special prices to use in campaigns, which can lead to user and subscriber confusion.

For example, when sending an abandoned cart email, only the base price of the product passes over, so if the item is on sale, the full price is shown. This decreases enthusiasm in the price when people open their email since they are shown a higher price than on the user's store site.

**Comment by ebizmarts-keller** [comment]
Hello, 

I'm afraid we have this in the backlog until the Mailchimp API supports it, there is already an existing issue for this: https://github.com/mailchimp/mc-magento/issues/109
