### ISSUE TITLE
Deleting Newsletter subscribers in Magento cleans them in MailChimp

### ISSUE THREAD

**Issue by jessiebrown** [mailchimp/mc-magento#448]
Selecting a subscriber in the Newsletter section of Magento and then deleting them will push a call to MailChimp cleaning them. This is less than ideal as, unlike a simple deletion, a cleaned address is in a compliance state. This would mean that they would not be able to be added back or further updated outside of a double opt-in signup.

**Comment by Santiagoebizmarts** [comment]
Hello @jessiebrown 

Thanks for your feedback, you are completely right about this.

Regards.
