### ISSUE TITLE
Create option in backend adminhtml to subsribe customers

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#450]
Create option in backend adminhtml to subsribe customers #270

Now customers are synced but not subscribed

But we have customers on the phone and ask them if they want to subscribe: if yes, then we would like to tick a box: subscribe to newsletter

if ticked, then sync customers but ALSO subscribe

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Thanks for your feedback. We will add this feature as soon as possible.

Regards.

**Comment by seansan** [comment]
please check then also
​ ​
​
#449
​ ​
already

​for EU law we must be able to prove​ for how+when the user subscribed (and
show the exact phrasing that the user consented to)


On Tue, Aug 29, 2017 at 9:18 PM, Santiagoebizmarts <notifications@github.com

**Comment by gonzaloebiz** [comment]
@seansan 

you don't need to put references to other issues that not have any relations, that only mess up the original issue

Thanks

**Comment by seansan** [comment]
there is a direct relation - and it is only a reference ...

On Tue, Aug 29, 2017 at 9:28 PM, Gonzalo Dominguez <notifications@github.com

**Comment by seansan** [comment]
Thx. As soon as possible is 1.1.10?

https://github.com/mailchimp/mc-magento/milestone/14

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Unfortunately we did not have the time to get into this for the incoming release.

Regards.

**Comment by seansan** [comment]
​lets plan it for next then .... because I think was supposed to be done
some versions earler​


On Thu, Oct 19, 2017 at 4:35 PM, Santiagoebizmarts <notifications@github.com

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Not really, when having access to the backend it is rather easy to access that customer and subscribe it.
I can confirm it will not be in the release after 1.1.10 neither.
Some things we consider to be a priority over this are:
- Adding interest group support
- Improving subscriber sending performance
- Adding support for bundled and grouped products when possible.

All these are big changes and will take some time.

Regards.

**Comment by seansan** [comment]
​I would then note this down as the extension does not sync all customers.
Our orders are 23% backend entered orders - and for many other retailers at
least a small percentage is entered via the backend​ (when on phone, in
store, or when correcting orders).

Would be great to finally have

Personally I would go for completeness first before addinf interest groups
- mailchimp now has 100-23%=77% only


On Thu, Oct 19, 2017 at 5:05 PM, Santiagoebizmarts <notifications@github.com

**Comment by Santiagoebizmarts** [comment]
@seansan 

Please note we arrange the priorities with MailChimp, anyways we understand your situation and greatly appreciate your feedback.
As we always say the extension is open source and community inputs are always welcome.

Regards.

**Comment by seansan** [comment]
see also https://github.com/mailchimp/mc-magento/issues/527

**Comment by giorello** [comment]
Hi Seansan, 

We had been investigating this and trying to implement this, but to do this work correctly we should do a magento rewrite and we try to avoid rewrites to prevent conflicts.

If you find out a way to do it without a rewrite, please let us know.

Regards, 
Javier Giorello.
