### ISSUE TITLE
First Purchase Automation Not Triggering

### ISSUE THREAD

**Issue by Thorstoned92** [mailchimp/mc-magento#453]
- Magento CE 1.9.1.0
- MailChimp for Magento 1.1.8

Although the module appears to sync correctly, and e.g. abandoned cart automation emails work, the "first purchase" automation we have set up does not trigger. The MailChimp team ran a 24h tracker test on our integration, and came with the following conclusion:

> When looking at the calls that input the e-commerce data, we saw that the BATCH call adding in the order for "twentyfourhourtrackertest@gmail.com" noted the order twice within that BATCH call. On the second call, the system read the data as a second order, which is why these test contacts have been unable to trigger that "first order" automation. This would lead us to want to investigate the syncing in more details, though unfortunately we have exhausted our resources on the tracker.  At this time I would recommend reaching out to the developers ebizmarts for additional troubleshooting on the syncing of these orders through the API. 

Expected result:
1. A new customer purchases something from the store
2. The integration sends this new customer's info to MailChimp
3. The customer's order total == 1 in MailChimp's system
4. First purchase automation triggers

Actual result:
1. A new customer purchases something from the store
2. The integration sends this new customer's info to MailChimp
3. The customer's order total == 2 in MailChimp's system, even though the customer has only placed 1 order
4. First purchase automation does not trigger, as the trigger is order total == 1

Thank you for looking into this!

**Comment by MelissaEbizmarts** [comment]
Hello Thorstoned92,
I was able to reproduce on Magento v1.9.3.4 with M4M v1.1.8. Our main developer will take look to this issue.

Thanks for your feedback.
Kind Regards
