### ISSUE TITLE
mailchimp_webhook_request

### ISSUE THREAD

**Issue by urifoox** [mailchimp/mc-magento#459]
Hello,

What is the table mailchimp_webhook_request used for - we have some tables that are GBs in size. Is it safe to truncate?

**Comment by gonzaloebiz** [comment]
Hi @urifoox 

no, it's not safe.
You can remove all the records with processed = 1 but not truncate the table
What is the size of this table in your magento?

Best

**Comment by sam327** [comment]
I came to ask a similar question - we're getting tables that are 250 MB & 300 MB in size. And it seems to grow pretty fast.

**Comment by gonzaloebiz** [comment]
We already have an issue for this (https://github.com/mailchimp/mc-magento/issues/460) and working in a solution for future version
