### ISSUE TITLE
Multistore links gives main-domain link in Campaign Newsletters

### ISSUE THREAD

**Issue by rsp-vicus** [mailchimp/mc-magento#464]
Hi,

- MailChimp For Magento v1.1.8.2
- Magento ver. 1.9.0.1
- Production site

Total subscribers: 35550
Ecommerce Data uploaded to MailChimp store xy NL:
Initial sync : Finished
Total Customers: 252
Total Products: 54
Total Orders: 319
Total Carts: 0

We have a Multistore
Shop1 nl
Shop1 en
Shop2 nl
Shop3 nl
Shop3 en

When we have a campaign of Shop3 and want to make an newsletter with products. We choose to pick some products of shop3 nl. The view and information is correct of the product. Except the link, the link goes always to the default (Shop1 nl) shop. 

How can we get the right link of a product in our newsletter?

**Comment by gonzaloebiz** [comment]
Hi @rsp-vicus 

please, follow our [issue reporting guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines)
I close the issue for now and reopen it when you follow the guidelines

Best

**Comment by rsp-vicus** [comment]
Please reopen ticket

**Comment by centerax** [comment]
well reopen as soon as the issue reported follow this guidelines: https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines

**Comment by Santiagoebizmarts** [comment]
This is a duplicate for issue https://github.com/mailchimp/mc-magento/issues/442
Check there for any update.

Regards.
