### ISSUE TITLE
Mailchimp ProcessWebhook.php giving Fatal error while executing magneto cron

### ISSUE THREAD

**Issue by bijugit** [mailchimp/mc-magento#466]
Hi,

We have using 
 Magento ver is : 1.9.2.4
 MailChimp For Magento v1.1.7
While executing the magneto default cron, it gives following error.
PHP Fatal error:  Call to a member function getId() on a non-object in app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php 
protected function _unsubscribe(array $data)
    {
        $subscriber = Mage::helper('mailchimp')->loadListSubscriber($data['list_id'], $data['email']);
        if ($subscriber->getId()) {
     ......

the $subscriber->getId() - call gives the error. 

Why this call gives Fatal error ? is there any additional changes need to implement.

Please give your valid feedback as soon as possible.

Please check the attached file for reference.

Regards, 
[ProcessWebhook.php.zip](https://github.com/mailchimp/mc-magento/files/1284895/ProcessWebhook.php.zip)

**Comment by Santiagoebizmarts** [comment]
Hello @bijugit 

This has been solved in the latest version.

Kind Regards.
