### ISSUE TITLE
New release ETA?

### ISSUE THREAD

**Issue by dbashyal** [mailchimp/mc-magento#468]
Hi,

There seems a lot of fixes/enhancements since last release. Is there ETA on next release? Or, is it safe to use master branch now in production?

Thank you.

**Comment by Santiagoebizmarts** [comment]
Hello @dbashyal 

This is not an issue, please contact our support at mailchimp@ebizmarts-desk.zendesk.com in order to ask questions.

Anyways the new version should be out next week.

Regards.
