### ISSUE TITLE
Support For Back To Stock Notifications

### ISSUE THREAD

**Issue by sprankhub** [mailchimp/mc-magento#469]
The old extension Ebizmarts_Autoresponder supported "Back to Stock Notifications". Is it planned to include them in this extension as well?

**Comment by Santiagoebizmarts** [comment]
Hello,

This is not responsibility of the extension anymore. Automations are handled by MailChimp, as soon as they allow this feature we will implement what's necessary in the code.

For any further details I suggest you to contact their support.

Kind Regards.

**Comment by sprankhub** [comment]
We asked the MailChimp Support as well. Answer:

> Unfortunately, there isn't anything innately built into the extension or MailChimp that will allow for automated emails to notify customers when an item is back in stock. This sort of workflow would need to be custom devised on your end.

> However, this is incredible feedback that I'd love to submit internally. We do have an API parameter for each product endpoint that is specifically for inventory, so it could be possible to have something setup that looks for positive integers in that field. At this time, though, we do not have anything setup to facilitate this.

So the remaining question regarding this extension is: Do you already send stock update information to MailChimp?

**Comment by sprankhub** [comment]
@Santiagoebizmarts could you please answer my question? Thanks!

**Comment by Santiagoebizmarts** [comment]
Hello @sprankhub 

Sorry for the delay, the extension does send stock updates to MailChimp every time the product is modified either manually or when doing a purchase.
