### ISSUE TITLE
Debugging alerts left in code

### ISSUE THREAD

**Issue by andrew-smart** [mailchimp/mc-magento#470]
There are two alerts that appear to be left in the code (probably for debugging purposes) https://github.com/mailchimp/mc-magento/blob/develop/app/design/frontend/base/default/template/ebizmarts/mailchimp/checkout/subscribe.phtml#L49 and https://github.com/mailchimp/mc-magento/blob/develop/app/design/frontend/base/default/template/ebizmarts/mailchimp/checkout/subscribe.phtml#L52

**Comment by Santiagoebizmarts** [comment]
Hello @andrew-smart 

Thanks for your feedback.
This has been removed in the develop branch. The new version will be released next week.

Kind Regards.
