### ISSUE TITLE
syncSubscriberBatchData sending same subscribers over and over

### ISSUE THREAD

**Issue by quasiobject** [mailchimp/mc-magento#475]
### Preconditions 

1. Magento EE 1.14.2.0
2. mc-magento 1.1.8 (or mc-magento 1.1.8.5)
3. Single store, MailChimp config saved in default scope

### Steps to produce

1. Install 1.1.4
2. Save MailChimp config in default scope
3. Upgrade from 1.1.4 to 1.1.8 (or 1.1.8.5)
4. Add enough newsletter subscribers to exceed mailchimp/general/subscriber_batch_amount or adjust config value so multiple batches are required to sync all subscribers
5. Ensure MailChimp cron jobs are running

### Actual and Expected result

Expected result:

All newsletter subscribers are synced to MailChimp and the mailchimp_sync_delta timestamps are updated for all records in newsletter_subscriber.

Actual result:

mc-magento sends the same batch (first X subscribers based on subscriber_batch_amount) over and over. Only the first batch timestamps are updated.

### Additional information

It appears the `createBatchJson` call in `Ebizmarts_MailChimp_Model_Api_Subscribers` looks for the config in the registry using store id 1.

```
$thisScopeHasSubMinSyncDateFlag = $helper->getIfConfigExistsForScope(Ebizmarts_MailChimp_Model_Config::GENERAL_SUBMINSYNCDATEFLAG, $storeId);
```

The registry is checked for:

`mailchimp_subminsyncdateflag_exists_for_scope_stores_1`

However, as stated, the config is saved in the default scope (0/default). Accordingly, this returns nothing and the config value is set to `Varien_Date::now()` on every run and the cron never progresses past the first batch.

Should a getRealScopeForConfig check for `Ebizmarts_MailChimp_Model_Config::GENERAL_SUBMINSYNCDATEFLAG` be added in order to resolve to the correct config scope?

**Comment by Santiagoebizmarts** [comment]
Hello @quasiobject 

This issue has been addressed in the commit https://github.com/mailchimp/mc-magento/commit/e379841a856a186d940a04336a2c432b76343796

It will be implemented in the 1.1.9 release next week.

Kind Regards.
