### ISSUE TITLE
Ebizmarts_MailChimp_Model_Email_Template->send() -> response "invalid" + "200 OK"

### ISSUE THREAD

**Issue by JeroenBoersma** [mailchimp/mc-magento#493]
Call to -> `messages/send`

If there is something wrong for instance a wrong e-mail address a `200 OK` is returned with a error status in the return.

```
array (size=1)
  0 => 
    array (size=4)
      'email' => string 'TEST' (length=4)
      'status' => string 'invalid' (length=7)
      '_id' => string '12345678901234567890123456789012' (length=32)
      'reject_reason' => null
```

In this case there is a invalid e-mail address and that's why it's declined, there is no way to debug this because the `->send()` will still return true.

`app/code/community/Ebizmarts/MailChimp/Model/Email/Template.php:161`
```php
        try {
            $result = $mail->messages->send($email);
        } catch (Exception $e) {
            Mage::logException($e);
            return false;
        }

        return true;
```

There should be some sort of check if there is a successful return from the server.

**Comment by JeroenBoersma** [comment]
maybe this should be resolved in the Mandrill API as well... I didn't check if there is a valid design choice why there should be a `200 OK`

**Comment by Santiagoebizmarts** [comment]
Solved at https://github.com/mailchimp/mc-magento/pull/860
