### ISSUE TITLE
Mailchimp not recognizing latest version for retargeting ads

### ISSUE THREAD

**Issue by studio2f** [mailchimp/mc-magento#495]
**Preconditions**

Magento CE 1.9.3.6
mc-magento 1.1.9.1 

**Steps to reproduce**

- Create a Google Remarketing Ad campaign at Mailchimp

**Expected Result**

- Ad campaign created.

**Actual Result**

- Mailchimp warns that "Retargeting ads require MailChimp for Magento 1, versions 1.1.7 or later." - -- Does not recognize mc-magento 1.1.9.1 

![Default image at MailChimp](https://www.joannehudson.com/googleads.png)

**Comment by Santiagoebizmarts** [comment]
Hello @studio2f 

Can you confirm you have at least one Magento store successfully synced?

Regards.

**Comment by studio2f** [comment]
We do and all other automations work

**Comment by Santiagoebizmarts** [comment]
Hello @studio2f @seansan 

I am told by MailChimp there was a bug on their side causing this but should be working now.
Can you confirm if this continues to happen when trying to create new Google Remarketing Ad.

Regards.
