### ISSUE TITLE
Magento Guest Checkouts Added as Transactional Despite Subscription Checkbox Being Checked

### ISSUE THREAD

**Issue by jessiebrown** [mailchimp/mc-magento#496]
If the "Subscribe On Checkout" checkbox is enabled, guest checkouts will still be added to the MailChimp list as Transactional even if they have checked this box.

When the API calls are made, the POST /orders passes "opt_in_status": false, and the subsequent PUT /list/:members/:subscriber_hash passes "status_if_new": "subscribed" with no "status" parameter. This means that when the POST /orders completes the customer is added as Transactional and the "status_if_new" parameter cannot set them as subscribed. In Magento they appear as Subscribed on the Newsletter.

**Comment by Santiagoebizmarts** [comment]
Hello @jessiebrown 

Thanks for your feedback. This has been spotted already and solved. You can find the solution [here](https://github.com/mailchimp/mc-magento/commit/bf1edaeab8cb29eca80b545a8594fbaefce64dc9)

Kind Regards.

**Comment by jessiebrown** [comment]
@Santiagoebizmarts thank you for letting me know.
