### ISSUE TITLE
Email not transmitted when signing up with customer account registration

### ISSUE THREAD

**Issue by JosephMaxwell** [mailchimp/mc-magento#507]
Hello,

We are running into a strange issue when a customer creates an account. We are getting the following error message:

```
Invalid Resource for Api Call: lists/51067a9f0b/members/d41d8cd98f00b204e9800998ecf8427e : Required fields were not provided: email_address / email_address : Schema describes string, NULL found instead / merge_fields.WEBSITE : Data did not match any of the schemas described in anyOf. / merge_fields.STOREID : Data did not match any of the schemas described in anyOf. / merge_fields.STORECODE : Data did not match any of the schemas described in anyOf.
```

In my troubleshooting, the cause seems to be that the email is not being transmitted. In every other case we have tested, the email is properly transmitted.

Do you have thoughts as to where we can go to troubleshoot?

**Comment by Santiagoebizmarts** [comment]
Hello,

Please read our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) before creating a new issue.
This does not look like a issue for github. Please contact our support at mailchimp@ebizmarts-desk.zendesk.com

Regards.

**Comment by JosephMaxwell** [comment]
@Santiagoebizmarts: thank you. I missed that.
