### ISSUE TITLE
Webhook not created when module configured on store view

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento#508]
If the Mailchimp plugin is configured at the store view level, the webhook is not created

**Comment by mfronmark** [comment]
Hi, I'm using 1.1.10, but still got the error:

> Could not add Webhook "https://--/monkey/webhook/index/wkey/26de919709a30de7/" for list "--", error code 508, Something went wrong, please try again later.

I removed the actual domain name and list name and replaced it with -- for privacy reasons.

Looking at the configured Webhooks in MailChimp, however, that webhook was actually registered.

Thank you for all your good work on this one!

**Comment by Santiagoebizmarts** [comment]
Hello @mfronmark,

If the webhook was actually created maybe the error was when trying to re-create it. A flag should have been created to prevent the process of creating the webhook again, perhaps that flag was missing but now it exists. Do you see that error more than once? If you do please contact our support at mailchimp@ebizmarts-desk.zendesk.com

Regards,
Santaigo.
