### ISSUE TITLE
Image for simple products not showing when inherited from configurable

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento#513]
When a simple product has no image, but the configurable product does, the simple product is sent without the image url, and the configurable product is sent with the image, along with the associated simple product also with the image url.

But Mailchimp isn't taking the image url from the simple product that comes with the configurable, resulting in simple products with no images to be displayed without any image.

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

When you create an automation which displays a product, you might want to only offer one particular sub product of a configurable. For those cases we need to send the simple product with the configurable data.

Regards.

**Comment by seansan** [comment]
​aha now I understand​

shall we label this for next milestone?

On Tue, Oct 24, 2017 at 4:00 PM, Santiagoebizmarts <notifications@github.com
