### ISSUE TITLE
Empty data

### ISSUE THREAD

**Issue by cfgalvani** [mailchimp/mc-magento#517]
I was getting the error "peer's certificate issuer is not recognized", but after I reinstalled the extension, I didn't get any error message anymore but at Account Details I got nothing (the Username and Total Subscribers are empty/null/blank) and the dropbox with my Mailchimp lists has no list.
Magento 1.9.3.1
Mailchimp For Magento 1.1.9.1
Does anybody has any idea of what is going on?

**Comment by Santiagoebizmarts** [comment]
Hello,

Please note this does not describe any particular issue. This is more of a support request. For those please contact our support team at mailchimp@ebizmarts-desk.zendesk.com.

Kind Regards.
