### ISSUE TITLE
mailchimp_process_webhook_data Never finishes

### ISSUE THREAD

**Issue by ryanrichard25** [mailchimp/mc-magento#521]
Im on 1.1.17 and Ive added the changes to ProcessWebhook.php from issue #295 , but the mailchimp_process_webhook_data task just runs forever and I have to manually kill the cron job via ssh. 

So im stuck in a permanent issue here as I kill it, magento restarts cron, it gets to that task, and its stuck again forever. It was literally running for over a month recently and never completed. Any ideas?

**Comment by Santiagoebizmarts** [comment]
Hello, please note the latest version is 1.1.9.2 so the version you mention does not exist.
Please contact our support team as suggested at https://github.com/mailchimp/mc-magento/issues/295

Regards.
