### ISSUE TITLE
Cron error after recent upgrade to 1.1.9.1 (magento 1934)

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#526]
Cron error after recent upgrade to  https://github.com/mailchimp/mc-magento/releases/tag/1.1.9.1

Hope it helps

MailChimp_Error:  for Api Call: ecommerce/stores/1a171e3f41f307716c0fa389fc89b49b -  in /lib/Ebizmarts/MailChimp.php:273
Stack trace:
#0 /lib/Ebizmarts/MailChimp/EcommerceStores.php(132): Ebizmarts_MailChimp->call('ecommerce/store...', '{"is_syncing":t...', 'PATCH')
#1 /app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php(137): MailChimp_EcommerceStore->edit('1a171e3f41f3077...', NULL, NULL, NULL, true)
#2 /app/code/community/Ebizmarts/MailChimp/Helper/Data.php(1967): Ebizmarts_MailChimp_Model_Api_Stores->editIsSyncing(Object(Ebizmarts_MailChimp), true, '1a171e3f41f3077...', '7')
#3 /app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2067): Ebizmarts_MailChimp_Helper_Data->setIsSyncingIfFinishedPerStore(true, '7')
#4 /app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(98): Ebizmarts_MailChimp_Helper_Data->handleResendDataBefore('7')
#5 /app/code/community/Ebizmarts/MailChimp/Model/Cron.php(28): Ebizmarts_MailChimp_Model_Api_Batches->handleEcommerceBatches()
#6 /app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Ebizmarts_MailChimp_Model_Cron->syncEcommerceBatchData(Object(Aoe_Scheduler_Model_Schedule))
#12 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#13 /cron.php(78): Mage::dispatchEvent('default')
#14 {main}​

**Comment by seansan** [comment]
Found this too

```
[03-Oct-2017 12:50:07 UTC] PHP Fatal error:  Uncaught Error: Call to protected method Ebizmarts_MailChimp_Model_Api_Products::joinProductAttributes() from context 'Ebizmarts_MailChimp_Helper_Data' in app/code/community/Ebizmarts/MailChimp/Helper/Data.php:2202
Stack trace:
#0 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2157): Ebizmarts_MailChimp_Helper_Data->isMissingProductLowerThanId('48598', '9')
#1 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2104): Ebizmarts_MailChimp_Helper_Data->isMissingItemLowerThanId('48598', 'PRO', '9')
#2 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2043): Ebizmarts_MailChimp_Helper_Data->allResendItemsSentPerStoreView('9')
#3 app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2023): Ebizmarts_MailChimp_Helper_Data->allResendItemsSent('9', 'stores')
#4 app/code/community/Ebizmarts/MailChimp/Helper in app/code/community/Ebizmarts/MailChimp/Helper/Data.php on line 2202


```

**Comment by ebizmarts-keller** [comment]
Hello @seansan 

Is the joinProductAttributes function protected in your installation? Check this line in your installation where you are getting the error: https://github.com/mailchimp/mc-magento/blob/master/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php#L517

**Comment by seansan** [comment]
​see image

[image: Inline image 1]​

**Comment by ebizmarts-keller** [comment]
I can't see the image

Can you please just confirm if the function is protected or public in your system?

**Comment by seansan** [comment]
​line 514

    /**
     * @param $collection
     * @param $magentoStoreId
     */
    public function joinProductAttributes($collection, $magentoStoreId)
    {
        $attributeCodes = array("name", "visibility", "description",
"price");
        $config = Mage::getSingleton("eav/config");
        foreach ($attributeCodes as $_code) {
            $attributeName = $config->getAttribute("catalog_product",
$_code);

            if ($_code != 'price') {
                $collection->joinField(
                    $_code, $attributeName->getBackendTable(), 'value',
'entity_id = entity_id',
                    '{{table}}.store_id = ' . $magentoStoreId . ' AND
{{table}}.attribute_id = ' . $attributeName->getId(), 'left'
                );
            }

            $collection->joinField(
                'default_' . $_code, $attributeName->getBackendTable(),
'value', 'entity_id = entity_id',
                '{{table}}.store_id = 0 AND {{table}}.attribute_id = ' .
$attributeName->getId(), 'left'
            );
        }
    }

    /**
     * @param $collection
     */
    public function joinQtyAndBackorders($collection)
    {
        $collection->joinField(
            'qty', 'cataloginventory/stock_item', 'qty',
'product_id=entity_id',
            '{{table}}.stock_id=1', 'left'
        );

        $collection->joinField(
            'backorders', 'cataloginventory/stock_item', 'backorders',
'product_id=entity_id',
            '{{table}}.stock_id=1', 'left'
        );
    }​

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

This looks like if a MailChimp store was deleted manually and Magento is trying to reach it throwing an error. Resetting the store at the configuration should fix the problem.

Regards.

**Comment by seansan** [comment]
​>> This looks like if a MailChimp store was deleted manually and Magento
is trying to reach it throwing an error.

No we never deleted any lists in mailchimp ...

We just started using m4m after magemonkey ...

why did you close the issue?
​


On Mon, Oct 23, 2017 at 7:47 PM, Santiagoebizmarts <notifications@github.com

**Comment by Santiagoebizmarts** [comment]
I closed the issue because there are two different issues here.
Please follow our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) when creating issues.
Also both solutions has been provided:
1. Reset ecommerce data.
2. Make sure the joinAttributeProducts method is public.

If you need any more help with this please contact our support at mailchimp@ebizmarts-desk.zendesk.com

Kind Regards.

**Comment by seansan** [comment]
​I think the actual ​and expected results are clear
I send all the error logs, made a correct description
Only you state: "Make sure the joinAttributeProducts method is public" but
as you can see it already was
Why should I reset eCommerce data? Does this solve the error at hand ...
our does it update update and then run into the error again?

Also about 2 issues. Well if they are 2 issues instead of 1. Then  2 things
are clear. a) They are issues as you say, why then close them? and b) there
are 2

I added the logging as "extra" info - not knowing this was another issue


Also I only post this here so you and others know about it ... and that we
can maybe find a solution
