### ISSUE TITLE
Debug improvement? download all info in 1 go under errors in M1

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#528]
QUICKWIN 

Debug improvement? download all info in 1 go under errors in M1

When sharing problems we send info + repsonse + screenshort of customer ... and always seems to be something missing because other files are requested

Can we not speed up the proces when we can download "all debug info" in 1 go here?

request, response, product var dump and order var dump: then you have it all

![image](https://user-images.githubusercontent.com/652395/31938489-f9ee6512-b8b7-11e7-82b9-cddee837b185.png)

would make everybody happy

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Thanks for your feedback. The information required for debugging is currently available without need of any modification.

Regards.
