### ISSUE TITLE
API call errors after upgrade

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#530]
API call errors after upgrade to latest version

Occurs multiple times in logging, is there more info you need?

How can we help?

```
MailChimp_Error: for Api Call: ecommerce/stores/1a171e3f41f307716c0fa389fc89b49b - in /lib/Ebizmarts/MailChimp.php:273
Stack trace:
#0 /lib/Ebizmarts/MailChimp/EcommerceStores.php(132): Ebizmarts_MailChimp->call('ecommerce/store...', '{"is_syncing":t...', 'PATCH')
#1 /app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php(137): MailChimp_EcommerceStore->edit('1a171e3f41f3077...', NULL, NULL, NULL, true)
#2 /app/code/community/Ebizmarts/MailChimp/Helper/Data.php(1967): Ebizmarts_MailChimp_Model_Api_Stores->editIsSyncing(Object(Ebizmarts_MailChimp), true, '1a171e3f41f3077...', '7')
#3 /app/code/community/Ebizmarts/MailChimp/Helper/Data.php(2067): Ebizmarts_MailChimp_Helper_Data->setIsSyncingIfFinishedPerStore(true, '7')
#4 /app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php(98): Ebizmarts_MailChimp_Helper_Data->handleResendDataBefore('7')
#5 /app/code/community/Ebizmarts/MailChimp/Model/Cron.php(28): Ebizmarts_MailChimp_Model_Api_Batches->handleEcommerceBatches()
#6 /app/code/community/Aoe/Scheduler/Model/Schedule.php(217): Ebizmarts_MailChimp_Model_Cron->syncEcommerceBatchData(Object(Aoe_Scheduler_Model_Schedule))
#12 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#13 /cron.php(78): Mage::dispatchEvent('default')
#14 {main}​
```

Split into 2 issues as requested #526 526

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

That error is trying to change the syncing flag to a non-existing store, therefore a store reset is required in order to correctly associate the local data stored in your Magento and the actual store id at MailChimp.

Regards.

**Comment by seansan** [comment]
Do we know which store it is? (strange thing is we never changed stores ... )

**Comment by Santiagoebizmarts** [comment]
Something should have been made that deleted the store. The store can be deleted by disabling the extension, the ecommerce section and reseting the MailChimp store. It can also be deleted from the MailChimp playground or by deleting the list associated to the store.

Regards.

**Comment by seansan** [comment]
​well if we would have done any of this then yes

but we did not

so re-creating all this? how does one do this ... since the last upgrade
actually little works

do we open each store view individually and click reset (again? have done
this every version upgrade so far) .... ​


On Mon, Oct 30, 2017 at 2:41 PM, Santiagoebizmarts <notifications@github.com

**Comment by seansan** [comment]
​Hi, are these errors not similar to when you tried to fix/help us some
weeks ago?

webhooks not working

and here I see scope value is empty when mailchimp tries to save data



2017-10-26T18:05:14+00:00 DEBUG (7): SQLSTATE[23000]: Integrity constraint
violation: 1048 Column 'scope' cannot be null, query was: INSERT INTO
`core_config_data` (`scope`, `scope_id`, `path`, `value`) VALUES (?, ?, ?,
?)
2017-10-26T18:07:07+00:00 DEBUG (7): Invalid Resource for Api Call:
lists/409d24faab/webhooks : url : We couldn't connect to the specified the
URL. Please double check and try again.
2017-10-26T18:07:07+00:00 DEBUG (7): Your store could not be accessed by
MailChimp's Api. Please confirm the URL:
https://shirtsofholland.com/mailchimp/webhook/index/wkey/ea7f2c33dc3a6a07/
is accessible externally to allow the webhook creation.
2017-10-27T12:41:10+00:00 DEBUG (7): Resource Not Found : The requested
resource could not be found.
2017-10-27T14:05:36+00:00 DEBUG (7):  for Api Call: batches -
2017-10-28T00:02:04+00:00 DEBUG (7): SQLSTATE[23000]: Integrity constraint
violation: 1048 Column 'scope' cannot be null, query was: INSERT INTO
`core_config_data` (`scope`, `scope_id`, `path`, `value`) VALUES (?, ?, ?,
?)
​


On Mon, Oct 30, 2017 at 2:41 PM, Santiagoebizmarts <notifications@github.com

**Comment by Santiagoebizmarts** [comment]
Hello,

Again these issues are not related. This is not the place to ask technical questions, it is to create issues when finding a bug.

You are welcome to send an email to our ticket system mailchimp@ebizmarts-desk.zendesk.com where we can help find the cause of these errors you see.
Always remember to state the extension version number and the customizations you have that might affect how products, orders, carts and customers are handled.

 Regards.
