### ISSUE TITLE
Product images not uploading with Stock in the Channel

### ISSUE THREAD

**Issue by smartteck** [mailchimp/mc-magento#536]
i am using stock in the channel for products in magento, so basically we do not host images on our own server but there extension just show images in magento.

when mailchimp imports products from my magento store to my mailchimp account, there are no product images.

        //image
        $productMediaConfig = Mage::getModel('catalog/product_media_config');
        $data["image_url"] = $productMediaConfig->getMediaUrl($product->getImage());

this is the string of code i found, any idea wha changes do i need to make, if we dont host image our self?

----------------------

Edit: http://support.stockinthechannel.com/own-server-solution/

**Comment by Santiagoebizmarts** [comment]
Hello @smartteck 

Please test the latest version. There is a new "original" option in the image size drowpdown that should allow your images to be sent correctly.

Kind Regards.
