### ISSUE TITLE
Order grid: All orders shows the mailchimp logo

### ISSUE THREAD

**Issue by m-overlund** [mailchimp/mc-magento#539]
After updating to v1.1.10 all frontend orders shows up on the admin order grid, as coming from mailchimp.
If you go to a specific order, the order view block with referred campaign details doesn't show up either, confirming they weren't actually referred by Mailchimp.

## Reproduce
1. Update Mailchimp for Magento to v1.1.10
2. Place a frontend order
3. Check admin order grid

## Expected result
Only orders referred by a mailchimp campaign shows up with mailchimp logo on order grid.

## Actual result:
All frontend orders shows as referred by a mailchimp campaign, on the order grid.

## version info
Mailchimp for Magento v.1.1.10
Magento 1.9.3.1 (all patched)

![all-monkeys](https://user-images.githubusercontent.com/504236/32492706-877c94a4-c3bb-11e7-94e3-e0afb28a4eab.png)

**Comment by Santiagoebizmarts** [comment]
Hello @m-overlund 

Thanks for your feedback.
There might be scenarios where the campaign id is not correctly retrieved, for example when using google analytics on top of a MailChimp ad.
The first thing would be to find out which order field is causing the monkey to be shown.
To find this run the following query on your database console:
**SELECT FROM sales_flat_order WHERE increment_id={order number};**
You can place any order# with this problem.

The fields I am interested in are **mailchimp_campaign_id**, **mailchimp_abandonedcart_flat** and **mailchimp_landing_page**.

Regards.

**Comment by m-overlund** [comment]
Field | Value
----------------------------------|---------------
mailchimp_campaign_id | (NULL)
mailchimp_abandonedcart_flag | 0
mailchimp_landing_page | [domain.com]/onestepcheckout/

**Comment by Santiagoebizmarts** [comment]
@m-overlund 

Thanks for helping us noticing this. You can get around this problem simply by removing some code as shown in the commit above.

Regards.
