### ISSUE TITLE
Sending specific sales data (sale attributes)

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#544]
Hi, looking at this we can control which customer data is sent 

http://wiki.ebizmarts.com/m4m-merge-fields

question: we use SIZE and BRAND and COLOUR of the products that customers buy very specifically. We can make a segment and filter thru sales (product) data, but ..... would it not be a lot better if we can somehow "promote" certain sales fields to a real attribute?

(in this age where everything is becoming more personal)

**Comment by gonzaloebiz** [comment]
If you have questions, please send an email to our support mailchimp@ebizmarts-desk.zendesk.com
