### ISSUE TITLE
A product with the provided variant ID does not exist in the account for this list.

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#554]
We see 1000-s of these errors in the log. 

We traced it down to the end

the product exists, the customer exists, the child product (simples) exist, the order exists

So how come there is still something wrong? And what is being referenced as the "account" which account?

**Comment by davidwindell** [comment]
@seansan did you ever resolve this? We are seeing the same errors. Thanks

**Comment by seansan** [comment]
We upgraded and upgraded and I must say there are a lot less errors

Problem in the past was products with no stock or disabled or not salable were not synced ... something like that

There is only a couple remaining, no idea why this is wrong. Systems says cant find product, but then shows a product link


![image](https://user-images.githubusercontent.com/652395/66392231-81ff3900-e9cf-11e9-9ee7-9e1e0c834515.png)

Issue can be closed I guess

**Comment by davidwindell** [comment]
Thanks!
