### ISSUE TITLE
Promorule error

### ISSUE THREAD

**Issue by babygear** [mailchimp/mc-magento#555]
We have just upgrade to version 1.1.10 and are now getting the following type of mailchimp errors. 

Have you seen that before?

Best regards, 
Jesper

"response": {
            "type": "http:\/\/developer.mailchimp.com\/documentation\/mailchimp\/guides\/error-glossary\/",
            "title": "Invalid Resource",
            "status": 400,
            "detail": "A promo rule for store '7ea313f5c2ed384586c1077a4bb62df3' with the id '2' already exists.",
            "instance": ""
        }
    },
    {
        "status_code": 400,
        "operation_id": "storeid-2_PCD_2017-11-21-14-42-33-17079500_317",

**Comment by Santiagoebizmarts** [comment]
Hello @babygear 

Thanks for reaching us.
I have seen this error a couple times and I believe it might be related to the PHP version, can you tell me yours?

Regards.

**Comment by darekkosyl** [comment]
Hi,
We have the same problem, our PHP version is 5.6.33 & magento is v 1.9.3.7. 
Thanks,

Darek
