### ISSUE TITLE
Shipment Email in Magento has status NOT SENT when Mandrill App activity for this Shipment Email has status Delivered

### ISSUE THREAD

**Issue by tuyennn** [mailchimp/mc-magento#558]
## Preconditions
Magento CE 1.9.3.1
mc-magento 1.1.10
## Expected Behavior
Shipment Email in Magento has status SENT when Mandrill App activity for this Shipment Email has status Delivered

## Current Behavior
Shipment Email in Magento has status NOT SENT when Mandrill App activity for this Shipment Email has status Delivered

## Possible Solution
API could be broken

## Steps to Reproduce
1. Create an order
2. Create Invoice -> then Create Shipment
3. Check the status Shipment on Admin Backend
4. Check status on Mandrill App

## Detailed Description
![2017-11-22 10_41_17-](https://user-images.githubusercontent.com/4010395/33221672-d3695d68-d183-11e7-8307-7552cab54180.png)
![2017-11-22 10_41_32-](https://user-images.githubusercontent.com/4010395/33221673-d39915d0-d183-11e7-8629-2ab5516cad51.png)

**Comment by Santiagoebizmarts** [comment]
Hello @tuyennn 

I made a test with a fresh Magento 1.9.3.1 and the message shown is correct.
![screen shot 2017-12-18 at 15 43 27](https://user-images.githubusercontent.com/8330778/34122193-5807f8d4-e40a-11e7-969c-0125feba1788.png)

There is probably something else affecting this.

Regards.
