### ISSUE TITLE
Images are not sent in certain versions of PHP

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento#559]
PHP versions lower than 5.4.32, 5.5.16 don't support the ucword function, and therefore products are sent without images.

**Comment by centerax** [comment]
I dont see why 5.4.32 and 5.5.16 do not support ucwords. on the php manual it only says that the *delimiters* parameter is added.

**Comment by ebizmarts-keller** [comment]
@centerax You are right, but in the code of the extension the ucwords function is used with a delimiter
