### ISSUE TITLE
Updating a customer crashes the website

### ISSUE THREAD

**Issue by durzel** [mailchimp/mc-magento#565]
When trying to change the email address for a registered account I get a white screen and the following error:

```
[Sun Dec 03 11:20:34.440723 2017] [:error] [pid 28991:tid 140639011460864] [client 1.1.1.1:49563] PHP Fatal error:  Uncaught Error: Call to a member function addOrUpdate() on null in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/Mail
Chimp/Model/Api/Subscribers.php:340
Stack trace:
#0 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Observer.php(146): Ebizmarts_MailChimp_Model_Api_Subscribers->updateSubscriber(Object(Ebizmarts_MailChimp_Model_Subscriber
), true)
#1 /home/magento/public_html/app/code/core/Mage/Core/Model/App.php(1358): Ebizmarts_MailChimp_Model_Observer->customerSaveBefore(Object(Varien_Event_Observer))
#2 /home/magento/public_html/app/code/core/Mage/Core/Model/App.php(1331): Mage_Core
_Model_App->_callObserverMethod(Object(Ebizmarts_MailChimp_Model_Observer), 'customerSaveBef...', Object(Varien_Event_Observer))
#3 /home/magento/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('customer_save_b...', Array)
#4 /home/ma
gento/public_html/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('customer_save_b...', Array)
#5 /home/magento/pu in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php on line 340, ref
erer: https://127.0.0.1/index.php/admin/customer/edit/id/17958/key/xyzabc123/
```

**system.log**
```
2017-12-03T11:20:34+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php on line 340
2017-12-03T11:20:34+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php on line 340
2017-12-03T11:20:41+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php on line 340
2017-12-03T11:20:41+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php on line 340
```

Running latest release avallable.  You have a `try..catch` structure here but it obviously only catches Mailchimp errors.  When this error occurs it prevents updating a customer account.

This seems to be caused where a store has an API key set, but is invalid or otherwise not correctly linked to Mailchimp.  Wrapping line 340 in `Subscribers.php` in a sanity check to make sure `$api` is not null fixes the problem, but feels like a bandaid solution.  It feels like there should be some kind of sanity check to make sure `getApi()` returns a valid object before doing anything.

**Comment by ebizmarts-keller** [comment]
@durzel Can you tell me what version of Mailchimp and version of Magento are you using so I can attempt to replicate this?

**Comment by durzel** [comment]
I'm using Magento CE 1.9.3.7 and mc-magento 1.1.10

Our Magento is set up with multiple stores, but only one of them is enabled (store level) and linked to Mailchimp.

**Comment by Santiagoebizmarts** [comment]
Hello @durzel 

Actually the Magento Exception is catched as well as the MailChimp_Error. I installed a Magento 1.9.3.7 and tested this exact case and everything worked okay.

Regards.

**Comment by durzel** [comment]
For what it's worth - I'm still getting this, just posting it here in case anyone else can provide any other feedback:

```
[Wed Jan 17 09:33:39.831571 2018] [:error] [pid 53377:tid 139702415107840] [client 1.1.1.1:57702] PHP Fatal error:  Uncaught Error: Call to a member function update() on null in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php:472
Stack trace:
#0 /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Observer.php(140): Ebizmarts_MailChimp_Model_Api_Subscribers->deleteSubscriber(Object(Ebizmarts_MailChimp_Model_Subscriber))
#1 /home/magento/public_html/app/code/core/Mage/Core/Model/App.php(1358): Ebizmarts_MailChimp_Model_Observer->customerSaveBefore(Object(Varien_Event_Observer))
#2 /home/magento/public_html/app/code/core/Mage/Core/Model/App.php(1331): Mage_Core_Model_App->_callObserverMethod(Object(Ebizmarts_MailChimp_Model_Observer), 'customerSaveBef...', Object(Varien_Event_Observer))
#3 /home/magento/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('customer_save_b...', Array)
#4 /home/magento/public_html/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('customer_save_b...', Array)
#5 /home/magento/public_html/a in /home/magento/.modman/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php on line 472, referer: https://127.0.0.1/index.php/admin/customer/edit/id/7971/key/1e514ff875ab220278a20cc87deafbf7/
```

The customer in question has a "store_id" of 0, as their account was created in the backend (Created From = Admin).  On our configuration of mc-magento it is not configured at the DEFAULT VALUES level (Default Values = Admin = store_id = 0), with Enabled = False, API blank, etc.  It is only enabled & configured at a WEBSITE level.

Steps to reproduce:
1) Configure mc-magento at WEBSITE level, not DEFAULT VALUES level (for multi-store configurations)
2) Create a customer account in the backend (doesn't matter what store you associate to)
3) Go into the customer account in the backend and modify the email

The function `deleteSubscriber()` in `app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php` assumes that $api is not null.  It does not sanity check it.  You have put this code inside try..catch blocks, but they do not trap PHP Fatal Errors, which calling a function on null is.

Incidentally this problem also affects `addOrUpdate()`, earlier in the file.

Solution: Sanity check $api to make sure that it is not null before trying to call member functions on it.

**Comment by JKSkog** [comment]
I also got this error, but we only use the mandrill function in this module.. @durzel did you have a quick fix on this? @Santiagoebizmarts  is this something that you will look at?
We get this error when trying to change a customers email address.

**Comment by Sarvesh-A** [comment]
Hello @JKSkog,
I was facing same issue when trying to change customers email.
As @durzel mentioned you have to sanity check before `$api` uses member functions.
e.g.: You need to do below code to solve issue.
```
if($api != null)
            {
                $api->lists->members->addOrUpdate(
                    $listId, $md5HashEmail, $subscriber->getSubscriberEmail(), $newStatus, null, $forceStatus, $mergeVars,
                    null, null, null, null
                );
            }
```
Before `$api->lists->members` calls any function you have to check condition `if($api != null)` everywhere where `$api->lists->members` is used.

Or you can download attached file and replace it at this path `app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php`

This solved my issue. Hope it helps you as well. :)
[Subscriber.zip](https://github.com/mailchimp/mc-magento/files/1673463/Subscriber.zip)

**Comment by durzel** [comment]
Apologies for not replying sooner, I have been (and still am) unwell...

What @Sarvesh-A has put above is essentially what I've done, although I've simply added a line which says:

`if (is_null($api)) return false;`

..after `$api` is assigned.

This needs to be done in both `updateSubscriber()` and `deleteSubscriber()` in the `Subscribers.php` file.

**Comment by Sarvesh-A** [comment]
Yes `if (is_null($api)) return false;` this will help more will add it. thanks @durzel.

**Comment by Santiagoebizmarts** [comment]
Hello @Sarvesh-A @durzel @JKSkog 

We were able to find the case where this fails and will fix this for the next release.
Thank you for your patience.
The issue #613 will be referenced once it is finished.

Regards.
