### ISSUE TITLE
Order comments not sent via Mandrill

### ISSUE THREAD

**Issue by HRR1337** [mailchimp/mc-magento#568]
Hello.

For our transaction e-mails we use Mailchimp with Mandrill Api. Its works perfect for orders, invoices, shipment, automatically e-mails sent via "Follow Up Email Extension".

Though the Order Comments are not sent via Mandrill.

How to test:

Go to: Sales. Click on a sale, add a comment. Tick the "Inform customer by e-mail" and hit "Save notition / Comment"

Expected result: E-mail is sended by Mandrill.

Result: E-mail is NOT sended by Mandrill.

We use 

- Magento 1.9.3.6
- Mailchimp for Magento 1.1.10

Thanks,

HRR

**Comment by Santiagoebizmarts** [comment]
Hello @HRR1337 

I was able to replicate this in Magento 1.9.3.7. This issue will be referenced once the solution is implemented in the develop branch.

Thank you very much for your feedback.

Regards.

**Comment by HRR1337** [comment]
Hi there, Thanks alot. looking really forward to the fix.

**Comment by Santiagoebizmarts** [comment]
Hello,

Sorry about my mistake, it just took a little while before the email was sent. I suggest you to contact our support to see why this is failing for you.

Regards.

**Comment by HRR1337** [comment]
Hi there, can you please verify its sent via mandrill? In the outgoing logs? Beceause the issue is not that it is not sent, but not sent by Mandrill.

**Comment by Santiagoebizmarts** [comment]
As you can see in the screenshots below the email is sent via Mandrill.
![screen shot 2017-12-18 at 14 03 33](https://user-images.githubusercontent.com/8330778/34118058-62c72424-e3fc-11e7-8cfa-58ca61973602.png)
![screen shot 2017-12-18 at 14 03 50](https://user-images.githubusercontent.com/8330778/34118059-62f046ec-e3fc-11e7-86e9-4acae0ce68a1.png)


Probably in your Magento another extension is affecting the sending process, this happens very often. Contacting our support at mailchimp@ebizmarts-desk.zendesk.com will allow us to see your particular case.

Regards.

**Comment by HRR1337** [comment]
Short update: Have used the smtp of mandrill and everything works.

**Comment by andresinspace** [comment]
We have changed Mandrill from being globally enabled, to disabled globally and only enabled on a specific website. 
Since the change, I am receiving this error:
Fatal error: Call to undefined method Zend_Mail::getBcc() in app\code\community\Ebizmarts\MailChimp\Model\Email\Template.php on line 81

**Comment by iamlolz** [comment]
> Short update: Have used the smtp of mandrill and everything works.

@HRR1337  do you remember what you did to fix this, I'm not sure what you mean by "Have used the smtp of mandrill". Thanks mate.
