### ISSUE TITLE
Issues with watermarks on imported products.

### ISSUE THREAD

**Issue by timothyCoxon** [mailchimp/mc-magento#573]
Anyone have anyway to edit the watermarks on the imported images?

![screen shot 2017-12-20 at 13 25 10](https://user-images.githubusercontent.com/2742042/34209250-4b215be4-e589-11e7-957d-9162358223bb.png)

Images look fine on the site but seems this plugin is using the settings for the base images (which we display at a relatively high res and then import them as 265*265px with the same watermark settings which make them useless.

**Comment by Santiagoebizmarts** [comment]
Hello @timothyCoxon 

Please note this is not a place to ask questions. If you do not want to send the base image there is a configuration for sending thumbnail or small image.

Regards.
