### ISSUE TITLE
All orders marked with Mailchimp logo even if they're not coming from Mailchimp

### ISSUE THREAD

**Issue by fabianaromagnoli** [mailchimp/mc-magento#576]
After installing the last version (1.1.10) of mailchimp/mc-magento I noticed that in admin panel all the new orders are marked with the Mailchimp Logo, even if they're not coming from Mailchimp.

Steps to reproduce the issue (I'm using Magento 1.9.3.7 and mailchimp/mc-magento 1.1.10):
* Go to frontend and complete an order 
* Open orders list in admin: the order just created should have the Freddie Icon in Mailchimp column

I looked at the code and I saw that the icon is displayed when the order has one of these fields set: mailchimp_abandonedcart_flag or mailchimp_campaign_id or mailchimp_landing_page

I also noticed that, since I installed version 1.1.10, in db table sales_flat_order almost all the orders have mailchimp_landing set to https://www.my-magento-store.com/[store_code]/checkout/onepage/, and I guess that's why the freddie icon is always shown in orders list.

But why is mailchimp_landing always set to checkout page?
That value seems to come from a cookie, mailchimp_landing_page, set by the javascript code in js/ebizmarts/mailchimp/campaignCatcher.js. The line 
`Mage.Cookies.set('mailchimp_landing_page', location);`
is always executed, so it seems to me that this cookie is overwritten every time a new page is loaded, and the value that is saved to order is the last one before order save.

**Comment by Santiagoebizmarts** [comment]
Hello @fabianaromagnoli 
Here is the original thread. It is already solved!
https://github.com/mailchimp/mc-magento/issues/539

**Comment by Santiagoebizmarts** [comment]
After further checking I see only a part of this have been solved in the issue mentioned above.
I am reopening this and will reference it once it is fully solved.

Thanks for your feedback!

Regards.
