### ISSUE TITLE
Sync stops if duplicate emails exist in Magento

### ISSUE THREAD

**Issue by stevefritz** [mailchimp/mc-magento#58]
I have a magento database with some duplicated email addresses in the customer_entity table. This causes the sync process to fail, as Mailchimp returns an error stating "This customer email already exists".  This error is fired during the cron job, from within one of the method called by _sendEcommerceBatch:142. 

For the duplicates which exist in the database, each one has a customer belonging to store_id 1 and the other to store_id 0.  While this is an issue with my data, maybe something could be done within the extension to prevent it from failing, as most users would not have been able to track down the cause of this. I have worked around the issue by modifying the api/customer model to exclude the problem customers (nin => Array of Customer IDs that I got from mysql). 

Thanks

**Comment by gonzaloebiz** [comment]
Hi @stevefritz 

thanks for your feedback.
Magento don't allow to have 2 customers with the same email, so no sense to have a extra control for this.

Best
