### ISSUE TITLE
Incomplete orders passed over as valid orders from MailChimp for Magento

### ISSUE THREAD

**Issue by jessiebrown** [mailchimp/mc-magento#580]
Declined orders from Magento still are appearing in MailChimp as valid orders.

This is problematic if the user has Order Notifications or other purchase based Automations set up, which can deliver emails which wouldn't be suitable for customers who did not actually complete a purchase. It can also skew the user's revenue reporting data.

**Comment by Santiagoebizmarts** [comment]
Hello,

Please read our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to see how to properly create a new issue.

Regards.
