### ISSUE TITLE
Orders from Magento Admin Panel displaying in Campaign Report

### ISSUE THREAD

**Issue by jessiebrown** [mailchimp/mc-magento#581]
When admin places an order for customers through the admin panel on Magento platform, the order is also showing in a campaign report even though there are no clicks through a campaign report for it.

**Comment by Santiagoebizmarts** [comment]
Hello,

This issue is a duplicate. Please check in our issues and Milestones to see if the problem doesn't exist already before creating new issues.
https://github.com/mailchimp/mc-magento/issues
https://github.com/mailchimp/mc-magento/milestones

**Comment by jessiebrown** [comment]
Hi @Santiagoebizmarts, could you point me to the issue that this duplicates? Thanks!

**Comment by Santiagoebizmarts** [comment]
Sure, it is https://github.com/mailchimp/mc-magento/issues/539

Regards.
