### ISSUE TITLE
query optimizations 1

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#583]
query optimizations 1
original query 1 runs 10 seconds! (seriously)
second query runs 0,0002 secs: do we really need the group_by? is there an alternative?

(dont know where this query originates from in the code, but Ebizmarts know I am sure)

runs 10secs
SELECT `e`.*, `at_qty`.`qty`, `at_backorders`.`backorders`, `at_category_id`.`category_id`, `at_name`.`value` AS `name`, `at_default_name`.`value` AS `default_name`, `at_visibility`.`value` AS `visibility`, `at_default_visibility`.`value` AS `default_visibility`, `at_description`.`value` AS `description`, `at_default_description`.`value` AS `default_description`, `at_price`.`value` AS `price`, `at_default_price`.`value` AS `default_price`, `m4m`.`related_id`, `m4m`.`type`, `m4m`.`mailchimp_store_id`, `m4m`.`mailchimp_sync_delta`, `m4m`.`mailchimp_sync_modified` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_website` AS `product_website` ON product_website.product_id = e.entity_id AND product_website.website_id = 7
 LEFT JOIN `cataloginventory_stock_item` AS `at_qty` ON (at_qty.`product_id`=e.entity_id) AND (at_qty.stock_id=1)
 LEFT JOIN `cataloginventory_stock_item` AS `at_backorders` ON (at_backorders.`product_id`=e.entity_id) AND (at_backorders.stock_id=1)
 LEFT JOIN `catalog_category_product` AS `at_category_id` ON (at_category_id.`product_id`=e.entity_id)
 LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (at_name.`entity_id`=e.entity_id) AND (at_name.store_id = 23 AND at_name.attribute_id = 65)
 LEFT JOIN `catalog_product_entity_varchar` AS `at_default_name` ON (at_default_name.`entity_id`=e.entity_id) AND (at_default_name.store_id = 0 AND at_default_name.attribute_id = 65)
 LEFT JOIN `catalog_product_entity_int` AS `at_visibility` ON (at_visibility.`entity_id`=e.entity_id) AND (at_visibility.store_id = 23 AND at_visibility.attribute_id = 95)
 LEFT JOIN `catalog_product_entity_int` AS `at_default_visibility` ON (at_default_visibility.`entity_id`=e.entity_id) AND (at_default_visibility.store_id = 0 AND at_default_visibility.attribute_id = 95)
 LEFT JOIN `catalog_product_entity_text` AS `at_description` ON (at_description.`entity_id`=e.entity_id) AND (at_description.store_id = 23 AND at_description.attribute_id = 66)
 LEFT JOIN `catalog_product_entity_text` AS `at_default_description` ON (at_default_description.`entity_id`=e.entity_id) AND (at_default_description.store_id = 0 AND at_default_description.attribute_id = 66)
 LEFT JOIN `catalog_product_entity_decimal` AS `at_price` ON (at_price.`entity_id`=e.entity_id) AND (at_price.store_id = 23 AND at_price.attribute_id = 69)
 LEFT JOIN `catalog_product_entity_decimal` AS `at_default_price` ON (at_default_price.`entity_id`=e.entity_id) AND (at_default_price.store_id = 0 AND at_default_price.attribute_id = 69)
 LEFT JOIN `mailchimp_ecommerce_sync_data` AS `m4m` ON m4m.related_id = e.entity_id and m4m.type = 'PRO' AND m4m.mailchimp_store_id = 'secret' WHERE (m4m.mailchimp_sync_delta IS null OR m4m.mailchimp_sync_modified = 1) GROUP BY `e`.`entity_id` LIMIT 5

 REPLACE BY

runs 0,0002secs
SELECT `e`.*, `at_qty`.`qty`, `at_backorders`.`backorders`, `at_category_id`.`category_id`, `at_name`.`value` AS `name`, `at_default_name`.`value` AS `default_name`, `at_visibility`.`value` AS `visibility`, `at_default_visibility`.`value` AS `default_visibility`, `at_description`.`value` AS `description`, `at_default_description`.`value` AS `default_description`, `at_price`.`value` AS `price`, `at_default_price`.`value` AS `default_price`, `m4m`.`related_id`, `m4m`.`type`, `m4m`.`mailchimp_store_id`, `m4m`.`mailchimp_sync_delta`, `m4m`.`mailchimp_sync_modified` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_website` AS `product_website` ON product_website.product_id = e.entity_id AND product_website.website_id = 7
 LEFT JOIN `cataloginventory_stock_item` AS `at_qty` ON (at_qty.`product_id`=e.entity_id) AND (at_qty.stock_id=1)
 LEFT JOIN `cataloginventory_stock_item` AS `at_backorders` ON (at_backorders.`product_id`=e.entity_id) AND (at_backorders.stock_id=1)
 LEFT JOIN `catalog_category_product` AS `at_category_id` ON (at_category_id.`product_id`=e.entity_id)
 LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (at_name.`entity_id`=e.entity_id) AND (at_name.store_id = 23 AND at_name.attribute_id = 65)
 LEFT JOIN `catalog_product_entity_varchar` AS `at_default_name` ON (at_default_name.`entity_id`=e.entity_id) AND (at_default_name.store_id = 0 AND at_default_name.attribute_id = 65)
 LEFT JOIN `catalog_product_entity_int` AS `at_visibility` ON (at_visibility.`entity_id`=e.entity_id) AND (at_visibility.store_id = 23 AND at_visibility.attribute_id = 95)
 LEFT JOIN `catalog_product_entity_int` AS `at_default_visibility` ON (at_default_visibility.`entity_id`=e.entity_id) AND (at_default_visibility.store_id = 0 AND at_default_visibility.attribute_id = 95)
 LEFT JOIN `catalog_product_entity_text` AS `at_description` ON (at_description.`entity_id`=e.entity_id) AND (at_description.store_id = 23 AND at_description.attribute_id = 66)
 LEFT JOIN `catalog_product_entity_text` AS `at_default_description` ON (at_default_description.`entity_id`=e.entity_id) AND (at_default_description.store_id = 0 AND at_default_description.attribute_id = 66)
 LEFT JOIN `catalog_product_entity_decimal` AS `at_price` ON (at_price.`entity_id`=e.entity_id) AND (at_price.store_id = 23 AND at_price.attribute_id = 69)
 LEFT JOIN `catalog_product_entity_decimal` AS `at_default_price` ON (at_default_price.`entity_id`=e.entity_id) AND (at_default_price.store_id = 0 AND at_default_price.attribute_id = 69)
 LEFT JOIN `mailchimp_ecommerce_sync_data` AS `m4m` ON m4m.related_id = e.entity_id and m4m.type = 'PRO' AND m4m.mailchimp_store_id = 'secret' WHERE (m4m.mailchimp_sync_delta IS null OR m4m.mailchimp_sync_modified = 1) LIMIT 5

**Comment by seansan** [comment]
Possibly generated here, not sure: https://github.com/mailchimp/mc-magento/blob/508fda56e0646cb137004dbaf244fe4801f1e2c6/app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php#L56

**Comment by seansan** [comment]
This was not the fix. Do see now what is happening, multiple rows of the same data are being returned making it a huge! dataset. Group is the quick way of deleting the duplicate rows but not the solution. One should add a filter so only 1 row of data is in the result set (and omit group by)

**Comment by seansan** [comment]
maybe do this? https://magento.stackexchange.com/questions/139052/how-to-use-a-subquery-while-performing-left-join-in-magento

Or send the complete category id's list as a concatened string (dont know if it accepts more than 1 id) using group_concat

**Comment by seansan** [comment]
Possible fix part 1
public function joinCategoryId($collection) {
        // need fix for table prefix or load DB name from catalog/category_product
        $subquery = new Zend_Db_Expr("(SELECT DISTINCT(product_id), category_id FROM `catalog_category_product` GROUP BY product_id)");
        $collection->getSelect()
            ->joinLeft(
                $subquery, 
                't.product_id = e.entity_id'
        );
    }

Possible fix part 2
After this remove group by entity_id

==============================

Other fix is to use group_concat, but then still the subquery can be smart

**Comment by Santiagoebizmarts** [comment]
@seansan 
Thanks for your contribution, we will review this query carefully to see if and how it can be improved.
If the category is the main problem I guess we can do that call separately to avoid messing the other attributes.

Regards.

**Comment by seansan** [comment]
​Thanks. Yes I think this will be smart to do. ​


On Thu, Dec 28, 2017 at 9:37 PM, Santiagoebizmarts <notifications@github.com

**Comment by seansan** [comment]
Can me mark this as https://github.com/mailchimp/mc-magento/milestone/15
Important win

**Comment by seansan** [comment]
plz share updates or make an urgent fix. Currently in slow query log this accounts for 40% of Mysql time - total response time since 2 days = 4,5 hours

**Comment by seansan** [comment]
@ebizmarts ... if there is any update on this plz let me know

**Comment by centerax** [comment]
we are going to take a look at it this week.

**Comment by seansan** [comment]
okay thanks waiting for update

**Comment by seansan** [comment]
Please add to first next release. This is important. THX

**Comment by seansan** [comment]
@centerax did you solve this  in the week of 8 JAN? And is it in release 1.11?!!

**Comment by centerax** [comment]
This task got delayed because of other priorities, its still a working process.

**Comment by seansan** [comment]
Thanks, please update to https://github.com/mailchimp/mc-magento/milestone/15

**Comment by seansan** [comment]
Thx> I see you removed all the joins? (so no category id sent etc). If this is the fix then plz close.

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Version 1.1.11 is already in the testing phase. We were not able to get it in before and will be for 1.1.12.
The changes can be done manually for anyone who needs it, just do the changes in the PR associated over version 1.1.11.

Regards.

**Comment by seansan** [comment]
​this is a shame - because it is quite critical​




Powered by Gmelius <https://gmelius.com?ref=mail>

On Thu, Feb 22, 2018 at 2:22 PM, Santiagoebizmarts <notifications@github.com
