### ISSUE TITLE
add index

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#584]
19% query usage

UPDATE mailchimp_ecommerce_sync_data SET mailchimp_sync_modified = 1 WHERE type = 'PRO'

there is no index on column type

**Comment by centerax** [comment]
PR?

**Comment by seansan** [comment]
​I see how this would be convenient; but altering the DB adding a next
version ​to your scripts etc etc is a little too far ... and can be done
easily and fast when you do the next release

Small changes! yes of course we will PR
