### ISSUE TITLE
Unable to "Reset MailChimp Store" because running out of memory

### ISSUE THREAD

**Issue by andrew-smart** [mailchimp/mc-magento#590]
**Versions**

We are running the latest release of the module; 1.1.10
Magento version: CE1.9.3.7
There are 3 stores set up

**Steps to reproduce**
  
Click the "Reset MailChimp Store" button in store view scope

**Expected Result**

Store in MailChimp is recreated

**Actual Result**

In the admin you simply get the message "Something went wrong."

Looking through the log files you get the following error;

[Fri Jan 05 14:33:40.970767 2018] [proxy_fcgi:error] [pid 29827:tid 140087815800576] [client 90.220.54.203:59732] AH01071: Got error 'PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in [path]/lib/Zend/Db/Statement/Pdo.php on line 291\nPHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in Unknown on line 0\n', referer: [url]/system_config/edit/section/mailchimp/website/base/store/[store_code]/key/[key]/

**Comment by centerax** [comment]
https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines
