### ISSUE TITLE
Send requests to Mailchimp asynchroniously

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento#593]
This module adds a lot requests to mailchimp for a lot of events:
- customer subscribe/unsubscibe - https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L41
- subscriber delete - https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L74
- customer save - https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L125
- customer address save - https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L157
- order save - https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L189
And much much more things.

All these requests are slowing down magento website and for big merchants it's really huge issue.

My suggestion - add all these requests to "queue" table and send them by cron job.

**Comment by Santiagoebizmarts** [comment]
Hello,

The only real time calls made are when someone subscribes/unsubscribes in the newsletter_subscriber_save_before event, not in the other events you mention. Anyways those calls will be removed in the next version to prevent this to happen.

Regards.

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts thank you for clarification! will see next updates

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts actually customer creation might be during order creation, as result - order creation will wait till customer will be subscribed (or request will fail). That's actually not true

**Comment by Santiagoebizmarts** [comment]
This should not happen in the default checkout. It will probably happen when another extension integrates the checkout subscription.
The change I mentioned should solve this situation as well.
