### ISSUE TITLE
Reduce logging in next version

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#595]
please check the following 

user@server:/public_html/var/log$ ducks
4.5G    total
4.4G    MailChimp_Requests
65M     aoe_cron.log

I am just amazed! to see 4GB of data here. If loggin is turned on or off: it is still a massive amount of data 

I remember cases in 2011 when Magento logged files fo 100GB and crashed our server because out of quota .... I dont think  this is something the Mailchimp extension should do. 

Advise for next version: 
- I as user can turn off logging yes
- But the Extension should have a MAX file size setting of logs to keep. There is also no sense in keeping 4GB of logging data

And actually: 
Surprised at all that we send THAT MUCH data to Mailchimp .... 

Request: please add a max log file size

**Comment by Santiagoebizmarts** [comment]
Hello,

The logs should be disabled after the testing process. Big stores handle a lot of information causing a lot of data to be logged. Please note we are sending pretty much all the Magento relevant data to MailChimp in order to use it for Automations and statistics.

Regards.

**Comment by seansan** [comment]
​​
​even then I said in 2nd bullit: maximize log size!!!

4GB can kill a server

​and in our case: we are fine with some logging, we always have it on ....
but 4gB defeats the purpose

please re-open issue

**Comment by Santiagoebizmarts** [comment]
@seansan we will review the log process in order to improve how logs are handled.
In the meantime I suggest you to disable the logs.
Thanks for your feedback.

Regards.

**Comment by ihor-sviziev** [comment]
@Santiagoebizmarts AFAIK in MailChimp_Requests directory located bundle requests that are sening to Mailchimp API. I think after sending they could be removed. What do you think?

**Comment by seansan** [comment]
​keeping some, esp errors is OK. The question is: how far back do you want
to go. How usefull is it to see 10.000 of the same errors? 1 is enough​

**Comment by Santiagoebizmarts** [comment]
Currently we plan to do this in two steps, firstly simply adding two different settings for request logs and error logs. This will probably be in the next version.
We want to add a more complex method in the future such as removing old entries but that will be done in a future release.

**Comment by seansan** [comment]
Glad that your tackling it

**Comment by seansan** [comment]
Thanks! Can we mark part 1 for https://github.com/mailchimp/mc-magento/milestone/15
