### ISSUE TITLE
No need to do any actions on "controller_front_init_before" event

### ISSUE THREAD

**Issue by ihor-sviziev** [mailchimp/mc-magento#598]
Could someone explain what is the reason to setting up event observer to ```controller_front_init_before``` event, that runs on EVERY request in magento, both for frontend or backend, so it slowing down magento website.
https://github.com/mailchimp/mc-magento/blob/ef34763847bb6e87baf76c4d3e04ae0b1c48fc7c/app/code/community/Ebizmarts/MailChimp/etc/config.xml#L136-L143

I see this code executing only in cases when was set "special" flag in the admin when we cleaned product images cache.

https://github.com/mailchimp/mc-magento/blob/ef34763847bb6e87baf76c4d3e04ae0b1c48fc7c/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L603-L617

https://github.com/mailchimp/mc-magento/blob/ef34763847bb6e87baf76c4d3e04ae0b1c48fc7c/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L597-L601

Is there any idea why it was done in this way? Why just not execute that code when we're flushing images cache?

**Comment by Santiagoebizmarts** [comment]
Hello @ihor-sviziev 

The original idea was to use a flag once any of the cache was cleared and then with the controller_front_init_before actually setting the image paths to be resent.
After checking the process, this can be improved with a postdispatch event listening to the controllers after clearing the cache.
Thanks again for your valuable help.

Regards.

**Comment by aingham** [comment]
Hi - I think this is causing big delays on one of our sites as well. Are there any plans for this to be changed in a future release?

**Comment by Santiagoebizmarts** [comment]
Hello @aingham 
This will only do something if the cache was flushed. If you have a problem with this method then there is something not working correctly when altering the database.

I suggest you to contact our support at mailchimp@ebizmarts-desk.zendesk.com

Regards.
