### ISSUE TITLE
Changing API Key Error

### ISSUE THREAD

**Issue by AdavisEbsco** [mailchimp/mc-magento#599]
Steps to reproduce:
1. Open MailChimp tab under Configuration.
2. Get API key
3. Paste API key in field and click Save Config
4. Save fails with following error:
```
API Key Invalid for Api Call: lists?fields=lists&count=100 - Your API key may be invalid, or you've attempted to access the wrong datacenter.
```

It looks when we try to change the API key in the configuration settings, the extension is trying to contact the Mailchimp API with the old API key, getting an error and then canceling the configuration save operation preventing the new API key from being saved. We have to manually disable the extension in the `core_config_data` table and then we can update the API key in configuration and re-enable the plugin.

**Comment by Santiagoebizmarts** [comment]
Hello @AdavisEbsco ,

Thanks for contacting us.
This issue has been solved already at https://github.com/mailchimp/mc-magento/pull/549/files

Regards.
