### ISSUE TITLE
all new newsletter subscriptions becomes Unsubscribed

### ISSUE THREAD

**Issue by mhmnaseem** [mailchimp/mc-magento#601]
after mailchimp for magento installed all new newsletter subscriptions becomes Unsubscribed.
![newsletter subscribers newsletter magento admin 1](https://user-images.githubusercontent.com/6754006/34823738-bd30fcde-f6f1-11e7-8670-61b38a029b02.png)

**Comment by mhmnaseem** [comment]
public function handleSubscriber(Varien_Event_Observer $observer)
    {
        $subscriber = $observer->getEvent()->getSubscriber();
        if ($subscriber->getSubscriberSource() != Ebizmarts_MailChimp_Model_Subscriber::SUBSCRIBE_SOURCE) {
            $isEnabled = $this->makeHelper()->isMailChimpEnabled($subscriber->getStoreId());
            if ($isEnabled) {
                $subscriber->setImportMode(true);
                if (!Mage::getSingleton('customer/session')->isLoggedIn() && !Mage::app()->getStore()->isAdmin()) {
                    Mage::getModel('core/cookie')->set(
                        'email', $subscriber->getSubscriberEmail(), null, null, null, null, false
                    );
                }
                if (true === $subscriber->getIsStatusChanged()) {
                    Mage::getModel('mailchimp/api_subscribers')->updateSubscriber($subscriber, true);
                } else {
                    $origData = $subscriber->getOrigData();
                    if (is_array($origData) && isset($origData['subscriber_status'])
                        && $origData['subscriber_status'] != $subscriber->getSubscriberStatus()
                    ) {
                        Mage::getModel('mailchimp/api_subscribers')->updateSubscriber($subscriber, true);
                    }
                }
            }
        }
    }

**Comment by Santiagoebizmarts** [comment]
Hello,

The portion of code you commented takes care of updating the subscriber status as it currently is in Magento. I beleive you might have a conflict with another extension.
Please read our guidelines and add more information about it in order to allow us to replicate this.

Regards.

**Comment by ibejo** [comment]
I can't see the part of file you indicated, maybe because the version is different. I have the same problem with my store. The new costumare are added to the list as unsubscribed users
Can you help me?
Thank you!

MailChimp For Magento v1.1.12 - Magento 1.9.2.0

**Comment by Santiagoebizmarts** [comment]
Hello @ibejo 

Please update the extension. In case it continues to happen contact our support to mailchimp@ebizmarts-desk.zendesk.com

Kind Regards.
