### ISSUE TITLE
after initial syncing subscribers data the follow up sync not works 

### ISSUE THREAD

**Issue by mhmnaseem** [mailchimp/mc-magento#602]
after initial syncing subscribers data the follow up sync not update subscriber data to mailchimp

**Comment by Santiagoebizmarts** [comment]
Hello @mhmnaseem 

Please read our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) before creating a new issue.
We can re-open this once the needed information is added.

Regards.
