### ISSUE TITLE
Cannot use "Product Recommendation" in production!!

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#603]
Cannot use "Product Recommendation" in production!! *using last av version 14-1

**Problem**
Images look like this, we cannot send this to live customers
![image](https://user-images.githubusercontent.com/652395/34915376-f05bac86-f925-11e7-8b02-935dacd7564e.png)

**I dont know how it is getting the image url, but this does not seem correct?** Why not use the base image, apparently this resize does not work
domain.com/media/catalog/product/cache/8/image/265x/9df78eab33525d08d6e5fb8d27136e95/6/6/6661-dean-ind_1.jpg

This is not a nginx issue. All images work fine. The wrong img url is generated ot submitted.
![image](https://user-images.githubusercontent.com/652395/34915371-cd097326-f925-11e7-9066-ae724e7f96a4.png)

Maybe it is smarter to set a width/height in the backend for the dimensions we want to submit? because this way your cache will also become bloathed: I mean it is reszing to every dimension. 
Why not make it so that we can hardcode 500x (resize to max 1 size 500px) just like on frontend. Then it also always works. 

The main downside on all this hocus pokus: is that we **really really need to be able to rely** on these "automated" elements. This is why it has to be fool proof.

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Do you know what is the difference between the images working and the ones that don't?
I see you mention the resize, maybe the problem is the same as in https://github.com/mailchimp/mc-magento/issues/589

Regards.

**Comment by seansan** [comment]
There is a link: see what I shared above. Only when I click it: there is no image; so something is wrong with the generated link

**Comment by Santiagoebizmarts** [comment]
What I mean is that I see the other images work okay, is there a difference in the image you mention? Did you refresh the image cache at any moment? Because this will cause all the images to be sent again because the image path may have changed.

Regards.

**Comment by seansan** [comment]
​>> Did you refresh the image cache at any moment? Because this will cause
all the images to be sent again because the image path may have changed.
I dont know cache is constantly refreshed based on store parameters. And
the image is generated dynamically correct? (based on the call)
Cache is also cleared using scripts.



Powered by Gmelius <https://gmelius.com?ref=mail>

On Thu, Jan 18, 2018 at 4:47 PM, Santiagoebizmarts <notifications@github.com
