### ISSUE TITLE
Initial sync : In Progress

### ISSUE THREAD

**Issue by davidmann4** [mailchimp/mc-magento#604]
Great plugin, only problem we have is that it stays in 

Initial sync : In Progress

for over a week now, cronjobs are working. Also triggered it manually.  Also I did not found any exceptions in the logs. 

any idea ? using MailChimp For Magento v1.1.9.1 by ebizmarts

**Comment by ebizmarts-keller** [comment]
This is working correctly and the issue isn't clearly reported, contact support to address your particular case sending request to: mailchimp@ebizmarts-desk.zendesk.com

You should also try the latest version 1.1.10 first.

**Comment by davidmann4** [comment]
for me it is not working correctly :) 

I've also contacted support. I wonder what I could tell you more than which version I am using and that all the other features work, except the shop sync to mailchimp. 

So we want to use the e-commerce features of your plugin but the sync function is not working.

**Comment by ebizmarts-keller** [comment]
I'll get back at you on the support ticket later.

Regards

**Comment by treestonemedia** [comment]
@davidmann4  were you able to resolve your issue?

**Comment by Santiagoebizmarts** [comment]
Hello @treestonemedia 
Please contact our support team at mailchimp@ebizmarts-desk.zendesk.com

Regards.
