### ISSUE TITLE
Unable to display popup in admin -> config, due to X-Frame-Options

### ISSUE THREAD

**Issue by MurKit** [mailchimp/mc-magento#608]
Preconditions
1. Magento ver. 1.9.2.3
2. MailChimp For Magento v1.1.8
3. Chrome

Steps to reproduce
1. Go to Magento Admin, Mailchimp settings
2. Click "Add new custom data entry in the column of the right", the error arises:

Expected result:
Popup opens with form.
Actual result:
Empty popup opens.
Error in Browser js console:
`Refused to display 'http://qbed.test/index.php/admin/admin/mergevars/addmergevar/?' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('DENY, SAMEORIGIN'). Falling back to 'deny'.`

**Comment by Santiagoebizmarts** [comment]
Hello @MurKit 

Please read our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) and add more information in order to allow us to replicate this.

Regards.

**Comment by MurKit** [comment]
Edited.

**Comment by Santiagoebizmarts** [comment]
Hello,

Please note we currently are in version 1.1.10, please make sure the problem persists in the latest version. If it does we can reopen this issue.

Regards.
