### ISSUE TITLE
Mailchimp product recommendations

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#610]
We are testing the V3 API and product recommendations, described here: 
https://mailchimp.com/features/product-recommendations/

The problem is that in preview mode ALL customers get **exactly the same recommendation**. 

This is not what  I understood product recommendations do. The are on a person per person basis. 

![image](https://user-images.githubusercontent.com/652395/35035247-054546f0-fb71-11e7-882c-57b82e1f9e35.png)

For example customer X (I checked all data)
- orders 4x brand A
- but is receiving only the recommendations (same as all others) for brand B

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Please note this is not something handled by the extension. The products recommended are decided by MailChimp's engine.

Regards.

**Comment by seansan** [comment]
​And you are sure it works with the data the extension sends ... (sorry for
double double  checking)




Powered by Gmelius <https://gmelius.com?ref=mail>



Powered by Gmelius <https://gmelius.com?ref=mail>

On Wed, Jan 17, 2018 at 4:09 PM, Santiagoebizmarts <notifications@github.com

**Comment by Santiagoebizmarts** [comment]
I am not sure what your questions is.
About how MailChimp creates the recommended products I don't know the details, if there is information missing in the MailChimp store we can take a look on why it was not sent.

Regards.

**Comment by seansan** [comment]
Well. I presume : did you ever test that suggested products work with the
uploaded data by your extension?

**Comment by seansan** [comment]
**This is what MC answers, data is NOT arriving in MC**

Seems the extension has been sending over 10GB of data last couple of weeks - but no orders available in Mailchimp????? Was this ever really tested: I mean seeing the product recommendations based on the API with Magento

Suggest: raise urgency +1

PRIORITY HELPDESK EMPLOYEE: (MailChimp)Jan 18, 5:25 AM EST

Thank you for reaching out to us here in support. Looking over the account, I can see that the account does have magento connected and is receiving ecommerce data that is needed to generate the product recommendations. What Im seeing there though is that you do not have a lot of orders that have been passed over, currently **seeing 13 orders**, while the minimum required to have more granular product recommendations is 500 orders, seen here below.

About Product Recommendations: http://eepurl.com/cRVYH5 

The orders data would be most important to see what has been ordered to match that data with all other orders, and this is what would give a recommendation. If enough of that data is not present to have ranging and varied recommendations, you will see some options more than others as the stores top sellers would be seen instead. | Dion (MailChimp)Jan 18, 5:25 AM ESTHello Sean,Thank you for reaching out to us here in support. Looking over the account, I can see that the account does have magento connected and is receiving ecommerce data that is needed to generate the product recommendations. What Im seeing there though is that you do not have a lot of orders that have been passed over, currently seeing 13 orders, while the minimum required to have more granular product recommendations is 500 orders, seen here below.About Product Recommendations: http://eepurl.com/cRVYH5 The orders data would be most important to see what has been ordered to match that data with all other orders, and this is what would give a recommendation. If enough of that data is not present to have ranging and varied recommendations, you will see some options more than others as the stores top sellers would be seen instead.
-- | --
Dion (MailChimp)Jan 18, 5:25 AM ESTHello Sean,Thank you for reaching out to us here in support. Looking over the account, I can see that the account does have magento connected and is receiving ecommerce data that is needed to generate the product recommendations. What Im seeing there though is that you do not have a lot of orders that have been passed over, currently seeing 13 orders, while the minimum required to have more granular product recommendations is 500 orders, seen here below.About Product Recommendations: http://eepurl.com/cRVYH5 The orders data would be most important to see what has been ordered to match that data with all other orders, and this is what would give a recommendation. If enough of that data is not present to have ranging and varied recommendations, you will see some options more than others as the stores top sellers would be seen instead.
