### ISSUE TITLE
Unable to send custom Merge Field

### ISSUE THREAD

**Issue by MurKit** [mailchimp/mc-magento#611]
**Preconditions**
Magento ver. 1.9.2.3
MailChimp For Magento v1.1.8

**Steps to reproduce**
1. Create new Merge field in Magento admin and create observer, due to this instruction:
https://ebizmarts.com/forums/topics/view/24875
2. My observer looks like this:
```
    public function addCouponMailchimp($observer)
    {
        $event = $observer->getEvent();
        $emailAddress = $event->getSubscriberEmail();
        $mergeFieldTag = $event->getMergeFieldTag();
        $mergeFieldValue = $event->getMergeFieldValue();
        if ($mergeFieldTag == "coupon_code") {
            $event->setMergeFieldValue('zzzz');
        }
    }
```
3. Check in debugger that PHP executes the custom observer

**Expected result:**
When adding a new subscriber, and code in observer executes, custom field is sent to Mailchimp.
**Actual result:**
When adding a new subscriber, and code in observer executes, all fields are sent to Maichimp, except custom field.

**Comment by Santiagoebizmarts** [comment]
Hello,

Please update your extension to the latest version 1.1.10 and let us know if this continues to happen.
Then we can reopen this issue.

Regards.

**Comment by MurKit** [comment]
Thank you, it really helped. Working right away!

**Comment by MurKit** [comment]
But the problem is it appears to be empty, even though I'm sending string 'zzzz' from Magento.
