### ISSUE TITLE
Distrusted SSL certificate chimpstatic.com

### ISSUE THREAD

**Issue by HRR1337** [mailchimp/mc-magento#622]
On my webshop I get the following console error:

The SSL certificate used to load resources from https://chimpstatic.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

Will there be on time a new ssl certificate?

**Comment by centerax** [comment]
Please reach out to [ecommercehelp at mailchimp.com] for further assitance. Thank you

**Comment by seansan** [comment]
Maybe @centerax can reach out to MC too ... as you guys have the relation & add the JS via the extension

And maybe to keep users engaged and sharing ideas also in the future: this response does the same but a great beneficial side effect.
"Thanks! HRR1337. We'll definitely pass it along. Do know that your feedback directly to Mailchimp also makes a big difference as the take user feedback quite serious. You can do this here [LINK]".

**Comment by centerax** [comment]
@seansan We did reach to mailchimp and thats what we agreed its best for the customer to do. Contact [ecommercehelp at mailchimp.com].

**Comment by seansan** [comment]
​thx! let's all try to make it work! together




Powered by Gmelius <https://gmelius.com?ref=mail>

**Comment by Mic2005** [comment]
I also have tis issue and sent a mail to mailchimp to ask if they can update the certificate.

**Comment by rahulbpatel** [comment]
Any luck?

**Comment by Mic2005** [comment]
Sent mail to Mailchimp. They know and working on it to fix it. Don't know when it's fixed.
