### ISSUE TITLE
Changing email, unsubscribe and delete? customer thru Magento

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#628]
1. how can we unsubscribe customer emails in mailchimp thru Magento? 
unticking this box and clicking save: should that do the trick and is Mailchimp then updated?
(strangely enough after untick+save: the box is still ticked)

2. how can we delete customer emails in mailchimp thru Magento? Maybe this is also a unsubscribe. But sometimes we get an email "this email is no longer in use". So we would want to delete it.

3. how can we change a customers email?  sometimes we get an email "my email hass changed from AAA to BBB. please update your records". But how do we update our records and  inform Mailchimp via an update in Magento. Does changing the email in customer adminhtml -> update mailchimp immediately?

![image](https://user-images.githubusercontent.com/652395/35622077-e0dab86a-0686-11e8-839a-7fc8d1935194.png)

**Comment by ebizmarts-keller** [comment]
Hello, this is not really an issue with the module, please contact support at mailchimp@ebizmarts-desk.zendesk.com for assistance

**Comment by seansan** [comment]
​Maybe you can answer the 3 questions? Because they are not all YES I think
... and therefore maybe an issue for the community
These are the most common cases we see when working with emails​




Powered by Gmelius <https://gmelius.com?ref=mail>

**Comment by ebizmarts-keller** [comment]
Hello, question 1 and 2 are really support questions, there is not a well defined issue with the module and we want to be organized, create a thread here for something more public: https://ebizmarts.com/forums/view/6 and we'll get back at you as soon as possible.

For your third question, it isn't possible at the moment and there is already an open issue here: https://github.com/mailchimp/mc-magento/issues/17

**Comment by seansan** [comment]
I can see.

So use case 1 and 2 are supported?

And use case 3 is marked urgent since last year?

I ask because these are major data flows and for gdpr we need to be certain
that an unsubscribe is really a unsubscribe

**Comment by gonzaloebiz** [comment]
Hi @seansan 

this is not the place to make questions. 
I think you know pretty well the dynamic, you are not a newbie, if you found an issue this is the right place to put it, if you have questions or doubts send us an email to our support team at mailchimp@ebizmarts-desk.zendesk.com or post in our forums at https://ebizmarts.com/forums/view/6.
Your feedback is always welcome in the right place

Best

**Comment by seansan** [comment]
Seeing the importance of list management and the MC Omnivore system, we really need to start adding OPT OUT options instead of only OPT IN options

- how can we unsubscribe customers in account?

- how can we delete customers/subscribers: suppose a customer acts on their GDPR right: delete all my data? or we just want them deleted because the order was cancelled/they are no customer?

- how can we unsubscribe customers maybe during credit note (logical step in process)?

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Unsubscription is already available in the customer account.

Please note you already created a ticket for this at https://github.com/mailchimp/mc-magento/issues/799

Regards.

**Comment by seansan** [comment]
Is it also sent to Mailchimp?
