### ISSUE TITLE
Description : Schema describes string, boolean found instead

### ISSUE THREAD

**Issue by jorgb90** [mailchimp/mc-magento#63]
Products aren't syncing for us and giving the following error in Mailchimp errors:

Invalid Resource	400	PRO	description : Schema describes string, boolean found instead

**Comment by Santiagoebizmarts** [comment]
Hello @jorgb90 
A new version will be released on Monday. We made some changes on how products are sent and it should work okay in this new version 1.1.2.

If the problem remains please check our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to create a new issue or simply go to our [forum](http://ebizmarts.com/forums/view/6).

Regards.
