### ISSUE TITLE
After update customer order email in order + customer data we get API error

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#630]
Situation: After update customer order email in order + customer data we get API error

Error message from system:
Invalid Resource for Api Call: lists/9ea0b3b54fxxx/members/bef3760cbef3760cbef3760cbef3760c: merge_fields.BILLING : Data did not match any of the schemas described in anyOf. / merge_fields.SHIPPING : Data did not match any of the schemas described in anyOf.

Reproduce:
title says it all, but again
- place order with emailX, then customer calls you made a typo needs to be emailY
- change email in order
- change email on customer level
- hit save
- shortly after we see this message from your extension in adminhtml

**Comment by seansan** [comment]
I thought it was clear already; but updated

**Comment by gonzaloebiz** [comment]
Can you please specify your magento end mc-magento version?

Thanks

**Comment by seansan** [comment]
Latest of all to date

**Comment by ebizmarts-keller** [comment]
Fix will be added on fix for this issue: https://github.com/mailchimp/mc-magento/issues/613

**Comment by seansan** [comment]
We do have api key set in contrary to other ticket

**Comment by ebizmarts-keller** [comment]
A fix for this is already on the develop branch and will be included in the next version, changes were made to this function: https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L225 (customerSaveBefore)

**Comment by jammy-git** [comment]
Just to add. This issue is still happening. Updated to 1.1.20 last week and still receiving this error in the error log (happened just a few hours ago).

**Comment by Santiagoebizmarts** [comment]
Hello @jammy-git 

**merge_fields.BILLING : Data did not match any of the schemas described in anyOf. /**
Please note the error message above is not necessairly a bug.
It means the data being sent does not match the Mailchimp Merge Field type.

Please contact our support at mailchimp@ebizmarts-desk.zendesk.com in order to get help with the configurations and confirm if in your case is indeed a bug or maybe just a missconfiguration.

Regards.
