### ISSUE TITLE
no data synced for shipping_city, shipping_state, shipping_telephone

### ISSUE THREAD

**Issue by mardisilaki** [mailchimp/mc-magento#639]
Hi anyone got an idea,

previously, i have magento version EE 1.14 and mailchimp 1.1.8, and i want to add customer fields, which are shipping_city, shipping_state, shipping_telephone. 
I did some code modification for shipping_city and shipping_state in community/Ebizmarts/Mailchimp/Model/Api/Subscribers.php, for shipping_telephone, the code came from Mailchimp originally. Below is the code:

                        case 'dop':
                            $dop = $helper->getLastDateOfPurchase($subscriberEmail);
                            if ($dop) {
                                $eventValue = $mergeVars[$key] = $dop;
                            }
                            break;
                        case 'shipping_city':
                            $addr = explode('_', $customAtt);
                            $address = $customer->getPrimaryAddress('default_' . $addr[0]);
                            
                            if ($address) {
                                $city = $address->getCity();
                                if ($city) {
                                    $eventValue = $mergeVars[$key] = $city;
                                }
                            }
                            break;
                        case 'shipping_state':
                            $addr = explode('_', $customAtt);
                            $address = $customer->getPrimaryAddress('default_' . $addr[0]);
                            
                            if ($address) {
                                $region = $address->getRegion();
                                if ($region) {
                                    $eventValue = $mergeVars[$key] = $region;
                                }
                            }
                            break;

and after the cron ran, i checked in the https://us17.admin.mailchimp.com/lists/members/, the data were there but no data were sync for shipping_city, shipping_state, shipping_telepohone.

![mailchimp_nodata](https://user-images.githubusercontent.com/10055796/36198798-2b307782-11aa-11e8-8d6f-e355ee752685.png)

![mailchimp_fields](https://user-images.githubusercontent.com/10055796/36198801-3150ebc4-11aa-11e8-9f4b-a2a08f8bb340.png)

After that i updated to 1.1.10 version, it became worst, because after sync, no data at all in https://us17.admin.mailchimp.com/lists/members.

Please help me,

**Comment by Santiagoebizmarts** [comment]
Hello,

Please note this is not an issue with the extension.
Check our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) before creating new issues.
This is something to ask to our support at mailchimp@ebizmarts-desk.zendesk.com or in our [forum](https://ebizmarts.com/forums/view/6).

About what you are trying to do please note it works out of the box int he latest version 1.1.10.
Just make sure you have the following entries in your configuration.
![screen shot 2018-02-14 at 11 52 44](https://user-images.githubusercontent.com/8330778/36210604-9a6b142c-117d-11e8-9ee0-fde01bd23af7.png)

Also you can see how to add custom entries in the merge fields [here](https://ebizmarts.com/forums/topics/view/24875).

Regards.
