### ISSUE TITLE
Promo rule already exists error

### ISSUE THREAD

**Issue by darekkosyl** [mailchimp/mc-magento#648]
Magento v 1.9.3.7  PHP 5.6.33

We have just upgraded to version 1.1.10 and are now getting the following type of mailchimp errors (over 4000 now):

e g "A promo rule for store '3a7a579d3c8624f23c21166e35a65dab' with the id '2' already exists.

Is there a fix for that?

Thanks

**Comment by Santiagoebizmarts** [comment]
Hello @darekkosyl 

We are testing version 1.1.11 which solves that. Should be out next week.

Regards.
