### ISSUE TITLE
Add some js in the admin to avoid save before continue

### ISSUE THREAD

**Issue by gonzaloebiz** [mailchimp/mc-magento#649]

**Comment by seansan** [comment]
Did you use the template for reporting issues? 💯 

@centerax Pable Police

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Note this is an enhancement we are doing to the extension. It is not an issue to report a bug or a problem.
Also we do know the environment where we find errors, the same does not happens when someone outside from Ebizmarts reports an issue.

Regards.
