### ISSUE TITLE
Freddy icon not showing in grid

### ISSUE THREAD

**Issue by elkawakibi** [mailchimp/mc-magento#650]
Orders placed through the MailChimp campaign don't show the mailchimp icon in the grid. This happend after the update from 1.1.7 to v1.1.10.

This is my first post, let me know if more information is needed.

### Preconditions
1.  Magento CE v1.9.1.1
2.  MailChimp v1.1.10

### Steps to reproduce
1. Go to Sales > Order

### Expected result
1. For every order that is placed via a newsletter the MailChimp icon needs to be displayed.

### Actual result
The MailChimp icon doesn't show when the order is placed via the MailChimp campaign. The columns that check if a order is placed via the MailChimp campaign:
mailchimp_campaign_id, mailchimp_abandonedcart_flag, mailcherpage are NULL for every order.

[Screenshot 1](https://ibb.co/krpqdS) // The arrow needs to be pointing to the Mailchimp column
[Screenshot 2](https://ibb.co/iA1iXn)

**Comment by Santiagoebizmarts** [comment]
Hello @elkawakibi 

It looks like the campaign id is not being properly catched.
Please contact our support team at mailchimp@ebizmarts-desk.zendesk.com

If we find this to be something needed to be fixed in the code I will re-open the issue.

Regards.
