### ISSUE TITLE
undefined offset - Model/ProcessWebhook.php on line 55

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#656]
[16-Feb-2018 13:30:57 UTC] PHP Notice:  unserialize(): Error at offset 225 of 484 bytes in app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php on line 55
[19-Feb-2018 09:50:47 UTC] PHP Notice:  unserialize(): Error at offset 219 of 478 bytes in app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php on line 55

**Comment by gonzaloebiz** [comment]
Please, follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines)

**Comment by seansan** [comment]
​it is in our logs​

Which part is not clear? expected result is no error, actual result is
webhook is not being processed






Not using Gmelius <https://gmelius.com?ref=mail> yet?

**Comment by gonzaloebiz** [comment]
We will reopen the issue when we have more information, like M4M version etc etc

**Comment by seansan** [comment]
​omg

you ignore errors

because ..... ???

we have the latest version: that is the release from last year .... I think
everyone is on that version ... and waiting for a next release




Not using Gmelius <https://gmelius.com?ref=mail> yet?

**Comment by gonzaloebiz** [comment]
We don't ignore errors, we need more information and the easy way to have all the required information is if you follow the [issue reporting guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines)
We reopen the issue when the information is complete

Best

**Comment by seansan** [comment]
This is the error

There is no more information otherwise I would have given it

[16-Feb-2018 13:30:57 UTC] PHP Notice: unserialize(): Error at offset 225
of 484 bytes in
app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php on line 55
[19-Feb-2018 09:50:47 UTC] PHP Notice: unserialize(): Error at offset 219
of 478 bytes in
app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php on line 55



Not using Gmelius <https://gmelius.com?ref=mail> yet?

**Comment by centerax** [comment]
might help https://stackoverflow.com/questions/10152904/unserialize-function-unserialize-error-at-offset

**Comment by centerax** [comment]
@seansan when you create an issue there is a template that everyone should follow. (you just need to fill in the gaps) it seems in your case you got rid of it and just pasted the error message. That template helps organize work.
