### ISSUE TITLE
Checkout subscription is only possible when isEcomSyncDataEnabled is enabled

### ISSUE THREAD

**Issue by jan-lukowiak** [mailchimp/mc-magento#657]
The checkout subscription is only working when the option for EcomSyncData is enabled. The condition is tested before the possible new subscriber is added.

In the function 'newOrder' in 'app/code/community/Ebizmarts/MailChimp/Model/Observer.php' the part for adding subscribers ('if (isset($post))') should be moved outside of the 'if ($ecommEnabled)' condition.

**Comment by Santiagoebizmarts** [comment]
This is being solved at https://github.com/mailchimp/mc-magento/pull/658

Regards.
