### ISSUE TITLE
Checkout + popup subscribers are instantly subscribed without double optin

### ISSUE THREAD

**Issue by jan-lukowiak** [mailchimp/mc-magento#666]
Checkout + popup subscribers subscribed through the function `Mage::helper('mailchimp')->subscribeMember()` with the status `Mage_Newsletter_Model_Subscriber::STATUS_SUBSCRIBED` and not `Mage_Newsletter_Model_Subscriber::STATUS_UNCONFIRMED`.

This leads to an instant subscribe without a MailChimp double optin mail. I would suggest changing the subscription status to `STATUS_UNCONFIRMED` or check the default magento config `newsletter/subscription/confirm`.

**Comment by Santiagoebizmarts** [comment]
Hello @jan-lukowiak 

This does not happens in my tests. The function used is not subscribeMember() in the helper class.
We just subscribe the guest normally as Magento does with the footer form.
The function used is [HERE](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Block/Popup/Emailcatcher.php#L77).

It checks the Need to confirm status and sends the confirm request unless you are logged in which is the same behavior Magento does by default.

If the use case you are talking about is different please elaborate and we will reopen the issue.

Regards.

**Comment by Santiagoebizmarts** [comment]
For checkout subscription you seem to be right, I am creating a [new issue](https://github.com/mailchimp/mc-magento/issues/668) for it.
