### ISSUE TITLE
Not getting Abandoned cart emails. 

### ISSUE THREAD

**Issue by tousif12** [mailchimp/mc-magento#667]
I am not getting Abandoned cart emails. 
Magento 2.1.8
Mailchimp  1.0.26

As list was not syncing on both sides so I manually ran cron job for it. Now list is sync but not getting any abandoned cart email.

**Account info** 
Username: XXXXX
Total Subscribers: 32892
Ecommerce Data uploaded to MailChimp
Total Customers: 142
Total Products: 28
Total Orders: 7
Total Carts: 45
Account Synced since: 2018-03-14

And on magento side  in   Reports- > abandoned cart   all user how abandoned cart are adding perfectly. So I think I am not getting webhook from magento to mailchimp ? or something like this ?

**Comment by Santiagoebizmarts** [comment]
Hello @tousif12 

Thanks for your feedback. Note this is the repository for Magento 1.
You can find the repo for Magento 2 at [https://github.com/mailchimp/mc-magento2](https://github.com/mailchimp/mc-magento2)

Regards,
