### ISSUE TITLE
Checkout subscription not sending confirmation email if double opt-in enabled.

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#668]
### Preconditions
1. Magento 1.9.3.7
2. MailChimp For Magento 1.1.11

### Steps to reproduce
1. Enable the general section of the extension configuration and select a list.
2. Enable checkout subscription.
3. Subscribe at the checkout as a guest.

### Expected result
1. Confirmation emails is sent.

### Actual result
1. Guest is subscribed directly.

**Comment by jan-lukowiak** [comment]
@Santiagoebizmarts You're right, it's only for checkout subscription. I've changed the method to the one used in `_handleCookie` and created a pull request #669

**Comment by jan-lukowiak** [comment]
@Santiagoebizmarts It's not only for guests but for all subscribers through checkout I think

**Comment by ZenMasta** [comment]
This would explain why my customers are recently telling me that they aren't getting order confirmation emails.

**Comment by Santiagoebizmarts** [comment]
Hello @ZenMasta 

Actually this should not affect order confirmation emails. Only subscription confirmation emails were affected, the subscriber were being subscribed just by enabling the checkout checkbox but nothing else was affected.
You can contact our support at mailchimp@ebizmarts-desk.zendesk.com for more information about your problem. We will help you find the cause of the problem you are experiencing.

Regards.
