### ISSUE TITLE
Updating order ecommerce data after refund results in exception

### ISSUE THREAD

**Issue by urko99** [mailchimp/mc-magento#678]
### Preconditions
Using Magento 1.7.0.2 with the latest devel version (1.1.12).

### Steps to reproduce
Make a refund on order and wait for the ecommerce data sync to process it.

### Actual result
Invalid store id argument is passed in Ebizmarts_MailChimp_Model_Observer on line 592 and 626 - $mailchimpStoreId instead of expected $storeId.

**Comment by Santiagoebizmarts** [comment]
@urko99 

Thanks for your contribution!
This will be included in version 1.1.12 as well.

Kind Regards.
