### ISSUE TITLE
GDPR using zero1-gdpr extension // how do we anonymize data ??

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#683]
We use zero GDPR extension. To date the only solution for GDPR in magento 1.x. 
Problem:
If customer requests data removal then we can do this
If no orders: account is deleted
If orders, then account is anonimized + all *allowed* data is erased (we cant even find it)
The problem is that the email is required: so this email address is anonimized (changed) + the user is unsubscribed from any newsletters

**Problem**=> changing the email never arrives in Mailchimp

This is a problem because we "officially" did not remove all the customers data: I mean I can find his email in mailchimp. So we are not compliant with GDPR and this is a real issue.

*Important*
To support this case: one could execute all the above steps manually to achieve the same result. The problem is that the mail address change never reaches Mailchimp: and personal data can still be found even when someone executed his right to removal of data

Option 1: Add ability to support change of email address: then the change of email arrives and combined with the anonimization of the email => we are compliant +++ this is the best solution because we dont want to loose the sales data

Option 2: create some kind of special event that the mailchimp extension watches and removes all data from mailchimp

### Preconditions
1. use https://marketplace.magento.com/zero1-zero1-gdpr.html
2. or do the above steps manually
3. customers requests complete! data removal
4. we anonimize account, remove non essential data, change email, unsubscribe from newsletter
5 save

### Steps to reproduce
See above

### Expected result
Customer unbsubscribed
Email address changed (to randomness)

### Actual result
Customer unbsubscribed
Email address NOT changed

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

This is something that is not allowed at MailChimp side of things. Email addresses cannot be changed.
It is not extension-related, therefore there is nothing we can do here.
You can see the issue about the email address change at https://github.com/mailchimp/mc-magento/issues/17
Any additional information about GDPR can be added at https://github.com/mailchimp/mc-magento/issues/449

Regards.

**Comment by seansan** [comment]
​please dont close the issue: one takes a lot of time to write down this
stuff

you could merge it to not loose the business rationale

this is someting we MUST tackle ... so great that there is another issue:
but they are not to positive

it has also been reported to mailchimp (they left the issue open)

​




Not using Gmelius <https://gmelius.com?ref=mail> yet?

**Comment by Santiagoebizmarts** [comment]
@seansan 
Please note this will not be lost because I added links to both issues related.
Now in those issues there is a notification showing a link to this one. Since github does not allow issue merging, this is the closest thing we can do.

We cannot allow multiple issues related to the same subject, it would make it hard to keep up with what needs to be done.

Regards.

**Comment by seansan** [comment]
​I still think this should be a separate issue

- it is not about GDPR in general
- it is not only about changing ones email, also this only 1 solution out
of many

I is about: Magento beeing made fully GDPR compliant only in the case of
"account anonimization", where Mailchimp and this extension dont support
this process.

Changing the email is only a *possible* solution of many


RE OPEN PLZ



​




Not using Gmelius <https://gmelius.com?ref=mail> yet?

**Comment by seansan** [comment]
in code this is issued, can we hang something on the delete() action??? Should delete not remove a customer from mailchimp anyways?

`        if ($subscriber->getId()) {
            $subscriber->unsubscribe();
            $subscriber->delete();
        }`

**Comment by seansan** [comment]
mailchimp just replied and said email can be updated right here (and this
is the advised way)

https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-patch_lists_list_id_members_subscriber_hash



Not using Gmelius <https://gmelius.com?ref=mail> yet?

**Comment by stevensagaar** [comment]
https://www.scommerce-mage.com/magento1-gdpr-compliance.html

**Comment by Santiagoebizmarts** [comment]
Hello @stevensagaar 
Have you tested this? I don't think this extension is compatible with ours.
I don't see anywhere in the description about it calling our export event.

Regards.

**Comment by stevensagaar** [comment]
@Santiagoebizmarts Yes I have tested this and it says on their FAQ section as well
