### ISSUE TITLE
Mandrill Default Scope Disabled - Enabled on Specific Website/Storeview Breaks OrderComment Emails

### ISSUE THREAD

**Issue by AndresInSpace** [mailchimp/mc-magento#684]
On 1.9+ CE
Mailchimp/Mandrill For Magento v1.1.12 

Steps:
Ensure 'Send Order Comment Email Copy To' field(s) in System->Config->Sales->Sales Emails->Order Comments is blank and method is BCC
Disable Mandrill Globally
Enable Mandrill for specific website/storeview
Go to any order of that website/store. 
Add a comment to order and notify customer. 
Submit comment.

You will receive an error:
Fatal error: Call to undefined method Zend_Mail::getBcc() in app\code\community\Ebizmarts\MailChimp\Model\Email\Template.php on line 81

It worked fine before we switched the scope. (Edit: I've since switched it back to being globally enabled, and the emails are working again.. but this scope issue still should be fixed.)

related: https://github.com/mailchimp/mc-magento/issues/568 https://github.com/mailchimp/mc-magento/issues/550

**Comment by Santiagoebizmarts** [comment]
Hello @andresinspace 
I think you have an old version of the extension. There have been some changes in Mandrill in the latest version 1.1.11.

I suggest you to contact our support at mailchimp@ebizmarts-desk.zendesk.com.

Regards.

**Comment by andresinspace** [comment]
We are on MailChimp For Magento v1.1.12 Mandrill For Magento v1.1.12 

I literally upgraded just now to ensure it was not something already solved in latest code release.

**Comment by Santiagoebizmarts** [comment]
I confirmed this to be a bug. Be extra careful when updating to the develop branch because database scripts might change and it won't be executed unless you manually edit the core_resource table in Magento.

Regards.

**Comment by andresinspace** [comment]
Where should I be downloading the 'Official' stable version?

As the last time I downloaded from the magento marketplace, the module was completely broken and didn't even connect to my account properly. (This was some months ago..)

**Comment by Santiagoebizmarts** [comment]
Official releases are tagged at https://github.com/mailchimp/mc-magento/releases

Regards.
