### ISSUE TITLE
mc_js_url not saving for store scope when inheriting from parent

### ISSUE THREAD

**Issue by bizlift** [mailchimp/mc-magento#685]
Site was running slow after upgrading the module.  I checked Magento profiler and it showed that BLOCK ACTION: addMCJs -> setText was taking over 1.5 seconds.

I don't have scope set for store, just in default.

When I edited Ebizmarts_MailChimp_Helper_Data to bypass the `if ($this->areJsUrlAndListScopesEqual($storeId))` in `public function getMCJs()`and just set the url regardless of if statement,  the profiler shows that it runs almost instantly.

In core_config_data it shows mailchimp/ecommerce/mc_js_url is set for default and website but not the store.  So it looks like it's hitting the API even though it's set in config data

Not sure if the problem is in Ebizmarts_MailChimp_Model_Api_Stores or Ebizmarts_MailChimp_Helper_Data

**Comment by Santiagoebizmarts** [comment]
Hello @bizlift 

There were some issues in previous versions with this file not being properly loaded.
If you are in version 1.1.11 then run the following query and it should be fixed.
**DELETE FROM core_config_data WHERE path='mailchimp/ecommerce/mc_js_url';**
