### ISSUE TITLE
Mailchimp sync if customer does NOT subscribe to newsletter

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#686]
M4M 1.1.11 latest
Magento 1.9.3.8

When testing sync of
-subscriber
versus
-non-subscriber / transactional email customer

We see that subscriber has all the data

But non-subscriber (transactional email customer) has no data: dont we need all the data in the image below as well for a good transactional email flow?

![image](https://user-images.githubusercontent.com/652395/38455291-527d7bc4-3a76-11e8-9191-396ab1704a9c.png)

### Preconditions
M4M 1.1.11 latest
Magento 1.9.3.8

### Steps to reproduce
1. checkout with customer, do not subscribe to newsletter (using magento default subscribe and unsubscribe box)

### Expected result
1. More data in Mailchimp

**Comment by Santiagoebizmarts** [comment]
@seansan This is the same issue as https://github.com/mailchimp/mc-magento/issues/425

Regards.
