### ISSUE TITLE
Newsletter Template is not sending to subscribed Email.

### ISSUE THREAD

**Issue by kikinbenshakib** [mailchimp/mc-magento#688]
I have facing problem to send Newsletter Template email to Subscribed user emails. I don't know why it's happening with my Magento 1.9.x.  

Could you please check the images below and give me an update how can I resolve it?

![screenshot from 2018-04-09 01-44-04](https://user-images.githubusercontent.com/22374102/38471776-c293fdc6-3b97-11e8-9c5a-975029863b14.png)

**Comment by Santiagoebizmarts** [comment]
Hello @kikinbenshakib 

Thanks for contacting us. Please read our [guidelines](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) in order to allow us to replicate this problem.
With the current information we are not able to do it.

Regards.
