### ISSUE TITLE
Sales Order Pagination/Toolbar breaks when MC adds to Sales Grid

### ISSUE THREAD

**Issue by andresinspace** [mailchimp/mc-magento#690]
Magento 1.9.x
on Mailchimp 1.1.11 with https://github.com/mailchimp/mc-magento/issues/662 bug fix applied.

I have mailchimp disabled globally, and only enabled on a specific website scope.

With mailchimp option 'Display on Order Grid', it breaks the pagination toolbar on the Sales->Orders grid.

I have set 'Display on Order Grid' to None for now to work around this bug. (as it doesn't modify sales order grid with it set to none)

**Comment by Santiagoebizmarts** [comment]
Thanks for your feedback @andresinspace 

We will test this and get back to you.

Regards.

**Comment by Santiagoebizmarts** [comment]
Hello,

This works fine for me. If you have more information in order to allow me replicating this we can reopen this.

Regards.
