### ISSUE TITLE
New Subscribers have no language in MC

### ISSUE THREAD

**Issue by receter** [mailchimp/mc-magento#695]
When a new customer registers for an Magento account and chooses to subscribe to the newsletter, he will be added to Mailchimp. The issues is that the language in Mailchimp is not set.

Language: Not Detected

### Preconditions
1. Magento 1.9.3.1
2. Multiple stores (Deutsch, English, Französisch)
3. Stores have correct locale in Magento

### Steps to reproduce
1. Create account in store eg. a store with french locale
2. Subscribe to list in the process (magento signup form)

### Expected result
1. New Member in Mailchimp-List with language set to "French (France)"

### Actual result
1. New Member in Mailchimp-List with language set to "Not Detected"

This is possible with the Mailchimp API.

See here:
https://stackoverflow.com/questions/13178685/possible-to-provide-a-subscribers-language-through-mailchimp-api

Cite: "So how to set the language when subscribing through the api? Same way, set the browser language in the http header of the api call. This worked like a champ for me. Can't say how you would do it in your php app, but in Rails using the Gibbon gem, you would pass the values in the 'headers' option, which just sets it in the http header of the api call:"

**Comment by Santiagoebizmarts** [comment]
Hello @receter 

Thanks for your feedback. You can see the fix in the comment above.

Regards.

**Comment by receter** [comment]
Hi,

Thanks for looking into it. The provided solution does not yet fix my issue.

It does work with this code though:
`$language = substr($helper->getStoreLanguageCode($storeId), 0, 2);`

getStoreLanguageCode returns something like "en_US" or "fr_FR" but the Mailchimp-API needs the language codes like this: [Docs](https://kb.mailchimp.com/lists/manage-contacts/view-and-edit-contact-languages?utm_source=mc-api&utm_medium=docs&utm_campaign=apidocs)

But there are some exceptions where more then 2 characters are needed:

French (Canada) = fr_CA 
Portuguese (Portugal) = pt_PT 
Spanish (Spain) = es_ES 

I guess you tested it with one of the above languages.

**Comment by seansan** [comment]
https://stackoverflow.com/questions/6579287/magento-get-language-code-in-template-file

**Comment by Santiagoebizmarts** [comment]
@receter @seansan 

Thank you both for your contribution to this. I removed the done label in order to fix it.

Regards.
