### ISSUE TITLE
STORECODE contains name of the store instead of code of the store

### ISSUE THREAD

**Issue by receter** [mailchimp/mc-magento#697]
I assumed that STORECODE will contain the code of the store. This is not the case. It is mapped to "Created From" per default which seems to return the stores name.

### Preconditions
1. Magento 1.9.3.1
2. Multiple stores (Name: Deutsch, Code: de, Name: English, Code: en, ...)

### Steps to reproduce
1. Sync one Magento customer with MC

### Expected result
1. Merge variable STORECODE contains store code

### Actual result
1. Merge variable STORECODE contains store name (eg. Deutsch)

**Comment by ebizmarts-keller** [comment]
Hello @receter 

You are right, there is an issue there that can cause a bit confusion. We'll add a patch to send the store code in STORECODE and a different merge field to send the store name for version 1.1.13, you'll see the associated commit here soon too.

Regards
