### ISSUE TITLE
Add campaignCatcher.js file only if ecommerce is enabled.

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#698]

**Comment by HRR1337** [comment]
Hi there! When can we expect this function in an release? Thanks!

**Comment by ebizmarts-keller** [comment]
Hello @HRR1337 

We don't have a very accurate ETA, this fix is scheduled for version 1.1.13, and at this moment version 1.1.12 is being tested to be released soon.

Perhaps 2 months, in the meantime you can implement the associated commit here: https://github.com/mailchimp/mc-magento/commit/55d94bcd7da884e71d0de272014501e682265bec
