### ISSUE TITLE
GDPR Consent and GDPR update of email subscription preference

### ISSUE THREAD

**Issue by jaimiedijstra** [mailchimp/mc-magento#701]
With the new GDPR EU rules and guidance from Mailchimp. we need customers to consent to the handling of their personal data via check boxes in GDPR fields on our Mailchimp signup forms [https://blog.mailchimp.com/gdpr-tools-from-mailchimp/](https://blog.mailchimp.com/gdpr-tools-from-mailchimp/). This process also records the customers acceptance of the data being handled by Mailchimp (the service provider). This information is not currently possible to syncronize with Magento as you cannot import these preferences or fields (GDPR Fields in Mailchimp), and Magento (community) by default does not support the additional customer fields required to make this workable. The customer needs to accept the handling of data by the service provider (Mailchimp) by checking the box (it can't be pre-checked or hidden!).
It is not so bad with double opt in emails as the confirmation email can inform the customer to update their profile, but if customers choose to unsubsribe and re-subscribe at a later date, this GDPR compliance and the GDPR form management of it becomes hazy.
Is there a workaround for this issue or options being considered to introduce to mailchimp4magento? It seems to me the entire subscription control should be handled in Mailchimp alone and not the customer dashboard in Magento as it is not sufficient. Could the newsletter block within the dashboard be replaced with  informative subscription status details, and a button to automatically email the customer an "update email preferences" link? Checkboxes on orders and account creation for signing up may be better off sending automated emails to the customers with a link to sign up through a mailchimp GDPR compliant form?
I think this is a valid issue and problem for merchants who have customers in the EU and we need to make it as easy / straight forward for customers to update their subscription, so we can be 100% compliant without creating too much work for customers to subscribe!

**Comment by Santiagoebizmarts** [comment]
Hello @jaimiedijstra 
We are working to implement interest groups in the extension allowing them to be checkboxes. I think that should do the trick.
The issue that will solve this is **https://github.com/mailchimp/mc-magento/issues/514**

Regards.

**Comment by jaimiedijstra** [comment]
Thanks @Santiagoebizmarts this sounds great and ideal
