### ISSUE TITLE
Product retargeting automation bug

### ISSUE THREAD

**Issue by babygear** [mailchimp/mc-magento#705]
Product retargeting automation bug in v 1.1.11  

MailChimp for Magento doesn't support product retargeting automation due to an bug within MailChimp for Magento and how the script is added to the store.

**Comment by Santiagoebizmarts** [comment]
Hello @babygear 
We don't have any knowledge about what you are talking about. I have contacted MailChimp in order to see what's the issue here.
Will reopen if I have more information about this.
