### ISSUE TITLE
No store was created for this scope & syncing does not end

### ISSUE THREAD

**Issue by MurKit** [mailchimp/mc-magento#706]
### Preconditions
1. Magento CE 1.7.0.2
2. php 5.6
3. MailChimp For Magento v1.1.11

### Steps to reproduce
1. Upgrade Mailchimp module from 1.1.5 to 1.1.11
2. Save config, clear cache
3. Optional: click "Reset MailChimp Store" button

### Expected result
1. Magento connects and syncs with MC

### Actual result
1. Error is visible in Module config:
_No MailChimp store was created for this scope, parent scopes might be sending data for this store anyways.
You can create a new MailChimp store for this scope by configuring a new list for this scope._

2. On every page reload in admin a message is flashed:
_Looks like your MailChimp store was deleted. A new one has been created._

3. In Mailchimp panel, in Connected sites:
List settings
Syncing list: mylist
(and it took a whole day, seems not to end)

4. In the database in table core_config_data, mailchimp/general/storeid is changing every time page is reloaded, producing an entry into the log.

5. Mailchimp log:
2018-05-03T15:11:41+00:00 DEBUG (7): Resource Not Found for Api Call: ecommerce/stores/5e40e7a4ed5dbb91dfe800e297491530?fields=connected_site - The requested resource could not be found.
2018-05-03T15:08:36+00:00 DEBUG (7): Bad Request for Api Call: ecommerce/stores - We were unable to process the request. A store with the domain http://www.mysite.com/ already exists in the account.

**Comment by Santiagoebizmarts** [comment]
Hello @MurKit 
There has been a change in the MailChimp's API that prevents multiple stores associated to the same domain to be created in the same MC account.
You can look for a workaround at [https://ebizmarts.com/forums/topics/view/28025](https://ebizmarts.com/forums/topics/view/28025)

We are working to adapt the extension to the new restriction.

Kind Regards,

**Comment by MurKit** [comment]
Hello @Santiagoebizmarts 
I've checked this workaround.

1: Scope configuration
We have multiple Magento stores, but they all use Default configuration. And they have different urls.
Does this count as a multi store? Does Mailchimp try to create a store for each Magento store?

2: Using multi-store with the same domain under a Mailchimp account.
Even if we are trying to use multi store, stores have different urls in our Magento instance.

3: Orphan Mailchimp Store
I have checked this in Mailchimp admin and through the API - there is only one store created.
And it is syncing through the weekend. 
_"is_syncing": true,_
There are 20K subscribers, but it shouldn't take so long.

**Comment by MurKit** [comment]
Looks like it worked now. We have disabled module for default config and enabled for each store view separately. And it has synced ecommerce data ok.
It is not clear where to browse the data on the Milchimp side though.

**Comment by Santiagoebizmarts** [comment]
Hello @MurKit 
MailChimp does not offer a place to check the ecommerce data.
I suggest you to do tests of all the features you want to use before actually using them in production to make sure everything is working correctly.

If the amounts of items sent in the account details at the extension configuration match the amount of items in your Magento store then it should be okay.
Minor differences might occur if you have bundled and grouped products because they are not supported.
Also the customer number can be different because the guest who do purchases will be created as customers in MailChimp.

Regards.
