### ISSUE TITLE
"No MailChimp store was created for this scope"

### ISSUE THREAD

**Issue by davirs** [mailchimp/mc-magento#713]
Hi. I installed latest extension version.
At my panel I see this error message.. How I solve it?
I don't see anything about this in documentation.

![screenshot_16](https://user-images.githubusercontent.com/4355062/40559293-988ba7a4-602c-11e8-81c1-00eaf1c72f71.png)

I read the manual for installation and configuration But I can't use Order Notifications, not works.
this extension is compatible with it?

**Comment by davirs** [comment]
At mailchimp panel, I see this situation:

![screenshot_17](https://user-images.githubusercontent.com/4355062/40559853-7f4cca96-602e-11e8-933c-74edb6c3539d.png)

it's normal?

**Comment by Santiagoebizmarts** [comment]
Hello @davirs 

The problem with this case is related to the cron jobs.
They are failing or not running at all.
Please make sure you have the latest version 1.1.11 and contact our support team at mailchimp@ebizmarts-desk.zendesk.com. We will be able to give you a hand there.

Regards.
