### ISSUE TITLE
Capitalization at Newsletter top menu

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#718]
Mailchimp in the Newsletter menu is with lower case "c", change it to capital "C".

**Comment by ronaldbarendse** [comment]
And now you can make it lowercase again: https://mailchimp.com/design/ 😜

**Comment by Santiagoebizmarts** [comment]
Hello @ronaldbarendse 
Has been updated already, it is available in the latest version.
