### ISSUE TITLE
Missing buttons in admin panel 1.1.12

### ISSUE THREAD

**Issue by hpz937** [mailchimp/mc-magento#720]
### Preconditions

1. Magento CE 1.7.0.2 - PHP 5.4.45
2. Mailchimp 4 Magento extension 1.1.12

### Steps to reproduce

1. Upgrade version 1.1.9.11 to 1.1.12 using modman 1.12
2. Admin -> System -> Configuration -> Mailchimp

### Expected result

1. All buttons such as resend ecommerce data should be there

### Actual result

1. all buttons are missing
![mailchimp](https://user-images.githubusercontent.com/421012/40796284-38c5913e-64ca-11e8-9f11-2ce4e6bb979f.jpg)

**Comment by Santiagoebizmarts** [comment]
Hello @hpz937 

Thanks for your feedback.
Your PHP version seems to be too old. If you still get this problem with a newer version we can re-open this issue.

Regards.

**Comment by centerax** [comment]
If you used Modman, you might need to follow this extra step https://github.com/colinmollenhour/modman#magento-users

**Comment by hpz937** [comment]
Thank you @centerax this worked for me.
