### ISSUE TITLE
Cron/email_queue emails not being sent via Mandrill

### ISSUE THREAD

**Issue by josh-carter** [mailchimp/mc-magento#722]
Emails being processed via the cron, and therefore the `core_email_queue`, are not being processed though Mandrill. The reason being is that the code is trying to get the value for system configuration and the store isn't initialised whilst running through the cron unless manually specified i believe. 

### Preconditions

1. Setup Mandrill
2. Enable and set all Magento configuration

### Steps to reproduce

1. Create a new order
2. Wait for Cron to process email queue

### Expected result

1. Email sent out via Mandrill

### Actual result

1. Email sent out via server, if statement to check if mandrill is enabled is not passed and therefore Zend_Mail is used as the mailer instead.

**Comment by Santiagoebizmarts** [comment]
Hello @josh-carter 

This looks like a configuration problem. Please contact our support at mailchimp@ebizmarts-desk.zendesk.com.

Regards.
