### ISSUE TITLE
Are there any manual actions to make after (before) upgrading to 1.1.12?

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#724]
https://github.com/mailchimp/mc-magento/releases/tag/1.1.12

Are there any manual actions to make after (before) upgrading to 1.1.12?

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
There are no change in the file names therefore there should not be any problem.

Regards.

**Comment by seansan** [comment]
​​
​no resend all customers?
no reset all data?
others?​

**Comment by Santiagoebizmarts** [comment]
Nope
