### ISSUE TITLE
Synced status not reporting correctly in orders grid

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento#726]
mc-magento 1.1.12

Local value on mailchimp_ecommerce_sync_data not saving correctly in this version, synced orders save 0 or null so they will be displayed as "Not Synced" or "In queue".

**Comment by seansan** [comment]
Thanks for logging

Was this version tested!?

**Comment by ebizmarts-keller** [comment]
The enhancements and bug fixes in the changelog were tested for this version, but this is something that wasn't touched in this version so it went unnoticed, it doesn't affect the functionality of the extension because it is only a local value, if you are using this version I recommend you to disable "Display on order grid" in the settings until 1.1.12.1 is released, we'll make it ready as soon as possible.

Regards

**Comment by seansan** [comment]
How about adding regression testing?

In the last version there was also a very simple error that could be easily
spotted

Another option is to release a beta two weeks in advance

But I would recommend testing for this “official ” MailChimp extension
