### ISSUE TITLE
No Double Opt-in Option for MailChimp for Magento

### ISSUE THREAD

**Issue by jessiebrown** [mailchimp/mc-magento#727]
MailChimp for Magento will automatically add contacts customers as either transactional or subscribed based off the customer's marketing settings during checkout. Users who are concerned about remaining GDPR compliant would like the ability to have customers opt-in via the confirmation emails.

### Preconditions
1. Magento Version 1.9.2.4 CE, PHP 5.6.26, MySQL 5.6.29

### Steps to reproduce
1. Purchase is made in store
2. Depending on the settings in the integration for "Subscribe all customers to the newsletter", the subscriber is either made Subscribed or Transactional
3. User never has an opportunity to double opt in to the list when making a purchase.
////
1. Cart is abandoned in the store
2. Depending on the settings in the integration for "Subscriber all customers to the newsletter", the subscriber is either made Subscribed or Transactional
3. User abandoning the cart is never given an opportunity to double opt into the list WHEN there is a situation in which they would be subscribed to the list.

### Expected result
1. Allow users to double opt in to the list

**Comment by ljay79** [comment]
I can confirm. The option to have such customers subscribe with status "pending" like it is implemented for regular plain newsletter subscriptions is not existing as part of the _newOrder_ event observer.
