### ISSUE TITLE
Auto-Translated MC emails and forms are not working

### ISSUE THREAD

**Issue by ljay79** [mailchimp/mc-magento#729]
Using this extension with Magento there is no way to preset the subscriber language within Mailchimp.
Therefor any opt-in confirmation email or other automations like the "Abandoned Cart Notification" provided by Mailchimp with "Auto-translate" active will not work - they will always be sent in the default MC language (usually english).

a) This extension does not provide any option to set a (default) language of a subscriber neither does it set the mailchimps "Language" value for any profile

b) Even if, mailchimp would ignore that setting as it fully relies on a user browser detection solely and ignoring the value set in a subscribers profile "Language". This has been tested by extending this module and setting the "language" field during signup. Mailchimp themself confirmed us, they do not use this value for such cases but rely on the browser detection. Which wont work with API signups.

### Preconditions
1. Magento Version 1.9.3.8 CE, PHP 7.0.27
2. Mailchimp4Magento Version 1.1.12
3. Ensuring the subscribers profile field "language" is set appropiatly during signup via API.

### Steps to reproduce
1. Enable Double-Opt-In on your MC list
2. Go to non-english shop of yours (sample: "german" shop)
3. Signup for the newsletter
4. Wait for the opt-in confirmation email sent from mailchimp

### Expected result
1. "Language" field in Mailchimp profile is set to "German"
2. Opt-In Confirmation email received by user is in german

### Actual result
1. "Language" field in Mailchimp profile is set to "not yet detected"
- 1a. With our customization this field is actually set to "German"
2. Opt-In Confirmation email is always in english - regardless of MC or Profile settings

**Comment by ljay79** [comment]
Maybe this (workaround) provided here on [StackOverflow](https://stackoverflow.com/questions/13178685/possible-to-provide-a-subscribers-language-through-mailchimp-api) could help solving the issue with MC not being able to "detect" browser language during a API signup process.

**Comment by Santiagoebizmarts** [comment]
Hello @ljay79 

Unfortunately there is a limitation in what can be translated. The solution you provided does not work because the form mentioned is not used in the extension.
Also the MailChimp stores used in Automations don't support multi-language setups.
The recommended set for this is using different lists for each language.

Regards.

**Comment by ljay79** [comment]
Hi @Santiagoebizmarts 

Sry, but this isnt entirly true.
I will provide a PR soon.

For sure i was able to have new subscribers receive a Opt-In confirmation email in the actual language of the user / store rather than the MC default language. It requires a few small enhancements of the mailchimp extension but they are really trivial...

**Comment by ljay79** [comment]
Just opend a PR #730 ... hope you like it and hope it actually complies with your guidelines :)
