### ISSUE TITLE
Multistore pulling in default store url for links

### ISSUE THREAD

**Issue by willwright111** [mailchimp/mc-magento#734]
Preconditions
1. Magento 2.2.3
2. Module version 1.0.29

Steps to reproduce
1. Setup 1 Magento install with multiple website views
2. Install Mailchimp Module
3. Configure Mailchimp Module 
4. Sync catalog from Magento to Mailchimp
5. Go to create a campaign in Mailchimp the url links to the products are for the default website not the specified website.

Expected result
1. Links in mailchimp to products in website 1 link to website 1
2. Links in mailchimp to products in website 2 link to website 2

Actual result
1. All links from products in mailchimp go to the default website rather than the website the products are from

**Comment by Santiagoebizmarts** [comment]
Hello @willwright111 

Thanks for your feedback.
This repo is for the Magento 1 extension. You can find the Magento 2 repo at https://github.com/mailchimp/mc-magento2

Regards.
