### ISSUE TITLE
Unparsed variable sent as domain to mailchimp

### ISSUE THREAD

**Issue by Poggen** [mailchimp/mc-magento#735]
### Preconditions
Magento version 1.9.3.8
MC-magento version 1.1.12

### Steps to reproduce
1. Create a new store by configuring the module in local configuration scope for domain1.com
2. Try creating another store by configuring the module in local configuration scope for for domain2.com
3. Module claims a store with the same domain already exists: `A MailChimp store with the same domain already exists in this account. You need to have a different URLs for each scope you set up the ecommerce data.`.

### Expected result
A separate store should be created for for domain2.com.

### Actual result
Looking at the response of the stores endpoint using Mailchimp's API Playground, I was able to find the cause. It seems like the variable `{{unsecure_base_url}}` is being sent to Mailchimp _unparsed_:
```
      {
         "id":"12324567899976543",
         "list_id":"1234567",
         "name":"StoreName",
         "platform":"Magento",
         "domain":"{{unsecure_base_url}}",
         "is_syncing":true,
         "email_address":"noreply@storename.com",
         "currency_code":"SEK",
         "money_format":"",
         "primary_locale":"sv_SE",
         "timezone":"Europe/Stockholm",
         "phone":"123456789",
         "address":{
            "address1":"",
            "address2":"",
            "city":"",
            "province":"",
            "province_code":"",
            "postal_code":"",
            "country":"",
            "country_code":"",
            "longitude":0,
            "latitude":0
         },
        [...]
       }
```
Thus, when the second configuration tries to create its store using the same unparsed variable name, the duplicate domain error is being thrown. The `getStoreDomain`-function responsible for getting the storeName is being called as a part of the `createMailChimpStore` here: https://github.com/mailchimp/mc-magento/blob/7819a0a822f769c856480143c39c50d7dc315d49/app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php#L25-L66.

**Comment by Santiagoebizmarts** [comment]
Hello @Poggen 

This work okay in all the stores I've seen.
Is there any particular configuration you are using that might affect how that setting is handled?

Can you tell me what version of php do you have installed?

Regards.

**Comment by Poggen** [comment]
5.5

**Comment by Poggen** [comment]
We're applying a workaround while this bug persists by manually setting `web_unsecure_base_link_url` to the actual url of the site instead of using the `{{unsecure_base_url}}` variable. When retrying the store creation using this setting the correct value was passed. This is not very optimal, though – you should look into getting this fixed.

**Comment by Santiagoebizmarts** [comment]
@Poggen This might be a problem with the PHP version. I will test this with PHP 5.5 to confirm the bug but I suggest you to run the extension with 5.6 to be as safe as possible.

**Comment by Poggen** [comment]
We're seeing the same issue on another installation which is running on 7.1, so I doubt the php version is the error at hand here.

**Comment by Santiagoebizmarts** [comment]
Hello @Poggen 

We've find the cause of this issue. The problem seems to be when setting up the extension in a website level.
There is a fix already applied at https://github.com/mailchimp/mc-magento/commit/83eea4c4f9562310aaacd270c49f403132452640

Regards.
