### ISSUE TITLE
Ecommerce data saving in website and store scopes

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#74]
Hi there!
Ecommerce settings are not visible in store and website scopes:

**app/code/community/Ebizmarts/MailChimp/etc/system.xml** (lines 166-169)

```xml
<show_in_default>1</show_in_default>
<show_in_website>0</show_in_website>
<show_in_store>0</show_in_store>
```
But there is no any check while data saving in the backend:

**app/code/community/Ebizmarts/MailChimp/Model/System/Config/Backend/Apikey.php** (lines 17-18)

```php
        $groups = $this->getData('groups');
        $active = $groups['ecommerce']['fields']['active']['value'];
```

So i got the error while saving settings on website scope:

> An error occurred while saving this configuration: Notice: Undefined index: ecommerce in app/code/community/Ebizmarts/MailChimp/Model/System/Config/Backend/Apikey.php on line 18

Hope you help with this issue or give an advice how to set up settings on website scope the best way.

Regards, Nikolay.

**Comment by grafikchaos** [comment]
This is still an issue in 1.1.5
