### ISSUE TITLE
Different API from one createad on mailchimp account

### ISSUE THREAD

**Issue by filimm** [mailchimp/mc-magento#746]
### Preconditions
1.1.13
Magento 1.9.3.4 

### Steps to reproduce
1. Get API credentials

### Expected result

1. Get API key I've created on my mailchimp account

### Actual result

1. I'm getting a different API key. The worse is that is working but I swear I don't have this API key created on my mailchimp account.
2. Is generating all comon errors like:

A MailChimp store with the same domain already exists in this account. You need to have a different URLs for each scope you set up the ecommerce data. Possible solutions HERE and HERE

Looks like your MailChimp store was deleted. Attempting to create a new one.

**Comment by Santiagoebizmarts** [comment]
Hello @filimm 

This is not a problem, it's a feature. MailChimp creates a special API key for Magento allowing the subscribers to go with the correct source. If you use a custom API key you created the source will be API - Generic but with this one it will show Magento as the source.

About the error message you mention, it is not related to the API key.
The problem there seems to be that you are configuring two different scopes with the same domain.
You can see information related to this, explaining how to approach each possible scenario at [https://ebizmarts.com/forums/topics/view/28025](https://ebizmarts.com/forums/topics/view/28025)

Regards.
