### ISSUE TITLE
Send products with no description available

### ISSUE THREAD

**Issue by ebizmarts-keller** [mailchimp/mc-magento#747]
Magento provides the posibility to make certain product attributes not mandatory, one of this is the product description. When a product has no description, the function returns false and we send this value to Mailchimp instead of a string. The Mailchimp API returns an error because this value must be a string and receives a boolean in this case, nevertheless this field is not mandatory in the API.

### Preconditions
Magento 1.x
mc-magento 1.1.12

### Steps to reproduce
1. Make "Description" field not mandatory
2. Create products with this field empty

### Expected result
Product synced to Mailchimp without description

### Actual result
A boolean value is sent on the description, the Mailchimp API rejects it with the following error:

_description : Schema describes string, boolean found instead_

**Comment by Leland** [comment]
Note that this happens with descriptions set to 0 (zero). false may work as well
