### ISSUE TITLE
when subscribed non customer registers do not update/sync the new data

### ISSUE THREAD

**Issue by alejandromartincruz** [mailchimp/mc-magento#750]
If a non registered customer, that is NOT previously subscribed to the newsletter, creates a new account and checks subscribe to newsletter all the data (address, phone, gender, etc..) is synced with mailchimp list.

If a non registered customer subscribes to the newsletter with the footer form, it only provides the email, and only the email is synced with mailchimp list.

If this non registered customer, that is already subscribed to the newsletter, creates a new account providing all the data as the address, the phone, etc this data won't update even if the customer checks the subscribe to newsletter checkbox  again.

I also see that if a subscribed customer with an account edit some data, it is synced with mailchimp list correctly. But if this customer edits the address, the new address is not updated in the mailchimp list. If this customer that has modified the address, changes another kind of customer data, then the new data and the address is updated in mailchimp. 

I see in the Observer the function customerSaveBefore(Varien_Event_Observer $observer) that is considering new customers that are subscribed previously

`//update subscriber data if a subscriber with the same email address exists
            $apiSubscriber->update($customerEmail, $storeId);`

EDIT 1:
Well, I found that model/api/Subscribers.php on updateSubscriber function is getting the previous customer data in the $mergeVars.

If I have 'street 1' and I edit it to 'another street', I have 'street 1' in the merge vars. If I update it again to 'a completely new street 3', then I see in the $mergeVars address the 'another street'. 
Maybe because it is a beforesave event and it has yet the previous data?

EDIT 2: I solved it:
to save the last address I had to change the event observer:
`<customer_address_save_before>
                <observers>
                    <mailchimp_save_before_address>
                        <type>model</type>
                        <class>mailchimp/observer</class>
                        <method>customerAddressSaveBefore</method>
                    </mailchimp_save_before_address>
                </observers>
            </customer_address_save_before>`
to

`<customer_address_save_after>
                <observers>
                    <mailchimp_save_after_address>
                        <type>model</type>
                        <class>mailchimp/observer</class>
                        <method>customerAddressSaveAfter</method>
                    </mailchimp_save_after_address>
                </observers>
            </customer_address_save_after>`

And to sync the data of a subscribed non customer data when creates an account I had to add an event observer with customer_register_success that goes to customerSaveBefore method. And in the method, I added:

`$subscriber = Mage::getModel('newsletter/subscriber')->loadByEmail($customer->getEmail());
            if ($subscriber->getId()) {
                Mage::getModel('mailchimp/api_subscribers')->updateSubscriber($subscriber, true);
            }`
under the 'if ($isEnabled) {'

**Comment by Santiagoebizmarts** [comment]
This is solved in the latest version.
The update is made at https://github.com/mailchimp/mc-magento/blob/1.1.14/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L259

Kind Regards.
