### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Mandrill_Message' not found 

### ISSUE THREAD

**Issue by dgitman** [mailchimp/mc-magento#762]
### Preconditions
1. Magento 1.9.3.8,
2. Tag 1.1.12
3. PHP 7.0.30
4. MySQL 5.6.10

### Steps to reproduce
1. Log into Magento admin
2. Navigate to System -> Config -> Mandrill 

### Expected result
1. I should see the Mandrill config page

### Actual result
1. Fatal error: Uncaught Error: Class 'Mandrill_Message' not found in /srv/public_html/app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Userinfo.php:40 Stack trace: #0 /srv/public_html/app/code/core/Mage/Core/Model/Config.php(1357): Ebizmarts_MailChimp_Model_System_Config_Source_Userinfo->__construct(Array) #1 /srv/public_html/app/Mage.php(471): Mage_Core_Model_Config->getModelInstance('mailchimp/syste...', Array) #2 /srv/public_html/app/Mage.php(485): Mage::getModel('mailchimp/syste...', Array) #3 /srv/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(449): Mage::getSingleton('mailchimp/syste...') #4 /srv/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element)) #5 /srv/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Ob in /srv/public_html/app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Userinfo.php on line 40

**Comment by Santiagoebizmarts** [comment]
Hello @dgitman 

This looks like a problem with your folder permissions or maybe some files were not correctly sent to your Magento installation.
I suggest you to verify that the file at **lib/Mandrill/Message.php** actually exists in your server.

If the file exists and have the correct permissions I suggest you to contact us to mailchimp@ebizmarts-desk.zendesk.com

Regards.
