### ISSUE TITLE
Promo rules "already exists" error causing endless resyncing

### ISSUE THREAD

**Issue by ericwkchan** [mailchimp/mc-magento#769]
I've noticed an issue that prevents promo rules from being syncing successfully. When there is an "already exists" error for promo rules, the module will mark the mailchimp_sync_modified to 1 in the mailchimp_ecommerce_sync_data for that promo rule :

https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L601

`mailchimp_sync_error: Invalid Resource : A promo rule for store with the id '190' already exists.`

This causes the promo rule to resync endlessly and no progress is made.

In addition, updating the promo rule and checking out with a promo rule deletes the rule and causes the endless resync again. The promo codes don't seem to be resyncing however. N

In order to get promo rules syncing into Mailchimp as a short term solution, we've had to monkey patch this extra condition on here https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L601

`if (strstr($errorDetails, 'already exists') && $type !== 'PRL')` instead of just `if (strstr($errorDetails, 'already exists'))`

Please advise on a more long term solution.

**Comment by Santiagoebizmarts** [comment]
Hello @ericwkchan 

Sorry for the delay on this.
The fact that the promo rules is flagged as modified will cause a different endpoint to be called in the next time therefore the already exists error will not show up again.
We've found a different problem that was causing some elements to be removed incorrectly from the **mailchimp_ecommerce_sync_data** table. I believe this was causing the error you mention.

Regards.
