### ISSUE TITLE
Abandoned cart in sales order grid

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#77]
Hi there!

The "Cart Recovered" column is added in Sales Order Grid despite of Abandoned Cart is disabled.
It's processing in **Ebizmarts_MailChimp_Model_Observer::addAbandonedToSalesOrderGrid**.
May be it would be better if there will be some kind of check for module is enabled and if it's disabled the column mustn't be added?

Thanks

**Comment by gonzaloebiz** [comment]
Hi @elluminatte thanks for your feedback.
You are wright, good idea, thanks

**Comment by Santiagoebizmarts** [comment]
Hello @elluminatte 

Actually that field is also used for purchases made from MailChimp campaigns so if you have the MailChimp sync enabled that field should be seen as well.
This checks will be added for the next release.

Thanks for your feedabck!

**Comment by elluminatte** [comment]
thnx guys :+1:

**Comment by elluminatte** [comment]
guys, one more question: what do you think about implementing some kind of setting to show or not to show this column? we don't have any data in this column at all, and it's always empty...
we don't want to subscribe to the same event as you and remove this column after you have just added it

**Comment by Santiagoebizmarts** [comment]
Hello,

This will be taken in consideration. It might be added for version 1.1.3. Version 1.1.2 is already set so I don't thing we will be adding anything else at this point.

Regards.

**Comment by Santiagoebizmarts** [comment]
You can remove it yourself commenting [this code](https://github.com/mailchimp/mc-magento/blob/master/app/code/community/Ebizmarts/MailChimp/etc/config.xml#L185-L189).

**Comment by elluminatte** [comment]
So if we commented this code we will not be able to update your plugin, so i think it's not right way. Thank you!

**Comment by Santiagoebizmarts** [comment]
Hello @elluminatte 

We concluded this will not be removed. We want our users to know when a purchase was made thanks to a campaign.

Regards.
