### ISSUE TITLE
"No MailChimp Store Was Created for This Scope" Error when Installing or Updating MailChimp for Magento

### ISSUE THREAD

**Issue by hillary-bridges** [mailchimp/mc-magento#776]
Certain users are receiving the "No MailChimp Store Was Created for This Scope" error on the Magento store's default configuration when attempting to install or update MailChimp for Magento to version 1.1.11-1.1.12. Because this error is appearing at the default configuration, users are unable to successfully sync their Magento store with their MailChimp account.

**First Example Report**
Magento Version: v1.1.12
store_id referenced in batches: 8157bcaaf20d0a170d740d8f38293cf3
store_id actually created: 7ca09d1461c48e7ac440c1bb82e6c924

A store is getting created on our end, but the POST to /batches are referencing a different store_id that hasn't existed in the account.

Errors Thrown:
"A MailChimp store with the same domain already exists in this account. You need to have a different URLs for each scope you set up the ecommerce data." error AND the "No MailChimp store was created for this scope" showing on the default configuration page.

**Second Example Report**
Magento Version: v1.1.12
User is getting multiple errors, but there is no dupe on the account. When fully disconnected it is reflected as disconnected on MailChimp's backend, however once re-enabled the following errors occur:

1)A MailChimp store with the same domain already exists in this account. You need to have a different URLs for each scope you set up the ecommerce data. Possible solutions HERE and HERE

2)Looks like your MailChimp store was deleted. Attempting to create a new one.

3)No MailChimp store was created for this scope, parent scopes might be sending data for this store anyways.  You can create a new MailChimp store for this scope by configuring a new list for this scope.

**Steps to Reproduce**

1. Install (v 1.1.11 or 1.1.12) version of the Mailchimp extension.
2. Insert API key in admin panel in MailChimp and enable it
3. Error displays on MailChimp integration page and Manage Products page

**Expected result**

No errors should be thrown, and store should be connected successfully.

**Actual result**

![4435440](https://user-images.githubusercontent.com/40395610/44423872-40a29480-a555-11e8-90cd-4b40e981086d.jpeg)

Example Error Logs:
2018-04-12T09:58:07+00:00 DEBUG (7): SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'type'

2018-04-12T10:18:37+00:00 DEBUG (7): Bad Request for Api Call: ecommerce/stores - We were unable to process the request. A store with the domain https://www.jplennard.com/ already exists in the account.

2018-04-12T10:18:42+00:00 DEBUG (7): Resource Not Found for Api Call: ecommerce/stores/0d394798e07c677fa67e89ce4a4db95a\?fields=connected_site - The requested resource could not be found.

2018-04-12T10:18:47+00:00 DEBUG (7): Resource Not Found for Api Call: ecommerce/stores/0d394798e07c677fa67e89ce4a4db95a\?fields=connected_site - The requested resource could not be found.

2018-04-12T10:18:48+00:00 DEBUG (7): Resource Not Found for Api Call: ecommerce/stores/0d394798e07c677fa67e89ce4a4db95a\?fields=connected_site - The requested resource could not be found.

2018-04-12T10:19:01+00:00 DEBUG (7): Resource Not Found for Api Call: ecommerce/stores/0d394798e07c677fa67e89ce4a4db95a\?fields=connected_site - The requested resource could not be found.

**Comment by ebizmarts-keller** [comment]
Hello, 

Please see the following guide explaining why this error happens and how to resolve it: https://ebizmarts.com/forums/topics/view/28025

At the moment that is the only way to handle this, we are working in a way to handle much better the stores to avoid this kind of errors completely (similar to the system we have in the Magento 2 version), but I'm afraid there is no ETA for this, it will be in no less than a couple of versions ahead.

**Comment by Santiagoebizmarts** [comment]
@hillary-bridges 
This errors are caused due to the automated store creation. We have not been able to identify why this happens exactly.
As @ebizmarts-keller said, we are currently working in a form to create the store manually in the same way it can be done for MailChimp For Magento 2. This will solve that problem and hopefully it will add a better customer experience for the initial extension configuration.

Regards,
Santiago.

**Comment by hans2103** [comment]
Hi there... any progress on this issue?

**Comment by Santiagoebizmarts** [comment]
Hello @hans2103 
We are currently working on a feature to imitate how the extension for Magento 2 works on the store creation process.
This is a manual process where the Store owner can carefully choose each store field and avoid any automatic process in creation and deletion of the store.
You can see this issue at https://github.com/mailchimp/mc-magento/issues/652

Kind Regards.
