### ISSUE TITLE
What does the MailChimp column in the orderview overview mean?

### ISSUE THREAD

**Issue by GeekMediaDK** [mailchimp/mc-magento#78]
What does the MailChimp icon by some of my orders mean? If i hover the mouse over it says "hep hep thanks MailChimp"

**Comment by gonzaloebiz** [comment]
Hi @GeekMediaDK,

thanks for your feedback.
Please, if you have doubts don't use the issue system, you can put your question at http://ebizmarts.com/mailchimp-for-magento-support

Best
