### ISSUE TITLE
Possible mysql speedimprovement for next verstion, table mailchimp_sync_batches quickwin

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#784]
Possible mysql speedimprovement

Add index to mailchimp_sync_batches

# EXPLAIN /*!50100 PARTITIONS*/
SELECT `main_table`.* FROM `mailchimp_sync_batches` AS `main_table` WHERE (`status` = 'pending') AND (`store_id` = 'codehere')

![image](https://user-images.githubusercontent.com/652395/44776976-a99f9300-ab79-11e8-8dd7-12074b01d319.png)

This query was accounting for 10% msql time, after adding the index 0%

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
I agree this can be improved. Adding a date and deleting old entires might be a good idea as well.

Regards.

**Comment by seansan** [comment]
Thx: we applied this improvement in 2018 ;P

good to hear it was found
