### ISSUE TITLE
Lost orders when Mandrill is down

### ISSUE THREAD

**Issue by maximehuran** [mailchimp/mc-magento#788]
https://github.com/mailchimp/mc-magento/blob/b92f7b29083bc80a89d4974de4cd6bd9c7d46df4/app/code/community/Ebizmarts/MailChimp/Model/Email/Template.php#L233

```php
try {
            return $mail->senders->domains();
        } catch (Mandrill_Error $e) {
            return [];
        }
```

**Comment by centerax** [comment]
theres a related PR #787
