### ISSUE TITLE
Not all completed orders are synced to MailChimp E-Commerce data

### ISSUE THREAD

**Issue by GeekMediaDK** [mailchimp/mc-magento#79]
A few of my orders does not get synced to MailChimp. It's not many, but a few here and there.

**Comment by GeekMediaDK** [comment]
I can also see on some of my order in the database that there is an MailChimp Error: Bad Request : A product with the provided ID does not exist in the account for this list.

Is this because some of the products where synced to MailChimp with a different module? And how can i get it to reload all the products, because these purchased products are used to create segmented newsletters

**Comment by gonzaloebiz** [comment]
Hi @GeekMediaDK 

thanks for your feedback.
Please follow this directions https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines to report an issue.

Best
