### ISSUE TITLE
When is 1.1.13 released?

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#790]
When is 1.1.13 released?

There have been numerous bug reports, grids not working anymore, serious performance issues

When will 1.1.13 be released ... and twill this be tested before release (for example testing the grids)

THANKS!!

**Comment by gonzaloebiz** [comment]
If you have questions, please send an email to mailchimp@ebizmarts-desk.zendesk.com

**Comment by seansan** [comment]
It would have been much easier to respond here for the whole community to
see
