### ISSUE TITLE
Bad requesr for Api Call: ecommerce/stores. We were unable to process the request. A store with the domain already exists in the account.

### ISSUE THREAD

**Issue by elisongit** [mailchimp/mc-magento#794]
### Preconditions
1. Magento CE 1.9.0
2. **Magento has 2 stores** (https://staging.project.it and https://other.staging.project.it)
2. Mailchimp for Magento version 1.1.12 (first installation in this project)
3. Account Mailchimp: **Plan Forever Free**

### Steps to reproduce
1. Installed module from composer
2. Configurated the module following the operations in section "Module Configuration" at link https://github.com/mailchimp/mc-magento

### Expected result
1. Magento connect and sync subscribers, orders, products ecc

### Actual result
1. Log Mailchimp:
_Bad Request for Api Call: ecommerce/stores - We were unable to process the request. A store with the domain https://staging.project.it/ already exists in the account.

Bad Request for Api Call: ecommerce/stores - We were unable to process the request. A store with the domain https://other.staging.project.it/ already exists in the account.
_ 

2. Error visibile in default config 
_A MailChimp store with the same domain already exists in this account. You need to have a different 
URLs for each scope you set up the ecommerce data. _

3. Error is visible in Module config (only in scope store):
_No MailChimp store was created for this scope, parent scopes might be sending data for this store anyways.
You can create a new MailChimp store for this scope by configuring a new list for this scope._

**Comment by Santiagoebizmarts** [comment]
Hello @elisongit 

Looks like you are in the scenario 3 of the following post: [https://ebizmarts.com/forums/topics/view/28025](https://ebizmarts.com/forums/topics/view/28025)

You can find the solution there. If you have problems with that process please contact us at mailchimp@ebizmarts-desk.zendesk.com where we can help you with any problem you find in this process.

Regards.
