### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by sprankhub** [mailchimp/mc-magento#795]
The [latest release 1.1.12 is 109 commits behind develop](https://github.com/mailchimp/mc-magento/compare/1.1.12...develop). When can we expect a new release?

**Comment by Santiagoebizmarts** [comment]
Hello @sprankhub 

The testing team is currently working in the Magento 2 version.
The Magento 1 version will start being tested right after this.
Usually the testing takes 1 week +/-

Regards.

**Comment by hans2103** [comment]
@Santiagoebizmarts Any progress on this one?

**Comment by Santiagoebizmarts** [comment]
Hello,

We are waiting for the testing team to finish. For the github release it usually don't take more than two weeks.

Regards.

**Comment by hans2103** [comment]
just released: https://github.com/mailchimp/mc-magento/releases/tag/1.1.13
case closed
