### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by centerax** [mailchimp/mc-magento#796]
### Reference
> https://inchoo.net/magento/magento-1-official-php-7-2-patches/

Magento released patches to make all Magento 1 versions compatible with PHP 7.2.
As of today (14/9/18) only patches for CE can be downloaded here https://magento.com/tech-resources/download, Magento Open Source Patches - 1.x section.

We should start testing this with the latest CE with the patch installed and see how the extension behaves.

**It seems Magento CE 1.9.3.9 does not require patches, so installing this version and PHP 7.2 and test the extension seems to be like the easiest path.**

### Preconditions

1. Magento version: 1.9.3.9
2. Module version: Any.

### Steps to reproduce

1. Install [Magento CE 1.9.3.9](http://ebizmartsbackup.s3.amazonaws.com/magento-1.9.3.9.tar.gz) 
2. Apply [patch](http://ebizmartsbackup.s3.amazonaws.com/PATCH-1.9.3.1-1.9.3.9_PHP7-2018-09-13-08-01-43.2_v2) 
3. Run manual and automatic tests.

### Expected result

1. Everything works as it should.

**Comment by Santiagoebizmarts** [comment]
Solved in #763
