### ISSUE TITLE
Had to reset store according to MC support: because product data sync set was 20x larger than the # articles in our store

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#801]
Had to reset store according to MC support: because product data sync set was 20x larger than the # articles in our store. 

The problem is that product syncing is doing something strange. According to MC there were multiple the same products in our database leading to gigantic datasets. No idea why. Also it seems to be searching for simple products instead of the parents images.

### Preconditions
1. M1936, MC

### Steps to reproduce
1. Based on MC support followed https://mailchimp.com/help/connect-or-disconnect-mailchimp-for-magento/#Configure_and_Connect
2. Click disconnect as also advised by support; then there is a MC gateway error
3. Try to reconnect by resetting ecommerce data
4. In Mailchimp we cannot reconnrect we only see waiting for connections

### Expected result
1. Delete all product data in MC
2. Resend all correct product data again from M to MC

### Actual result
1. Not working
ps the 2 HERE and HERE links are not applicable

![image](https://user-images.githubusercontent.com/652395/46246907-5f256680-c404-11e8-879d-2c9e639531bb.png)

![image](https://user-images.githubusercontent.com/652395/46246936-a7dd1f80-c404-11e8-9490-7c211af140c3.png)

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

I think Scenario 3 -> Method 3 of the following guide is the solution for you. If you are not able to get around that error with it please contact our support.

Regards.

**Comment by seansan** [comment]
thanks

this sounds very very invasive

should mailchimp not do this? I mean we disconnected using their UI

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

The store is no longer associated to your Magento. It is an error in the extension that will be fixed in the next release.

Kind Regards.

**Comment by seansan** [comment]
btw thanks I did use postman

but our reply from API is not a whitescreen

but rather

The server encountered an internal error or misconfiguration and was unable
to
complete your request.

**Comment by Santiagoebizmarts** [comment]
mailchimp@ebizmarts-desk.zendesk.com
