### ISSUE TITLE
description : Schema describes string, boolean found instead

### ISSUE THREAD

**Issue by jorgb90** [mailchimp/mc-magento#81]
<img width="771" alt="schermafbeelding 2016-10-17 om 23 40 55" src="https://cloud.githubusercontent.com/assets/7294081/19456752/36a892b2-94c3-11e6-8e32-a8104976e497.png">

**Comment by gonzaloebiz** [comment]
Hi @jorgb90,

thanks for your feedback.
Please read this steps to report an issue.
https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines

Best
