### ISSUE TITLE
Growing DB Table `mailchimp_webhook_request`

### ISSUE THREAD

**Issue by sprankhub** [mailchimp/mc-magento#812]
The DB table `mailchimp_webhook_request` grows extremely.

### Preconditions
1. Magento 1.9.3.10
2. Ebizmarts_MailChimp 1.1.12

### Steps to reproduce
1. Simulate a high traffic shop, which leads to more than 200 webhook requests per day, which get logged to the table `mailchimp_webhook_request`.

### Expected result
1. Cronjob `mailchimp_delete_webhook_processed` cleans all webhook requests older than 30 days.

### Actual result
1. Cronjob `mailchimp_delete_webhook_processed` only cleans 200 webhook requests each day.
2. The DB Table `mailchimp_webhook_request` grows and grows and grows and ...

**Comment by sprankhub** [comment]
Current workaround is to execute something like

    while true; do n98-magerun.phar sys:cron:run mailchimp_delete_webhook_processed; done

manually and kill the script when the table size does not change any more.

**Comment by sprankhub** [comment]
Faster workaround is a simple MySQL query:

    DELETE FROM `mailchimp_webhook_request` WHERE `fired_at` < NOW() - INTERVAL 30 DAY AND `processed` = 1;

**Comment by centexdabull** [comment]
Why does this extension suck so badly?

**Comment by Santiagoebizmarts** [comment]
Thanks for your feedback @sprankhub 
We will make that change and probably set the cron to run every hour for big stores that have a lot of traffic.

**Comment by ebizmarts-keller** [comment]
Solution in: https://github.com/mailchimp/mc-magento/issues/818
