### ISSUE TITLE
Issue about Ecommerce360 Integration

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#82]
Hi there!

I don't see any ecommerce data (orders for example) in my Mailchimp account.
Orders data doesn't fetch because of **$syncDelta** is false in **Ebizmarts_MailChimp_Model_Api_Orders::GeneratePOSTPayload**

What i'm doing wrong and what i should do orders to be sent in mailchimp ecommerce data?

Regards, Nikolay.

**Comment by elluminatte** [comment]
Guys, it's very important.
Have you ever challenged with similar problem?

**Comment by gonzaloebiz** [comment]
Hi @elluminatte,

thanks for your feedback.
Please read [this](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) and put your issue according

Best
