### ISSUE TITLE
1.1.12 "Display on order grid" also hides Ebizmarts_MailChimp_Block_Adminhtml_Sales_Order_View_Info_Monkey

### ISSUE THREAD

**Issue by fballiano** [mailchimp/mc-magento#826]
I just upgraded to 1.1.12 and setting  "Display on order grid" to "none" also hides the Ebizmarts_MailChimp_Block_Adminhtml_Sales_Order_View_Info_Monkey block from within the order detail mask, which I think shouldn't.

**Comment by ebizmarts-keller** [comment]
The behavior is correct, there are 4 settings, "None" doesn't show anything, "Both" shows both columns, then you can chose to display only one of the 2 columns.

![screen shot 2018-11-26 at 3 09 28 pm](https://user-images.githubusercontent.com/19838935/49033308-8c389000-f18d-11e8-85e5-2eefab520aca.png)

**Comment by fballiano** [comment]
that's now what I said... I understand that that hides the column, but it also hides the Ebizmarts_MailChimp_Block_Adminhtml_Sales_Order_View_Info_Monkey block from the order detail! that's the issue!

**Comment by fballiano** [comment]
and by "order detail" I mean "sales_order/view/order_id/xxxxx", not the order grid as you understood

**Comment by ebizmarts-keller** [comment]
I'm sorry I misunderstood, this is controlled here: https://github.com/mailchimp/mc-magento/blob/1.1.12/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L428

If you remove $addColumnConfig from the if statement it will work, for some reason it was made this way on purpose so I will consult the developer on this anyway next week.
