### ISSUE TITLE
1.1.12 "Display on order grid" breaks the grid

### ISSUE THREAD

**Issue by fballiano** [mailchimp/mc-magento#827]
Hi,
after upgrading to 1.1.12 I set the "Display on order grid" to "Icon for mailchimp orders" and suddenly the order grid show just a few records (around 1 page of records"), when I reset the "Display on order grid" the orders show up correctly

**Comment by ebizmarts-keller** [comment]
Hello, 

This can't be reproduced in a vanilla Magento with 1.1.12 I'm afraid, you can see the following issues for reference:

https://github.com/mailchimp/mc-magento/issues/725 (try applying commit in this issue)
https://github.com/mailchimp/mc-magento/issues/751

For further assistance send a support request to mailchimp@ebizmarts-desk.zendesk.com
