### ISSUE TITLE
JS Errors - <params>async</params>

### ISSUE THREAD

**Issue by posttechguy** [mailchimp/mc-magento#828]
Async killed my implementation. 

When <params>async</params> was added to 
app/design/frontend/base/default/layout/ebizmarts/mailchimp.xml on line 8

`<params>async</params>`

It resorted the js so the skin js was above the js folder js causing jQuery to not work

and added a "1" at the end of the script tags

### Preconditions
1. Using Mailchimp 1.1.12 updated from 1.1.7
2. Js is merged on production and not on UAT, both had same issue

### Steps to reproduce
Updated code from new 1.1.12

### Expected result
1. No js errors, Mailchimp getCampaign() to run

### Actual result
1. Getting TypeError: document.observe is not a function error in Chrome console
The skin js loaded before js files and failed on js/ebizmarts/mailchimp/campaignCatcher.js line 46
    `document.observe('dom:loaded', getCampaign);`
2. other  errors that required Jquery

I see that it was added in https://github.com/mailchimp/mc-magento/issues/624

**Comment by Santiagoebizmarts** [comment]
Hello @posttechguy 

Can you elaborate on this?
I don't see anything in the "skin_js" sections that could have problems with our javascript file.
The campaignCatcher.js file is under "js", not "skin_js" so it should be loaded after everything else.

Can you point me to your site's url in order to see the error for myself and hopefully understand what is happening in this particular case?

Regards.

**Comment by Santiagoebizmarts** [comment]
Hello @posttechguy 

I will do some tests with this as I am not able to replicate your problem.
Could you try placing "defer" in stead of "async". The idea of this is to avoid wasting time when the page is being loaded, I would prefer a different solution than removing it.

Kind Regards.

**Comment by posttechguy** [comment]
Hi @Santiagoebizmarts 

Used defer and cleared the cache; the same thing happened. Yes anything to speed up Magento would be good. :0)

Kind Regards

Bevan

**Comment by posttechguy** [comment]
Hi @Santiagoebizmarts 

Can I provide you any more information on this ticket

Kind Regards
Bevan

**Comment by mindfriction** [comment]
@posttechguy Are you using Cloudflare by chance? I encountered this same problem when using Cloudflare. Specifically, Rocket Loader (Cloudflare feature) which loads all scripts async. 

For me, It seemed that when using Rocket Loader the <params>async</params> would cause issues for me, so I just had to manually remove the params and everything worked fine.

**Comment by posttechguy** [comment]
@mindfriction Yes, we are but we are not using any apps. I did the same thing by removing the async tags, and it worked. Good spotting

**Comment by leeroybrun** [comment]
Same problem here. After updating Mailchimp for Magento our whole site crashed (lots of Javascript errors, jQuery not defined, etc).

I removed the `<params>async</params>` and everything works fine again.

**Comment by Santiagoebizmarts** [comment]
Hello @leeroybrun 

Thanks for your notification.
Unfortunately we are not able to replicate this. Please note the field in the latest version is **defer** not **async**.
I suggest you to try with the latest version and see how it goes.

Regards.
