### ISSUE TITLE
Missing Ecommerce Data in Mailchimp

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#83]
Hi there!

**I use this configuration:**
1. Magento ver. 1.9.2.4
1. mc-magento 1.1.1 (challenged with this problem in 1.0.6 too)
1. Catalog products of custom type
1. Mailchimp integration configured right

**Steps to reproduce:**
1. Order product
1. Make status of order "complete"
1. Run cron task "mailchimp_bulksync_data"

**Actual Result:**
1. User is subscribed to list in Mailchimp
1. Ecommerce data is empty

**Expected result:**
1. User is subscribed to list in Mailchimp
1. There is data about user's orders in Ecommerce data in Mailchimp.

**Additional information:**
i've investigated that **$syncDelta** is false in **Ebizmarts_MailChimp_Model_Api_Orders::GeneratePOSTPayload** and processing is terminated here because of this.

I'll be happy to answer additional questions, hope you help me with this issue.

Regards, Nikolay.

**Comment by Santiagoebizmarts** [comment]
Hello @elluminatte 
This problem has been fixed in the develop branch.
Just update your Products.php file with the one [here](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php) and the product should be sent correctly.

Regards.
