### ISSUE TITLE
Mailchimp Outage Blocks Checkout

### ISSUE THREAD

**Issue by sprankhub** [mailchimp/mc-magento#830]
As you probably know, there was a [global Mailchimp outage yesterday](https://status.mailchimp.com/).

### Preconditions
1. Magento 1.9.3.10
2. Mailchimp 1.1.12
3. PHP 7.2
4. Mailchimp API not reachable

### Steps to reproduce
1. Order something in the store

### Expected result
1. Order possible without any issues

### Actual result
1. After clicking on the order button, nothing happens for a huge amount of time. It seems as if there is a synchronous call to the Mailchimp API without any timeout or whatsoever.

**Comment by ebizmarts-keller** [comment]
Hello @sprankhub 

We are aware of this issue, we already have an issue for this with a patch to add a much shorter (and configurable) timeout for when the API is down, for default set for 20 seconds and can be configured for 10 seconds as a minimum, will be available for version 1.1.13 and you can see the associated commit below as well.

https://github.com/mailchimp/mc-magento/issues/815
