### ISSUE TITLE
Stores with long domain name doesn't create properly in Ecommerce

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#85]
**Preconditions**
1. Magento ver. 1.9.2.4 Community Edition with real customers data
1. mc-magento 1.1.2 (dev) - older versions too

**Steps to reproduce**
1. Run magento site on long domain (http://9267-yjmqmd-smdoirty-ikkjuqiue.qa.mdjeurj.com for example)
1. Press Reset Ecomerce Data Button

**Actual and Expected result**
_Actual Result:_
1. Store that is actually created in Mailchimp has id 9267-yjmqmd-smdoirty-ikkjuqiue.qa.mdjeurj.com_2016
1. Store that actually saved in site config data has id  9267-yjmqmd-smdoirty-ikkjuqiue.qa.mdjeurj.com_2016_27_10_070120
1. Mailchimp API returns error that store with id 9267-yjmqmd-smdoirty-ikkjuqiue.qa.mdjeurj.com_2016_27_10_070120 is not found

_Expected Result:_
1. Store id in Mailchimp and in store config data are the same
1. Ecommerce works correctly

_The bug is here_

``` php
storeId = parse_url(Mage::getBaseUrl(), PHP_URL_HOST) . '_' . $date;
```

May be we should check that it's not longer than API limits?

Regards, Nikolay.

**Comment by gonzaloebiz** [comment]
Hi @elluminatte 

thanks for your feedback.
You are right, mailchimp limit is 50 for this field, so you can modify [this line](https://github.com/mailchimp/mc-magento/blob/master/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L296) with:
$storeId = md5(parse_url(Mage::getBaseUrl(), PHP_URL_HOST) . '_' . $date);

This fix will be available in the next release.

Best

**Comment by Santiagoebizmarts** [comment]
Make sure to have the latest version and then replace the Data.php with the one at https://github.com/mailchimp/mc-magento/blob/1a7f7684b6ef30cbadf99418ec8b2c159074c86c/app/code/community/Ebizmarts/MailChimp/Helper/Data.php

Regards.
