### ISSUE TITLE
Magento newsletter successful subscription email - not sending

### ISSUE THREAD

**Issue by ktsixit** [mailchimp/mc-magento#858]
I have installed version 1.1.5 of Mailchimp extension and have selected "Use Magento emails" to Yes.

### Preconditions
1. Magento 1.9.3.8
2. Mailchimp For Magento v1.1.15

### Steps to reproduce
1. Subscribe to Newsletter
2. Receive the "Confirm Newsletter Subscription" email
3. Click on the confirmation link 

### Expected result

1. Receive the Successful Subscription Newsletter email. (newsletter_subscription_success_email_template)

### Actual result

1. Successful Subscription Newsletter email is not sent

**Comment by Santiagoebizmarts** [comment]
Hello @ktsixit 

I don't think that is the expected behavior. Magento only sends the Success email if "Need to confirm" is disabled.
The only place where the **sendConfirmationSuccessEmail** is called is when executing the subscribe function which is not called after the confirmation.

Kind Regards.

**Comment by ktsixit** [comment]
What do you mean by not an expected behaviour? 
"Need to confirm" is enabled and Mailchimp extension should be compatible with that setting.

Two way synch is enabled for Newsletter subscription. This means that user has to receive two seperate emails. First email for validating his email. Second email for successful subscription.

Here are some screenshots from settings, that proves it:
[https://ibb.co/ZMxL004](https://ibb.co/ZMxL004)

**Comment by ktsixit** [comment]
Could you please tell me why did you close this topic, since there's an issue here? I have explained the situation above.

**Comment by Santiagoebizmarts** [comment]
Hello @ktsixit 
I closed this because Magento by default does not send a confirmation success email after the subscriber clicks in the confirm button.
The options are to send one email or the other, not both.

Kind Regards,
