### ISSUE TITLE
Date of birth is lacking year

### ISSUE THREAD

**Issue by tim-bezhashvyly** [mailchimp/mc-magento#861]
### Preconditions
1. Customer date of birth is enabled in Magento
2. Date of birth attribute MailChimp mapping is set up

### Steps to reproduce
1. Register new customer or place an order, anything which would create or update MailChimp subscriber

### Expected result
1. Subscriber full date of birth is transferred to MailChimp

### Actual result
1. Date of birth year is alway a current year (i.e. 2019)

This is caused but this code - https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php#L228

Too obvious to be a bug. Is there a reason behind it?

**Comment by Santiagoebizmarts** [comment]
Hello @tim-bezhashvyly 

This is not a bug, is a limitation form MailChimp. If the merge field is created as birthday it does not have year, if it is created as a normal date it will not work with birthday automations.
One way to have both is to leave the birthday field as it is and create a new one with name "Birthday 2" or something like that and add it with type "date".

Kind Regards.
