### ISSUE TITLE
Avoid real time calls to Mailchimp API in case it's down

### ISSUE THREAD

**Issue by alexjamesbrown** [mailchimp/mc-magento#862]
Once again, Mailchimp API was down earlier today, and once again, we see a huge spike in response times, and degredation of service to our customers using our Magento store.
WHY is the product page tightly coupled to the Mailchimp API?

This abslolutely needs resolving. We've had no choice but to disable the extension for now

Using latest version of the extension.

What gives?

/catalog/product/view is affected the most

#815 was closed, but this still happens!

![image](https://user-images.githubusercontent.com/437743/51826324-abaf7e80-22de-11e9-9d38-bb3150a6406b.png)

![image](https://user-images.githubusercontent.com/437743/51826333-b1a55f80-22de-11e9-8570-446bd3de8478.png)

**Comment by alexjamesbrown** [comment]
Front end.
Yes. 1.1.13

**Comment by Santiagoebizmarts** [comment]
Do you have any feature enabled for the Mailchimp javascript file?
For example: Pop up enabled, Product retargeting.

Kind Regards

**Comment by Santiagoebizmarts** [comment]
Did you get my last question? I want to see if the site is loading the javascript before the page has been fully loaded. This is not the expected behavior.

Regards.

**Comment by alexjamesbrown** [comment]
www.gardeningexpress.co.uk

**Comment by Santiagoebizmarts** [comment]
Hello @alexjamesbrown 

I think I was finally able to find the problem and why I was not being able to replicate it on my end.
Please let me know if this is your scenario:
When a new store is created in Mailchimp from Magento an URL is saved in the table core_config_data with the URL to a javascript file created by MailChimp.
In case there are more than one store with the same domain but different paths in your Mailchimp account. (i.e.: domain.com/en, domain.com/es)
This field will not be created as Mailchimp will not provide an URL for these cases.

This scenario can be verified by running the following query:
**SELECT * FROM core_config_data WHERE path='mailchimp/ecommerce/mc_js_url';**
One entry should be returned for every scope in Magento with a Mailchimp store associated.

Can you confirm if this was your case? Do you have more than one store view with the same domain configured?

**Comment by alexjamesbrown** [comment]
@Santiagoebizmarts yes, that's right

**Comment by Santiagoebizmarts** [comment]
The fix has been applied at https://github.com/mailchimp/mc-magento/pull/865

Thanks for your feedback!

Kind Regards.
