### ISSUE TITLE
Changing and clearing config cache during batch processing

### ISSUE THREAD

**Issue by Swahjak** [mailchimp/mc-magento#89]
Ebizmarts_MailChimp_Model_Api_Batches 98 - 100

```PHP
Mage::helper('mailchimp')->resetMCEcommerceData(true);
Mage::getConfig()->saveConfig(Ebizmarts_MailChimp_Model_Config::GENERAL_MCSTORE_RESETED, 0);
Mage::getConfig()->cleanCache();
```

This should not be there. The config in not meant for frequently changing values and clearing the cache can impact the performance of the frontend. As much as I dislike this method myself; if this value needs to be saved it should be in a database table.

**Comment by Swahjak** [comment]
Any update?

**Comment by gonzaloebiz** [comment]
Hi @Swahjak 

thanks for your feedback.
The call to Mage::getConfig()->cleanCache() don't impact in the frontend, this call only reload the config, the others caches like page blocks or eav types are not impacted.
In other hand, these values are rarely modified, so we don't see problems on there

Best

**Comment by Swahjak** [comment]
@gonzaloebiz the thing is; the cache is obviously there for a reason. Whether it directly impacts the frontend or not, values that change on a regular basis should not be in the config. Just took a quick look and this seems to happen twice during an cron cycle, which happens every 5 minutes. But maybe I'm just being nitpicky.

**Comment by gonzaloebiz** [comment]
Hi @Swahjak,

thanks for your feedback.
This call is not happen every cron cycle, this call happens only with your change the mailchimp store. I will try to explain.
In mailchimp all the ecommerce data is associated to a store, a store is associated with a list (and only with one list), this list can't be changed. So, if you change the APIKey or the list, then the old mailchimp store is deleted and a new one is created (and all the data must be re synced).  If you take a look, the call is [with a control](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php#L100), when is called? Only when you create a new mailchimp store (change the APIKey or the list) and the cron is working at the same time, so to prevent send data to an non existing store.
If you detect that the call is made every cron run, that's not the idea in the logic, and some other logic is wrong.
