### ISSUE TITLE
How can we clean the table mailchimp_ecommerce_sync_data

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#897]
### Preconditions
Use latest M1 and extension

### Steps to reproduce
1. Let it sync for some months

### Expected result
1. Not the biggest table in the whole database

### Actual result
1. mailchimp_ecommerce_sync_data is the largest M1 tablein our database with almost 2 mio rows

![image](https://user-images.githubusercontent.com/652395/53733718-2b061400-3e82-11e9-97ab-94893ff82cfd.png)

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
The size of this table should be proportional to the amount of items in your store.
In a normal usage the only data that could be removed are old quotes (carts) and old promo codes if promo codes are enabled.
Unfortunately this is not a priority right now.

**Comment by seansan** [comment]
Well it is an issue. And a result of the extension. I see more similar topics
