### ISSUE TITLE
Mailchimp client doesn't clear POST body

### ISSUE THREAD

**Issue by francescosalvi** [mailchimp/mc-magento#898]
### Preconditions

Magento EE 1.14.3.8, ebizmarts/mc-magento 1.1.15, PHP 7.0.30

### Steps to reproduce

run the following snippet

```
$api = Mage::helper('mailchimp')->getApi($scopeId, $scope);

$api->ecommerce->stores->add($mcStoreId, $listId, 'A dummy store', 'EUR', true);
$api->ecommerce->stores->get($mcStoreId, 'name,is_syncing');
$api->ecommerce->customers->getAll($mcStoreId, 'total_items');
```

### Expected result

Above code runs and no exceptions are thrown

### Actual result

last line in above snippet causes:
```
MailChimp_Error with message ' for Api Call: ecommerce/stores/[...]/customers?fields=total_items - '
```

Inspecting the curl response body (in `lib/Ebizmarts/MailChimp.php:358`) reveals:
```
<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference[...]
</BODY>
</HTML>
```

### Probable root cause

The lib client class makes use of `CURLOPT_CUSTOMREQUEST` at `lib/Ebizmarts/MailChimp.php:355`, from the official doc https://curl.haxx.se/libcurl/c/CURLOPT_CUSTOMREQUEST.html:

> Many people have wrongly used this option to replace the entire request with their own, including multiple headers and POST contents. While that might work in many cases, it will cause libcurl to send invalid requests and it could possibly confuse the remote server badly

This hints at the fact that the last GET is still sending the (un-cleared) POST body content from the first call (oddly enough this doesn't seem to affect the second call / first GET )

### Possible solutions

Don't reuse the curl handle (e.g. with `CURLOPT_FORBID_REUSE`), or better, add `curl_setopt($ch, CURLOPT_POSTFIELDS, null);` after line 344 (in the conditional branch for `$method == Ebizmarts_MailChimp::GET`)

**Comment by Santiagoebizmarts** [comment]
Hello @francescosalvi 

Thanks for helping us noticing this problem.
We will add the fix and it will be ready for the next version.

Kind Regards.
