### ISSUE TITLE
Suggestion: Different error messages for different subscription failure errors

### ISSUE THREAD

**Issue by SC-RG** [mailchimp/mc-magento#901]
### Preconditions

Zoey 2.41.14-1

### Steps to reproduce

For failed newsletter signup attempts, the same error message is given in both these cases:

1. When an email address exists for a customer but the customer is not signed into their store account
2. When a customer is signed into their store account but their email address is already subscribed

In both cases, the error message given by default is:
_"There was a problem with the subscription. This email address is already assigned to another user."_

The best way I could think to explain both situations with a single custom error message was:
_"There was a problem with the subscription. Please login to your store account and try again. If subscription still fails, it means your email address is already subscribed."_

That’s a little clunky, so I believe it would be better to have the two situations use different error messages, such as:
1. When an email address exists for a customer but the customer is not signed into their store account: _“There was a problem with the subscription. Please login to your store account and try again.”_
2. When a customer is signed into their store account but their email address is already subscribed: _“There was a problem with the subscription. The email address is already subscribed.”_

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by Santiagoebizmarts** [comment]
Hello @SC-RG 
Unfortunately this error is thrown by Magento (Zeoy in your case).
After looking at this code I see the error will only be thrown when the customer logged in has a different id than the customer found on the database with the same email address.
It should not ben given when the email is already subscribed.

Regards.
