### ISSUE TITLE
Unnecessary entity loading in batch processing

### ISSUE THREAD

**Issue by Swahjak** [mailchimp/mc-magento#91]
In [Ebizmarts_MailChimp_Model_Api_Products::createBatchJson](../blob/master/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php#L38) the following code is executed:

```PHP
foreach ($collection as $item) {
        $product = Mage::getModel('catalog/product')->load($item->getId());
```
Why is it necessary to load the product? If we just add the attributes needed to the product collection this can be done in 1 instead of a 101 database calls (not counting the calls needed to actually load the full eav model of a product).

The same goes for [Ebizmarts_MailChimp_Model_Api_Orders::createBatchJson](../blob/master/app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php#L43)
```PHP
foreach ($collection as $item) {
        try {
            $order = Mage::getModel('sales/order')->load($item->getEntityId());
```
In that case it will load the model *again* in [Ebizmarts_MailChimp_Model_Api_Orders::GeneratePOSTPayload](../blob/master/app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php#L123)

```PHP
    protected function GeneratePOSTPayload($orderFromCollection,$mailchimpStoreId)
    {
        $order = Mage::getModel('sales/order')->load($orderFromCollection->getEntityId());
```

I assume the same thing is happening in the other models (haven't checked yet)

**Comment by Santiagoebizmarts** [comment]
Thanks for the feedback.
We no longer do any loads in the product sending.

Regards.
