### ISSUE TITLE
MC 1.1.15 Reset Local Errors gives an error

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#911]
This is the issue after pushing the button. Tried on default config level and storeview level same outcome

![image](https://user-images.githubusercontent.com/652395/54342524-f68e1700-463c-11e9-82a6-2b9c86419b9c.png)

### Preconditions
M 1934 + MC 1.1.15

### Steps to reproduce
Try to reset local errors

Logs
Sorry nothing in php logs or magento logs to hint us at the direction

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

This error is usually thrown when the amount of items to delete from the error table is very large.
You should be able to get around it either by clicking the button several times until it finishes removing everything or running the following query: **TRUNCATE TABLE mailchimp_errors;**
After running the query Magento cache should be flushed and the button Reset Errors should be clicked again. If the error message persist we can re-open and continue working on this.

Kind Regards.

**Comment by seansan** [comment]
1. *TRUNCATE TABLE mailchimp_errors; DONE*
*2. Flush cache; DONE*
*3. Click button several times = SAME ERROR*

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

Maybe you are getting an error in the browser console?
In case you have more than one scope configured I suggest you to go through each and reset the errors for each scope.

Regards.

**Comment by seansan** [comment]
I am getting the error exactly like in the screenshot I attached

Also when doing it 1 by 1 per storeview the same error

https://github.com/mailchimp/mc-magento/blob/ffc32e83865add5e426e09607d184c77d7efa972/app/design/adminhtml/default/default/template/ebizmarts/mailchimp/system/config/reseterrors.phtml#L12

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
As you correctly flagged the response on that ajax call seems to be returning 0 causing the error to be displayed.
I see the exception message is not being added to the logs with the current code.
In order to see the exact message please add a log below the following line:
https://github.com/mailchimp/mc-magento/blob/1.1.15/app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php#L33

The log entry should be as follow:
$helper->logError($e->getMessage());

Kind Regards,

**Comment by seansan** [comment]
This is the error

2019-03-15T07:57:57+00:00 DEBUG (7): Notice: Undefined index: customer_id
in app/code/community/Ebizmarts/MailChimp/Helper/Data.php on line 3381

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 
You will be happy to hear we were able to find why this happens.
The fix is referenced above in PR #922 

Kind Regards.

**Comment by seansan** [comment]
Lucky me. 

Glad we took the time to reply after the issue was closed immediately. 

And now everyone benefits
