### ISSUE TITLE
Missing template: group/types.phtml

### ISSUE THREAD

**Issue by bobdavison** [mailchimp/mc-magento#912]
I made a fix to app/design/frontend/base/default/layout/ebizmarts/mailchimp.xml
to correct the <block type="mailchimp/group_type[s]" bug and noticed that it references a template template="ebizmarts/mailchimp/group/types.phtml" that does not exist.

**Comment by Santiagoebizmarts** [comment]
Hello @bobdavison 

Thanks for your feedback.
Please note this has already been fixed at https://github.com/mailchimp/mc-magento/pull/889

Kind Regards,

**Comment by bobdavison** [comment]
#889 corrects the <block> tag but the <template> tag still references a template that does not exist.

**Comment by Santiagoebizmarts** [comment]
Hello @bobdavison 
You are right, thanks for noticing this.

It does not create any problem with how the feature works.
Anyways I am reopening this and will close it once that template is removed.

Regards.

**Comment by Santiagoebizmarts** [comment]
Thanks for your feedback @bobdavison 

This has been solved now and will be available in the next release.

Kind Regards.
