### ISSUE TITLE
Tier prices

### ISSUE THREAD

**Issue by GeekMediaDK** [mailchimp/mc-magento#92]
I used a RC of the 1.1.2, but this version had the same Tier-price error as one of the earlier versions, and i can se that the released version looks the Product API model the same as the release candidate. Arent it missing the corrections made in the earlier version to prevent it from dropping tier prices when syncing. Because we are not interested in used several hours again in recreating the price table.

**Comment by gonzaloebiz** [comment]
Hi @GeekMediaDK,

thanks for your feedback,
Please, follow [this instructrions](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines) to report an issue.

Best
