### ISSUE TITLE
Product Data Not Created Correctly At MailChimp

### ISSUE THREAD

**Issue by bobbrodie** [mailchimp/mc-magento#93]
### Preconditions
```
* Magento EE 1.14.3.0 without sample data is installed.
* mc-magento 1.1.2.
```

### Steps to reproduce
```
* Clear local errors
* Clear eCommerce data
```

### Actual and Expected result
```
Expected result: Data would be batched and data is created at MailChimp.

Actual result: Process runs for hours and data is not created correctly at MailChimp.
```

### Additional Information
MailChimp enabled extra logging on our account and watched it while the data was syncing. They responded with, "Thanks for getting that additional info over. Looking at the calls we were able to log I am seeing failed GET batches calls, but not getting an exact response for the failure on those. I took a quick look at a recent Batch that was passed over, and looking over the JSON I'm seeing mostly that same error of The parent product must exist, but not anything I can actually see about the call made to generate that within the batch. We definitely want to help as far as we can for you, but at this point your best bet is going to be working with Ebizmarts directly since they handle the output side of the integration."

**Comment by gonzaloebiz** [comment]
Hi @bobbrodie 

in the error grid (in newsletter/mailchimp/mailchimp errors) yo have the errors and the batch_id. If you run the script getMailchimpResponse.php passing apiKey and batchId as parameter, the script download the response for this batch.
In the var/log directory you have each batch log (the name of the file has the form batchid.Request.log)
Please, send us both files to mailchimp@ebizmarts-desk.zendesk.com referring this issue 

Best

**Comment by gonzaloebiz** [comment]
No data received in 3 months, so close the issue
