### ISSUE TITLE
getLastRealOrder() doesn't exist

### ISSUE THREAD

**Issue by churiart** [mailchimp/mc-magento#946]
### Preconditions

1. Magento 1.7.0.2
2. mc-magento v1.1.15.2

### Steps to reproduce

1. On successful checkout this [template file](https://github.com/mailchimp/mc-magento/blob/develop/app/design/frontend/base/default/template/ebizmarts/mailchimp/checkout/success/groups.phtml) is rendered. The third line attempts for `$block->getInterest();` which has a call to ` $this->getSessionLastRealOrder();`.
2. `getSessionLastRealOrder()` is defined this way:

```
protected function getSessionLastRealOrder()
{
    return Mage::getSingleton('checkout/session')->getLastRealOrder();
}
```
but `getLastRealOrder()` on `Mage_Checkout_Model_Session` is neither a normal method nor an attribute code to magically be set or gotten (however it seems to exist in Magento 2.0) the reason it evaluates to null.

### Expected result

1. `groups.phtml` to render sucessfully.

### Actual result

1. `Fatal error: Call to a member function getCustomerEmail() on null in /*/app/code/community/Ebizmarts/MailChimp/Block/Checkout/Success/Groups.php on line 42`

**Comment by Santiagoebizmarts** [comment]
Hello @churiart 

Thanks for your feedback, maybe that function was added in a later version of Magento.
We will review and get back once we are able to replicate.

Kind Regards,

**Comment by dinc5150** [comment]
I'm getting the exact same error @Santiagoebizmarts with:
- Magento 1.7.0.2
- mc-magento v1.1.16

**Comment by roberto-ebizmarts** [comment]
Hello, @churiart, @dinc5150 
We have checked out that it is a bug.
When we finish the fix, we will reference it through this issue.
