### ISSUE TITLE
Timeout doesn't apply

### ISSUE THREAD

**Issue by churiart** [mailchimp/mc-magento#954]
### Preconditions

1. Magento v1.7.0.2
2. Ebizmart's MailChimp v1.15

### Steps to reproduce

1. Go to System -> Configuration -> MailChimp
2. Change `Connection timeout (in secs)` to anything other than `20`

### Expected result

1. New timeout should take place while initializing curl requests

### Actual result

1. It is still `20`

### Reason

[MailChimp.php:204](https://github.com/mailchimp/mc-magento/blob/develop/lib/Ebizmarts/MailChimp.php#L204):

```
if (!isset($opts['timeout']) || !is_int($opts['timeout'])) {
    $opts['timeout'] = 20;
}
```

`$opts['timeout']` contains new value but it is not of type **integer** so timeout would remain `20` forever. It should be something like:

```
if (!isset($opts['timeout']) || !is_numeric($opts['timeout']) || (int) $opts['timeout'] <= 20) {
    $opts['timeout'] = 20;
}
```

**Comment by Santiagoebizmarts** [comment]
Hello,

If you see the if it only only adds the 20 sec timeout in case no value has been specified before.
Please see https://github.com/mailchimp/mc-magento/blob/1.1.16/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L1204 where the object is created. As you can see $opts['timeout'] is set based on the config value.

Kind Regards.
