### ISSUE TITLE
Missing method in Version 1.1.16 // Call to undefined method Ebizmarts_MailChimp_Helper_Data::getListIdByApiKeyAndMCStoreId()

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#956]
Upgrade to last version M1941

Can no longeredit backend settings

Stack trace:
#0 app/code/local/Mage/Core/Model/Config.php(1374): Ebizmarts_MailChimp_Model_System_Config_Source_List->__construct(Array)
#1 app/Mage.php(464): Mage_Core_Model_Config->getModelInstance('mailchimp/syste...', Array)
#2 app/Mage.php(478): Mage::getModel('mailchimp/syste...', Array)
#3 app/code/community/EW/ConfigScopeHints/Block/Adminhtml/System/Config/Form.php(227): Mage::getSingleton('mailchimp/syste...')
#4 app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): EW_ConfigScopeHints_Block_Adminhtml_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), in app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/List.php on line 48
[10-May-2019 10:29:50 UTC] PHP Fatal error:  Uncaught Error: Call to protected method Ebizmarts_MailChimp_Helper_Data::isErrorLogEnabled() from context 'Ebizmarts_MailChimp_Block_Adminhtml_System_Config_CreateMergeFields' in app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/CreateMergeFields.php:57
Stack trace:
#0 app/design/adminhtml/default/default/template/ebizmarts/mailchimp/system/config/createmergefields.phtml(12): Ebizmarts_MailChimp_Block_Adminhtml_System_Config_CreateMergeFields->getMessageForMailchimpErrorLog()
#1 app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/s...')
#2 app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#3 app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
#4 app/code/community/Ebizmarts/MailChimp/ in app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/CreateMergeFields.php on line 57
[10-May-2019 10:35:50 UTC] PHP Fatal error:  Uncaught Error: Call to protected method Ebizmarts_MailChimp_Helper_Data::isErrorLogEnabled() from context 'Ebizmarts_MailChimp_Block_Adminhtml_System_Config_CreateMergeFields' in app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/CreateMergeFields.php:57
Stack trace:
#0 app/design/adminhtml/default/default/template/ebizmarts/mailchimp/system/config/createmergefields.phtml(12): Ebizmarts_MailChimp_Block_Adminhtml_System_Config_CreateMergeFields->getMessageForMailchimpErrorLog()
#1 app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/s...')
#2 app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#3 app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
#4 app/code/community/Ebizmarts/MailChimp/ in app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/CreateMergeFields.php on line 57
[10-May-2019 10:36:01 UTC] PHP Fatal error:  Uncaught Error: Call to protected method Ebizmarts_MailChimp_Helper_Data::isErrorLogEnabled() from context 'Ebizmarts_MailChimp_Block_Adminhtml_System_Config_CreateMergeFields' in app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/CreateMergeFields.php:57
Stack trace:
#0 app/design/adminhtml/default/default/template/ebizmarts/mailchimp/system/config/createmergefields.phtml(12): Ebizmarts_MailChimp_Block_Adminhtml_System_Config_CreateMergeFields->getMessageForMailchimpErrorLog()
#1 app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/s...')
#2 app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#3 app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
#4 app/code/community/Ebizmarts/MailChimp/ in app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/CreateMergeFields.php on line 57
[10-May-2019 10:36:27 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Ebizmarts_MailChimp_Helper_Data::getListIdByApiKeyAndMCStoreId() in app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/List.php:48
Stack trace:
#0 app/code/local/Mage/Core/Model/Config.php(1374): Ebizmarts_MailChimp_Model_System_Config_Source_List->__construct(Array)
#1 app/Mage.php(464): Mage_Core_Model_Config->getModelInstance('mailchimp/syste...', Array)
#2 app/Mage.php(478): Mage::getModel('mailchimp/syste...', Array)
#3 app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): EW_ConfigScopeHints_Block_Adminhtml_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), in app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/List.php on line 48

**Comment by seansan** [comment]
Refresh cache 2nd time, log out/in 2nd time, restart nginx = gone
A quirck? or opcache?
Error is gone

**Comment by Santiagoebizmarts** [comment]
Hello @seansan 

This kind of errors are usually related to caches not letting the updated code to execute.
Don't hesitate to reopen this if you find this error again.

Regards.
