### ISSUE TITLE
Changing Customer attribute data does not seem to sync to Magento

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#958]
Using M194x and MC Version 1.1.16

Case:
Add custom customer attribute (Something like _customer_brand_preference_)
Added attribute to merge vars in extension settings
Clicked create merge vars button
Checked in MC: the merge var does exist
Set data manually to the customer attribute _customer_brand_preference_
Hit save

Expected:
New customer attribute _customer_brand_preference_ data is sent to MC and visible

Actual:
No data there, new merge vars are all empty

I would expect if you change customer data, and this is a merge var, that of course this data is updated from Magento to MC

**Comment by luciaebizmarts** [comment]
Hi @seansan,

Thanks for your feedback we will look into this.

Best regards.

**Comment by luciaebizmarts** [comment]
Hi @seansan,

After you add the new merge field, you will need resend the subscribers in other way the new merge field will be empty for the old subscribers.

**Comment by seansan** [comment]
I would expect some check. If data changes then resync

Also after resend all it does not show the new fields

**Comment by brian-ebizmarts** [comment]
Hi @seansan 

I've tested the case and the value has been sent correctly, the extension can send any Customer attribute, the ones from Magento and the ones created by custom extensions. If you want to send information that is not specifically a customer attribute, you need to create a custom entry.
[https://ebizmarts.com/forums/topics/view/24875](url)

When the customer updates their account information the new value should be sent, resend the customers is not required. Take in mind that actually the merge fields are sent only for customers subscribed.

Best regards.
