### ISSUE TITLE
Multiple Mandrill_Message instances created instead of returning existing one in Ebizmarts_MailChimp_Model_Email_Template

### ISSUE THREAD

**Issue by thomascharbit** [mailchimp/mc-magento#959]
Hi,

I think after #684 a bug was introduced in `Ebizmarts_MailChimp_Model_Email_Template` class.
See https://github.com/mailchimp/mc-magento/commit/22d972ac3033cb6924a12ff0205280770040248f.
The test should check that Mandrill is active, not inactive ?
The current if test would always create a new `Mandrill_Message`.

My actual issue was a compatibility issue with Fooman EmailAttachment module.
Fooman EmailAttachment module send email like this :
https://github.com/fooman/emailattachments/blob/master/app/code/community/Fooman/EmailAttachments/Model/Core/Email/Template/Mailer.php#L24-L42

But `Ebizmarts_MailChimp_Model_Email_Template` will instanciate 3 different `Mandrill_Message` and thus attachments and bcc actions are lost in the process.

### Preconditions
1. Magento CE 1.9.0
2. Fooman EmailAttachment 0.11.8 (latest)
3. Ebizmarts MailChimp 1.1.16

### Steps to reproduce
1. Configure Fooman EmailAttachment to attach PDF to any email (like order confirmation)
2. Send email from admin

### Expected result
Email should be sent with the attachment

### Actual result
Email is received without attachment

**Comment by luciaebizmarts** [comment]
Hi @thomascharbit,

Thanks for your feedback we will look into this.

Best regards.

**Comment by Santiagoebizmarts** [comment]
Hello @thomascharbit
That is actually the idea. That way the new object is clean. This prevents conflicts with other extensions using that same object.
Kind regards

**Comment by Santiagoebizmarts** [comment]
We will review the conflict with fooman extension and get back.
Thanks for your feedback on this.

**Comment by govereem** [comment]
Changing: vendor/ebizmarts/mc-magento/app/code/community/Ebizmarts/MailChimp/Model/Email/Template.php getMail() method

### From
```
        if ($this->_mail && (!$this->isMandrillEnabled($storeId))) {
            return $this->_mail;
        } else {
```

### To
```
        if ($this->_mail && $this->isMandrillEnabled($storeId)) {
            return $this->_mail;
        } else {
```

Solves the fooman attachement issue, This->mail object will not be recreated '$this->createMandrillMessage($storeId);', Recreation wil remove all setting done before like the attachment.
