### ISSUE TITLE
Exception when calling webhook for clean

### ISSUE THREAD

**Issue by hakanonal** [mailchimp/mc-magento#96]
Hello,

When the mailchimp calls the webhook for cleaning purpose I get an exception 
Call to undefined method Ebizmarts_MailChimp_Helper_Data::isAdminNotificationEnabled()

preconditions
1. Magento CE 1.9.2.2 without sample data is installed.
2. mc-magento 1.1.1.
3. all customers and subscribers are synced

steps to reproduce
1.send a campaign and find some emails that needs to be cleaned

expected result
no exception
actual result
an exception

addtional information:

**Comment by gonzaloebiz** [comment]
Hi @hakanonal 

thanks for your feedback.
Please update to 1.1.2 and confirm if the issue is there.

Best

**Comment by hakanonal** [comment]
Hello @gonzaloebiz ,

I have upgraded to 1.1.2 and the problem is still there. So you see there is really no method called isAdminNotificationEnabled in helper class Ebizmarts_MailChimp_Helper_Data. And the case continues in version 1.1.2 too.
