### ISSUE TITLE
Childrens of disabled products don't send to mailchimp if one children is included in the order

### ISSUE THREAD

**Issue by luciaebizmarts** [mailchimp/mc-magento#960]
### Preconditions
1. Mailchimp for Magento 1.1.16
2. Magento any version

### Steps to reproduce
1. Create an order, add the children of a disabled product.

### Expected result
1. The order should be send to Mailchimp.

### Actual result
1. The order is not synced with Mailchimp.

**Comment by roberto-ebizmarts** [comment]
Hello.
This is not an issue.
I followed these steps, in Magento 's backend:

1. I created a **simple product** named "Pullover1", having **Visibility** attribute with value: "Not Visible Individually".
2. I created a **configurable product** just named "Pullover", having "Pullover1" simple product as an _associated_ **child product**.
3. I **disabled** the parent product ("Pullover").
4. I made an order via Magento 's backend (Sales->Orders->Create Order) with "Pullover" as product requested.
5. I waited for cron job.
6. I verified that order was sent to Mailchimp.
7. I verified that "Pullover" product was not visible from Mailchimp, after the order was sent.
