### ISSUE TITLE
Synchronization Hanging on a Second Storefront

### ISSUE THREAD

**Issue by KylePalko** [mailchimp/mc-magento#961]
### Preconditions
Magento 1.9.4.1
Plugin Version: v1.1.15.1
PHP: Not sure
MySQL: Not sure

I will update this issue once I am able to confirm the PHP/MySQL version.

### Steps to reproduce
1. Install Plugin
2. Select first Magento Storefront
3. Click Get API Credentials
4. Authenticate
5. Select second Magento Storefront
6. Click Get API Credentials
7. Authenticate with the same Username from Step 4
8. Wait for Synchronization for 3 weeks

### Expected result
The Initial Sync field for the second Storefront should say "Finished" with a timestamp.

### Actual result
For the first Storefront the Initial Sync completes and says "Finished". For the second Storefront the Initial Sync is stuck as "In Progress" with these results:

Initial Sync : In Progress
Total Customers: 0
Total Products: 0
Total Orders: 0
Total Carts: 0

**Comment by Santiagoebizmarts** [comment]
Hello @KylePalko 

Pleaae note 1.1.15.1 is not an official release.
Update to latest version 1.1.16 and you should get that working properly.
