### ISSUE TITLE
BCC doesn't work throw Mandrill (works with queue)

### ISSUE THREAD

**Issue by advocat** [mailchimp/mc-magento#962]
### Preconditions
- Magento CE 1.9.x, EE 1.14.x
- MailChimp 1.1.6
- Mandrill configured for any scope

### Steps to reproduce
- Configure BCC copy for Shipment emails
- Create shipment with Notify customer

### Expected result
- Sends Email to customer
- Sends Email to BCC copy

### Actual result
- Sends Email to customer
- BCC copy is not sent

### Some technical note
In method `Ebizmarts_MailChimp_Model_Email_Template::getMail` the system each time returns new instance of `Mandrill_Message` instead of stored one
If Mandrill is disabled the system run parent logic, but if it's enabled code tries to check one more time if it's not enable (logical error) for return correct instance
Please also double check cases in https://github.com/mailchimp/mc-magento/issues/684

**Comment by Santiagoebizmarts** [comment]
Hello @advocat 
Seems like you are using an old version of the extension 1.1.6.
Can you confirm this happens with latest version 1.1.16?

Kind Regards.

**Comment by boldbart** [comment]
I can confirm this also happens on 1.1.16 (Magento 1.9.4.1).

Maybe related: also e-mail attachments are not attached anymore. When we disable Mandrill module, the attachments are attached correctly.

**Comment by roberto-ebizmarts** [comment]
Hello @advocat, under these Preconditions:

- Magento CE 1.9.4.1
- MailChimp 1.1.16
- Mandrill configured for any scope

And following theses steps:
- Configure BCC copy for Shipment emails
- Create shipment with Notify customer

We have checked out that expected result was nicely succes:
- Sends Email to customer
- Sends Email to BCC copy

**Comment by advocat** [comment]
It's mistake in description, tested latest version 1.1.16
Looks like @boldbart also can reproduce this issue
Please see comment with technical details in initial ticket

**Comment by Santiagoebizmarts** [comment]
Hello @advocat 
In case there is something wrong in the steps to replicate please add the missing information.
With the steps given the email got sent correctly.

Regards.

**Comment by danielcmuresan** [comment]
Hello,
We have the same issue, BCC and attachments are not working anymore.

- Magento CE 1.8.1
- MailChimp 1.1.16
- Mandrill configured for any scope

No BCC for Order confirmation, invoices or shipments.
No attachments to shipments or any other emails. (pdfs)

Issue started since the mailchimp update to 1.1.16.

**Comment by Santiagoebizmarts** [comment]
Hello @danielcmuresan 
Do you have any customization over the email sending besides Mandrill?
How are you adding attachments?

Kind Regards.

**Comment by danielcmuresan** [comment]
Just for the attachments of pdfs, but nothing special.
Something like this:

```
$mail = Mage::getModel('core/email_template');
...
$mail->getMail()->createAttachment(
    $pdf,
    Zend_Mime::TYPE_OCTETSTREAM,
    Zend_Mime::DISPOSITION_ATTACHMENT,
    Zend_Mime::ENCODING_BASE64,
    $pdfHelper->getPdfFilename($po)
);
```

We didn't touched the bcc.
I forgot to mention that I was upgrading from 1.1.13 to 1.1.16.

The problem was here:
Ebizmarts_MailChimp/app/code/community/Ebizmarts/MailChimp/Model/Email/Template.php

I had to revert it to the version of 1.1.13 in order to work. I didn't looked into it to see what was the problem.

**Comment by Santiagoebizmarts** [comment]
Hello @danielcmuresan 

I think this might be related to the issue https://github.com/mailchimp/mc-magento/pull/988
I suggest you all to try the fix and see if it works.

Kind Regards.
