### ISSUE TITLE
Fix MagemOnkey remnants

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#966]
Use this link

https://github.com/mailchimp/mc-magento/search?q=magemonkey&unscoped_q=magemonkey

Module code uses MageMonkey

**Comment by seansan** [comment]
Rather than fixing a small issue you like to flag it? I think it is very clear and exact

**Comment by gonzaloebiz** [comment]
The rules are pretty clear

**Comment by seansan** [comment]
the small glitch also
