### ISSUE TITLE
Custom type products support

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#97]
Hello!

**Preconditions**
1. Magento ver. 1.9.2.4 Community Edition with real customers data
1. mc-magento 1.1.2

**Steps to reproduce**
1. Add custom product type
1. Add product with created custom type
1. Run cron job **mailchimp_bulksync_data**

**Actual and Expected result**
_Actual Result:_
1. We get the error "This product type is not supported"

_Expected Result:_
1. Product is imported correctly as Simple product

Guys, may be it's possibly to import custom type products to magento as simple products?
So there is **else** condition in **Ebizmarts_MailChimp_Model_Api_Products::_buildNewProductRequest** and it's reserved for **bundle** according the comment.
May be we should add bundle-specific condition and process simple and other product types in **else** condition?

**Comment by Santiagoebizmarts** [comment]
Hello @elluminatte 
I know this is an old issue, sorry for the delay, but unfortunately we need to know how the product is formed in order to be able to send it. With custom product types the behavior may be as the developers want it making it impossible for us to know how to treat it.
