### ISSUE TITLE
Fix for infinite sync of modified orders containing only unsupported products

### ISSUE THREAD

**Issue by TroyPatteson** [mailchimp/mc-magento#970]
I noticed when running the mailchimp_bulksync_ecommerce_data cron while testing mc-magento v1.1.16 that the same order kept getting processed. With the additional logging I have added to mc-magento v1.1.16 I see the following when I first synced the order to mailchimp:
```
2019-05-30T23:11:26+00:00 INFO (6): Marked subscriber ID 5 email XXXXXXXX for store 2 as modified for syncing
2019-05-30T23:11:26+00:00 DEBUG (7): Handle subscriber event for subscriber ID 5 email XXXXXXXX status 1
2019-05-30T23:12:02+00:00 DEBUG (7): Creating e-commerce batch for store 2: Adding customer XXXXXXXX email XXXXXXXX fname Troy lname Patteson opt-in NO num_orders 3 total_spent 259.91
2019-05-30T23:12:03+00:00 DEBUG (7): Creating e-commerce batch for store 2: Adding updated product ID 863 title Extra Page sku EP price none url http://XXXXXXXX/au/extra-page.html/
2019-05-30T23:12:03+00:00 DEBUG (7): Creating e-commerce batch for store 2: Adding updated product ID 2550 title 11"x8" (28x20cm) Hard Cover Book 20 pages sku 101646 price none url http://XXXXXXXX/au/11x8-hard-cover-book-20-pages.html/
2019-05-30T23:12:03+00:00 WARN (4): Ignoring e-commerce batch for store 2: order ID 200000003 currency AUD total 62.9800 tax 0.0000 discount 0 shipping 4.9900: no supported products
2019-05-30T23:12:03+00:00 DEBUG (7): MC-API Request: Sending e-commerce batch
2019-05-30T23:12:04+00:00 INFO (6): MC-API Request: Sent e-commerce batch as ID 15d1fbc450
```
On a side-note, notice the product URL has a trailing slash in the above log output. That happens for products that are not directly visible (ewww!).

Running the mailchimp_bulksync_ecommerce_data cron another 3 times I see:
```
2019-05-30T23:18:42+00:00 WARN (4): Ignoring e-commerce batch for store 2: order ID 200000003 currency AUD total 62.9800 tax 0.0000 discount 0 shipping 4.9900: no supported products

2019-05-30T23:31:11+00:00 WARN (4): Ignoring e-commerce batch for store 2: order ID 200000003 currency AUD total 62.9800 tax 0.0000 discount 0 shipping 4.9900: no supported products

2019-05-30T23:31:43+00:00 WARN (4): Ignoring e-commerce batch for store 2: order ID 200000003 currency AUD total 62.9800 tax 0.0000 discount 0 shipping 4.9900: no supported products
```

### Preconditions
1. magento v1.9.4.1 / php 7.2
2. mc-magento v1.1.16

### Steps to reproduce
1. Place an order containing a single bundled product
2. Sync the order to Mailchimp by running mailchimp_bulksync_ecommerce_data cron
3. Modify the order status which re-saves the order
4. Re-sync the order by running _mailchimp_bulksync_ecommerce_data_ cron and confirm that the corresponding ORD record in _mailchimp_ecommerce_sync_data_ table has a changing _mailchimp_sync_delta_.

### Expected result
1. The order should not be synced after the initial sync (_mailchimp_sync_delta_ should not change).

### Actual result
1. The ORD record has a _mailchimp_sync_delta_ that changes each time the _mailchimp_bulksync_ecommerce_data_ cron is run.

### The Problem
I have tracked the problem down to how the ORD record in the _mailchimp_ecommerce_sync_data_ table is updated when an existing order containing only unsupported mailchimp products is saved. The relevant code is in __getModifiedOrders()_ in **app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php**:
```
                } else {
                    $error = $helper->__('Something went wrong when retrieving product information.');
                    $this->_updateSyncData($orderId, $mailchimpStoreId, Varien_Date::now(), $error, null, 0);
                    continue;
                }
```
The _syncModified_ parameter is passed as **null** which means that the __mailchimp_sync_modified__ field in the _mailchimp_ecommerce_sync_data_ record is left  unchanged and the order will be detected as modified when the cron is next run.

### The Solution
Simply pass the _syncModified_ parameter as 0 instead:
```
                } else {
                    $error = $helper->__('Something went wrong when retrieving product information.');
                    $this->_updateSyncData($orderId, $mailchimpStoreId, Varien_Date::now(), $error, 0, 0);
                    continue;
                }
```

I also think it is bad practice to leave the _syncModified_ parameter as null when inserting new records in the _mailchimp_ecommerce_sync_data_ table. It works because the columns are defined as NOT NULL with a DEFAULT of 0 but really you should be explicitly setting them. A new record that has been synced is by definition not modified so it should be explicitly set to 0. That is true for all records (QUO, ORDER, PRO, etc) stored in that table.

**Comment by Santiagoebizmarts** [comment]
Hello @TroyPatteson 

Actually when sending null it uses the default value for the function _updateSyncData.
Please see https://github.com/mailchimp/mc-magento/blob/1.1.16/app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php#L505

This actually sets the modified value to 0.

If you find I am wrong please let me know and I will reopen the ticket.

Kind Regards,

**Comment by TroyPatteson** [comment]
You are in fact wrong. I don't know why you didn't check this yourself. It took me all of two minutes to test with this:
```
<?php

function check_params($param = 0)
{
	var_dump($param);
}

check_params();
check_params(1);
check_params(null);
```
The output using PHP v7.2 is:
```
int(0)
int(1)
NULL
```
You might think the result is different using a class method instead but that is not the case:
```

class Test
{
	function check_params($param = 0)
	{
		var_dump($param);
	}
}

$test = new Test();
$test->check_params();
$test->check_params(1);
$test->check_params(null);
```
Output:
```
int(0)
int(1)
NULL
```

The second part of this is that the magento _save()_ method doesn't save fields that are _NULL_ if the database column is _NOT NULL_. You can see this in **app/code/core/Core/Model/Resource/Abstract.php**:
```
    /**
     * Prepare data for passed table
     *
     * @param Varien_Object $object
     * @param string $table
     * @return array
     */
    protected function _prepareDataForTable(Varien_Object $object, $table)
    {
        $data = array();
        $fields = $this->_getWriteAdapter()->describeTable($table);
        foreach (array_keys($fields) as $field) {
            if ($object->hasData($field)) {
                $fieldValue = $object->getData($field);
                if ($fieldValue instanceof Zend_Db_Expr) {
                    $data[$field] = $fieldValue;
                } else {
                    if (null !== $fieldValue) {
                        $fieldValue   = $this->_prepareTableValueForSave($fieldValue, $fields[$field]['DATA_TYPE']);
                        $data[$field] = $this->_getWriteAdapter()->prepareColumnValue($fields[$field], $fieldValue);
                    } else if (!empty($fields[$field]['NULLABLE'])) {
                        $data[$field] = null;
                    }
                }
            }
        }
        return $data;
    }
```
If _$fieldValue_ is _NULL_ and the field is not _NULLABLE_ it is ignored.

I am not sure what you are using to develop the software with but I highly recommend the combination of Phpstorm with magicento plugin and xdebug.

**Comment by Santiagoebizmarts** [comment]
Hello @TroyPatteson 

Thanks for your feedback. I have reopened this and will be solved for next release.

Kind Regards.
