### ISSUE TITLE
Errors saved in mailchimp_sync_ecommerce_data table may not set the sync_modified value to 0

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#976]
### Preconditions

1. Mailchimp For Magento 1.1.16

### Issue

Sometimes the function saveEcommerceSyncData is called with syncModified value set as null. This means the value is not changed.
We should validate that every time this function is called with syncModified set as null we actually expect the item to remain with the same in stead of changing back to 0.
### Expected result

1. When an error is saved in any item, the syncModified value should be updated to 0.

### Actual result

1. Some items don't update the syncModified value to 0 when errors are saved.

One example where this happens is https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php#L88

**Comment by Santiagoebizmarts** [comment]
Related to #970

**Comment by giorello** [comment]
Merged in #984.
