### ISSUE TITLE
Ecommerce multi-store support

### ISSUE THREAD

**Issue by elluminatte** [mailchimp/mc-magento#98]
Hi there!

Do you have implementation plan for enabling support of multi-store configuration for Ecommerce Mailchimp Data? Will it be implemented in the nearest future?

Regards, Nikolay.

**Comment by Santiagoebizmarts** [comment]
Hello @elluminatte 

We are focusing on the Magento 2 extension at the moment. We will keep up fixing bugs but for new features it will probably take a couple months.

You can Watch the repo to stay tuned for new releases.

Please check our [guideliness](https://github.com/mailchimp/mc-magento/wiki/Issue-reporting-guidelines). This kind of question should not be placed as an issue.

Regards.
