### ISSUE TITLE
Currency discrepancy in order confirmation email 

### ISSUE THREAD

**Issue by brian-ebizmarts** [mailchimp/mc-magento#982]
### Preconditions
1. Magento 1 any version
2. Mailchimp for Magento 1.1.16

### Steps to reproduce
1. Go to (Magento Default config) Configuration > Currency setup and set "Base currency" option.
2. Go to (Magento Storeview) Configuration > Currency setup and set a different currency for  "Default Display Currency" option.
3. place a new order

### Expected result
Base price used in both parameters order data and "lines". 

### Actual result
- Base price is sent in the order data but is not sent in the "lines" parameter. 
- price conversion is applied  
![wrong data](https://user-images.githubusercontent.com/46751037/59791857-55e96c00-92a9-11e9-90dd-a3bb7031a334.png)

Order API reference: https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/orders/

**Comment by Santiagoebizmarts** [comment]
We should do this in the same way Mailchimp4Magento2 does it:
https://github.com/mailchimp/mc-magento2/blob/develop/Model/Api/Order.php#L290-L294
https://github.com/mailchimp/mc-magento2/blob/develop/Model/Api/Order.php#L350-L357

That way the Order Confirmation Automation will be sent with the currency the Customer actually paid.
The downside of this is that Mailchimp will show incorrect revenue as they add different purchases all together even when they are made in different currencies.
