### ISSUE TITLE
compatibility problem with mysql 5.5.x

### ISSUE THREAD

**Issue by stoutik** [mailchimp/mc-magento#987]
compatibility problem with mysql 5.x

### Preconditions

1. Magento ver. 1.9.3.9
2. PHP ver. 5.6
3. Mysql ver. 5.5.40

### Steps to reproduce

1. Add the module to your Magento Installation.

### Expected result

1. no Problem

### Actual result

![image](https://user-images.githubusercontent.com/10999921/60515313-a4e8c580-9cdb-11e9-846e-34387596194d.png)

app/code/community/Ebizmarts/MailChimp/sql/mailchimp_setup/mysql4-upgrade-1.1.14-1.1.15.php

**Comment by gonzaloebiz** [comment]
Hi @stoutik 

thanks for your feedback.
Please read carefully here https://docs.magento.com/m1/ce/user_guide/magento/system-requirements.html as you can see you need mysql 5.6

Best
