### ISSUE TITLE
Error subscribing customer from backend.

### ISSUE THREAD

**Issue by roberto-ebizmarts** [mailchimp/mc-magento#990]
### Preconditions

1. Magento v1.9.4.2, **Mailchimp** for Magento v1.1.16, PHP 5.6.40, MySQL v15.1 Distrib 10.4.6-MariaDB

### Steps to reproduce

1. Set to "Yes" the option "Enabled" under **Mailchimp integration by ebizmarts** section at Store View level. Note: ensure there is a valid API KEY set for Mailchimp and there is any **audience** selected
2. Disable "Use Magento emails" at Mailchimp extension configuration page.
3. Create a customer from Magento's backend. Note: ensure to choose "Store View (For MailChimp)" with the same Store View selected in step 1.
4. Subscribe from backend this customer you have created earlier.

### Expected result

1. Customer should appear as subscribed in your configured Mailchimp **audience**.

### Actual result

1. Customer doesn't appear in your configured Mailchimp list.

**Comment by Santiagoebizmarts** [comment]
This can be tested simply by subscribing a Customer from the back end making sure the field Store view (for Mailchimp) is configured.
See image:
![Screen Shot 2019-09-30 at 17 10 01](https://user-images.githubusercontent.com/8330778/65912795-2c120c00-e3a5-11e9-8e4b-e0b34b046d54.png)
