### ISSUE TITLE
Feature request: only send ecommerce data for subscribers - GDPR consent issue

### ISSUE THREAD

**Issue by m-overlund** [mailchimp/mc-magento#997]
To comply with GDPR you need consent and use, to send customers data to Mailchimp.
That would normally be when the customer subscribes to the newsletter.

**Problem:**
- Customers not subscribed to the newsletter are sent as transactional contacts without their consent, which in turn means you do not comply with GDPR laws.

- Transactional contacts counts towards Mailchimp account limits, whichis an issue, if you do not use features like postcards and ordre confirmations through Mailchimp.

**Current solution:**
It can be fixed by disabling ecommerce data.
But that would also disable ecommerce data for subscribers which means a lot of mailchimps features is useless.

**Suggested solution:**
Make an option to only send ecommerce data for subscribed customers.

**Comment by Santiagoebizmarts** [comment]
Hello @m-overlund 

This should not be necessary. Mailchimp requested us to do the following: https://github.com/mailchimp/mc-magento/issues/929

Supposedly it should take care of the same, asking for specific consent on what can be sent.
